>gi|18424615|ref|NP_568958.1| Tic22-like family protein [Arabidopsis thaliana]
ISSLSSDGKRGGPAFVGQVFSMCDLTGTGLMAVSTHFDIPFISKRTPEWLKKMFSTITKS
ERNGPVFRFFMDLGDAVSYVKKLNIPSGVVGACRLDLAYEHFKEKPHLFQFVPNERQVKA
ANKLLKSMPQNGKTQKVEGVPVFGAQNLDIAVATADGIKWYTPYFFDKAVLDNILEE---
-----SVDQHFHTLIQTRHVQRRRDVVDDSLASEVMEEMGDSMLEPPEVQEA--MEEIGT
SGIPLSVVAKAAEIQLLYAVDRVLLGSRWFRKATGIQPKLPYLVDSFERRSAFSIQRASG
SATRCLGDSVEADTSASLLRVEDDSPSEAEKRQQHLWFPFGDWISHSVSRKEHTHHKGSS
DQRDMESREREMLRSPFLPKITMVGISTGEAAQMSKANLKKTMEDLTEDLEQSDEGNDHG
SKRYDSLKIEERDPLFVANVGDYYSGLAKAGSARLSRRGDDQ
>gi|3769671|gb|AAC64606.1| Tic22 [Pisum sativum]
-ATLT-------PNHVAK-----SLAGTSVYTVSNS-DNEFVLMSDAEGAKSI-GLLCFR
QEDAEAF-----LAQVRSRKKEFRGGAKVV-PITLDQVY-MLKVEGIAFRFLPDPVQIKN
ALEL-----RAANRGSFDGVPVFQSDLLVVKKKN----KRYCPVYFSKEDLEYELSKVSR
SSKGVGVSQHI-------MVGSFEDVLKKMELSEKSSGWEDLVFIPPGKKHSQHMQEV--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------IA------------------------
