>AT5G62650-tail
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------SVEA------DTSASLL
RVED-DSPSEA-E----------------KRQQ--HL-----WFPFGDWISHSVSRKEHT
HHKGSSDQRDM-----ESREREML-----RSPFLPKITMVGISTGEAAQMSKANLKK---
-TMEDLTEDLEQSD--------------------------EGN---D-HGSKRYDSLKIE
E--R-------------DPLFVANV-----------------------------------
--GDY----------YSGL--------AKAGSARLSRRGDDQ------------------
-----------------

>gi|300813510|ref|ZP_07093850.1| ribonuclease HII [Peptoniphilus sp. oral taxon 836 str. F0141]
------------------------------------------------------------
-----------------------------------------GSLF-GDVLSCAIIMKEDS
NIEGVN---DSKKLTAKKRKELYNKILKDSL-----------------------------
-AVGIGRADAK-------------TIDKLNIKMATHLSMVRAIENLRDSQGNLVVPDLVL
IDAENIETTI-------------FQHSII-----KGDENCYSIACASIIAKVYRDSLCDK
--------------------------------------------------------WAT-
------------------------------------------------------------
------------IYPGYGIEKH--------------------------------------
------KGYGTKFHREALKA-----------YGPSPMH----------------------
-----------------------------
>gi|282883154|ref|ZP_06291753.1| ribonuclease HII [Peptoniphilus lacrimalis 315-B]
--------------------------MTFTAYEKDY------------------------
--------------RKKGSKLIAGIDEVG-----------RGSLF-GDVLSCAIIMKEDS
NIEGVN---DSKKLTAKKRKELYNKILEDSL-----------------------------
-AVGIGRADAK-------------TIDKLNIKMATHLSMVRAIENLRDSQGNLVVPDLVL
IDAENIETTI-------------FQHSII-----KGDENCYSIACASIIAKVYRDSLCDK
--------------------------------------------------------WAT-
------------------------------------------------------------
------------IYPGYGIEKH--------------------------------------
------KGYGTKFHREALKA-----------YGPSPMHR-------------KSFMNNLK
KW---------------------------
>gi|399924187|ref|ZP_10781545.1| ribonuclease H [Peptoniphilus rhinitidis 1-13]
--------------------------MNFEKFEDDY------------------------
--------------YKKGYKNICGIDEVG-----------RGCLF-GDVVSCAIIMPKGD
YIEGVN---DSKKLTPKKREELYTKILENCV-----------------------------
-AVGIGRADAD-------------IIDKVNIKMATHISMINALENLKDSEGKKVEADCVL
IDAETIKTGI-------------FQKAII-----KGDESCYSIACASIIAKVYRDNLCKR
--------------------------------------------------------WAE-
------------------------------------------------------------
------------KYPNYGIEKH--------------------------------------
------KGYATKYHREALKT-----------YGPSDMHR-------------KTFLKNIK
LW---------------------------
>gi|313888218|ref|ZP_07821892.1| ribonuclease HII [Peptoniphilus harei ACS-146-V-Sch2b]
--------------------------MSFYNFEEEY------------------------
--------------YEKGYKNICGIDEVG-----------RGCLF-GDVVSCAVIMPRGK
YIEGVN---DSKKLSPKKREALYLKILESAI-----------------------------
-AVGIGRANAD-------------IIDKVNIRMATHISMINALENLRDSENNKIEADCVL
IDAETIETGI-------------FQKAIV-----KGDESCYSIACASIVAKVYRDNLCKK
--------------------------------------------------------WAE-
------------------------------------------------------------
------------EYPQYGLEKH--------------------------------------
------KGYATKYHREALKA-----------YGPSDMHR-------------KTFLKNIK
SW---------------------------
>gi|350566999|ref|ZP_08935610.1| ribonuclease HII [Peptoniphilus indolicus ATCC 29427]
----------------------------MEEFEKEY------------------------
--------------KKIGYTNIVGIDEVG-----------RGSLF-GDVLACAIIMP-DS
RIEGVA---DSKKLSVKKRESLYEKILDECI-----------------------------
-AVGIGRIDSK-------------KIDEINIKNATHLAMEQAIKNMRDQKGRKVYADLLL
IDAEKIDTQI-------------AQVSII-----KGDDRCYSIACASIVAKVYRDSLCDN
--------------------------------------------------------WEK-
------------------------------------------------------------
------------LYPGYNLKKN--------------------------------------
------KGYGTTEHRNAIKE-----------VGYTPMHR-------------LTFLRNLI
G----------------------------
>gi|342217276|ref|ZP_08709923.1| ribonuclease HII [Peptoniphilus sp. oral taxon 375 str. F0436]
--------------------------MNGCEFDQTY------------------------
--------------YQEGYGSLVGIDEVG-----------RGCLF-GDVVACAIVMPRES
FIEGVK---DSKKLSEKRREALYEEILKECK-----------------------------
-AVGIGRVDSK-------------TIDEINIKQASRLAMKKAVENLRDQEGQVFKPDLAL
IDAETIDLDI-------------EQKAII-----HGDDLSYSISCASIVAKVYRDRLCIQ
--------------------------------------------------------WSK-
------------------------------------------------------------
------------DYPGYGIEKH--------------------------------------
------KGYATVLHRGAIKA-----------LGPSPLHR-------------MTFLRKIL
SNESH------------------------
