>AT5G62650-tail
-------------------SVEADTSASLLRVEDDSPSEAEKRQQHLWFPFGDWISHSVS
RKEHTHHKGSSDQRDMESREREMLRSPFLPKITMVGISTGEAAQMSKANLKK----TMED
LTEDLEQSDEGND-----------------------HGSKRYDSLKIEE------RDPLF
VANVGDY--YSGLAKAGSARLSRRGDDQ----------------------
>gi|300813510|ref|ZP_07093850.1| ribonuclease HII [Peptoniphilus sp. oral taxon 836 str. F0141]
--------------------------GSL---------------------FGDVLSCAII
MKEDSNIEGVNDSKKLTAKKRKELYNKILKDSLAVGIGRADAKTIDKLNIKMATHLSMVR
AIENLRDS-QGNLVVPDLVLIDAENIETTIFQHSIIKGDENCYSIACASIIAKVYRDSLC
DKWATIYPGYGIEKHKGYGTKFHREALKAYGPSPMH--------------
>gi|282883154|ref|ZP_06291753.1| ribonuclease HII [Peptoniphilus lacrimalis 315-B]
MTFTAYEKDYRKKGSKLIAGIDEVGRGSL---------------------FGDVLSCAII
MKEDSNIEGVNDSKKLTAKKRKELYNKILEDSLAVGIGRADAKTIDKLNIKMATHLSMVR
AIENLRDS-QGNLVVPDLVLIDAENIETTIFQHSIIKGDENCYSIACASIIAKVYRDSLC
DKWATIYPGYGIEKHKGYGTKFHREALKAYGPSPMHRKSFMNNLKK---W
>gi|399924187|ref|ZP_10781545.1| ribonuclease H [Peptoniphilus rhinitidis 1-13]
MNFEKFEDDYYKKGYKNICGIDEVGRGCL---------------------FGDVVSCAII
MPKGDYIEGVNDSKKLTPKKREELYTKILENCVAVGIGRADADIIDKVNIKMATHISMIN
ALENLKDS-EGKKVEADCVLIDAETIKTGIFQKAIIKGDESCYSIACASIIAKVYRDNLC
KRWAEKYPNYGIEKHKGYATKYHREALKTYGPSDMHRKTFLKNIKL---W
>gi|313888218|ref|ZP_07821892.1| ribonuclease HII [Peptoniphilus harei ACS-146-V-Sch2b]
MSFYNFEEEYYEKGYKNICGIDEVGRGCL---------------------FGDVVSCAVI
MPRGKYIEGVNDSKKLSPKKREALYLKILESAIAVGIGRANADIIDKVNIRMATHISMIN
ALENLRDS-ENNKIEADCVLIDAETIETGIFQKAIVKGDESCYSIACASIVAKVYRDNLC
KKWAEEYPQYGLEKHKGYATKYHREALKAYGPSDMHRKTFLKNIKS---W
>gi|350566999|ref|ZP_08935610.1| ribonuclease HII [Peptoniphilus indolicus ATCC 29427]
M--EEFEKEYKKIGYTNIVGIDEVGRGSL---------------------FGDVLACAII
MP-DSRIEGVADSKKLSVKKRESLYEKILDECIAVGIGRIDSKKIDEINIKNATHLAMEQ
AIKNMRDQ-KGRKVYADLLLIDAEKIDTQIAQVSIIKGDDRCYSIACASIVAKVYRDSLC
DNWEKLYPGYNLKKNKGYGTTEHRNAIKEVGYTPMHRLTFLRNLIG----
>gi|342217276|ref|ZP_08709923.1| ribonuclease HII [Peptoniphilus sp. oral taxon 375 str. F0436]
MNGCEFDQTYYQEGYGSLVGIDEVGRGCL---------------------FGDVVACAIV
MPRESFIEGVKDSKKLSEKRREALYEEILKECKAVGIGRVDSKTIDEINIKQASRLAMKK
AVENLRDQ-EGQVFKPDLALIDAETIDLDIEQKAIIHGDDLSYSISCASIVAKVYRDRLC
IQWSKDYPGYGIEKHKGYATVLHRGAIKALGPSPLHRMTFLRKILSNESH
