>at5g62650_i|18424615|ref|NP_568958.1| Tic22-like family protein [Arabidopsis thaliana]
------------------------------MGSPDKQHRRHVAAEFLHSAVTSISSSIIP
LFPPKTAPSRVCLPLRFSVSDDVSSPFESTVKSTSSASSSGLNSTVRISSLSSD------
-------GKRGGPAFVGQVFSMCDLTGTGLMAVSTHFDIP-FISKRTPEWL----KKMFS
TITKSERNGPVFRFFMDLGDAVSYVKKLNIPSGVVGACRLDLAYEHFKEKPHLFQFVPNE
RQVKAANKLLKSMPQNGKTQKVEGVPVFGAQNLDIAVATADGIKWYTPYFFDKAVLDNIL
EESVDQHFHTLIQTRHVQRRRDVVD---DSLASE-VMEEMGDSMLEPPEVQEAMEEIGTS
GIPLSVVA-KAAEIQLLYAVDRVLLGSRWFRKATGIQPKLPYLVDSFERR-SAFSIQRAS
GSAT--------RCLGD------SVEADTSASLLRVEDDS-------PSEA-EKRQQHLW
FPFGDWISH-------------SVSRKEHTHHKGSSDQRDMESREREMLRSPFLPKITMV
GISTGEAAQMSKANLKKTMEDLTEDLEQS-----DEGNDHGSKRYDSLKIEERDPLF--V
ANVG-----------DYYSGLAKAGSARLSRRGDDQ--------
>Arabidopsis_lyrata_gnl|BL_ORD_ID|26695 _496448|PACid:16060442
------------------------------MGSPDKQHRRHVAAEFLHSAVT----SIIP
LFPPKTAPSRVCLPLRFSVSDDVSSPFESTVKSSSSTSSSGLNSTVRISSLSSD------
-------GKRGGPAFVGQVFSMCDLTGTGLMAVSTHFDIP-FISKRTPEWL----KKMFS
TITKSERNGPVFRFFMDLGDAVSYVKKLNIPSGVVGACRLDLAYEHFKEKPHLFQFVPNE
RQVKAANKLLKSMPQNGRKQKVEGVPVFGAQNLDIAVATADGIKWYTPYFFDKAVLDNIL
EESVDQHFHTLIQTRHVQRRRDVVD---DSLASE-VMEEMGDSMLEPPEVQEAMEEIGSS
GIPLSVVA-KAAEIQLLYAVDRVLLGSRWFRKATGIQPKLPYLVDSFERR-SAFSIQRAS
GSAT--------RCLGD------SVEADTSASLLRVEDNS-------PSED-EKRQQNLW
FPFGDWINH-------------SESKKEHTHHKGPSDGRDMESREREMLRSPFLPKITMV
GISTGEAAQMSKANLKKTMEDLTEDLEQS-----DEGNDHGSKRYDPRKMEERDPLF--V
ANVG-----------DYYSGMAKAGSARLSRRGDDQ--------
>Brassica_rapa_gnl|BL_ORD_ID|11888 _010109|PACid:22695398
------------------------------MDSPDKIHRRYNAAEILHGAATSIS-SIIP
LFPPKTTPSRVCLPLRFS---DV-SPFESTVKNASSTSTSSS--GLNSTVRISSLSSDGK
R---------GGPAFVGQVFSMCDLTGTGLMAVSTHFDIP-FISKRTPEWL----KKMFS
TITKSERKGPVFRFFMDLGDAVSYVKKLNIPSGVVGACRLDLAYEHFKEKPHLFQFVPNE
RQVKAANKLLKSMPPSEKKQRVDGVPVFAAQNLDIAVATSDGIKWYTPYFFDKAVLDNIL
EESVDQHFHTLIQTRHVQRRRDVVD---DSLTSE-IMEEMGDSMLEPPEVQEAMEEIGTS
GIPLSVVA-KAAEIQLLYAVDRVLLGSRWFRKATGIQPKLPYLVDSFERR-SALSIQRAS
GSTT--------KCLGD------SNS---SASLLKVEDGS-------PSEE-EKRQQSLW
FPFGDWLKA----------------------QKDSSGQREMESREREMQRSPFLPKITMV
GISTGEAAHMSKANLKKTMEDLTQDLEQS-----DEGSDHGSNRYDPLKIEERDPLF--V
ANVG-----------DYYSGLARAGSARWSRRGDDRNETPPRSS
>Zea_mays_gnl|BL_ORD_ID|9045 _GRMZM2G097959_T01|PACid:20828771
--------------------------------MP--------CSSSSSNPFHSLA-SAFP
FLSSTSPPP-SPPASPAPAAPHLAVPLLLPVSSASESRRGA---QPLPGTRMVGA---GA
TGGGNMASGGGGPAFVGQVFTMLDPSGNGLMAVTTRFELPRFLTNRTPMWF----KRMLS
PSKKTE-NSPVFRFFMDLNDAVSYVKRLNVPSGMVGACRLDVAYEHFKEKPHMFQFVPNE
KQVQAANKLLKSLPQRGRRKKLDGVPVFSAQNLNIAVATNDGIRWYTPYFFDKNLLDNIL
EASMDQHFHSIMQNRHTRRRRDIVD---DSLTSE-IIEESAESLLEPPEVQELMNEIGPA
GIPLNVVT-KAAEIQFLDVVDKVLLGNKWLRKASGIQPKFPYVVDSFEER-TAVSIANIA
TTSSLTASNDDSSC-QN------NQETQSSEPSGDNSSYR-------NHNN-EDHNH---
FPFSNLLPN----------IWPGHDRKFKSQESDNKFSRYDADVKSKLQANPLLPKITMV
GISMGDGAQMSKANLKKTMEDLTKELEQT-----SEENMFG---------DEKDPLF--V
ANVG-----------DYSRITKISSA------------------
>Oryza_sativa_gnl|BL_ORD_ID|20689 _LOC_Os01g12550.1|PACid:21903161
--------------------------------MPRGRSTTTTTSSSASNPFHAFA-STLP
FLPSPSPSPTSASPSPSPPAPHLAVPLILPITSSSSASAAAASPESNRGARMAAAASGGK
AGGGGGLGKGGGPAFVGQVFTMLDPSGNGLMAVTTRFELPQFLASRTPMWF----KRILS
PLKKSE-NGPVFRFFMDLNDAVSYVKRLNVPSGMVGACRLDVAYEHFKEKPQMFQFVPSE
KQVKAANKLLKSLPQRRRRKKLDGVPVFSAQNLNIAVATNDGIRWYTPYFFDKNLLDNIL
EASMDQHFHSMVQNRHTRRRRDIVD---DSLTSE-MMEESADSFLEPPEVQELMNEIGPV
GIPLNVVT-KAAEIQFLDVVDKMLLGNKWLRKATGIQPQFPYVVDSFEER-TAAAIDRAA
TASSSFTASKDADCFQI------SKQPETLESDVDNSNRG-------KHEN-SNNGQS-H
FPFSNLLPN----------IWPGHDRSFKAQGRDRAFRRCDASINNDLQANPLLPKITMV
GISMGEGGQMSKANLKKTMEDLTKELEQA-----GEKTIFS---------DEKDPLF--V
ANVG-----------DYSRITKISST------------------
>Physcomitrella_patens_gnl|BL_ORD_ID|36425 _Pp1s68_153V6.1|PACid:18072962
MGRNRDTCNVPGCSKDEKPCLVTGPKIVSFKLPNPALFSSWVQTVTSNLAWTVQSFQTLK
TDGLNCLSLLVEHKPMVSPLPVPYLALNNLIFPVPSSTSSVQVCQKAVSSIPQDHFSKGN
AVNEKGEVSSTGPAFIGQVYTMCDASRQGLIAVRPSDVLKKIKVPPYMKLMEKAYERAMN
VLFTDDMKGPVFRFYFNKDDAAEYVRRLNITGSAVGPCSLDAAYKYYKSKEGMFKFIADQ
RQVKVAKELVRRERGDKAANKLKGVPVFTARNLTIALSTPQGVRWFRPYFFNKKQLDSLI
GHSVDHYYEMLISARRAQRYSQIAENNGDAFAGGESMDDELDGLMDPPEVQELMEELGQG
GGGMEFVGLKVLEAQFMDLADRVLLGHQWSRRMIHLQPRFPVIVDSFERLISASELDHSS
ESEGSVTSSRNSFAKKEGTQEKSQRGQGDEGMSISGRDERSASNDSSESVS-KEYSQSSP
NSLFNLFKKKWGANANLVFKRKDSGNAEILEEDSDSEYLQETAQKDPPGKIPFQPKLTMM
GISMN--VNKVEGGLQQAMAAAAKDVEDRLRKGEGSGPDHG-------------PLF--I
ANLG-----------SGIPQWGRPVSASSGVLDDDAE-------
>gi|300813510|ref|ZP_07093850.1| ribonuclease HII [Peptoniphilus sp. oral taxon 836 str. F0141]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------GSLFGDVLSCAIIMKE----------DSN-IEGVN
DS------KKLTAKKRKELYNKILK---DSLAVG-I------GRADAKTIDKLNIK----
---------MATHLSMVRAIENLR-----DSQGNLVVPDL-VLIDA-ENI--ETTIFQHS
------------IIKGD------ENCYSIACASIIAKVYR-------DSLC-DKWATI--
YPGYGIEKH---------------------------------------------------
---KGYGTKFHREALKA-----------Y-----GPSPMH--------------------
--------------------------------------------
>gi|282883154|ref|ZP_06291753.1| ribonuclease HII [Peptoniphilus lacrimalis 315-B]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MTFTAYEKDYRKK---GSKLIAGI
DEV--------------------GRGSLFGDVLSCAIIMKE----------DSN-IEGVN
DS------KKLTAKKRKELYNKILE---DSLAVG-I------GRADAKTIDKLNIK----
---------MATHLSMVRAIENLR-----DSQGNLVVPDL-VLIDA-ENI--ETTIFQHS
------------IIKGD------ENCYSIACASIIAKVYR-------DSLC-DKWATI--
YPGYGIEKH---------------------------------------------------
---KGYGTKFHREALKA-----------Y-----GPSPMHR-------------KSF--M
NNLK-----------KW---------------------------
>gi|399924187|ref|ZP_10781545.1| ribonuclease H [Peptoniphilus rhinitidis 1-13]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MNFEKFEDDYYKK---GYKNICGI
DEV--------------------GRGCLFGDVVSCAIIMPK----------GDY-IEGVN
DS------KKLTPKKREELYTKILE---NCVAVG-I------GRADADIIDKVNIK----
---------MATHISMINALENLK-----DSEGKKVEADC-VLIDA-ETI--KTGIFQKA
------------IIKGD------ESCYSIACASIIAKVYR-------DNLC-KRWAEK--
YPNYGIEKH---------------------------------------------------
---KGYATKYHREALKT-----------Y-----GPSDMHR-------------KTF--L
KNIK---------------LW-----------------------
>gi|313888218|ref|ZP_07821892.1| ribonuclease HII [Peptoniphilus harei ACS-146-V-Sch2b]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MSFYNFEEEYYEK---GYKNICGI
DEV--------------------GRGCLFGDVVSCAVIMPR----------GKY-IEGVN
DS------KKLSPKKREALYLKILE---SAIAVG-I------GRANADIIDKVNIR----
---------MATHISMINALENLR-----DSENNKIEADC-VLIDA-ETI--ETGIFQKA
------------IVKGD------ESCYSIACASIVAKVYR-------DNLC-KKWAEE--
YPQYGLEKH---------------------------------------------------
---KGYATKYHREALKA-----------Y-----GPSDMHR-------------KTF--L
KNIK-----------SW---------------------------
>gi|350566999|ref|ZP_08935610.1| ribonuclease HII [Peptoniphilus indolicus ATCC 29427]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------MEEFEKEYKKI---GYTNIVGI
DEV--------------------GRGSLFGDVLACAIIMP-----------DSR-IEGVA
DS------KKLSVKKRESLYEKILD---ECIAVG-I------GRIDSKKIDEINIK----
---------NATHLAMEQAIKNMR-----DQKGRKVYADL-LLIDA-EKI--DTQIAQVS
------------IIKGD------DRCYSIACASIVAKVYR-------DSLC-DNWEKL--
YPGYNLKKN---------------------------------------------------
---KGYGTTEHRNAIKE-----------V-----GYTPMHR-------------LTF--L
RNLI-----------G----------------------------
>gi|342217276|ref|ZP_08709923.1| ribonuclease HII [Peptoniphilus sp. oral taxon 375 str. F0436]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MNGCEFDQTYYQE---GYGSLVGI
DEV--------------------GRGCLFGDVVACAIVMPR----------ESF-IEGVK
DS------KKLSEKRREALYEEILK---ECKAVG-I------GRVDSKTIDEINIK----
---------QASRLAMKKAVENLR-----DQEGQVFKPDL-ALIDA-ETI--DLDIEQKA
------------IIHGD------DLSYSISCASIVAKVYR-------DRLC-IQWSKD--
YPGYGIEKH---------------------------------------------------
---KGYATVLHRGAIKA-----------L-----GPSPLHR-------------MTF--L
RKIL-----------SNESH------------------------
>gi|407474072|ref|YP_006788472.1| ribonuclease HII [Clostridium acidurici 9a]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------MIQIEKKLWNE---GYKYIACI
DEV--------------------GRGCLLGDVVACAIIMPI----------DEL-IEGIK
DS------KKISQKKREKLYDSIID---RSLGVG-I------GRVDAKTIDEINIK----
---------KATLLAMKKAIGNIK-----DKDGNKIEPDY-LLIDA-EKL--DVDIPQEN
------------IIKGD------EKCYGIASASIIAKVYR-------DRLC-GEWDKD--
YPEYGIEKH---------------------------------------------------
---KGYGTKQHREMILT-----------C-----GITPIHR-------------KTF--L
TKIL-----------SQK--------------------------
>gi|158320503|ref|YP_001513010.1| ribonuclease H [Alkaliphilus oremlandii OhILAs]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MPTIDIESAIWNS---GYENIACC
DEV--------------------GRGCLFGSVLAAAVIMPK----------DVI-IDGVK
DS------KKLSHKKREQLYEIIKE---KSLAIG-V------GTVSSEIIDKINIK----
---------NATRLAMKKAILSLK-----DKDGNIVAPDY-ILIDA-EEI--DVPTPQSA
------------VIKGD------DLCHGIAAASIVAKVLR-------DRLC-QRWEEE--
HPNYGIGQN---------------------------------------------------
---KGYGTKAHREALKE-----------H-----GPSPMHR-------------KSF--L
NKIL----------------------------------------
>gi|150390501|ref|YP_001320550.1| ribonuclease H [Alkaliphilus metalliredigens QYMF]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MNRLEIENQLWEE---GYESIAGC
DEV--------------------GRGCLFGSVLAATVILPK----------GLL-IEGVK
DS------KKLSPKRREELYEVIKK---NAIAMG-V------GIISAEVIDQINIR----
---------QASRLAMKKSVLSLT-----TIDGESKIPDY-ILVDA-ENI--DIAIPQSA
------------IIKGD------DRSQGIAAASIVAKVIR-------DRLC-IRWDEE--
YPNYGIAQH---------------------------------------------------
---KGYGTKLHREALLK-----------Y-----GPSELHR-------------RSF--L
KKIL-------K--------------------------------
>gi|334340376|ref|YP_004545356.1| Ribonuclease H [Desulfotomaculum ruminis DSM 2154]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MVSLEYEQKLWAQ---GSQWIAFC
DEV--------------------GRGPLLGSVVAAAVILPV----------DLF-IEGVD
DS------KKLTPNKREALQQSIRE---QCVALG-I------GEVDNRQIDQINIR----
---------QASRLAMKKAVLNLQ-----NKDGQPVKPDY-LLIDA-ETI--DLEIPQQA
------------IIHGD------ALCHGIAAASIVAKVFR-------DNLC-LEWDQQ--
YPHYGIASH---------------------------------------------------
---KGYSTRAHMEALVK-----------L-----GPTPLHR-------------SSF--I
RKIL-------ARAKEQQQIFFK---------------------
>gi|323702665|ref|ZP_08114326.1| Ribonuclease H [Desulfotomaculum nigrificans DSM 574]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MVSLELEQKLWQQ---GIKLVAFC
DEV--------------------GRGPLLGSVVAAAVVLPV----------GLL-IEGVD
DS------KKLTPKKRETLCRYIYD---QALAVG-I------GEVDNNLIDQINIR----
---------QASRLAMKQAVMNLR-----SKEGHKVTPDY-LLIDA-ESI--DLDIPQQS
------------IIHGD------AVSHGIAAASIVAKVFR-------DSMC-MEWDQM--
YPDYGIASH---------------------------------------------------
---KGYATKAHIEALLK-----------L-----GATPLHR-------------RTF--L
RKIF--------ARAQQQVLFTD---------------------
>gi|414154249|ref|ZP_11410568.1| Ribonuclease HII [Desulfotomaculum hydrothermale Lam5 = DSM 18033]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MVSMDIEQKLWAE---GIELVAFC
DEA--------------------GRGPLLGSVVAAAVILPV----------RLW-IEGVN
DS------KKLTVKKREALYDIIQQ---HALAVG-I------GEVDNRQIDQINIR----
---------QASRLAMKKAVMNLQ-----NKQGMPVRPDY-LLIDGIESI--DLDIPQQG
------------VVHGD------AISHGIAAASILAKVFR-------DRKC-LEWHNR--
FPAYGIASH---------------------------------------------------
---KGYCTKAHVAALAQ-----------H-----GPTPLHR-------------LTF--L
KKLM------ARLAAEQQVLFQNQDTE-----------------
>gi|354584929|ref|ZP_09003820.1| Ribonuclease H [Paenibacillus lactis 154]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------MTDLLMYEREYWPR----YLHIAGV
DEV--------------------GRGCLFGDVVAAAVILPE----------GLV-IEGIN
DS------KKLSAKKRDALYEQIMD---QALAVG-V------GRVDAETIDRINIK----
---------QAARLAMKMALDQLV-----------VTPEF-LLVDA-ERV--DCDIPQQA
------------IIKGD------ANSQSIAAASIIAKVTR-------DRLCEGEWEAQ--
YPGYGIAVH---------------------------------------------------
---KGYATKTHREQLQL-----------H-----GPTPMHR-------------RSF--L
KNME----------IEQLSLF-----------------------
>gi|315648159|ref|ZP_07901260.1| ribonuclease HII [Paenibacillus vortex V453]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------MTDLLMYERDYWNH----YIHIAGI
DEV--------------------GRGCLFGDVVAAAVILPE----------GLV-IEGID
DS------KKLSAKKRETLYDLIME---DALAVG-V------GLVDAETIDRINIK----
---------QAARLAMKMAVEQLA-----------VTPQF-LLVDA-EKV--DCDIPQRA
------------IIKGD------ANSQSIAAASIIAKVTR-------DRLCEREWEAR--
YPEYGIAVH---------------------------------------------------
---KGYATKFHREQLQL-----------H-----GPTSMHR-------------RSF--L
KNME----------IEQLSLF-----------------------
>gi|261408005|ref|YP_003244246.1| Ribonuclease H [Paenibacillus sp. Y412MC10]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------MTDLLMYEREYWSR----YIHIAGI
DEV--------------------GRGCLFGDVVAAAVIMPE----------GLV-IEGIN
DS------KKLSAKKRETLYDLIME---QALAVG-V------GLVDAETIDRINIK----
---------QAARLAMKKAIEQLA-----------VPPQF-LLVDA-EKV--DCDIPQRA
------------IIKGD------ANSQSIGAASIIAKVTR-------DRLCEGEWEAR--
YPEYGIAVH---------------------------------------------------
---KGYATKFHREQLQL-----------H-----GPTAMHR-------------RSF--L
KNME----------IEQLSLF-----------------------
>gi|253573503|ref|ZP_04850846.1| ribonuclease HII [Paenibacillus sp. oral taxon 786 str. D14]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------MEDLLKYEREYWQA---GYSHIAGI
DEV--------------------GRGCLFGDVVAAAVILPQ----------GLV-LEDVN
DS------KKLSAKKREKLFDLIME---QAIAVG-I------GSVDAATIDQINIK----
---------QATRRAMKQAVEQLS-----------IQPEY-LLIDA-EKV--DVPIPQLS
------------VIKGD------ATSQSIAAASIVAKVTR-------DRLCQGEWDAR--
YPEYGIAVH---------------------------------------------------
---KGYATKLHREQLLA-----------L-----GPTPMHR-------------KSF--M
RNLF----------VEEQTLF-----------------------
>gi|308068634|ref|YP_003870239.1| ribonuclease HII [Paenibacillus polymyxa E681]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------MENKEIVAKDMLHYEKKCWEQ---SCERIAGI
DEV--------------------GRGCLFGDVVAAAVILPV----------GEL-LEGVD
DS------KKLTDKKREAYYELIME---KAIAVG-V------GYVDAHTIDDINIK----
---------QAARLAMKQAIEALH-----------VSPDY-LLVDA-EKV--DVSIPQLS
------------IIKGD------ANSQSIAAASIIAKVTR-------DRLCKGEWDAK--
YPEYGIGIH---------------------------------------------------
---KGYATKLHREQILA-----------L-----GPTEMHR-------------RSF--L
GNLL----------TEQPTLFDL---------------------
>gi|390454092|ref|ZP_10239620.1| ribonuclease H [Paenibacillus peoriae KCTC 3763]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------MEDKEVVVKDMLHYEKKCWEQ---SCERIAGI
DEV--------------------GRGCLFGDVVAAAVILPV----------GEL-LEGVD
DS------KKLTDKKREAYYELIME---KAIAVG-V------GYVNARTIDEINIK----
---------QAARLAMKQAIEALS-----------VSPDY-LLVDA-EKV--DVPIPQLS
------------IIKGD------ANSQSIAAASIIAKVTR-------DRLCKGEWDAK--
YPEYGIGIH---------------------------------------------------
---KGYATKLHREQILA-----------L-----GPTEMHR-------------RSF--L
GNLL----------TEQPTLFDL---------------------
>gi|375308201|ref|ZP_09773488.1| ribonuclease HII, partial [Paenibacillus sp. Aloe-11]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------PAVILPV----------GEL-LEGVD
DS------KKLTDKKREAYYELIME---KAIAVG-V------GYVNARTIDEINIK----
---------QAARLAMKQAIEALS-----------VSPDY-LLVDA-EKV--DVPIPQLS
------------IIKGD------ANSQSIAAASIIAKVTR-------DRLCRGEWDAK--
YPEYGIGIH---------------------------------------------------
---KGYATKLHREQILA-----------L-----GPTEMHR-------------RSF--L
GNLL----------TEQPTLFDL---------------------
>gi|310641522|ref|YP_003946280.1| ribonuclease hii [Paenibacillus polymyxa SC2]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------MMKLKLRKDGQVLNMEAKENAVKDMLHYEKKCWEQ---SCERIAGI
DEV--------------------GRGCLFGDVVAAAVILPV----------GEL-LEGVD
DS------KKLTDKKREAYYELIME---KAIAVG-V------GHVDARMIDEINIK----
---------QAARLAMKKAVEALH-----------VSPDY-LLVDA-EKV--DVPIPQLS
------------IIKGD------ANSQSIAAASIIAKVTR-------DRLCKGEWDAK--
YPEYGIGIH---------------------------------------------------
---KGYATKLHREQILA-----------L-----GPTEMHR-------------RSF--L
GNLL----------TEQPTLFDL---------------------
>gi|374323444|ref|YP_005076573.1| ribonuclease HII [Paenibacillus terrae HPL-003]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------MEEKAVTDMLRYEKECREQ---SYERIAGI
DEV--------------------GRGCLFGDVVAAAVILPN----------GEL-LEGVD
DS------KKLTDKKRETYYELIME---KAIAVG-V------GYVDARTIDAINIK----
---------QAARLAMKQAVEALH-----------VSPDY-LLVDA-EKV--DLPISQLS
------------IIKGD------ANSQSIAAASIIAKVTR-------DRLCKGEWDAK--
YPEYGIGIH---------------------------------------------------
---KGYATKLHREQILT-----------L-----GPTAMHR-------------RSF--L
GNLL----------IEQPTLFDL---------------------
>gi|402818517|ref|ZP_10868100.1| ribonuclease HII [Paenibacillus alvei DSM 29]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------MGKKKQETAAEPIDLLAWERQYWAR---SIRHIAGI
DEV--------------------GRGCLFGDVVAAAVILPE----------GLI-IEGIN
DS------KKLSEKKRDELYDIIIA---EAVAWS-V------AHVDAATIDQINIK----
---------QAARRAMKEAVETLD-----------IQPEV-LLVDA-EKI--DLPFTQEA
------------IIKGD------ANSQSIAAASIIAKVTR-------DRLCSGEWNDR--
YPEYGIAVH---------------------------------------------------
---KGYGTKMHREQLLI-----------H-----GPTPMHR-------------KSF--L
SSLF--------PKEEQLTLF-----------------------
>gi|374603431|ref|ZP_09676411.1| ribonuclease HII [Paenibacillus dendritiformis C454]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------MQEEGKIMGQRKTVDAEAEAIDLTAWEKRLWEE---GLQYVAGI
DEV--------------------GRGCLFGDVVAAAVILPA----------GVV-IDGIN
DS------KKLSAKKREALYEEITE---CAIAWS-V------AQVDASTIDRINIK----
---------QASRLAMKQAVEGLG-----------VRPDM-LLIDA-ERI--DCPLPQEA
------------IVKGD------ANSQSIAAASIVAKVTR-------DRLCAGLWDEM--
YPDYGIAVH---------------------------------------------------
---KGYATKLHREQLEQ-----------L-----GPTPMHR-------------KSF--L
KSLF--------PEEEQLSLF-----------------------
>gi|421860564|ref|ZP_16292670.1| ribonuclease HII [Paenibacillus popilliae ATCC 14706]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------MGQRKTVEAEAAAIDLTAWEKRLWDE---GLQYVAGI
DEV--------------------GRGCLFGDVVAAAVILPA----------GVV-IEGIN
DS------KKLSAKKREALYKEITE---RAIAWS-V------AQVDVSTIERINIK----
---------QASRLAMKQAVEGLG-----------IRPDM-LLIDA-ERI--DCPLPQEA
------------IVKGD------ANSQSIAAASIIAKVTR-------DQLCAGLWNEL--
YPEYGIAVH---------------------------------------------------
---KGYATKLHRQQLER-----------L-----GPTPMHR-------------KSF--L
KSLF--------PEEEQLSLF-----------------------
>gi|251797462|ref|YP_003012193.1| ribonuclease H [Paenibacillus sp. JDR-2]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------MLEYEERLWAE---GYSAIAGV
DEV--------------------GRGCLFGDVVAAAVILPP----------HLV-LEGVN
DS------KKLSEKKRNELYDIIVD---QSIAWA-A------ARVDAETIDRINIK----
---------QAARLAMKIALESLK-----------TEPDY-FLVDA-EKV--DLPKPQLA
------------IIKGD------ATSQSIAAASIIAKVTR-------DRLCEKEWEQL--
YPEYGIAIH---------------------------------------------------
---KGYATKLHRERLLE-----------Y-----GASPLHR-------------KSF--L
GKIF----------VEQQQLF-----------------------
>gi|304404228|ref|ZP_07385890.1| Ribonuclease H [Paenibacillus curdlanolyticus YK9]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------MLEYEKLLWEQ---GCSNIAGI
DEV--------------------GRGCLFGDVVAAAVILPP----------GLV-LDGVN
DS------KKLSEKKRNELYDIIIE---HALYWS-I------ARIDSDEIDRINIK----
---------QASRLAMKQAVQTLG-----------VDPDH-LLVDA-EKI--DLDLPQQA
------------IIKGD------ATSQSIAAASILAKVTR-------DRLCTTEWESL--
YPGYGIAIH---------------------------------------------------
---KGYATKLHREKLLE-----------L-----GPTPLHR-------------KSF--L
GNIM-------AQMEQQQMLF-----------------------
>gi|350550807|ref|ZP_08920104.1| Ribonuclease H [Thermobacillus composti KWC4]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------MESTDMLAQERELAQR---GFRAIAGV
DEV--------------------GRGCLFGDVVAAAVILPP----------DLH-LPDVN
DS------KKLTAKQRERCYEAIIK---QAVAWS-V------SRVGPEEIDRINIR----
---------QASRLAMKLAVEALS-----------VKPDH-LLIDA-ETI--DLDVPQLA
------------VVHGD------ARCQSIAAASIVAKVTR-------DRLCTDEWDRM--
YPEYGIAIH---------------------------------------------------
---KGYATKLHRERLLE-----------F-----GPSPMHR-------------RSF--L
GKLL----------DEQLTLF-----------------------
>gi|167463784|ref|ZP_02328873.1| Ribonuclease H [Paenibacillus larvae subsp. larvae BRL-230010]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------MKENKTSSSAKLKRKEKRKKAETPDLLQKEKELWAA---GYTAIAGI
DEV--------------------GRGCLFGDVVAAAVILPA----------DSY-IEEIN
DS------KKLTEKKREALFETIMN---EAVAVG-I------GRVDVQTIERINIK----
---------QAARLAMKLAVEELA-----------LAPDY-LLIDA-EKV--DLSFPQEA
------------VIHGD------ELSQSIAAASIVAKVTR-------DRLC-AEWDGL--
YPGYGIAGH---------------------------------------------------
---KGYATKEHREQIRL-----------L-----GPTPLHR-------------SLF--L
RNIL----------MEQQTLF-----------------------
>gi|334135575|ref|ZP_08509059.1| ribonuclease HII [Paenibacillus sp. HGF7]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------MLQEETGLWEK---GYSRIAGV
DEV--------------------GRGCLFGDVVAAAVIMPQ----------GLI-LEGVD
DS------KKLSEKKREELYDVIMK---EAIAVG-I------GTIDVKTIEEINIK----
---------QASRLAMKLAVEQLN-----------PAPDF-LLVDA-EKV--DLNTRQMA
------------IIHGD------ATSQSIAAASIIAKVTR-------DRMC-REWDKL--
HPEYGIAKH---------------------------------------------------
---KGYATRQHREMLIE-----------Y-----GPTPLHR-------------KLF--I
RNVL----------VMQQELF-----------------------
>gi|357014326|ref|ZP_09079325.1| ribonuclease HII [Paenibacillus elgii B69]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------MLEYEQELWGR---GKTLVAGV
DEV--------------------GRGCLFGDVVAAAVILPK----------GLV-LEGVD
DS------KKLSEKKREALYDVIRQ---EALSIG-I------GMADVDTIERINIK----
---------QAARLAMKRAVEQLD-----------PIPDS-LLVDA-EKV--DVDAEQLA
------------VIHGD------ALSQSIAAASIIAKVTR-------DRMC-LQWDME--
FPEYGIAIH---------------------------------------------------
---KGYATKMHRERLAE-----------Y-----GPSPMHR-------------KTF--L
RNIV----------YEQQVLF-----------------------
>gi|379722917|ref|YP_005315048.1| ribonuclease HII [Paenibacillus mucilaginosus 3016]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------MLEYEQSVWSA---GKRLVAGV
DEV--------------------GRGCLFGDVVAAAVILPQ----------GLV-LEEVN
DS------KKLSAKKRDKLYDIIRQ---EAVAVG-V------GIVDVETIEKINIR----
---------QASLLAMKLAVKSLE-----------VTPDY-LLVDA-EQV--NVPIEQMS
------------LIHGD------AVSQSIAAASIIAKVTR-------DRMC-LKWDEE--
FPGYGLADH---------------------------------------------------
---KGYATKFHRERILE-----------F-----GPTAMHR-------------SLF--L
RKLLGTGEEEEV---EQGVLF-----------------------
>gi|337750069|ref|YP_004644231.1| ribonuclease HII [Paenibacillus mucilaginosus KNP414]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------MLEYEQSVWSA---GKRLVAGV
DEV--------------------GRGCLFGDVVAAAVILPQ----------GLV-LEEVN
DS------KKLSAKKRDKLYDIIRQ---EAVAVG-V------GIVDVATIEKINIR----
---------QASLLAMKLAVKSLE-----------VTPDY-LLVDA-EQV--NVPIEQMS
------------LIHGD------AVSQSIAAASIIAKVTR-------DRMC-LKWDEE--
FPGYGLADH---------------------------------------------------
---KGYATKFHRERILE-----------F-----GPTAMHR-------------SLF--L
RKLL---GTGEEEEVEQGVLF-----------------------
>gi|403378826|ref|ZP_10920883.1| ribonuclease H [Paenibacillus sp. JC66]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------MLTYEKSLWDR---GYRLIAGV
DEV--------------------GRGCLFGDVVAAAVILPQ----------GLL-IEDIN
DS------KKLSAKKREELYEVICK---EAVAVS-T------GQVSSEMIDQINIK----
---------QAARLAMKQAVEGLS-----------IMPDY-LLIDA-ERI--DVNMEQMA
------------VIHGD------ALSQSIAAASIIAKVTR-------DRMC-LHWDRE--
YPEYGIAIH---------------------------------------------------
---KGYATKQHRESILQ-----------Y-----GPSRLHR-------------RSF--L
SKLL-----------NQQQQFPF---------------------
>gi|304440378|ref|ZP_07400267.1| ribonuclease HII [Peptoniphilus duerdenii ATCC BAA-1640]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------MIEIEKNYYDK---GLDLVCGI
DEV--------------------GRGCLFGDVVAAAVIMPK------------TRIPGVN
DS------KKLTELRRAELYDKILS---SCVAYG-I------GIMDSVTIDKINIK----
---------MATHLAMLLAVQNLR-----AKDGSKVDPNV-LLIDA-EHL--ETDIPQES
------------IVKGD------EKVYSIACASIVAKVYR-------DRLC-EKWGKE--
YPGYEIEKH---------------------------------------------------
---KGYGTKKHREILLE-----------K-----GPTPHHR-------------KSF--L
KNME-----------NWK--------------------------
>gi|417925866|ref|ZP_12569281.1| ribonuclease HII [Finegoldia magna SY403409CC001050417]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------MFAIDYNEFEE-----ELICGI
DEV--------------------GRGPLAGPVVTCAIIMPK----------NCEIIEGVT
DS------KKLSEKKRIKFKDMILN---QALAYS-V------NFVDQGVIDEINIK----
---------QATRLSMKRAVESLK-----TKDNKFIKPDL-IVIDA-EEI--DTDIKQMS
------------FVKGD------QKLYPISCASIVAKVIR-------DEYM-KEMAVI--
YPQYGFEKH---------------------------------------------------
---KGYGTKLHREMILE-----------Y-----GECPLHR-------------KTF--L
RKLY-----------ENGKKPR----------------------
>gi|169824229|ref|YP_001691840.1| ribonuclease HII [Finegoldia magna ATCC 29328]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------MFAIDYNEFEE-----ELICGI
DEV--------------------GRGPLAGPVVTCAIIMPK----------NCEIIEGVT
DS------KKLSEKKRIKFKDMILN---QALAYS-V------NFVDQGVIDEINIK----
---------QATRLSMKRAVESLK-----TKDNKFIKPDL-IVIDA-EEI--DTDIKQMS
------------FVKGD------EKLYPISCASIVAKVIR-------DEYM-KEMAVI--
YPQYGFEKH---------------------------------------------------
---KGYGTKLHREMILE-----------H-----GECPLHR-------------KTF--L
RKLY-----------ENGKKPR----------------------
>gi|303234893|ref|ZP_07321518.1| ribonuclease HII [Finegoldia magna BVS033A4]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------MFAIDYNEFEE-----ELICGI
DEV--------------------GRGPLAGPVVTCAIIMPK----------NCEIIDGVT
DS------KKLSEKKRIKFKDMILN---QALAYS-V------NFVDQGVIDEINIK----
---------QATRLSMKRAVESLK-----TKDNKFIKPDL-IVIDA-EEI--DTDIKQMS
------------FVKGD------EKLYPISCASIVAKVIR-------DEYM-KDMAVI--
YPQYGFEKH---------------------------------------------------
---KGYGTKLHREMILE-----------H-----GECPLHR-------------KTF--L
RKLY-----------ENGKKPR----------------------
>gi|302380879|ref|ZP_07269341.1| ribonuclease HII [Finegoldia magna ACS-171-V-Col3]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------MFAIDYNEFEE-----ELICGI
DEV--------------------GRGPLAGPVVTCAIIMPK----------NCEIIEGVT
DS------KKLSEKKRIKFKDMILN---QALAYS-V------DFVDQGVIDEINIK----
---------QATRLSMKKAVESLK-----TKDNKFIKPDL-IVIDA-EEI--DTDIKQMS
------------FVKGD------EKLYPISCASIVAKVIR-------DEYM-KEMAVI--
YPQYGFEKH---------------------------------------------------
---KGYGTKLHREMILE-----------Y-----GECPLHR-------------KTF--L
RKLY-----------ENGKKPR----------------------
>gi|297587481|ref|ZP_06946125.1| ribonuclease H [Finegoldia magna ATCC 53516]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------MFAIDYNEFEE-----ELICGV
DEV--------------------GRGPLAGPVVTCAIIMPK----------NCEIIDGVT
DS------KKLSEKKRIKFKDMILD---QALAYS-V------NFVDQSVIDEINIK----
---------QANRLSMKRAVESLK-----TKDNKFIKPDL-IVIDA-EKI--DTDIKQMS
------------FVKGD------EKLYPISCASIVAKVIR-------DEYM-KDMAVI--
YPQYGFEKH---------------------------------------------------
---KGYGTKLHREMILE-----------H-----GECPLHR-------------KTF--L
RKLY-----------ENGKKPR----------------------
>gi|227499923|ref|ZP_03930016.1| ribonuclease H [Anaerococcus tetradius ATCC 35098]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MKYSPYNDDIKRKVHEKYELIAGI
DEV--------------------GRGPLAGPVVTCALIMKK----------DSK-IEGVT
DS------KKLTRKKMLVLKDKILA---DCLTYA-Y------GYANSLLIDKLNIK----
---------NATHKAMEDALNNLK-----------IRPEI-VLIDA-ERI--NTDLPQMN
------------IVKGD------LNEYVISCASILAKIRR-------DDIM-INFSKI--
YKGYGFETN---------------------------------------------------
---MGYGTKKHYEGLEK-----------Y-----GETPIHR-------------QTF--L
RKFH-----------ERQMSFDDL--------------------
>gi|257066780|ref|YP_003153036.1| Ribonuclease H [Anaerococcus prevotii DSM 20548]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MRYSPYDDAIKKKVHEDYELIAGI
DEV--------------------GRGPLAGPVVTCAVIMKR----------DSN-IGGVT
DS------KKLTRKKMLSLKEKILD---DAIDFA-Y------GYANPSLIDELNIK----
---------NATHKAMEDALNKLK-----------IRPEI-VLIDA-ERI--NTDIPQMN
------------IVKGD------LNEYVISCASILAKVRR-------DDIM-INFSKI--
YPGYSFETN---------------------------------------------------
---MGYGTKKHYEGLEK-----------Y-----GETPIHR-------------QTF--L
RKFH----------ERQLSIYDL---------------------
>gi|417002753|ref|ZP_11942057.1| ribonuclease HII [Anaerococcus prevotii ACS-065-V-Col13]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MRYSLYNDQIKKEIHDKYKLIAGI
DEV--------------------GRGPLAGPVVTCAVIMKS----------DSA-IDGIT
DS------KKLSRKKMLNLKEKILE---DTICYA-Y------GYANPRLIDRVNIK----
---------NATHKAMEDALNNLK-----------IKPEI-VLIDA-ERI--DTDIPQLN
------------IVKGD------LNEYVISCASILAKIRR-------DDIM-INFSKL--
YPNYGFDTN---------------------------------------------------
---MGYGTKKHYQGLEE-----------Y-----GETSIHR-------------QTF--L
RKFH-----------ERQMTFDDL--------------------
>gi|227486581|ref|ZP_03916897.1| ribonuclease H [Anaerococcus lactolyticus ATCC 51172]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MKYSLYNDEIKKEIYETYDLIAGI
DEV--------------------GRGPLAGPVVTCAVIMKK----------NSH-IEGVT
DS------KKLSRKKMLVLKEKILA---DALAVS-Y------GFANSRKIDQINIR----
---------QATLQAMKDALDHLE-----------IRPDI-VLIDA-ERI--DTDLPQLN
------------IVKGD------LNEYAISCASILAKVRR-------DDIM-INFSKI--
YPGYGFETN---------------------------------------------------
---FGYGTKAHYQGLEQ-----------H-----GETPIHR-------------QSF--L
RKFH-----------ERQLSFI----------------------
>gi|256545488|ref|ZP_05472850.1| ribonuclease HII [Anaerococcus vaginalis ATCC 51170]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------MKKPRYSEFNDKIKNEIHEKYELIAGI
DEV--------------------GRGPLAGPVVACAVIMKK----------DSH-IEGVT
DS------KKLSKKRMNELYQKIID---DSISYS-F------GYANNILIDKINIK----
---------EATKLAMKDALEGLE-----------KKPQI-VLIDA-ERI--DTHIKQLN
------------IVKGD------LYEYAISCASILAKVRR-------DKIM-ENFSKI--
YPYYSFESN---------------------------------------------------
---VGYGTKKHYEGLEK-----------F-----GECPIHR-------------KTF--L
RKFY-----------ERQLSFL----------------------
>gi|375091719|ref|ZP_09738007.1| hypothetical protein HMPREF9709_00869 [Helcococcus kunzii ATCC 51366]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------MRIKLNRDQLEILLDKAK--------DYNSICGV
DEV--------------------GRGPIAGPVVSCAIVMG-----------GDH-IDGVK
DS------KKLTDKKRRELAKDIYS---RAIAIG-Y------GIVEHNIIDEINIR----
---------QASLLAMKQAIDNLS-----DKKGNPYKCDL-ALIDA-EII--EHDIDQIA
------------IISGD------DLVYEISCASILAKIFR-------DDIM-IEYSKK--
YPEYMFEAH---------------------------------------------------
---KGYGTKKHYEAIDE-----------Y-----GLTDIHR-------------KTF--M
KKYY-----------EQRNKSNR---------------------
>gi|312622766|ref|YP_004024379.1| ribonuclease h [Caldicellulosiruptor kronotskyensis 2002]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------MRLSEDENYFEIEEKLLNE---GYRFICGV
DEA--------------------GRGPLAGPVFAAAVVMDR----------KRI-IEGVR
DS------KKLTPKKREKLFEEIIK---ESIAYS-V------AMVDSKVIDEININ----
---------NATFLAMKNAIENLK-----------IEPDI-VLVDGYKIP--NLSFNQRA
------------IIKGD------KKSYSIACASILAKVSR-------DRFI-VEISSK--
YPLYKFEKH---------------------------------------------------
---KGYGTKEHIEILQK-----------Y-----GPCEIHR-------------ISF--L
KNIL-----------SL---------------------------
>gi|222528967|ref|YP_002572849.1| ribonuclease HII [Caldicellulosiruptor bescii DSM 6725]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------MRLSEDENYFEIEEKLLNE---GYRFICGV
DEA--------------------GRGPLAGPVFAAAVVMDR----------KRI-IEGVR
DS------KKLTPKKREKLFEEIIK---ESIAYS-V------AMVDSKVIDEININ----
---------NATFLAMKNAIENLK-----------IEPDI-VLVDGYKIP--NLGFNQRA
------------IIKGD------RKSYSIACASILAKVSR-------DRYI-VEISSK--
YPLYKFEKH---------------------------------------------------
---KGYGTKEHIEILQK-----------Y-----GPCEIHR-------------ISF--L
KNIL-----------SL---------------------------
>gi|312127966|ref|YP_003992840.1| ribonuclease h [Caldicellulosiruptor hydrothermalis 108]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------MRLSEDENYFEIEEKLLNE---GYRFICGV
DEA--------------------GRGPLAGPVFAAAVVMDR----------KRI-IEGVR
DS------KKLTPKKREKLFEEIIK---ESIAYS-V------AMVDSKIIDEININ----
---------NATFLAMKNAIENLK-----------IEPDI-VLVDGYEIP--NLGFNQRA
------------IIKGD------RKSYSIACASILAKVSR-------DRYI-VEISSK--
YPLYKFEKH---------------------------------------------------
---KGYGTKEHIEILQK-----------Y-----GPCEIHR-------------ISF--L
KNIL-----------SF---------------------------
>gi|302872177|ref|YP_003840813.1| Ribonuclease H [Caldicellulosiruptor obsidiansis OB47]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------MRLSEDENYFEIEEKLLNE---GYRFICGV
DEA--------------------GRGPLAGPVFAAAVVMDR----------KRI-IEGVR
DS------KKLTPKKREKLFEEIIK---GSIAYS-V------AMVDSKIIDEININ----
---------NATFLVMKNAIENLK-----------IEPDI-VLVDGYEIP--NLNFNQRA
------------IIKGD------RKSYSIACASILAKVSR-------DRYI-VEISSK--
YPLYKFEKH---------------------------------------------------
---KGYGTKEHIEILQK-----------Y-----GPCEIHR-------------ISF--L
KNIL-----------SL---------------------------
>gi|312134790|ref|YP_004002128.1| ribonuclease h [Caldicellulosiruptor owensensis OL]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------MRLSEDENYFEIEEKLLNE---GYRFICGV
DEA--------------------GRGPLAGPVFAAAVVMDR----------KRI-IEGVR
DS------KKLTPKKREKLFEEIIK---ESIAYS-V------AMVDSKIIDEININ----
---------NATFSAMKNAIENLK-----------IEPDI-VLVDGYEIP--NLNFNQRA
------------IIKGD------RKSYSIACASILAKVSR-------DRYI-VEISSK--
YPLYKFEKH---------------------------------------------------
---KGYGTKEHIEILRK-----------Y-----GPCEIHR-------------ISF--L
KNIL-----------SL---------------------------
>gi|312793164|ref|YP_004026087.1| ribonuclease h [Caldicellulosiruptor kristjanssonii 177R1B]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------MRLLEDENYFEIEEKLLNE---GYRFICGV
DEA--------------------GRGPLAGPVFAAAVVMDR----------KKI-IEGVR
DS------KKLTPKKREKLFDEIIK---ESIAYS-V------AMVDSKIIDEININ----
---------NATFLAMKNAIENLK-----------IEPDI-VLVDGYEIP--NLSFNQMA
------------IIKGD------RKSYSIACASILAKVSR-------DRYI-VEISSK--
YPVYKFEKH---------------------------------------------------
---KGYGTKEHIEILQK-----------Y-----GPCEIHR-------------ISF--L
KNIL-----------SL---------------------------
>gi|344996623|ref|YP_004798966.1| ribonuclease HII/HIII [Caldicellulosiruptor lactoaceticus 6A]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------MRLSEDENYFEIEEKLLNE---GYRFICGV
DEA--------------------GRGPLAGPVFAAAVVMDR----------KRI-IEGVR
DS------KKLTPKKREKLFDEIIK---ESIAYS-V------AMVDSKIIDEININ----
---------NATFLAMKNAIENLK-----------IEPDI-VLVDGYEIP--NLSFNQMA
------------IIKGD------RKSYSIACASILAKVSR-------DRYI-VEISSK--
YPVYKFEKH---------------------------------------------------
---KGYGTKEHIEILQK-----------Y-----GPCEIHR-------------ISF--L
KNIL-----------SL---------------------------
>gi|146297153|ref|YP_001180924.1| ribonuclease HII [Caldicellulosiruptor saccharolyticus DSM 8903]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------MKLGIDENYFELEENLLKE---GYRFICGV
DEA--------------------GRGPLAGPVFAAAVIMDR----------EII-IEGVR
DS------KKLTPKKREKLFEEIVK---ESITYS-V------AMVDNKTIDEININ----
---------NATFLAMKNAIEALE-----------LVPDI-VLVDGYEIP--DLNLPQKA
------------LIKGD------RKSYSIACASILAKVSR-------DRFI-TQISSL--
YPVYKFEKH---------------------------------------------------
---KGYGTKEHIRLILE-----------Y-----GPCEIHR-------------KSF--L
KNIL-----------R----------------------------
>gi|429123912|ref|ZP_19184444.1| ribonuclease HII [Brachyspira sp. 30446]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------MFFDNKEDKFVYEREYLSL---GHKYICGI
DEV--------------------GRGCLFGPVTAAAVIMPLELYNDTELKRENI-VEDID
DS------KKISAKKREELYDKIID---KALSFS-I------YSVDSKTIDEINIY----
---------NAVKLAMIKSIENLT-----------IKPDI-LLIDA-MKL--DTSIKQCS
------------IIKGD------SKSYSIGCASILAKVYR-------DRMM-NELSDF--
YQKYRVSKN---------------------------------------------------
---KGYGTKEHIKTIEM-----------Y-----GPSDMHR-------------YSFDPI
KSNY--------KKTEDNLLL-----------------------
>gi|404431583|emb|CCG57629.1| ribonuclease HII [Brachyspira pilosicoli WesB]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------MYFFDNEENEEIDKLHYEKYYLDL---GYKYICGI
DEV--------------------GRGSLFGEVTACAVIMPL----------DDDIIKEAN
DS------KKLTAKKREELYKIIIQ---KALSYS-V------YSVAANTIDKINIY----
---------NATKLAMLKAVEGLS-----------IKPDI-LLIDA-MKI--DTEIKQES
------------IIKGD------LKSYSIACASIVAKVSR-------DKAMDRLSEKNKE
YDKYKISKN---------------------------------------------------
---KGYGTKEHIEAIKK-----------Y-----GASDLHR-------------LSFEPI
KSIK-----------EENSFFI----------------------
>gi|300870469|ref|YP_003785340.1| ribonuclease HII [Brachyspira pilosicoli 95/1000]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------MYFFDNEENEEIDKLHYEKYYLDL---GYKYICGI
DEV--------------------GRGSLFGEVTACAVIMPL----------DDDIIKEAN
DS------KKLTAKKREELYKIIIQ---KALSYS-V------YSVAANTIDKINIY----
---------NATKLAMLKAVEGLS-----------IKPDI-LLIDA-MKI--DTEIKQES
------------IIKGD------LKSYSIACASIVAKVSR-------DKAMNILSEKNKE
YDKYKISKN---------------------------------------------------
---KGYGTKEHIEAIKK-----------Y-----GASDLHR-------------LSFEPI
KSIK-----------EENSFFI----------------------
>gi|116514255|ref|YP_813161.1| ribonuclease HII [Lactobacillus delbrueckii subsp. bulgaricus ATCC BAA-365]
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------MKINEIKDLLQA------DSID
PAILAELAKDDRKGVQKLLVSYQRRQEKLAKQKEEFLGRFSYEKDFWAK---G-QLVGGV
DEV--------------------GRGPLAGPVVAAAVILPE----------DFS-LLEVN
DS------KKLSPQKRLALYPKILQ---EAVAVG-V------GVMDNKVIDQINIY----
---------EADRLAMKQAVEALS-----------TRPDV-LLVDA-MNV--PVDLPQLE
------------LIKGD------AKSNSIAAASIVAKVFR-------DSLM-DDYARL--
YPDYAFDHN---------------------------------------------------
---AGYGTKDHLEALRK-----------Y-----GPTPIHR-------------LTFSPV
SEMV-----------GLKKAD-----------------------
>gi|104774162|ref|YP_619142.1| ribonuclease HII [Lactobacillus delbrueckii subsp. bulgaricus ATCC 11842]
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------MKINEIKDLLQA------DSID
PAILAELAKDDRKGVQKLLVSYQRRQEKLAKQKEEFLGRFSYEKDFWAK---G-QLVGGV
DEV--------------------GRGPLAGPVVAAAVILPE----------DFS-LLEVN
DS------KKLSPQKRLALYPKILQ---EAVAVG-V------GVMDNKVIDQINIY----
---------EADRLAMKQAVEALS-----------TRPDA-LLVDA-MNV--PVDLPQLE
------------LIKGD------AKSNSIAAASIVAKVFR-------DSLM-DDYARL--
YPDYAFDHN---------------------------------------------------
---AGYGTKDHLEALRK-----------Y-----GPTPIHR-------------LTFSPV
SEMV-----------GLKKAD-----------------------
>gi|300812547|ref|ZP_07092964.1| ribonuclease HII [Lactobacillus delbrueckii subsp. bulgaricus PB2003/044-T3-4]
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------MKINEIKDLLQA------DSID
PAILAELAKDDRKGVQKLLVSYQRRQEKLAKQKEEFLGRFSYEKDFWAK---G-QLVAGV
DEV--------------------GRGPLAGPVVAAAVILPE----------DFS-LLEVN
DS------KKLSPQKRLALYPKILQ---EAVAVG-V------GVMDNKVIDQINIY----
---------EADRLAMKQAVEALS-----------TRPDA-LLVDA-MNV--PVDLPQLE
------------LIKGD------AKSNSIAAASIVAKVFR-------DSLM-DDYARL--
YPDYAFDHN---------------------------------------------------
---AGYGTKDHLEALRK-----------Y-----GPTPIHR-------------LTFSPV
SEMV-----------GLKKAD-----------------------
>gi|422843895|ref|ZP_16890605.1| ribonuclease HII [Lactobacillus delbrueckii subsp. lactis DSM 20072]
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------MKINEIKDLLQA------DSID
PAILAELAKDDRKGVQKLLVSYQRRQEKLAKQKEEFLGRFSYEKDFWAK---G-QLVAGV
DEV--------------------GRGPLAGPVVAAAVILPE----------DFS-LLEVN
DS------KKLSPQKRLVLYPKILQ---EAVAVG-V------GVMDNKVIDQINIY----
---------EADRLAMKQAVEALS-----------TRPDA-LLVDA-MNV--PVDLPQLE
------------LIKGD------AKSNSIAAASIVAKVFR-------DSLM-DDYARL--
YPDYAFDHN---------------------------------------------------
---AGYGTKDHLEALRK-----------Y-----GPTPIHR-------------LTFSPV
SEMV-----------GLKKAD-----------------------
>gi|385815908|ref|YP_005852299.1| Ribonuclease HII [Lactobacillus delbrueckii subsp. bulgaricus 2038]
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------MKINEIKDLLQA------DSID
PAILAELAKDDRKGVQKLLVSYQRRQEKLAKQKEEFLGRFSYEKDFWAK---G-QLVGGV
DEV--------------------GRGPLAGPVVAAAVILPE----------DFS-LLEVN
DS------KKLSPQKRLALYPKILQ---EAVAVG-V------GVMDNKVIDQINIY----
---------EADRLAMKQAVEALS-----------IRPDA-LLVDA-MNV--PVDLPQLE
------------LIKGD------AKSNSIAAASIVAKVFR-------DSLM-DDYARL--
YPDYAFDHN---------------------------------------------------
---AGYGTKDHLEALRK-----------Y-----GPTPIHR-------------LTFSPV
SEMV-----------GLKKAD-----------------------
>gi|313123917|ref|YP_004034176.1| ribonuclease hii [Lactobacillus delbrueckii subsp. bulgaricus ND02]
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------MKINEIKDLLQA------DSID
PAILAEFAKDDRKGVQKLLVSYQRRQEKLAKQKEEFLGRFSYEKDFWAK---G-QLVAGV
DEV--------------------GRGPLAGPVVAAAVILPE----------DFS-LLEVN
DS------KKLSPQKRLTLYPKILQ---EAVAVG-V------GVMDNKVIDQINIY----
---------EADRLAMKQAVEALS-----------TRPDA-LLVDA-MNV--PVDLPQLE
------------LIKGD------AKSNSIAAASIVAKVFR-------DSLM-DDYARL--
YPDYAFDHN---------------------------------------------------
---AGYGTKDHLEALRK-----------Y-----GPTPIHR-------------LTFSPV
SEMV-----------GLKKAD-----------------------
>gi|409349424|ref|ZP_11232891.1| Ribonuclease HII [Lactobacillus equicursoris CIP 110162]
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------MKINEIKDLLK------QENPD
PALLEKLREDPRKGVAQLLASYDRRQEKLKKKKAEFLGRFAYEKAFWQS---G-QLVAGV
DEV--------------------GRGPLAGPVVAAAVILPE----------DFD-LIEVN
DS------KKVSPARRLALYPQILE---KAVAVG-I------GLMDNQVIDQINIY----
---------EADRQAMKQAVEKLS-----------VKPDA-LLVDA-MNV--PVDLPQTE
------------LIKGD------AKSNSIAAASIVAKVYR-------DQLM-DEYAKT--
YPQYGFERN---------------------------------------------------
---AGYGTSEHLKALAE-----------F-----GPTPIHR-------------LTFAPV
KESL-----------EQHRKN-----------------------
>gi|408410160|ref|ZP_11181401.1| Ribonuclease HII [Lactobacillus sp. 66c]
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------MKINEIKDLLK------QENPD
PALLEKLREDPRKGVAQLLASYDRRQEKLKKKRAEFLGRFAYEKAFWQR---G-QLVAGI
DEV--------------------GRGPLAGPVVAAAVILPE----------DFD-LIEVN
DS------KKVSPARRLALYPQILE---KAVAVG-I------GLMDNQVIDQINIY----
---------EADRQAMKQAVEKLS-----------VKPDA-LLVDA-MNV--PVDLPQTE
------------LIKGD------AKSNSIAAASIVAKVYR-------DQLM-DEYAKA--
YPQYGFERN---------------------------------------------------
---AGYGTSEHLKALAE-----------F-----GPTPIHR-------------LTFAPV
KESL-----------EQHQKN-----------------------
>gi|395243568|ref|ZP_10420553.1| Ribonuclease HII [Lactobacillus hominis CRBIP 24.179]
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------MTVTEIKQLLASC------HVS
KEQLDELSQDPRKGVQKLINSYLKKQEKLAVKKEAFLQRFSFEKKYWDK---GLK-VAGV
DEV--------------------GRGPLAGPVVTAAVILSE----------DFD-LIDVN
DS------KKLSPKRRLELFPKILD---QAVAVS-V------GLANNDVIDQINIY----
---------EADRVAMAHAVEGLT-----------IKPDA-LLVDA-MNV--PVDLPQTS
------------LIKGD------SKSNSIAAASIVAKVFR-------DSLM-NAYGEK--
YPQYGFDQN---------------------------------------------------
---AGYGTKQHIEALKK-----------Y-----GPTPIHR-------------MTFAPV
SEFN-----------KN---------------------------
>gi|282852052|ref|ZP_06261410.1| ribonuclease HII [Lactobacillus gasseri 224-1]
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------MTITEIRNLL----QGEVS
SEQLEELRADERKGVQKLLISYEKRQAKRAQAVAQFQDRFSYEKKFWQK----SQLVAGV
DEV--------------------GRGPLAGPVVTAAVILPH----------NFD-LIDVN
DS------KKLSPKKRKELFPKILA---KAVSVG-V------GLANNDVIDRINIY----
---------EADRLAMAHAVQGLK-----------VKPDA-LLVDA-MNV--PLNIPQVK
------------LIHGD------AKSNSIAAASIVAKVFR-------DNLM-DAYGEV--
YPEYDFKHN---------------------------------------------------
---AGYGTREHMEALKK-----------Y-----GPTPIHR-------------RSFAPV
SEYE-----------K----------------------------
>gi|116629569|ref|YP_814741.1| ribonuclease HII [Lactobacillus gasseri ATCC 33323]
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------MTITEIRNLL----QGEVS
SEQLEELRADERKGVQKLLISYEKRQAKRAQAVAQFQDRFSYEKKFWQK----SQLVAGV
DEV--------------------GRGPLAGPVVTAAVILPH----------NFD-LIDVN
DS------KKLSPKKRKELFPKILA---KAVSVS-V------GLANNDVIDRINIY----
---------EADRLAMAHAVQGLK-----------VKPDA-LLVDA-MNV--PLNIPQVK
------------LIHGD------AKSNSIAAASIVAKVFR-------DNLM-DAYGEV--
YPEYDFKHN---------------------------------------------------
---AGYGTREHMEALKK-----------Y-----GPTPIHR-------------RSFAPV
SEYE-----------K----------------------------
>gi|238853072|ref|ZP_04643464.1| ribonuclease HII [Lactobacillus gasseri 202-4]
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------MTITEIRNLL----QGEVS
SEQLEELRADERKGVQKLLISYEKRQAKRAQAVAQFQDRFSYEKKFGQK----SQLVAGV
DEV--------------------GRGPLAGPVVTAAVILPH----------NFD-LIDVN
DS------KKLSPKKRKELFPKILA---KAVSVS-V------GLANNDVIDRINIY----
---------EADRLAMAHAVQGLK-----------VKPDA-LLVDA-MNV--PLNIPQVK
------------LIHGD------AKSNSIAAASIVAKVFR-------DNLM-DAYGEV--
YPEYDFKHN---------------------------------------------------
---AGYGTREHMEALKK-----------Y-----GPTPIHR-------------RSFAPV
SEYE-----------K----------------------------
>gi|321315372|ref|YP_004207659.1| ribonuclease HII [Bacillus subtilis BSn5]
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------MNTLTVKDIKDRLQEV----KDAQD
PFI-AQCENDPRKSVQTLVEQWLKKQAKEKALKEQWVNMTSYERLARNK---GFRLMAGV
DEV--------------------GRGPLAGPVVASAVILPE----------ECE-ILGLT
DS------KKLSEKKREEYYELIMK---EALAVG-I------GIVEATVIDEINIY----
---------EASKMAMVKAIQDLS-----------DTPDY-LLVDA-MTL--PLDTAQAS
------------IIKGD------AKSVSIAAAACIAKVTR-------DRMM-SAYAET--
YPMYGFEKN---------------------------------------------------
---KGYGTKEHLEALAA-----------Y-----GPTELHR-------------KTFAPV
QSFR----------------------------------------
>gi|16078669|ref|NP_389488.1| ribonuclease HII [Bacillus subtilis subsp. subtilis str. 168]
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------MNTLTVKDIKDRLQEV----KDAQD
PFI-AQCENDPRKSVQTLVEQWLKKQAKEKALKEQWVNMTSYERLARNK---GFRLIAGV
DEV--------------------GRGPLAGPVVASAVILPE----------ECE-ILGLT
DS------KKLSEKKREEYYELIMK---EALAVG-I------GIVEATVIDEINIY----
---------EASKMAMVKAIQDLS-----------DTPDY-LLVDA-MTL--PLDTAQAS
------------IIKGD------AKSVSIAAGACIAKVTR-------DRMM-SAYAET--
YPMYGFEKN---------------------------------------------------
---KGYGTKEHLEALAA-----------Y-----GPTELHR-------------KTFAPV
QSFR----------------------------------------
>gi|418033248|ref|ZP_12671725.1| ribonuclease HII [Bacillus subtilis subsp. subtilis str. SC-8]
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------MNTLTVKDIKDRLQEV----KDAQD
PFI-AQCENDPRKSVQTLVEQWLKKQAKEKALKEQWVNMTSYERLARNK---GFRLIAGV
DEV--------------------GRGPLAGPVVASAVILPE----------ECE-ILGLT
DS------KKLSEKKREEYYELIMK---EALAVG-I------GIVEATVIDEINIY----
---------EASKMAMVKAIQDLS-----------DTPDY-LLVDA-MTL--PLDTAQAS
------------IIKGD------AKSVSIAAGACIAKVTR-------DRMM-SAYAET--
YPVYGFEKN---------------------------------------------------
---KGYGTKEHLEALAA-----------Y-----GPTELHR-------------KTFAPV
QSFR----------------------------------------
>gi|428279200|ref|YP_005560935.1| ribonuclease HII [Bacillus subtilis subsp. natto BEST195]
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------MNTLTVKDIKDRLQEV----KDAQD
PFI-AQCENDPRKSVQTLVEQWLKKQAKEKALKEQWVNMTSYERLARNK---GFRLIAGV
DEV--------------------GRGPLAGPVVASAVILPE----------ECE-ILGLT
DS------KKLSEKKREEYYELIMK---EALAVG-I------GIVEATVIDEINIY----
---------EASKMAMVKAIQDLS-----------GTPDY-LLVDA-MTL--PLDTAQAS
------------IIKGD------AKSVSIAAGACIAKVTR-------DRMM-SAYAET--
YPMYGFEKN---------------------------------------------------
---KGYGTKEHLEALAA-----------Y-----GPTELHR-------------KTFAPV
QSFR----------------------------------------
>gi|386758329|ref|YP_006231545.1| ribonuclease HII [Bacillus sp. JS]
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------MNTLTVKDIKDRLQEV----KDAQD
PFI-AQCENDPRKSVQTLVEQWLKKQAKEKALKEQWVNMTSYERLARNK---GFRLIAGV
DEV--------------------GRGPLAGPVVASAVILPE----------ECE-ILGLT
DS------KKLSEKKREEFYELIMK---EAMAVG-I------GIVEAAVIDEINIY----
---------EASKMAMVKAIQDLS-----------DTPDY-LLVDA-MTL--PLDMAQSS
------------IIKGD------AKSVSIAAGACIAKVTR-------DRMM-SAYSDT--
YPMYGFEKN---------------------------------------------------
---KGYGTKEHLEALAA-----------Y-----GPTELHR-------------KTFAPV
QSFS----------------------------------------
>gi|296330821|ref|ZP_06873296.1| ribonuclease HII [Bacillus subtilis subsp. spizizenii ATCC 6633]
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------MNTLTVKDIKDRLQEV----KDEQD
PFL-AQCENDPRKSVQTLVEQWIKKQAKEKALKEQWVNMTSYERLARNK---GFRLIAGV
DEV--------------------GRGPLAGPVVASAVILPE----------ECE-ILGLT
DS------KKLSEKKRDEYYELIMK---EALAVG-I------GIVEASVIDEVNIY----
---------EASKMAMVKAIHDLS-----------DTPDY-LLVDA-MTL--PVGIDQSS
------------IIKGD------AKSVSIAAGACIAKVTR-------DRMM-SAYAET--
YPIYGFEKN---------------------------------------------------
---KGYGTKEHLEALAA-----------H-----GPTELHR-------------KTFAPV
QSFR----------------------------------------
>gi|398310702|ref|ZP_10514176.1| ribonuclease HII [Bacillus mojavensis RO-H-1]
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------MNTLTVKDIRDRLQGV----KDDQD
PFL-VQCENDPRKSVQALVEQWLKKHAKEKALKEQWMNMTSYERLARNK---GFRFIAGV
DEV--------------------GRGPLAGPVVASAVILPE----------ECE-ILGLT
DS------KKLTEKKREEYYDLIMK---EAVAVG-I------GIVEAAVIDEINIY----
---------EASKLAMVEAIRDLS-----------DTPDY-LLVDA-MTL--PLDTSQSS
------------IIKGD------AKSVSIAAGACIAKVTR-------DRMM-SSYAEK--
YPQYGFEKN---------------------------------------------------
---KGYGTKEHLEALAA-----------Y-----GPTDLHR-------------KTFAPV
QSYR----------------------------------------
>gi|311068127|ref|YP_003973050.1| ribonuclease HII [Bacillus atrophaeus 1942]
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------MNTLTVKDIKDRLQEV----KDERD
PFL-AECEKDQRKSVQTLVEQWLKKNAKEKALKEQWESMTHCERLARNK---GFCIIAGI
DEV--------------------GRGPLAGPVVASAVILPA----------ECE-ILGLT
DS------KKLSEKKREEYYERIMN---EALGVG-I------GIIEASVIDEMNIY----
---------EASKLAMVKAVRELS-----------EAPDY-LLVDA-MTL--PLDIPQSS
------------IIKGD------AKSVSIAAGACVAKVTR-------DRMM-SEYAKT--
YPMYGFEKH---------------------------------------------------
---KGYGTKEHLEALAA-----------Y-----GPTDIHR-------------RTFAPV
QTYC----------------------------------------
>gi|52080208|ref|YP_078999.1| ribonuclease HII [Bacillus licheniformis DSM 13 = ATCC 14580]
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------MKTLTVKEIKEHLQSV----SDEKD
PFI-EQCKNDERKSVQALVDAWLKKNERLSAMREEWQAMTSFERSLRAR---GYQYIAGI
DEA--------------------GRGPLAGPVVAAAVILKE----------DCE-ILGLT
DS------KKLSKQKREDYYSYIME---EAAAVG-V------GIADAHEIDELNIY----
---------EASKAAMLKAVQALD-----------VAPDY-LLIDA-MSL--AVDTEQSS
------------IIKGD------AKSASIAAGACIAKVTR-------DRLM-DEYAEK--
YPLYGFEKH---------------------------------------------------
---KGYGTKEHLNALAK-----------Y-----GPSPIHR-------------RSFAPV
KAHE----------------------------------------
>gi|332686610|ref|YP_004456384.1| ribonuclease HII [Melissococcus plutonius ATCC 35311]
------------------------------------------------------------
------------------------------------------------------------
--------------------------------MSKKNSESIQQIKDQLNLL----TDEED
PRL-SIWQLDQRIGVQKALKQWQNRQKKKQEKQIHYQKMQQFEKKAMQE---GYQAIAGI
DEV--------------------GRGPLAGPVVAAAVILPE----------DCQ-IFELN
DS------KQLSAKTRERLFDEIGK---KALAIG-I------GLVSHETIDEINIY----
---------QATKQAMIQAVANLQ-----------RIPDY-LLIDA-MTL--PLTTIQQS
------------IIKGD------ARSLSIAAASIVAKVTR-------DRLM-VHYAAE--
FPGYGFEKN---------------------------------------------------
---AGYGTKEHLEGLKK-----------Q-----GISPIHR-------------KTFAPI
KTMI-----------TI---------------------------
>gi|379727378|ref|YP_005319563.1| ribonuclease HII [Melissococcus plutonius DAT561]
------------------------------------------------------------
------------------------------------------------------------
--------------------------------MSKKNSESIQQIKDQLNLL----TDEED
PRL-SIWQLDQRIGVQKALKQWQNRQKKKQEKQIHYQKMQQFEKKAMQE---GYQAIAGI
DEV--------------------GRGPLAGPVVAAAVILPE----------DCQ-IFELN
DS------KQLSAKTRERLFDEIGK---KALAIG-I------GLVSHETIDEINIY----
---------QATKQAMIQAVANLQ-----------RIPDY-LLIDA-MTL--PLTTTQQS
------------IIKGD------ARSLSIAAASIVAKVTR-------DRLM-VHYAAE--
FPGYGFEKN---------------------------------------------------
---AGYGTKEHLEGLKK-----------Q-----GISPIHR-------------KTFAPI
KTMI-----------TI---------------------------
>gi|328957389|ref|YP_004374775.1| ribonuclease HII [Carnobacterium sp. 17-4]
------------------------------------------------------------
------------------------------------------------------------
----------------------------------MEKPLTITAIKELLTTI----THTDD
ERL-VFIKSDSRKGVLNAYKSWENQMRKQQLILEKQQEMLQIEQFFWEQ---GTQFVAGI
DEV--------------------GRGPLAGPVVAAAVILPQ----------DFN-VLEIN
DS------KQLSSAKREVLFDQIQE---SALAIG-I------GIKDHQVIDKVNIY----
---------QATKLAMIEAVEQLP-----------QQPEQ-LLIDA-MHL--PITIPQES
------------FIKGD------SKSLSIAAASIIAKVTR-------DRMM-AEYDTL--
YPGYGFSKN---------------------------------------------------
---AGYGTKIHLEGLEK-----------H-----GICPIHR-------------KTFAPV
KNLL-----------G----------------------------
>gi|406579907|ref|ZP_11055132.1| ribonuclease HII [Enterococcus sp. GMD4E]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MTESIQSIKERLKSI----QRIDD
PTL-ESLRNDPRKGVQQALASFERRLKKEALIKEKYEEMFCFEKQGYAQ---GHQWIAGI
DEV--------------------GRGPLAGPVVAAAVILSK----------NEI-ILGLN
DS------KQLSEKKRELLYQQVQE---KALAIG-I------GIVDQQTIDDVNIY----
---------EASKLAMIQAVEKLS-----------IVPSY-LLIDA-MTL--DLPIQQEK
------------IIKGD------ARSVSIAAASIIAKVYR-------DQLM-KEYDVL--
YPGYGFSHN---------------------------------------------------
---AGYGTKEHLEGLER-----------Q-----GITPIHR-------------KSFAPV
KKYL-----------Q----------------------------
>gi|257878020|ref|ZP_05657673.1| ribonuclease HII [Enterococcus faecium 1,230,933]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MTESIQSIKERLKSI----QRIDD
PTL-ESLRNDPRKGVQQALASFERRLKKEALIKEKYEEMFCFEKQGYAQ---GHQWIAGI
DEV--------------------GRGPLAGPVVAAAVILPK----------NEI-ILGLN
DS------KQLSEKKRELLYQQVQE---KALAIG-I------GIVDQQTIDDVNIY----
---------EASKLAMIQAVEKLS-----------IVPSY-LLIDA-MTL--DLPIQQEK
------------IIKGD------ARSVSIAAASIIAKVYR-------DQLM-KEYDVL--
YPGYGFSHN---------------------------------------------------
---AGYGTKEHLEGLER-----------Q-----GITPIHR-------------KSFAPV
KKYL-----------Q----------------------------
>gi|416134963|ref|ZP_11598424.1| ribonuclease HII [Enterococcus faecium E4452]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MTESIQSIKERLKSI----QRIDD
PTL-ESLRNDPRKGVQQALASFERRLKKEALIKEKYEEMFCFEKQGYAQ---GHQWIAGI
DEV--------------------GRGPLAGPVVAAAVILPK----------NEI-ILGLN
DS------KQLSEKKRELLYQQVQE---KALAIG-I------GIVDQQTIDDVNIY----
---------EASKLAMIQAVEKLS-----------IVPSY-LLIDA-MTL--DLPIQQEK
------------IIKGD------ARSVSIAAASIIAKVYR-------DQLM-KEYDVL--
YPGYGFLHN---------------------------------------------------
---AGYGTKEHLEGLER-----------Q-----GITPIHR-------------KSFAPV
KKYL-----------Q----------------------------
>gi|257884857|ref|ZP_05664510.1| ribonuclease HII [Enterococcus faecium 1,231,501]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MTESIQSIKERLKSI----QRIDD
PTL-ESLRNDPRKGVQQALASFERRLKKEALIKEKYEEMFCFEKQGYAQ---GHQWIAGI
DEV--------------------GRGPLAGPVVAAAVILPK----------NEI-ILGLN
DS------KQLSEKKRELLYQQVQE---KALAIG-I------GIVDQQTIDDVNIY----
---------EASKLAMFQAVEKLS-----------IVPSY-LLIDA-MTL--DLPIQQEK
------------IIKGD------ARSVSIAAASIIAKVYR-------DQLM-KEYDVL--
YPGYGFSHN---------------------------------------------------
---AGYGTKEHLEGLER-----------Q-----GITPIHR-------------KSFAPV
KKYL----------------------------------------
>gi|227551191|ref|ZP_03981240.1| ribonuclease H [Enterococcus faecium TX1330]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MTESIQSIKERLKSI----QRIDD
PTL-ESLRNDPRKGVQQALVSFERRLKKEALIKEKYEEMFCFEKQGYAQ---GHQWIAGI
DEV--------------------GRGPLAGPVVAAAVILPK----------NEI-ILGLN
DS------KQLSEKKRELLSQQIQE---KALAIG-I------GIIDQQTIDEVNIY----
---------EASKLAMIQAVENLS-----------IAPSY-LLIDA-MTL--DLSIQQEK
------------IIKGD------ARSVSIAAASIIAKVYR-------DQLM-KEYDVL--
YPGYGFSHN---------------------------------------------------
---AGYGTKEHLEGLER-----------Q-----GITPIHR-------------KSFAPV
KKYL-----------Q----------------------------
>gi|392989831|ref|YP_006488424.1| ribonuclease HII [Enterococcus hirae ATCC 9790]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------MIQEKYLEMSLFEKQAYEQ---GYEWIAGI
DEV--------------------GRGPLAGPVVAAAVILPK----------DEP-ILGLN
DS------KQLSEKKRELLYDQIQQ---KALAIG-I------GIIDEKKIDEVNIY----
---------EASKLAMIQAVEKLA-----------IRPNY-LLIDA-MTL--DLPIQQEK
------------LIKGD------ARSVSIAAASIIAKVYR-------DDLM-KKYDEL--
YPGYGFGHN---------------------------------------------------
---AGYGTKEHLQGLAT-----------Q-----GITPIHR-------------RSFAPI
KNYL-----------S----------------------------
>gi|71903522|ref|YP_280325.1| ribonuclease HII [Streptococcus pyogenes MGAS6180]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------MATDARLGVQKALKSRQKAIQADLAEEERLEAMLSYEKALYKE---GYQAIAGI
DEV--------------------GRGPLAGPVVAACVILPQ----------HCK-IKGLN
DS------KKIPKSKHETIYQAVKE---KALAIG-I------GIIDNQLIDEVNIY----
---------EATKLAMLEAIKQLE--------GQLTQPDY-LLIDA-MTL--DIAISQQS
------------ILKGD------ANSLSIAAASIVAKVTR-------DQMM-ANYDRI--
FPGYGFAKN---------------------------------------------------
---AGYGTKEHLQGLKA-----------Y-----GITPIHR-------------KSFEPV
KSMC-----------CDSTNP-----------------------
>gi|94990506|ref|YP_598606.1| ribonuclease HII [Streptococcus pyogenes MGAS10270]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MSTSIKAIKESLEAV----TSLLD
PLF-QELATDARLGVQKALKSRQKAIQADLAEEERLEAMLSYEKALYKE---GYQAIAGI
DEV--------------------GRGPLAGPVVAACVILPQ----------HCK-IKGLN
DS------KKIPKSKHETIYQAVKE---KALAIG-I------GIIDNQLIDEVNIY----
---------EATKLAMLEAIKQLE--------GQLTQPDY-LLIDA-MTL--DIAISQQS
------------ILKGD------ANSLSIAAASIVAKVTR-------DQMM-ANYDRI--
FPGYGFAKN---------------------------------------------------
---AGYGTKEHLQGLKA-----------Y-----GITPIHR-------------KSFEPV
KSMC-----------CNSTNP-----------------------
>gi|306827335|ref|ZP_07460622.1| ribonuclease HII [Streptococcus pyogenes ATCC 10782]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MSTSIKAIKESLEAV----TSLSD
PLF-QELATDTRLGVQKALKSRQKAIQTDLAEEERLEAMLSYEKALYKE---GYQAIAGI
DEV--------------------GRGPLAGPVVAACVILPQ----------HCK-IKGLN
DS------KKIPKSKHETIYQAVKE---KALAIG-I------GIIDNQLIDEVNIY----
---------EATKLAMLEAIKQLE--------GQLTQPDY-LLIDA-MTL--DIAISQQS
------------ILKGD------ANSLSIAAASIVAKVTR-------DQMM-ANYDRI--
FPGYGFAKN---------------------------------------------------
---AGYGTKEHLQGLKA-----------Y-----GITPIHR-------------KSFEPV
KSMC-----------CDSTNP-----------------------
>gi|139473750|ref|YP_001128466.1| ribonuclease HII [Streptococcus pyogenes str. Manfredo]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MSTSIKAIKESLEAV----TSLSD
PLF-QELATDARLGVQKALKSRQKAIQADLAEEERLEAMLSYEKALYKE---GYQAIAGI
DEV--------------------GRGPLAGPVVAACVILPQ----------HCK-IKGLN
DS------KKIPKSKHETIYQAVKE---KALAIG-I------GIIDNQLIDEVNIY----
---------EATKLAMLEAIKQLE--------GQLTQPDY-LLIDA-MTL--DIAISQQS
------------ILKGD------ANSLSIAAASIVAKVTR-------DQMM-ANYDRI--
FPGYGFAKN---------------------------------------------------
---AGYGTKEHLQGLKA-----------Y-----GITPIHR-------------KSFEPV
KSMC-----------CDSTNP-----------------------
>gi|19746108|ref|NP_607244.1| ribonuclease HII [Streptococcus pyogenes MGAS8232]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MPTSIKAIKESLEAV----TSLLD
PLF-QELATDARLGVQKALKSRQKAIQTDLAEEERLEAMLSYEKALYKK---GYQAIAGI
DEV--------------------GRGPLAGPVVAACVILPK----------YCK-IKGLN
DS------KKIPKAKHETIYQAVKE---KALAIG-I------GIIDNQLIDEVNIY----
---------EATKLAMLEAIKQLE--------GQLTQPDY-LLIDA-MTL--DIAISQQS
------------IIKGD------ANSLSIAAASIVAKVTR-------DQMM-ANYDRI--
FPGYGFAKN---------------------------------------------------
---AGYGTKEHLQGLKA-----------Y-----GITPIHR-------------KSFEPV
KSMC-----------CDSTNP-----------------------
>gi|50914225|ref|YP_060197.1| ribonuclease HII [Streptococcus pyogenes MGAS10394]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MSTSIKAIKESLEAV----TSLLD
PLF-QELATDARLGVQKALKSRQKAIQTDLAEEERLEAMLSYEKALYKK---GYQAIAGI
DEV--------------------GRGPLAGPVVAACVILPK----------YCK-IKGLN
DS------KKIPKAKHETIYQAVKE---QALAIG-I------GIIDNQLIDEVNIY----
---------EATKLAMLEAIKQLE--------GQLTQPDY-LLIDA-MTL--DIAISQQS
------------ILKGD------ANSLSIAAASIVAKVTR-------DQMM-ANYDRI--
FPGYGFAKN---------------------------------------------------
---AGYGTKEHLQGLKA-----------Y-----GITPIHR-------------KSFEPV
KSMC-----------CDSTNP-----------------------
>gi|21910354|ref|NP_664622.1| ribonuclease HII [Streptococcus pyogenes MGAS315]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MPTSIKAIKESLEAV----TSLLD
PLF-QELATDTRSGVQKALKSRQKAIQADLAEEERLEAMLSYEKALYKE---GYQAIAGI
DEV--------------------GRGPLAGPVVAACVILPQ----------HCK-IKGLN
DS------KKIPKAKHETIYQAVKE---KALAIG-I------GIIDNQLIDEVNIY----
---------EATKLAMLEAIKQLE--------GQLTQPDY-LLIDA-MTL--DIAISQQS
------------ILKGD------ANSLSIAAASIVAKVTR-------DQMM-ANYDRI--
FPGYGFAKN---------------------------------------------------
---AGYGTKEHLQELKA-----------Y-----GITPIHR-------------KSFEPV
KSMC-----------CDSTNP-----------------------
>gi|392331468|ref|ZP_10276083.1| ribonuclease HII [Streptococcus canis FSL Z3-227]
------------------------------------------------------------
------------------------------------------------------------
------------------------------------MSTSIKAIKESLETV----TSLSD
PLF-QELATDARLGVQKALKSRQKAIQADLAEEERLEAMLSYEKVLYKK---GYQAIAGI
DEV--------------------GRGPLAGPVVAACVILPQ----------HCK-IKGLN
DS------KKIPKAKHETIYQAVKE---KALAIG-I------GIIDNQLIDEVNIY----
---------EATKLAMLEAINQLE--------GQLTRPDY-LLIDA-MTL--DIAISQQS
------------IIKGD------ANSLSIAAASIVAKVTR-------DQLM-ARYDQA--
FPGYGFAKN---------------------------------------------------
---AGYGTKEHLEGLKT-----------Y-----GITPIHR-------------KSFEPV
KSMS-----------SFSNNP-----------------------
>gi|336064248|ref|YP_004559107.1| ribonuclease HII [Streptococcus pasteurianus ATCC 43144]
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------MATVKEIKEALAAI----ESLDD
ARW-QAYESDSRAGVQKAIQQRKKAIQADIDEDLRLENMLRYEKELYQQ---GYQAIAGI
DEV--------------------GRGPLAGPVVTACVILPK----------NCK-IKHLN
DS------KKIPKKHHEEIYQEILA---RALGIG-I------GIVDNNVIDQINIY----
---------EATKVGMLQAINQLK--------GEVTKPDY-LLIDA-MHL--ETSIPQQS
------------LLKGD------ANSLSIAAASIVAKVTR-------DRMM-ADYAND--
YPGYAFEKN---------------------------------------------------
---VGYGTKEHLEGLKK-----------Y-----GITPIHR-------------KTFEPI
KSML--------------KEP-----------------------
>gi|306833475|ref|ZP_07466602.1| ribonuclease HII [Streptococcus bovis ATCC 700338]
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------MATVKEIKEALAAI----ESLDD
ARW-QAYESDSRAGIQKAIQQRKKAIQADIDEDLRLENMLRYEKELYQQ---GYQAIAGI
DEV--------------------GRGPLAGPVVTACVILPK----------NCK-IKHLN
DS------KKIPKKHHEEIYQEILA---RALGIG-I------GIVDNNVIDQINIY----
---------EATKVGMLQAINQLK--------GEVTKPDY-LLIDA-MHL--ETSIPQQS
------------LLKGD------ANSLSIAAASIVAKVTR-------DRMM-ADYAND--
YPGYAFEKN---------------------------------------------------
---VGYGTKEHLEGLKK-----------Y-----GITPIHR-------------KTFEPI
KSML--------------KEP-----------------------
>gi|374337963|ref|YP_005094672.1| ribonuclease HII [Streptococcus macedonicus ACA-DC 198]
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------MATVKEVKEVLAAI----ESLDD
ARW-QAYESDSRAGVQKAIQHRKKAIQANIDEDLRLENMLRYEKELYQQ---GYQAIAGI
DEV--------------------GRGPLAGPVVTACVILPK----------NCK-IKHLN
DS------KKIPKKHHEEIYQEILA---RALGIG-I------GIVDNNVIDQINIY----
---------EATKVGMLQAINQLK--------GEVVKPDY-LLIDA-MHL--ETSIPQQS
------------LIKGD------ANSLSIAAASILAKVTR-------DRMM-ADCAKD--
YPGYAFEKN---------------------------------------------------
---VGYGTKEHLEGLKK-----------Y-----GITPIHR-------------KTFEPI
KSML--------------KEP-----------------------
>gi|194014254|ref|ZP_03052871.1| ribonuclease HII (RNase HII) [Bacillus pumilus ATCC 7061]
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------MYTVKQIKELIEKH----SQDES
YIH-ELVKDDKRKSVQKLIEKWHKEREKQQQLHVAWNEMLQFENNAKAQ---GYTCIAGI
DEA--------------------GRGPLAGPVVAAAVILKE----------DTV-LLGLN
DS------KQLSEKKRLAYYDLIQK---EALDIG-I------GIVDAATIDEINIY----
---------EASRLAMVRAVEQLT-----------HTPDY-LLIDA-MTL--PLPIHQEN
------------IIKGD------AKSASIAAGACIAKVTR-------DQMM-EEYGRK--
YPEYQFEKH---------------------------------------------------
---KGYGTKEHLAAIQT-----------H-----GAAPIHR-------------LSFAPV
KSVI-----------S----------------------------
>gi|315924213|ref|ZP_07920439.1| ribonuclease HII [Pseudoramibacter alactolyticus ATCC 23263]
------------------------------------------------------------
------------------------------------------------------------
-----------------------------MMLKDEVAGSSVAAIRERVKAL----PEDSI
PVWIEALNADKRKGVRAIGEQLQKKQMRLKAAIAKIHEHQAIERAARAQ---GYALISGI
DEV--------------------GRGPLAGPVVAAAVILPE----------TSA-IAGID
DS------KKISAKRRETLNAAIRD---EALAIG-I------GVVDPETIDAMNIL----
---------EATKLAMTNAVAQLV-----------PRPDL-LLIDA-LKL--PSQIPVQA
------------VVHGD------ARCYCIGAASIVAKVYR-------DHLM-QEYART--
YPEYGFERN---------------------------------------------------
---MGYGTAAHIEAIQT-----------C-----GPTPVHR-------------RSF--I
THFV-----------QE---------------------------
>gi|374308408|ref|YP_005054839.1| ribonuclease HII [Filifactor alocis ATCC 35896]
------------------------------------------------------------
------------------------------------------------------------
---------------------------------MFEGQSISAIKQKILQMN----EEEKN
LELEQILLMDDRLGVQKIGISLRKNRLKAEEEKQRILQMKAKEQDWNSK---GILLVGGV
DEA--------------------GRGPLAGPVVAACVIMKS----------DSL-ILGMN
DS------KKIKETVREELYDKVIQ---DSISFG-I------GIASSEEIDRYNIL----
---------QATFLAMKRAMQEMK-----------QVPDL-VLVDGNQEI-SNCSIRQET
------------VIHGD------SICYSIACASILAKVYR-------DRIM-RDYDRI--
YPEFDFLSN---------------------------------------------------
---KGYGTSHHYDALRT-----------Y-----GVTPIHR-------------KSF--L
KS------------------------------------------
