>AT_gi|18424615|ref|NP_568958.1| Tic22-like family protein [Arabidopsis thaliana]
MGSPDKQHRRHVAAEFLHSAVTSISSSIIPLFPPKTAPSRVCLPLRFSVSDDVSSPFEST
VKSTSSASSSGLNSTVRISSLSSDGKRGGPAFVGQVFSMCDLTGTGLMAVSTHFDIPFIS
KRTPEWLKKMFSTITKSER--NGPVFRFFMDLGDAVSYVKKLNIPSGVVG------ACRL
DLAYEHFKEKPH-----LFQFVPNERQVKAANKLLKSMPQNGKTQKVEGVPVFGAQNL--
DIAVATADGIKWYTPYFFDKAVLDNILEESVDQHFHTLIQTR-HVQRRRDVVDDSLASEV
MEEMGDSMLEPP-EVQEAMEEIGTSGIPLSVVAKAAEIQLLYAVDRVLLGSRWFRKATGI
QPKLPYLVDSFERRSAFSIQRASGSATRCLGDSVEADTSASLLRVEDDSPSEAEKRQQHL
WFPFGDWISHSVSRKEHTHHKGSSDQRDMESREREMLRSPFLPKITMVGISTGEAAQMSK
ANLKKTMEDLTEDLEQSDEGNDHGSKRYDSLKIEERDPLFVANVGDYYSGLAKAGSARLS
RRGDDQ
>gi|113475327|ref|YP_721388.1| Tic22-like [Trichodesmium erythraeum IMS101]
MKSLI----------------------------------RLSAVLGVMVSS-LIGP----
--SLKD----------MSALALPEKEVLQKLTPVPVFTITDQNGSPLVR-----------
------------SIRREGNEVNSSVAGVFISKSDADAFVNKLKGENPDLAATVKVVPVSL
GEVYEKSQSIQENGQRLEFAYVPIRRQVESAKALLEKNGQD--FNNFSGVPLFMAKGGPD
DGYLTIQRGEKQVIPMFFNKEDLQGMLDRAETQQPEVFSSVEIEVVNLEGVIN-ALKNDD
DPFLEKIIFIPPRESLEFVQQLRESD----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----NK
>gi|119486658|ref|ZP_01620708.1| hypothetical protein L8106_12945 [Lyngbya sp. PCC 8106]
MKSLA----------------------------------RLSLVLGIIGSHLLINP----
--GLPSRLPSFLPIGIQPAFALTPNEVLEKLGAVPVFTITDSEGSPLVG-----------
------------TAQSQGQ--SASVVEVYISRQDAQAFINELKTQNPELASSVQVTAVPL
GKIYEIGQQNQSDPERLMFAFVPTQQQLNSAKAVLEANGQD--VNQFRGVPLFLARAGAD
DRVITVQQGDKQAIPFFFTKEDLQGMLEQFKTQQPDLISSVKIEVVPLEVLLE-AFRTDS
DQFLDLVILIPPRETVEFIQQQRQSS----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----GQ
>gi|86607397|ref|YP_476160.1| chloroplast envelope protein translocase (CEPT or Tic-Toc) family protein [Synechococcus sp. JA-3-3Ab]
MKMMRGNAVPLLGSLCRRRAQAGGRAAFVAAV-------RSTLLLGLAG---VIWG----
--GVPTFAQGGPLSTQAVAAPMSRQEVAERLNLVPVFAIVSQNGTPVVA-----------
------------NVEREGR--TIQVASFWLDQNQAQQALDQVKAKNPEVGQQAQVVPIPL
GYAYEKSEEERAKNSNLYFEVVPRAADVEAAKQVLKETGQE-VPPEVIGVPLFYGRSG--
EGLLTIEQDGQEVVPFFFDRNDLKGALDRAAAQNPEVVGKTQIEVTSLAIVVERMLAPDA
QEDVQKIAFIPPRASLEYVQSLIRSATPQPNPPATPQPQ---------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----RR
