>gi|11465684|ref|NP_053828.1| hypothetical protein PopuCp033 [Porphyra purpurea]
MYCSQAITQTSRLPVSNNFYCKKTFFSSVNSNYQNLSQMQSWSSLKVLAFGLPDLHSIPV
NLNNSFQEAIVISTINDNNIFADVTNSWIKMHKDKNHYSLFYKEIFKALLTKQIHVIDSP
IGS---KDIDNKIILIQQYIWKKGLKSPQFNSIARLNKNVDISNISTKFIMEQLST----
-SPVFV---------VKNGLNEIILGHPLSRIRRTAFNQIASSLSNLFHQPIATSPISNG
---LFFFHPDDAIEF--KNFVQSKAPEACKDMDIKIQPVGLHVAYKMNRNFSSDIQFRFV
PDFKEVGDLIFRHQQAKNLHFHENQYYGK-NFFQGQPIYMIQPIIIKHRNGRISIIKFTG
ANDDREVVFTNL--EAANKSWANFIKRTPYLKRLK------KPNLLVYNLESFLKDKEVL
HKADLTKF----IVVTNKSAYITTKESVTLPYHNGLSKHLELNVKPKL-FFVKLWIRRLL
FTLTY-------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------E
>gi|378787257|gb|AFC39888.1| hypothetical protein [Porphyra umbilicalis]
MYCSQTFXXXXXXXFSNNFYCKKKFFSSVNSXXXXXXXXXXXXXXRVLAFALPELSSIPI
NFRNSFQEAIVISTIHDNNIFADVTNSWIKTHKDKNHHSLFYKEIFKALLTKQIHVTNSP
IEL---KNIDNKIISVQKYIWSKGFKSPQFYSSMGGDNYVNTSSISTKFIMEQLSS----
-SPVFV---------VKNGFNEVILGHPLSRIKRTALKQIAFSFSNVFHQPVATSPTSNG
---LFFFHPDDAIEF--KNFLQSKSFEASKHMGIKIQPIGLHVAYKMNRKFAGDIQFRFI
PDFKEVGDLIFKHQKAKNLIFHENQYYGK-DFFQGQPIYMIQPINIKHRNGKISTIKFTG
LNDKREVVFTNL--EAANKSWTNFIKTEPYLKRIK------KPTLLVYNLESFLKDKEIL
YRADLTKF----VVVTNKSAYITTKESIAIPYSKSLSKHLKLNIKPQL-FFIKLWMRRLL
STLMC-------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------E
>gi|18424615|ref|NP_568958.1| Tic22-like family protein [Arabidopsis thaliana]
M-------------------------------------------------GSP-------
---------------------------------DKQHRRHVAAEFLHSAVTS---ISSSI
IPLFPPKTAPSRVCLPLRFSVSDDVSSP-FESTVKSTSSASSSGLNSTVRISSLSSDGKR
GGPAFVGQVFSMCDLTGTGLMAVSTHFDIPFISKRTPEWLKKMFSTI------TKSERNG
PVFRFFMDLGDAVSYVKKLNIPSGVVGACR----------LDLAYEHFKEKPH--LFQFV
PNERQV--------KAANKLLKSMPQNGKTQKVEGVPVFGAQNLDIA--VATADGIKWYT
PYFFDKAVLDNILEESVDQHFHTLIQTRHVQRRRDVVDDSLASEVMEEMGDSMLEPPEVQ
EAMEEIGTSGIPLSVVAKAAEIQLLYAVDRVLLGSRWFRKATGIQPKLPYLVDSFERRSA
FSIQRASGSATRCLGDSVEADTSASLLRVEDDSPSEAEKRQQHLWFPFGDWISHSVSRKE
HTHHKGSSDQRDMESREREMLRSPFLPKITMVGISTGEAAQMSKANLKKTMEDLTEDLEQ
SDEGNDHGSKRYDSLKIEERDPLFVANVGDYYSGLAKAGSARLSRRGDDQ
