>Escherichia_coli_UTI89_gi_91210123|ref|YP_540109.1| hypothetical protein UTI89_C1094 [Escherichia coli UTI89]
MKREAFMCLLAPENPYPIYALPPLVRNAIIETQKNTQAPLAMVATSALTATSIACQNQVDVCRPGNLRGPVNLYSLILADSGERKTTVDKVFMKAFYLRDEALAEEYAKLVENYSTEKEIWEQKQKALESKLHKEIRAGKGCKATESELKRHLNKCPVPPQIRRTIFNETTIEGMLKYYSDSNRSFALVSSEGGIIFDGRAMSKLGILNSLWDGGSLFIDRKSSPGIILKDPRLTVSVMIQPDVYQKGFCTRKKELVKTSGHHARFLMCQPTSTQGTRIITGDNYSSQYQDLFEQRINELIDESLAMSGERRCLHFSPQAARIWTDYYNDVESKLGGLGPLRHCREYAAKNAEYMARLAGLIHHSSGEEGDISPYTAEMARELAIWYGNEYVRLSNPLTFDNPALTVPVRLIPEELELFNWIKSYCIEKGIPCMKKNDILQRGPNRFRKKDKINWLLDLLYEQNRVVPVIEGKTLCVAPNFDL
>Escherichia_coli_UTI89_gi_91211787|ref|YP_541773.1| phosphotransacetylase [Escherichia coli UTI89]
MIIKRCRELALRAPARVVFPDALDQRVLKAAQYLHQQGLATPILVANPFELRQFALSHGVAMDGLQVIDPHGNLAMREEFAHRWLARAGEKTPPDALEKLTDPLMFAAAMVSAGKADVCIAGNLSSTANVLRAGLRIIGLQPGCKTLSSIFLMLPQYSGPALGFADCSVVPQPTAAQLADIALASAETWRAITGEEPRVAMLSFSSNGSARHPCVANVQQATEIVRERAPKLVVDGELQFDAAFVPEVAAQKAPASPLQGKANVMVFPSLEVGNIGYKIAQRLGGYRAVGPLIQGLAAPMHDLSRGCSVQEIIELALVAAVPRQTEVNRESSLQTLVE
>Arabidopsis_thaliana_AT3G23710.1
MN------------------------SNIFPPSKQQNELNNIQ-----------------
--QSFSNLQS------------------------------------QCSNLLLNVSQTLN
PLFNANTNNNKPNIFSALNSFRD-QAKQALDSRISRFN-----SGKAPVWARISDD---G
GGARAQVT-VPIRGSGK-----GLSADAIEERLAGVPVYALSNSNEE----FVLVSGT-S
SG-------------KSLGLLFCKEEDAETLLKE-----MKSMDPRMRKEGSKVVALALS
KVFQL--------KV-NG-------------------------------------VAFRL
IPESTQVKNA--LKERKTAGID--DDDFHGVPVFQ-----------------------SK
SLILRSEN----MSYRPVFFRKEDLEKSLIRASSQQNRLNPAL-----------------
-------------------------------------K-PGDIQVAVFEDIVKGMRE---
------S-TT--SNWDDIV--F----------------------------IPPGFEVSTE
QTQE--------------------------------------------------------
--------------

>Arabidopsis_thaliana_AT4G33350.1
MESS------------------------------------VKP-----------------
--NPFLSFSSFIHH--------------------------------QCTRFSSDLSARI-
-----------------EDTKRFAETLATRRF----------SLPTPPPFASVS------
-----QSKSG---TPTT-----TLSPSLVAKALAGTSVFTVSNTNNE----FVLISDP-T
GG-------------KSIGLLCFRQEDAEAFLAQ-----ARLRRRELK-TNAKVVPITLD
QVYLL--------KV-EG-------------------------------------ISFRF
LPDPIQIKNA--LELKSSGN----KNGFDGVPVFQ-----------------------SE
LLVVRKKN----RRYCPVYFSKEDIERELSKYTRASRG----------------------
---------------------------------------DQQIMVGSLEDVLRKMEM---
------SEKN--SGWEDVI--F----------------------------IPPGRSYAQH
MQDLIKE-----------------------------------------------------
--------------

