>Acaryochloris_marina_MBIC11017@ 641253409 AM1_4328 tic22-like family protein, putative [Acaryochlor	
--------------------------------------------MK-----------GLI
RWGLIVS----------------LAGGGFV----------GTSLVQ--QEAAIAIPEAEA
VK---------------------------RLETVPTFAVTDEKGSPVLAAVPNPKD-KTK
KIQVATFFMSQTDAQNLVN-NLKAN--------------K------PDIGKSAR------
----VTLISLRDAYEI------TKKNKDKQ--DQLVFQFIPN----------------KE
QVDLAKAILKQEG-------QDV-KQFQGVPMFFAI-GGKEK------GLLTI---E---
------------------------------QGKEKI--------------------I---
---------------------------------------PFYFRKQDLQGMIDQLKKQNN
PL-SGTTKIQVTSLDRL---------VGSLFKSE-----DATAKQIVL------------
-I---PARDALEYAVQQQKK-----------NGA--------------------------
---------------------------------------------QQKPSATPAATPK--
----------K
>Arthrospira_platensis_NIES_39@ 650384942 NIES39_D00560 periplasmic protein, function unknown [Arthr	
------------MEAWGRYQEE------------LLLRSQLENMIK-----------SFF
HLSLLLG----------------VISGNLLMSPTLPPGTVGASLLG--TQAAEALTLEEI
QA---------------------------KLRPVPVFTITDPTGSPLVATVPAGEN-GSG
TAAVAGIFISRQDALRFVE-NLRNN--------------N------PELANSVE------
----VTAVSLGEVYQM------SQQSRNRA--DDIQFAYVPV----------------QQ
EVESARAVMQQSG-------RSP-NEFNGVPLFMAR-GGPDN------GYLTI---Q---
------------------------------RGNDQV--------------------I---
---------------------------------------PMFFSKQDLEGMLSQFREEQP
DL-ISSVTVQVVPLEAL---------LEAFRTDD-----NQFLDRIIL------------
-V---PPRETLEFLRNNQ------------------------------------------
------------------------------------------------------------
----------R
>Arthrospira_platensis_Paraca@ 646131540 AplaP_010100019463 Tic22-like protein [Arthrospira platensi	
-------------------------------------------MIK-----------SFF
HLSLLLG----------------VISGNLLMSPTLPPGTVGASLLG--TQAAEALTLEEI
QA---------------------------KLRPVPVFTITDPTGSPLVATVPAGEN-GSG
TAAVAGIFISRQDALRFVE-NLRNN--------------N------PELANSVE------
----VTAVSLGEVYQM------SQQSRNRA--DDIQFAYVPV----------------QQ
EVESARAVMQQSG-------RSP-NEFNGVPLFMAR-GGPDN------GYLTI---Q---
------------------------------RGNDQV--------------------I---
---------------------------------------PMFFSKQDLEGMLSQFREDQP
DL-ISSVTVQVVPLEAL---------LEAFRTDD-----NQFLDRIIL------------
-V---PPRETLEFLRNNQ------------------------------------------
------------------------------------------------------------
----------R
>Arthrospira_sp_PCC_8005@ 648389407 APCC8_010100021640 Tic22-like protein [Arthrospira sp. PCC 8005]	
-------------------------------------------MIK-----------SFF
HLSLLLG----------------VISSHLLMSPILPPRTVGASLLG--TQAAEALTLEEI
QE---------------------------KLRPVPVFTITDPTGSPLVATVPAGEN-GSG
TAAVAGIFISRQDALRFVE-NLRNN--------------N------PELANSVE------
----VTAVSLGEVYKM------SQQSRNRP--DDIQFAYVPV----------------QR
EVESARAVMQQSG-------RSP-NEFNGVPLFMAR-GGPDN------GYLTI---Q---
------------------------------RGNDQV--------------------I---
---------------------------------------PMFFSKQDLEGMLSQFQEQQP
DL-ISSVTVQVVPLEAL---------LEAFRTDD-----NQFLDRIIL------------
-V---PPRETLEFLRNN-------------------------------------------
------------------------------------------------------------
-----------
>Lyngbya_sp_CCY_8106@ 640016084 L8106_12945 hypothetical protein [Lyngbya sp. CCY 8106]	
--------------------------------------------MK-----------SLA
RLSLVLG----------------IIGSHLLINPGLPSRLPSFLPIG--IQPAFALTPNEV
LE---------------------------KLGAVPVFTITDSEGSPLVGTAQSQG----Q
SASVVEVYISRQDAQAFIN-ELKTQ--------------N------PELASSVQ------
----VTAVPLGKIYEI------GQQNQSDP--ERLMFAFVPT----------------QQ
QLNSAKAVLEANG-------QDV-NQFRGVPLFLAR-AGADD------RVITV---Q---
------------------------------QGDKQA--------------------I---
---------------------------------------PFFFTKEDLQGMLEQFKTQQP
DL-ISSVKIEVVPLEVL---------LEAFRTDS-----DQFLDLVIL------------
-I---PPRETVEFIQQQRQS-----------SG---------------------------
------------------------------------------------------------
----------Q
>Oscillatoria_sp_PCC_6506@ 648859041 OSCI_3460067 Tic22-like [Oscillatoria sp. PCC 6506]	
--------------------------------------------MK-----------SLV
RLGAVLG----------------ILGSTLL----------APALTR--NMSALALPDPQV
LE---------------------------KLRPVPVFTITDAQGAPLIASVPKEGQ-SGS
NTSVAGVFISQRDAQAFVD-RLKTR--------------N------PQLAASVK------
----VVPVSLGEIYQL------SQANKGKA--EEVQFAYVPT----------------TT
QVESAKTLLRQGG-------QQV-NEFSGVPLFLAR-GGPEN------GYLTI---Q---
------------------------------RGQEQV--------------------I---
---------------------------------------PLFFNKEELQGMLERFKQQQP
NI-ASSLKIEVVNLEAV---------LEAMRTDN-----DPFLSQIIL------------
-V---PPRESLEYVRTLQPS-----------GGN--------------------------
---------------------------------------------QLQPAQPGARPSAPV
PSQPR-----R
>Trichodesmium_erythraeum_IMS101@ gi|113475327|ref|YP_721388.1| unnamed protein product [Trichodesmi	
--------------------------------------------MK-----------SLI
RLSAVLG----------------VMVSSLI----------GPSL-K--DMSALALPEKEV
LQ---------------------------KLTPVPVFTITDQNGSPLVRSIRREGN--EV
NSSVAGVFISKSDADAFVN-KLKGE--------------N------PDLAATVK------
----VVPVSLGEVYEK------SQSIQENG--QRLEFAYVPI----------------RR
QVESAKALLEKNG-------QDF-NNFSGVPLFMAK-GGPDD------GYLTI---Q---
------------------------------RGEKQV--------------------I---
---------------------------------------PMFFNKEDLQGMLDRAETQQP
EV-FSSVEIEVVNLEGV---------INALKNDD-----DPFLEKIIF------------
-I---PPRESLEFVQQLRES-----------DN---------------------------
------------------------------------------------------------
----------K
>Microcoleus_chthonoplastes_PCC_7420@ 647570224 MC7420_2577 Tic22-like family [Microcoleus chthonopl	
--------------------------------------------MK-----------SLV
RWSATLG----------------LVGTTLL----------GSFLGG--NLRALALTEQQV
ME---------------------------KLQTVPVFTVTDGEGSPLVASIPSQNN---Q
NEAVAGVFISQRDAEAFVE-RLKRE--------------K------PELGNQVR------
----VVPVSLAEVYQL------DQQSQNQP--NGLDFAYIPV----------------QQ
QVQSAQQLLGQ-G-----------QEFRGVPLFVAK-GGQQG------GYLTI---Q---
------------------------------QEGQQV--------------------I---
---------------------------------------PFFFDKEQLQNLVNRFKEQQP
NL-ASSVQIQVVPLEGI---------INTLQTQD-----NPQLEQILL------------
-I---PSQESLQFLRQSSSQ----------------------------------------
------------------------------------------------------------
-----------
>Cyanothece_PCC_7424@ gi|218438435|ref|YP_002376764.1| Tic22 family protein [Cyanothece sp. PCC 7424	
-------------------------------------------MMK-----------SIF
RWSAALG----------------LVSSTLL----------TPWLGG--NFKALALPEQQI
IE---------------------------RLQAVPVFTLADDKGVPLVAVVE-------N
DQKVTGVFISQEDAKAFLE-QLKKD--------------N------PQVAEKVK------
----VQPVSLGQVYKL-------QNSQKEP--DGLIVSYVPD----------------ET
EVESAKKLLSESG-------KEY-Q--GGVPLFVAK-AGEDQ------GYLTI---N---
------------------------------QNNQQV--------------------I---
---------------------------------------PMFFEKASVTAMVEQFKKQKP
DL-ASTVKIEVIPLESV---------IETLESSD-----DQMLNKIVL------------
-V---PSQETMNFIRANLPN-----------QNN--------------------------
---------------------------------------------QK-------------
----------K
>Cyanothece_PCC_7822@ gi|307152686|ref|YP_003888070.1| Tic22 family protein [Cyanothece sp. PCC 7822	
--------------------------------------------MM-----------KLF
RRTAIVG----------------LVGSTIF----------ASGLGG--NFRALALPEQQI
LE---------------------------KLQPIPVFTVADDQGVPLVEVVE-------N
DKKVTGVFISRQDAQAYLA-QVQKQ--------------N------PEIGKKVK------
----VQPVSLGQVYKL-------QQSQKEP--NALIVDYVPT----------------QT
EVESAKKLLTDNG-------QEY-K--GGVPLFVAK-AGKEE------GYLMI---N---
------------------------------QNNQPV--------------------I---
---------------------------------------PMFFEKSAATALAEEYKKQKP
EL-ASTVKIEVVPLEGV---------IGALKESN-----DQMLTKIVL------------
-V---PSKDTLDFIRANLPK-----------QAP--------------------------
---------------------------------------------QQAPQQAPQQQPK--
----------K
>Microcystis_aeruginosa_NIES_843@ 641537843 MAE_38380 Tic22-like protein [Microcystis aeruginosa NIE	
------------------------------------------------------------
----------------------------ML----------TSLLGS--YSKALALPEEQI
VR---------------------------TLQSVPVFAIADDQGVPLIAVGE-------K
EQKFTGVFISRQDAQNFFE-RLKKE--------------N------PEVASKVK------
----VQPVSLAQVYKM-------QTSQTDQ--NRLIIDFVPK----------------ES
EVESAKKLLSERG-------QQY-Q--GGVPLFVPK-AGKES------NFLVI---S---
------------------------------RNNQDL--------------------I---
---------------------------------------PFFFEKAAALQMVEQYKKANP
AE-AATVKIDVIPLENV---------IATLQQSN-----DEALTKILL------------
-Y---PSQETIDFIRANSNQ----------------------------------------
----------------------------------------------KAPNQPPANQPRPN
NNTNNPPAPNR
>Cyanobacterium_sp_UCYN_A@ 646530648 UCYN_08680 Tic22-like family [Cyanobacterium sp. UCYN-A]	
--------------------------------------------MK-----------SLV
RWGTTMG----------------LIASTLL----------TSWLGK--VPKVLALPEADI
VK---------------------------LLQSVPVFTITTEEGGPLVATVE-------N
NQKVTQVFMSLKDADGFLD-KLRKH--------------Q------PDVGNKVK------
----VQPVSLGEIYRF------AIANNSDTQKEPLQFVYVPM----------------KS
AIDSAKKLLDTKG-------QEY-K--GGVPLFLLR-GGPEN------SMLTI---Q---
------------------------------QNDQEV--------------------I---
---------------------------------------PLFFEEAPIQAITEKMKKDQP
NI-AQTIKVEVVPLENV---------IGLLQTKD-----DEALKQIQL------------
-V---PSEETIQFIQNKIKL-----------QQA--------------------------
---------------------------------------------QE-------------
----------G
>Cyanothece_sp_BH68_ATCC_51142@ 641678169 cce_3672 putative Tic22-like protein [Cyanothece sp. BH68,	
---------------------------------------MRLIFMK-----------SLI
RWSATLG----------------LLGSTII----------TTWFGQ--IPKVLALPEADV
IK---------------------------VLQGVPVFTITTEQGGPLIATLE-------D
NQKVTQVFMSQQDANQFLA-KLKEN--------------Q------PDIGNRVK------
----VQPVSLGEVYRF------AIANNTET--ESLKFAYIPM----------------QS
AVDSAKKVLNDNG-------QQY-Q--GGVPLFTLR-GGPDN------SILTI---Q---
------------------------------QDEQEV--------------------I---
---------------------------------------PFFFEKAPIQAIAEQMKKDQP
DI-AQTMQIEVVALENV---------IGLLQTKD-----DAMLKQIQL------------
-I---PSQETMKFIQETIKS-----------QQN--------------------------
---------------------------------------------QG-------------
----------Q
>Cyanothece_sp_CCY_0110@ 640625841 CY0110_24921 hypothetical protein [Cyanothece sp. CCY 0110]	
--------------------------------------------MK-----------SLI
RWSATLG----------------LLGSTLL----------TSWFGQ--VPKALALPEAEV
IK---------------------------VLQGVPVFTITTEEGGPLIATLE-------D
DQKVTQVFMSQEDANQFLA-KLKAN--------------Q------PEIGNKVK------
----VQPVSLGAVYSF------ALANNTET--ESLKFAYIPM----------------AS
AVDSAKKVLSDNG-------QQY-Q--GGVPLFTLR-GGPDN------SILTI---Q---
------------------------------QDDKEV--------------------I---
---------------------------------------PFFFEKAPIQAIAEQMKKDQP
DI-AETMQIEVIALENV---------IGLLQNKD-----DAMLKQIQL------------
-V---PSQETMEFIQEAIKS-----------QQN--------------------------
---------------------------------------------QG-------------
----------Q
>Synechocystis_sp_PCC_6803@ 637011978 slr0924 hypothetical protein [Synechocystis sp. PCC 6803]	
MPWLQTFSFRRSPFSLARRHLKNKIFVKIKSIFLLSLLFEATATMK-----------SLL
RIGATLG----------------LIGTTAI----------GTWLGT--TLQALALPTEEV
VK---------------------------ILQGVPVFTIVDAQGAPLVAVGN-------D
NEKVTGVFISQQEANGFLQ-ELKKQ--------------K------PDVGSQVS------
----VQPVSLGEVVKI------AQANANQT--DPLGFAYVPI----------------PA
QVQAAQQMPN----------SEY-Q--GGVPLFVAR-GGEDQ------GYLTI---Q---
------------------------------QENEQI--------------------I---
---------------------------------------PFFLEASQIQQMVERFKQEQP
AM-ADSIVIDVIAMENV---------ISTLQTSD-----DAMLKQIRI------------
-V---PTQEAIQFIRSLSAQ-----------QP---------------------------
------------------------------------------------------------
----------K
>Cyanothece_PCC_8801@ gi|218247698|ref|YP_002373069.1| Tic22 family protein [Cyanothece sp. PCC 8801	
--------------------------------------------MK-----------TLI
RWSVTLG----------------LVASTLF----------STGLSQ--LRPVLALSKEEV
IK---------------------------VLNAIPAFILIDDKNFPLAGKID-------D
KTIFTNVFMSQQGAQQFLA-SLQKE--------------K------PDLASKYK------
----VELISLGGIYQL------AQQNSNQS--QRYLLQYIPN----------------QA
EVEAAKPILSASG-------KQY-E--GGVPLYLAR-GGQQQ------SYLTM---E---
------------------------------QNGETI--------------------T---
---------------------------------------PVFFEKKTIQAMVDNVTKQEP
NL-APTVKIEVVLLDNL---------ITTLEEKN-----DTFIKSIRL------------
-W---PSEEMMGIIRSNQSN-----------QGN--------------------------
---------------------------------------------KP-------------
----------Q
>Cyanothece_PCC_8802@ gi|257060965|ref|YP_003138853.1| unnamed protein product [Cyanothece sp. PCC 8	
--------------------------------------------MK-----------TLI
CWSVTLG----------------LVASTLF----------STGLSQ--LPPVLALSKEEV
VK---------------------------VLNAIPAFILIDDKNFPLAGKID-------D
KTIFTNVFMSQQGAQQFLA-SLQKE--------------K------PDLASKYK------
----VELISLGGIYQL------AQQNSNQS--QRYLLQYIPN----------------QA
EVEAAKPILSASG-------KQY-E--GGVPLYLAR-GGQQQ------SYLTM---E---
------------------------------QNGETI--------------------T---
---------------------------------------PVFFEKKTIQAMVDNVTKQEP
NL-APTVKIEVVLLDNL---------ITTLEEKN-----DTFIKSIRL------------
-W---PSEEMMGIIRSNQSN-----------QGN--------------------------
---------------------------------------------KP-------------
----------Q
>Cyanothece_sp_BH68_ATCC_51142@ 641678170 cce_3673 putative Tic22-like protein [Cyanothece sp. BH68,	
-------------MSLGIQSIC------------LFVILITKNAMK-----------NLI
RWSLTLG----------------ILINPIS----------NLNLIN--PAPVVALTQAEI
VE---------------------------FLSGVPVYSLLDQQGLPIGRQLE-------D
GSVVTPVFMSRKEAQAFLQ-ELKEI--------------D------SETADSYR------
----IQILPLSRIYEI------ARETSTNS--SRLFLDYIPS----------------AT
ELQAARELVKEKG-------QKY-P--GDVPLYLAK-IESDQ------SYLTI---K---
------------------------------QEDQEI--------------------V---
---------------------------------------PVFFEKATIDQWIETVSQTRP
EL-GQEININVISLSSL---------IANLEKND-----NDLLRSLRF------------
-W---PSKEMMRIIRSSSET-----------QP---------------------------
------------------------------------------------------------
----------Q
>Cyanothece_sp_CCY_0110@ 640625842 CY0110_24926 hypothetical protein [Cyanothece sp. CCY 0110]	
--------------------------------------------MK-----------TLI
RWSLTLG----------------ILINPLT----------NLNFIQ--PAAVVALPQREI
VE---------------------------FLSGVPVYSLLDQQGLPIGRQLD-------D
GSVITPVFMSRNEAQAFLR-ELKEI--------------N------SQTADSYR------
----IQILPLSRIYEI------ARDTSTNS--SRLFLDYIPS----------------AQ
ELRTARELVTEKG-------QKY-P--GDVPLYLAK-LESDQ------SYLTI---K---
------------------------------QEDQEV--------------------V---
---------------------------------------PIFFEKATIDRWIETVSQTRP
EL-GQDISINVISLSSL---------IANLENND-----NALLRSLRF------------
-W---PSQEMMKIIRSNSEN-----------QL---------------------------
------------------------------------------------------------
----------Q
>Nostoc_punctiforme_ATCC_29133@ Npun_R3857 Tic22 family protein	
--------------------------------------------MK-----------SFI
RLGATLG----------------IAGSVFLAGLSGIG---NLPGIG--NLEAVALPQDQI
VK---------------------------KLQEVPVFTLTNPKGEFVVLSRKNN---ASK
PISQVGFFISKQDAQKFLDNRLKKE--------------N------PQLASTLQ------
----VRPLSLADYYKI------VQESKKKS--DSVIYTLVPT----------------QA
QVASATSMLNQNG-------KKG-EQFNGIPLFVPK-FKKDN------SYLTIPL-A---
------------------------------KGNERY--------------------I---
---------------------------------------PFFFEKEQAVALLEQFKKAVP
KE-AENTEIQVVDLYGV---------MEALNSSS-----DPSINKIVL------------
-Y---PSRESISFIRSLAPN-----------QSP--------------------------
---------------------------------------------AAAPAPK--------
----------K
>Nostoc_punctiforme_PCC_73102@ gi|186683988|ref|YP_001867184.1| Tic22 family protein [Nostoc punctif	
--------------------------------------------MK-----------SFI
RLGATLG----------------IAGSVFLAGLSGIG---NLPGIG--NLEAVALPQDQI
VK---------------------------KLQEVPVFTLTNPKGEFVVLSRKNN---ASK
PISQVGFFISKQDAQKFLDNRLKKE--------------N------PQLASTLQ------
----VRPLSLADYYKI------VQESKKKS--DSVIYTLVPT----------------QA
QVASATSMLNQNG-------KKG-EQFNGIPLFVPK-FKKDN------SYLTIPL-A---
------------------------------KGNERY--------------------I---
---------------------------------------PFFFEKEQAVALLEQFKKAVP
KE-AENTEIQVVDLYGV---------MEALNSSS-----DPSINKIVL------------
-Y---PSRESISFIRSLAPN-----------QSP--------------------------
---------------------------------------------AAAPAPK--------
----------K
>Anabaena_variabilis_ATCC_29413@ gi|75907705|ref|YP_322001.1| unnamed protein product [Anabaena vari	
--------------------------------------------MK-----------ALV
RWGATLG----------------LVGSTLL----------GTLSLG--SLPAVALSEQQI
KE---------------------------KLDSVPIYLVTNEKGLPLSRPLPNAQNGQKA
GGSITGAYMSRQEAQAFIN-ELRNA--------------KNKDPKMQEIVKSLQ------
----VTAVPLGVIYQQ------LQQTKKDP--NRLLFAFKPV----------------DQ
EIKGAMDLLRQSG-------QQV-NQFKSVPMFAVR-FAPDQ------GYVPIKV-G---
------------------------------TGNEQV--------------------V---
---------------------------------------PLFLSKQDAQGLLGQVKPKHP
-----KADIQVLDIDGV---------LQTLQDKN-----DPWLNQVVL------------
-V---PSPESREYIRTLPKDKAPNTPAAPNRNNN--------------------------
---------------------------------------------NSRPNS---------
----------R
>Nostoc_sp_PCC_7120@ 637230470 alr0114 hypothetical protein [Nostoc sp. PCC 7120]	
--------------------------------------------MK-----------ALV
RWGATLG----------------LVGSTLL----------GTLSLG--SLPAIALSEQQI
KE---------------------------KLDSVPIYLVTNEKGLPLSRPLPNAPNGQKA
GGSITGAYMSRQEAQAFIN-ELRNA--------------KNKDPKMQEIVKSLQ------
----VTAVPLGVIYQQ------LQQTKKDP--NRLLFAFKPV----------------DQ
EIKGAMDLLRQSG-------QQV-NQFKSVPMFAVR-FAPDQ------GYVPIKV-G---
------------------------------TGNEQV--------------------V---
---------------------------------------PLFLSKQDAQGLLGQVKPKHP
-----KADIQVLDIDGV---------LQTLQDKN-----DTWLNQVVL------------
-V---PSPESREYIRTLPKP--PNTPAAPNRNNN--------------------------
---------------------------------------------NSRPGA---------
----------K
>Nodularia_spumigena_CCY9414@ 640024174 N9414_08450 hypothetical protein [Nodularia spumigena CCY941	
--------------------------------------------MK-----------ALV
RWGATLG----------------LVGSTLV----------GSVFVG--NLPVLALSEEQI
KI---------------------------KLDAVPVYLITNKEGLPLSRPLPNA---EKP
GGSVTGVYMSRQEAQSFIK-ELQGA--------------QGKDPKTQQMVKSLQ------
----VTAVPLGVIYQQ------LQQSKNQS--ERLLFAFKPV----------------EQ
EIKGAMELLRKSG-------QQV-NQFTSVPVFAVR-FSPDQ------GYVPIQL-K---
------------------------------SDKEQL--------------------I---
---------------------------------------PLFLSKQDAQGLLTQVKPKFP
-----KADIQVIDIDGV---------IKTLQDKN-----DSWLNQVVL------------
-V---PSQESREYIKTLPTE-----------NGN--------------------------
---------------------------------------------NSKPGRPQQ------
----------R
>Synechococcus_sp_JA_2_3B_a2_13@ 637875369 CYB_0967 chloroplast envelope protein translocase (CEPT o	
--------------------------------------------MRMTRCNVVSPVRSLC
RCAAQVGGVAGI-----------LIGTAWGGLAVTPVWAQENALLA--QAAAGPMSRQEV
AE---------------------------RLNLVPVFAIVSQNGTPVVANVER----DGR
TIQVVSFWLDQAQAQQVLE-QVKAS--------------N------PEIASQAR------
----VVPLSLGYAYEK------SEEERAKN--SDLYFEVVPR----------------AS
DVEAAKQVLKETG-------QDVPAEAIGVPLFYGR-SGE--------GLLTI---E---
------------------------------QDGHEV--------------------V---
---------------------------------------PFFFDRNDLRRALDRAAAQNP
DV-VGKTQIEVTSLAIV---------VERMLAPD----AQADVQKIAF------------
-I---PSRSALEYIQSLARP----------------------------------------
----------------------------------------------ANPSASPQPQ----
----------R
>Synechococcus_sp_JA_3_3Ab@ 637874307 CYA_2795 chloroplast envelope protein translocase (CEPT or Tic	
--------------------------------------------MKMMRGNAVPLLGSLC
RRRAQAGGRAAFVAAVRSTLLLGLAGVIWGGV---PTFAQGGPLST--QAVAAPMSRQEV
AE---------------------------RLNLVPVFAIVSQNGTPVVANVER----EGR
TIQVASFWLDQNQAQQALD-QVKAK--------------N------PEVGQQAQ------
----VVPIPLGYAYEK------SEEERAKN--SNLYFEVVPR----------------AA
DVEAAKQVLKETG-------QEVPPEVIGVPLFYGR-SGE--------GLLTI---E---
------------------------------QDGQEV--------------------V---
---------------------------------------PFFFDRNDLKGALDRAAAQNP
EV-VGKTQIEVTSLAIV---------VERMLAPD----AQEDVQKIAF------------
-I---PPRASLEYVQSLIRS-----------ATP--------------------------
---------------------------------------------QPNPPATPQPQR---
----------R
>Gloeobacter_violaceus_PCC_7421@ 637461026 glr3613 hypothetical protein [Gloeobacter violaceus PCC 7	
--------------------------------------------MK-----------RRV
QGWAAAI----------------LVSSIVW------------------SGEVLALTQAQI
IE---------------------------KLKPVVLFTVATADGKPLLSLPPD----GSK
GPLVAGVYFSPQDAEAFVA-AFKKK--------------D------AARGGQLR------
----VQPVSLGNLYRL------RLESRGTE--EEVTLAFFAN----------------RT
EVEWALSLLQAAG-------RKP-EDLQGAPLFAATVNAGKK------QYLTL---Q---
------------------------------QNNRTV--------------------V---
---------------------------------------PVYFTKQEMTAFIDRYRRQQA
NA-NVPVTVEVLDLEGI---------LEALQEPT-----DSQTKKVML------------
-V---TPKAALDYARTQSGS-----------PIP--------------------------
---------------------------------------------TVQPPKSPPAEGLAP
TPDP------H
>Synechococcus_sp_PCC_7002@ 641611608 SYNPCC7002_A1598 hypothetical protein [Synechococcus sp. PCC 7	
----------MTAYFFRINFSN------------LAVILFEVLFMK-----------SLV
RLGQKAL----------------LMGTVIA----------GTILGV--NGSVLALPEAAV
VE---------------------------KLRPIPMYMLINDEGQPIFATVTDQ---NGG
ESGVTGVFVSLSDAENLVA-ARQTESKRLLDAERAKPNAD------PQIVAELEAQAALW
QEANVLPIGLDKIYQF------AQS--DEA--EDLTFKFLPT----------------MA
QLNAAAQVTQQ-------------ENFPGVPLFFLSIQEKDANGQDIVSFPTLAGDD---
------------------------------NNGNGE--------------------I---
---------------------------------------PVFFEVQPILEQLDAFPEDE-
-----ELSINVMPLEVF---------IAKLLDEDLPAEEQEFLESMTL------------
-I---PSTESAQLIQAVIEQ-----------QRQ--------------------------
---------------------------------------------Q--------------
----------Q
>Synechococcus_sp_PCC_7335@ 647578192 S7335_3895 hypothetical protein [Synechococcus sp. PCC 7335]	
--------------------------------------------MKL----------SIR
RIFAQVL----------------AIGTLGL----------GPMAIGLLSAPVLALSEEQI
VQ---------------------------QREAVLSFILEDEEG-PI------------A
GPDGILVFVTLQSASDYIA-ANRLE--------------D---------TDTIK------
----VIPTNLERIHQV------AEEIEG----EPLRITLVPE----------------EA
EVENARDIDP--------------DYQGGVPLFYAQ--LPNG------AFAPLW--Q---
------------------------------PDGEVV--------------------F---
---------------------------------------PLYFSRSDLDESLARLPQEE-
----LGIEVAVIPLQVI---------LQEIHTSD-----NEDLSRIRM------------
-L---SPQ-VVDAIRAASEE------------AE--------------------------
---------------------------------------------NTAPSDEPEA-----
----------Q
>Synechococcus_elongatus_PCC_6301@ 637617923 syc2232_c hypothetical protein [Synechococcus elongatus	
MARQSKFSVELGRLRALLQDLR------------HQHRRELGIDVN-----------KFL
TSAAALV----------------ISLSGGV----------AIPLIA--PPAAIALSDQEV
AA---------------------------RIGRVPVFVILTKEQQPLLFTSRDKD--GKE
VNKTFPVFINQTQAQAALA-ELQKS--------------N------QPLGKDAR------
----IGSLLLPKALEL------ILDFLKKTNDPKVTYEIIPD----------------PK
QRAKALELYKADKNIKPEQLKQL-ESEAFVPIFYSE-------------SLSITMTN---
------------------------------QQGQPVKDAKGNAIRR----------I---
---------------------------------------PLFLEYEPLAAELEKLKKQDT
NAKAGEYAITVTDLLTI---------INTLTAAQ----PGSNESLIEL------------
-L---PPVSSLPVLQELVKQLTPTNGTTPPRATT--------------------------
---------------------------------------------TTPPAAGTGTTPPRA
TNPTPTPRPAN
>Synechococcus_elongatus_PCC_7942@ gi|81300671|ref|YP_400879.1| unnamed protein product [Synechococc	
--------------------------------------------MN-----------KFL
TSAAALV----------------ISLSGGV----------AIPLIA--PPAAIALSDQEV
AA---------------------------RIGRVPVFVILTKEQQPLLFTSRDKD--GKE
VNKTFPVFINQTQAQAALA-ELQKS--------------N------QPLGKDAR------
----IGSLLLPKALEL------ILDFLKKTNDPKVTYEIIPD----------------PK
QRAKALELYKADKNIKPEQLKQL-ESEAFVPIFYSE-------------SLSITMTN---
------------------------------QQGQPVKDAKGNAIRR----------I---
---------------------------------------PLFLEYEPLAAELEKLKKQDT
NAKAGEYAITVTDLLTI---------INTLTAAQ----PGSNESLIEL------------
-L---PPVSSLPVLQELVKQLTPTNGTTPPRATT--------------------------
---------------------------------------------TTPPAAGTGTTPPRA
TNPTPTPRPAN
>Synechococcus_sp_WH5701@ 638959889 WH5701_12149 Bacterial regulatory proteins, Crp family protein [	
--------------------------------------------MS--------------
---------------------------------------------------FRFLPDQPL
SC---------------------------VRMPAGQTVLLDPALRPGGSSIE-------V
LEGIARVYCPCEETEGMTLAFLQPG--------------D-----------QLRTDRLCS
EGVCVEAL------------------------TPLCF---------------------RS
ETEAGNDT------------------------------GFDPVNEWTLQLLRIRHLG---
------------------------------SAEQRLHALFGLLVRRLGRRCGPWCDL---
---------------------------------------PFRLTHERIGELI--------
----GTTRVTTTRL------------ISRIRQAQ-------------L------------
-LEAPAGEPGLRLAPSLVES----------------------------------------
-----------------------------------------------APLAA--------
----------A
>Cyanothece_PCC_7425@ gi|220910506|ref|YP_002485817.1| unnamed protein product [Cyanothece sp. PCC 7	
--------------------------------------------MK---------SSSLK
NSQSQVI-----------------------------------------RLLYLAFIDKQI
IKPGTQPKLRKSADQGFALPTILGLGLVILMIAIYTFARSTSDRVAAIAQVQNAQSVGVA
EAGIARTLAGMSTLNTSYL-FTRNY--------------DDPSILGPDQVQYSGDEAASN
TWATATPVIGGCSYTPPSLPVPVSGTTTEGTYQVLAYRFTPNVSNSSPGTGGVGSLLVQG
NVNAGTNIQRQARLQVNIPITRT-TRLNSFPGLYGR------------DSVSLGNNDVGN
GTGGTTANSSGVANVICENCTVPSGQCTNGQPNQSA--------------------VESV
VNKGPNSEIAGNIYLGSANLPAPPTPPTPDCPVSGTFSAPCKITIANITSTTTLPRPSDP
DPTNNSIPYQYVITGNISLSGNSSNRLTAITSTD--VNHNPPGSRIVLFVGGNISFSGQA
NITHSGSPERLAIIGTGGTSQTFTLNGGSSGNNAFVYIADGTVGVNGGSGGPNGCDFRGA
VWARVWDGSSGTNAKVCIPDDMPTLLENVFGSSYGIMAAGIQRYIAGAPLAWQGQEV---
----------R
