>Arabidopsis_thaliana_gi|18424615|ref|NP_568958.1| Tic22-like family protein [Arabidopsis thaliana]
------------------------------------------------------------
--------------MG-SPD-----KQ---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------HRRHV---AAEFLHSAVTSI-----
-----------SSSII--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------PLF
----PPKTA---P---------------SRVCLPLRF---------SVSD----------
---------------DVSS-------P----FESTVK--STSSASSSGLNSTVRISSLSS
DGK--R-------GGPA-------------FVGQVFSMCDLTGTGLMAVS-----THFDI
P-FISKRTPEWLKKMFSTITKSERNGPVFRFFMDLGDAVSYVKKLNIPSGV------VGA
CRLDLAYEHFKEKPH--------------LFQFVPNERQVKAANKLLKSMPQNGKTQKVE
GVPVFGAQNLDIAVATADGIKWYTPYFFDK--AVLDNILEESVDQHF-------HTLIQT
RHVQRRRDVVDDS----LASEVMEEMGDSMLEPP-----EVQEAMEEIGT-SGIPLSVVA
-KAAEIQLLYAV------------DRVLLGSRWFRKAT--------GIQP----------
--------------KLPYLVDSFERRS-AFSIQRASGSATRCLGDSVEA------D-TSA
SLLRVED------------DSPSEA-EKRQ--QHLWFPFGDWISHSVSRKEH---THHKG
SSDQR-----DMESREREMLRSP-----FLPKITMVGISTGEAA-----QMSKANLKKTM
EDLTEDLEQSDEGND-HGSKRYDSLKIEER-------------DPLFVANV---------
----------------------------GDYYSGL-AKAGSARLSRRGDDQ---------
----
>iTic22-like_gi|18424615|ref|NP_568958.1| Tic22-like family protein [Arabidopsis thaliana]
------------------------------------------------------------
--------------MG-SPD-----KQ---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------HRRHV---AAEFLHSAVTSI-----
-----------SSSII--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------PLF
----PPKTA---P---------------SRVCLPLRF---------SVSD----------
---------------DVSS-------P----FESTVK--STSSASSSGLNSTVRISSLSS
DGK--R-------GGPA-------------FVGQVFSMCDLTGTGLMAVS-----THFDI
P-FISKRTPEWLKKMFSTITKSERNGPVFRFFMDLGDAVSYVKKLNIPSGV------VGA
CRLDLAYEHFKEKPH--------------LFQFVPNERQVKAANKLLKSMPQNGKTQKVE
GVPVFGAQNLDIAVATADGIKWYTPYFFDK--AVLDNILEESVDQHF-------HTLIQT
RHVQRRRDVVDDS----LASEVMEEMGDSMLEPP-----EVQEAMEEIGT-SGIPLSVVA
-KAAEIQLLYAV------------DRVLLGSRWFRKAT--------GIQP----------
--------------KLPYLVDSFERRS-AFSIQRASGSATRCLGDSVEA------D-TSA
SLLRVED------------DSPSEA-EKRQ--QHLWFPFGDWISHSVSRKEH---THHKG
SSDQR-----DMESREREMLRSP-----FLPKITMVGISTGEAA-----QMSKANLKKTM
EDLTEDLEQSDEGND-HGSKRYDSLKIEER-------------DPLFVANV---------
----------------------------GDYYSGL-AKAGSARLSRRGDDQ---------
----
>Arabidopsis_lyrata_gnl|BL_ORD_ID|26695 _496448|PACid:16060442
------------------------------------------------------------
--------------MG-SPD-----KQ---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------HRRHV---AAEFLHSAVT-------
-------------SII--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------PLF
----PPKTA---P---------------SRVCLPLRF---------SVSD----------
---------------DVSS-------P----FESTVK--SSSSTSSSGLNSTVRISSLSS
DGK--R-------GGPA-------------FVGQVFSMCDLTGTGLMAVS-----THFDI
P-FISKRTPEWLKKMFSTITKSERNGPVFRFFMDLGDAVSYVKKLNIPSGV------VGA
CRLDLAYEHFKEKPH--------------LFQFVPNERQVKAANKLLKSMPQNGRKQKVE
GVPVFGAQNLDIAVATADGIKWYTPYFFDK--AVLDNILEESVDQHF-------HTLIQT
RHVQRRRDVVDDS----LASEVMEEMGDSMLEPP-----EVQEAMEEIGS-SGIPLSVVA
-KAAEIQLLYAV------------DRVLLGSRWFRKAT--------GIQP----------
--------------KLPYLVDSFERRS-AFSIQRASGSATRCLGDSVEA------D-TSA
SLLRVED------------NSPSED-EKRQ--QNLWFPFGDWINHSESKKEH---THHKG
PSDGR-----DMESREREMLRSP-----FLPKITMVGISTGEAA-----QMSKANLKKTM
EDLTEDLEQSDEGND-HGSKRYDPRKMEER-------------DPLFVANV---------
----------------------------GDYYSGM-AKAGSARLSRRGDDQ---------
----
>Capsella_rubella_gnl|BL_ORD_ID|25653 _v10028359m|PACid:20911489
------------------------------------------------------------
--------------MG-SPE-----KQ---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------HRRHI---AAEFLHSAVTSI-----
-----------SSSIV--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------PLF
----PPKTT---P---------------SRVWLPLKF---------SVSD----------
---------------DVSS-------P----FESTVN--SKSSKSSSGLNSTVRISSLSS
DGK--R-------GGPA-------------FVGQVFSMCDLTGTGLMAVS-----THFDI
P-FISKRTPEWLKKMFSTITKSERNGPVFRFFMDLGDAVSYVKKLNIPSGV------VGA
CRLDLAYEHFKEKPH--------------LFQFVPNERQVKAANKLLKSMPQNGKKQKVD
GVPVFGAQNLDIAVATADGIKWYTPYFFDK--AVLDNILDESVDQHF-------HTLIQT
RHVQRRRDVVDDS----LTSEVMEEMGDSMLEPP-----EVQEAMEEIGS-SGIPLSVVA
-KAAEIQLLYAV------------DRVLLGSRWFRKAT--------GIQP----------
--------------KLPYLVDSFERRS-ALSIQRASGSAARCLSDSVET------D-TSA
SLLRVEE-----------GDSPRED-EKRR--QNLWFPFGDWLKHSVSRKDQ---AHQKG
SSGQR-----DMESRDREMLQSP-----FLPKITMVGISTGEAA-----QMSKANLKKTM
EDLTEDLEQSDEGND-HGSKRYDPLKIEER-------------DPLFVANV---------
----------------------------GDYYSGL-AKAGSARLSRRGDDQ---------
----
>Thellungiella_halophila_gnl|BL_ORD_ID|20311 _Thhalv10003967m|PACid:20199916
------------------------------------------------------------
--------------MD-LPD-----KQ---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------HRRHI---ATEFLHSAATSI-----
------------SSII--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------PLF
----PPKAT---P---------------SRVCLPLRF---------SVSD----------
---------------DV-F-------P----FDSTVRNASSASTSSSSLNSTVRISSLSS
DGK--R-------GGPA-------------FVGQVFSMCDLTGTGLMAVS-----THFDI
P-FISKRTPEWLKKMFSSITKSERNGPVFRFFMDLGDAVSYVKKLNIPSGV------VGA
CRLDLAYEHFKEKPH--------------LFQFVPNERQVKAANKLLKSMPPNGKKQKVE
GVPVFGAQNLDIAVATADGIKWYTPYFFDK--AVLDNILEESVDQHF-------HTLIQT
RHVQRRRDVVDDS----LTSEVMEEMGDSMLEPP-----EVQEAMEEIGT-SGIPLSVVA
-KAAEIQLLYAV------------DRVLLGSRWFRKAT--------GIQP----------
--------------KLPYLVDSFERRS-AFSIQRASGSTSRCIGDSAEA------D-TSA
SLRRVED------------DSPSED-EKRQ--QNLWFPFGDWLNHSGSRKEH---A-QKV
TSDQR-----EMECREREMQQSP-----FLPKITMVGISTGEAA-----QMSKANLKKTM
EDLTEGLEQSDEGSSEHGSKRYDPLKMEER-------------DPLFVANV---------
----------------------------GDYYSGL-AKAGSARWSRRGGDSNETHPRS--
----
>Brassica_rapa_gnl|BL_ORD_ID|11888 _010109|PACid:22695398
------------------------------------------------------------
--------------MD-SPD-----KI---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------HRRYN---AAEILHGAATSI-----
------------SSII--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------PLF
----PPKTT---P---------------SRVCLPLRF---------S-------------
---------------DV-S-------P----FESTVKNASSTSTSSSGLNSTVRISSLSS
DGK--R-------GGPA-------------FVGQVFSMCDLTGTGLMAVS-----THFDI
P-FISKRTPEWLKKMFSTITKSERKGPVFRFFMDLGDAVSYVKKLNIPSGV------VGA
CRLDLAYEHFKEKPH--------------LFQFVPNERQVKAANKLLKSMPPSEKKQRVD
GVPVFAAQNLDIAVATSDGIKWYTPYFFDK--AVLDNILEESVDQHF-------HTLIQT
RHVQRRRDVVDDS----LTSEIMEEMGDSMLEPP-----EVQEAMEEIGT-SGIPLSVVA
-KAAEIQLLYAV------------DRVLLGSRWFRKAT--------GIQP----------
--------------KLPYLVDSFERRS-ALSIQRASGSTTKCLGDS---------N-SSA
SLLKVED------------GSPSEE-EKRQ--QSLWFPFGDWLK------------AQKD
SSGQR-----EMESREREMQRSP-----FLPKITMVGISTGEAA-----HMSKANLKKTM
EDLTQDLEQSDEGSD-HGSNRYDPLKIEER-------------DPLFVANV---------
----------------------------GDYYSGL-ARAGSARWSRRGDDRNETPPRSS-
----
>Citrus_clementina_gnl|BL_ORD_ID|24296 _0.9_006877m|PACid:19275444
------------------------------------------------------------
--------------MA-SPA-EPN------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------HLQNQ---ISSFINATTSTL-----
------------FSLI--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------TP-
-----TKTT---PSSQSQPSSA----PASRLCIPLQF---------ADSSC---------
----PSSSTRSPVGSDSIS---------------SNSGASSSESSSSGFPSTVRISAINS
SGK--G-------GGPA-------------FVGQVFSMCDLSGTGLMAVS-----THFDI
P-FISKRTPEWLKKLFATITKSERNGPVFRFFMDLGDAVTYVKQLNIPSGV------VGA
CRLDLAYEHFKEKPH--------------LFQFVPNEKQVKAANKLLRTIPDSGRKKKVD
GVPVFSAQNLDIAIATADGIKWYTPYFFDK--NMLDNILEESVDQHF-------HALIQT
RHMQRRRDVIDDN----LAAEVVEEIGDSIWEPP-----EVQEMMDEIGH-PAIPLSVIS
-KAAEIQLLYAV------------DRVLLGNRWLRKAT--------GIQP----------
--------------KFPYMVDSFENRS-AASFLRASESTSCLANSET--------N-NGS
SDLKLED-------------KHLDK-RDQR--PDFRFPFGDWFRHLWSKQDC---EAQGS
SY---------IECTKRNLQLNP-----FLPKVTMVGISTGEAG-----QMTKANLKKTM
ENLTKELEQTDQENA--TSSGSNEYIIEDR-------------DPLFVANV---------
----------------------------GGYYSGL-AKTGSTRWVRGRSNN---------
----
>Citrus_sinensis_gnl|BL_ORD_ID|32460 _1.1g009199m|PACid:18125400
------------------------------------------------------------
--------------MA-SPA-EPN------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------HLQNQ---ISSFINATTSTL-----
------------FSLI--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------TP-
-----TKTT---PSSQSQPSSA----PASRLCIPLQF---------ADSSC---------
----PSSSTRSPVGSDSIS---------------SNSGASSSESSSSGFPSTVRISAINS
SGK--G-------GGPA-------------FVGQVFSMCDLSGTGLMAVS-----THFDI
P-FISKRTPEWLKKLFATITKSERNGPVFRFFMDLGDAVTYVKQLNIPSGV------VGA
CRLDLAYEHFKEKPH--------------LFQFVPNEKQVKAANKLLRTIPDSGRKKKVD
GVPVFSAQNLDIAIATADGIKWYTPYFFDK--NMLDNILEESVDQHF-------HALIQT
RHMQRRRDVIDDN----LAAEVVEEIGDSIWEPP-----EVQEMMDEIGH-PAIPLSVIS
-KAAEIQLLYAV------------DRVLLGNRWLRKAT--------GIQP----------
--------------KFPYMVDSFENRS-AASFLRASESTSCLANSET--------N-NGS
SDLKLED-------------KHLDK-RDQR--PDFRFPFGDWFRHLWSKQDC---EAQGS
SY---------IECTKRNLQLNP-----FLPKVTMVGISTGEAG-----QMTKANLKKTM
ENLTKELEQTDQENA--TSSGSNEYIIEDR-------------DPLFVANV---------
----------------------------GGYYSGL-AKTGSTRWVRGRSNN---------
----
>Manihot_esculenta_gnl|BL_ORD_ID|29919 _4.1_003879m|PACid:17989925
------------------------------------------------------------
--------------MA-SST-QPAPNR---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------HH-------SNLFHSATTAL-----
------------ISLV--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------SS-
-----PKAS---PLS-TIPLCP------PKICIPFQF---------ADSSY-------PL
IQ--SIRSPFDSNQPESVS-------P----KSAAVKGL-SSAESNSGFPSTVRIAGLKS
NGK--S-------GGPA-------------FVGQVFSMCDLSGTGLMAVS-----THFDI
P-FISKRTPEWLKKIFATVTKSERNGPVFRFFIDLGDAVAYVKRLNIPSGV------VGA
CRLDLAYEHFKEKPH--------------LFQFVPNEKQVKAANQLLKKIPQGNGRRKVD
GVPVFTAQNLDIAIATADGIKWYTPYFFDK--NMLDNILEESVDQHF-------HSLIQT
RHMQRRRDVVDDN----LAAEVIEEMGDNMLEPP-----EVQEMLDEMGH-PGIPLSVIS
-KAAEIQLLHAV------------DRVLLGNRWLRKAT--------GIQP----------
--------------KFPYMVDSFEKRS-ASSFQRASESTSYLANPKT----------DST
SNCTFKD-------------NAQAD-HEQK--TDLRIPFGDWFRHPWLKQKW---KPEKL
PEIRS--HESLSECTKQKLERNS-----FLPKITMVGISTGEAG-----QMSKASLKKTM
EDLTRELEQTDRENA-----TVGRLECNVRILILLTEAPRNIENVLMLSNILSLARYREN
FSIVICFWECILSPYSLSSFPLSYPDRQGGTFSSL-YEESGFSILTGLYGSSGIFAKETL
HSWI
>Ricinus_communis_gnl|BL_ORD_ID|23216 _30169.m006582|PACid:16821381
------------------------------------------------------------
--------------MS-LSP-DP-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------NHHHQ---PSNFFHSATTAI-----
------------TSLI--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------ST-
----NPKTS---PSS-TIPLSP------PKICIPFQF---------ADSSYR------PL
-----TRSSFESTHPDSVS-------P----KSAAVKGL-SSAESSSGFPSTVRIAGLNS
NGK--G-------GGPA-------------FVGQVFSMCDLSGTGLMAVS-----THFDI
P-FISKRTPEWLKKVFTTVTKSERKGPVFRFFMDLGDAVTYVKRLNIPSGV------VGA
CRLDLAYEHFKEKPH--------------LFQFVPNEKQVKAANQLLKTIPQSDGRRKVD
GVPVFSAQNLDIAIATTDGIKWYTPYFFDK--SMLDNILEESVDQHF-------HALIQT
RHMQRRRDVIDDN----LAAEVIEEMGDSMLEPP-----EVQEMMDEIGH-PAIPLNVIS
-KAAEIQLLYAV------------DRVILGNRWLRKAT--------GIQP----------
--------------KFPYMVDSFEKRS-ASSFRRASEPASYLAKSKT--------D-ADT
SKLNLED-------------GAQAN-HEPI--TDLRLQFGDWFKSLGLKQQQ---KPEKG
SEI--------SECRKQKLEMNP-----FLPKITMVGISTGEAG-----QMSKASLKKTM
EDLTRELEHTDRENAPGSSNNGNDLEMEDR-------------DPLFVANV---------
----------------------------GDYYSGM-SKTNSPRLVRGGSK----------
----
>Populus_trichocarpa_gnl|BL_ORD_ID|3641 _POPTR_0017s00970.1|PACid:18209660
------------------------------------------------------------
--------------MP-SPP-EPPQHR---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------HNNHH---LSNFLNSTTKTL-----
------------FSLL--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------SP-
-----PNIL---------PLAP----PQPKICISFHL---------PNAPL-------PL
TQ--STLSLFESTQPDSLS-------PSKS-SSASVKDI-SSAESNSGFPSAVRIGRLNP
NGN--G-------GGPA-------------FVGQVFSMCDLSGTGLMAVS-----THFDV
P-FISKRTPEWLKKIFATVTKSERNGPVFRFFMDLGDAVAYVKRLNIPSGV------VGA
CRLDLAYEHFKEKPH--------------LFQFVPNEKQVKAANQLLKSIPHGDGSRRVD
GVPVFSAQNLDIAIATTDGIKWYTPYFFDK--NMLDNILEESVDQHF-------HALIQT
RHMQRRRDVIDDN----VAAEVIEEMGDSLLEPP-----EVQEVLDEMGH-PAIPLSVIS
-KAAEIQLLYAV------------DKVLLGNRWLRKAT--------GIQP----------
--------------KFPYLVDSFERRS-ASSLRRALESTSCLANSKI--------D-DST
SEHKLKD-------------NVQTD-HEQR--KDLRLPFGDWFSHPWLKKHS---KSERE
SDTRK--EGLSKDCLKWKSESNP-----FLPKVTMVGVSTGDAG-----QLSKSSLKKTM
EDLTKELEQTDEANDSFISNSSSEFKVNDR-------------DPLFVANV---------
----------------------------GDYYSGM-AKTGISR-----------------
----
>Malus_domestica_gnl|BL_ORD_ID|44230 _0000777828|PACid:22664215
------------------------------------------------------------
--------------MA-SPS-EPPHTR---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------QQLRP--SITHLVHSTTSNL-----
------------LSLL--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------AS-
-----PKTT---PSP-SLSTTP------PEIRVALFL---------PNLPK-------PL
-----------AFQPDS--------------KLSAMKGVASSPESTSGFPSTVRIAGLNS
NIK--G------SGGPA-------------FVGQVFSMCDLSGTGLMAVS-----THFDI
P-FISKRTPEWLKKMFKSITNSERNGPVFRFFMDLGDAVTYVKRLNIPSGV------VGA
CRLDLAYEHFKEKPH--------------LFQFVPNEKQVKAANKLLKTMPQSGRCKRVD
GVPVFSAQNLDIAIASSDGIKWYTPYFFDK--NMLDNILEESVDQHF-------HSLIQT
RHTQRRHDVIDDN----IPAEVIEEMGDNLWEPP-----EVQEVMDEIGN-SGIPLSVIS
-KAAEMQLLYAV------------DKVLLGNRWLRKAT--------GIQP----------
--------------KFPYMVDSFERRS-AASFLRASQSARCLTNGEAVNDNEDSLD-CST
SKIKSKD-------------DIHTN-KGNK--TDLRFPFSDWFSHLWSKQKD---QNEEL
S----------KERIEQSTLQNP-----NLPKITMVGISTGAAG-----PMSKANLKKTM
EDLTKELEQTDSGNA-FGSDTGNELRFEDR-------------DPLFVANV---------
----------------------------GDYYSGM-AKTGSAKWVRGGNN----------
----
>Prunus_persica_gnl|BL_ORD_ID|26753 _ppa003928m|PACid:17667413
------------------------------------------------------------
--------------MA-SPT-EPAH-K---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------KQARP---ITHLVHSTAANL-----
------------LSLF--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------AS-
-----PKTT---PS------TP------STIRVAFLF---------PNSPK-------PL
--------AFHSAQPDF--------------K-SAMKGVESSSESNSGFPSTVRIAGLNS
NIK--G-------GGPA-------------FVGQVFSMCDLSGTGLMAVS-----THFDI
P-FISKRTPEWLKKMFASVTNSERNGPVFRFFMDLGDAVTYVKRLNIPSGV------VGA
CRLDLAYEHFKEKPH--------------LFQFVPNEKQVKAANKLLKAMQQNGRCKRVD
GVPVFSAQNLDIAIASSDGIKWYTPYFFDK--NMLDNILEESVDQHF-------HSLIQT
RHMQRRRDVIDDS----LPAEVIEEMGDNLWEPP-----EVQEVMDEMGN-PGIPLSVIS
-KAAEMQLLYAV------------DKVLLGNRWLRKAT--------GIQP----------
--------------KFPYMVDSFERRS-AASFLRASQSSNRLANREAVNDNKDSVH-CST
SEVKLND-------------DIQTN-KGNK--LDLRFPFGDWFSHLLLKQKD---QTEEL
S----------KECVELSSQQNP-----NLPKITMVGISTGEAG-----QMSKATLKKTM
EDLTKELEQPDAGNA-GGSDMSNELRFEDR-------------DPLFVANV---------
----------------------------GDYYSGM-ARTGSARWVRGGNN----------
----
>Carica_papaya_gnl|BL_ORD_ID|1469 _evm.model.supercontig_107.127|PACid:16405310
------------------------------------------------------------
--------------MA-SATDQPQH-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------NFHHR---IANLLHATSSSL-----
------------SFLL--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------PS-
-----PKTA---P----YPPSP------PKLCVPFKF---------ADSPVL------PL
------TSVFESPQSDSVS------------SKSTIKGV-SSAESNSGFSSAVRIGGLNS
NGK--A-------SGPA-------------FVGQVFSMCDLTGTGLMAVS-----THFDI
P-FISKRTPQWLKKIFATITKSERNGPVFRFFMDLGDAVAYVKQLNIPSGV------VGA
CRLDLAYEHFKEKPH--------------MFQFVPNERQIKAANKLLKKIPQNDGRTKVD
GVPVFGAQNLDIAIATVDGIKWYTPYFFDK--NMLDNILEESVDQHF-------HSLIQT
RRIQRRRDVVDDS----FAAEVIEEMGDNSWEPP-----EVQEVLNEIGH-PGIPLSVIS
-KAAEIQLLYAV------------DKLLLGNRWLRKAT--------GIQP----------
--------------KFPYLVDSFERRS-TASFLKASKPTNCLTDFEA--------G-LDT
SGVELDD-------------KFQGN-HRET--KDFQLPIGDWLNHSWLKQGQ---KHQML
ADTGY-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Vitis_vinifera_gnl|BL_ORD_ID|19207 _GSVIVT01028824001|PACid:17835832
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------MCDVSGNGIMAVS-----NHFDI
P-FISKRMPQRIKKMFATITKSDKNGPVFRFFMDLGDAVRYVKKLNIPSGG------VGA
CRLDLAYGHFMEKPH--------------LFRFVPNEKQVKAANKLLKKIPQNGGRKRID
GVPVFTAQNLDIAIATTDGIKWYTPYFFDK--HTLDSILEQSIDHHF-------HHLIQS
RHVQRRRDVIDDN----LAAEVLEDNAESLWEPP-----EVQEVLDEVGH-PGIPLSVIS
-KAAEMQLLYAV------------DRVLLGNRWLRKAT--------GIQP----------
--------------KFPYMVDSFEKRS-AASFRRASPSKRFVASPEMGNDNKDTEE-LGP
SDPKLED-------------NTQRD-QGQN--SASWFPVWDLFNHPWSNKRQ---EPQNR
SNARI--EDASREHIKQELQLAP-----FLPKITMVGISAGESG------MSKVNLKKTM
EDLTKELEQADQENA--VGCINSEFEVENR-------------DPLFVANV---------
----------------------------GSYGSGL-VARSPVPSVRGENN----------
----
>Eucalyptus_grandis_gnl|BL_ORD_ID|2953 _A02719.1|PACid:23564674
------------------------------------------------------------
--------------MA-VSPEPPRKHR---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------HHPNP------LSHLLNSTL-----
------------LPLI--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------PN-
-----HKAA---PPSLVSPPPP------PKLLLPVRL---------PP----------AL
SIASPSDSAPPPPHPTPLK-------P----APEVKAPAEPGAAAAGAFPSTVRISAIKS
NGK--G-------RGPA-------------FVGQVFSMCDLSGTGLMAVS-----THFDV
P-FLSKRTPEWLKKVFASITKSERNGPVFRFFMDLGDAVTYVKRLNIPSGV------VGA
CRLDLAYEHFKEKPH--------------LFQFVPNEKQVKAANKLLKTISQGNGNRQID
GVPVFSAQNLDIAIATSDGIKWYTPYFFDK--NMLDNILEESVEQHF-------HSLIQT
RHMQRRRDVIDDN----LT-EVADDVGDSLWEPP-----EVQEVLEEMGH-PGIPLSVIS
-KAAEMQLLYAV------------DRVILGNRWLRKAT--------GIQP----------
--------------KFPYIVDSFERRT-AASLVRASDLTHYLGDRGMKTDESS--Q-EST
DKLALEE-------------NHHVD-LGQK--ADFRFPFGDWLRHPWSKEQQ---KLQKE
VGARHRLESLTGEPVKQKLQPNP-----FLPKITMVGISMGEAG-----QANKATLKKTM
EDLTRELEQTDHGNA--AGNIAD--VSEDR-------------DPLFVANV---------
----------------------------GDYYSGL-AKTGSARLIRRSEAKKQQ------
----
>Glycine_max_gnl|BL_ORD_ID|45053 _16g29580.1|PACid:16303315
------------------------------------------------------------
--------------MA-LPSEPHRRRR---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------HNHNH---ISTFLQSTASNF-----
------------ASLF--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------N--
-----PPNP---PSL-TLPHPP------TSVSLPLFF---------AP----------PL
S------------------------------GSSTVDSA--TSKPAHPPAKSVRIARLGA
NGK-GG-------GGPV-------------FLGEVFSLCDLSGTGLIAAS-----KHFGI
P-FISERTPEWLKKIFAPITKSERNGPVFRFFIDLEDAVSYVEKLNIPSCV------VGA
FRLDLAYKQFKEKPH--------------LFQFVPNEKQVKAANKLLKTISEHGDKKKVD
GVPVFGAQNLDIAIATTDGIKWYTPYFFDK--NMLDNILEDAVDQHF-------HNLIQT
RHMQRRRDVVDDN----LAAEVIEEMSDRLGEPP-----EVQELLDEMGH-PSIPLSVIS
-KAAGLQFQYTV------------DKVLLGNRWLRKAT--------GIQP----------
--------------KFPYMVDSFERRS-EASLLRATESSSCLENSKVEDDRQISEC-LDS
SNCSLDG-------------NTEAI-KQPS--PSLSLPFGNWFHHLWPKQCR---EKASS
SR---------KGVNKEEMKPRP-----ILPKVTMVGLSTEEAG-----QTSKANLKKTM
DDLTRELEKTELDIM--TDGGSKECKVEDR-------------DPLFVANG---------
----------------------------GNYYSSMRRKPGSGR-----------------
----
>Phaseolus_vulgaris_gnl|BL_ORD_ID|6869 _091010222m|PACid:23537334
------------------------------------------------------------
--------------MA-LPSEPHRRRR---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------HHNNH---IATFLQSTASNF-----
------------ASLF--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------N--
-----PPNP---PSL-TLPHPP------SSLSLPLFF---------AP----------PL
S------------------------------ASNALDSAATASEPARPAAKSVRVARLGV
NGKGGG-------GGPA-------------FVGQVFSMCDLSGTGLMAVS-----THFDI
P-FISKRSPEWLKKIFAAITKSERNGPVFRFFIDLGDAVSYVKKLNIPSGV------VGA
CRLDLAYEHFKEKPH--------------LFQFVPNEKQVKAANKLLKAISQHGIRKKVD
GVPVFSAENLDIAIATTDGIKWYTPYFFDK--NMLDNILEEAVDQHF-------HTLIQT
RHMQRRRDVVDDN----LAAEVIEEMGDNLGEPP-----EVQELLDEMGH-PSIPLSVIS
-KAAELQFHYTV------------DKVFLGNRWLRKAT--------GIQP----------
--------------KFPYLVDSFERRS-EASYLRATESRRCLENPKVEDDGKISEC-VDS
SDCGLDD-------------NTEAI-RQPS--YRLSLPFGNWFNHLWPKQCH---EKARS
FK---------KGVNKEDMKPTP-----FLPKVTMVGLSTEEAG-----QMSKANLKKTM
EDLTRELEKTELDNM--AGGGGKECTMEDR-------------DPLFVANV---------
----------------------------GDYYSSL-GKAGSGRWIRGGSN----------
----
>Cucumis_sativus_gnl|BL_ORD_ID|17033 _192940.1|PACid:16968025
------------------------------------------------------------
--------------MA-FQI-EPSSEP---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------HEQNPLTFITHLFHSSTSNF-----
------------STLF--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------AN-
-----PQSI---PPF-PFQSSS------SKLCIPVAF---------PPSPKP------PF
----LSHSGFHSIHYDLDS-------P----KSAAVKGLSSSPNFDSGFPSTLRISGLNS
DGK--T-------GGPA-------------FVGQVFSMCDLSGAGLMAVT-----SNMNI
P-FVSKRTEEWLKKMFSTITKSKRNAPIFRFFTDLGDAVTYVKRLNIPSAV------VGV
CRLDLAYEHFKEKPH--------------LFQFIPNEKQVKAANKLLKGLPQNGGSKKID
GVPVFSAQNLDIAIATTNGIKWYTPYFFDK--NMLDNILEESVDQHF-------HALIQT
RRLQRRREIVDDN----AAAEVLEEMGDSLLEPP-----EVQEVMDEMGN-PGIPLSVIS
-KVAEMQLLYTV------------DKVILGNRWLRKAV--------GIQP----------
--------------KFPYMVDSFERRS-AASLLRIQESASGLTNSESVEETKELQC-YSS
SPLNTED-------------NREAN-QEPK--QHSFNPFRNWFGHLWSKQRQ---RDD--
---------FSQERTKQNVQISP-----FLPKITMVGISTGDSG-----HTSKANLKKTM
EDLTRELEHIDQGNA--ASHNEYEFNNEER-------------DPLFVANV---------
----------------------------SHFSSGL-SKAGSARWVRGND-----------
----
>Linum_usitatissimum_gnl|BL_ORD_ID|5439 _10027537|PACid:23144619
------------------------------------------------------------
--------------MA-TSA-EPPQNH---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------HRRHH--PFPNFFHSATSAV-----
------------LSLL--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------PN-
-----PRTSSA-PPI-TSPSSS----PPPHVCIPFNF---------VDSSY-------PL
NQQSVIRSPLESGQSDSVS-------S----TSATVKGL-SSAESNSGFPSTVRISGLNS
DGK--G-------GGPA-------------FVGQVFSMCDLSGTGLMAVS-----TYIEL
P-FINERTPEWLKKILAPVTKKDKNGPMFRFFMDLGDAVSYVKKLNIPSGV------VGA
CRLDLAYEHFKEKPN--------------LFQFVPNKEQVKAAKQLLKTMPESDGKTTVD
GVPIFSAHNLDIAIATSDGIKWYTPYFFNK--SMLDGIIEDSVDQHF-------HTLIQT
RHMQRRRDVVDDN----FAADVMEEMADSLMDPP-----EVDEMMDEMGN-VGIPLSVIS
-KAAEMELLYAV------------DKVLLGNRWLRKAT--------GIQP----------
--------------RFPYVVDSFERRS-AYSFKKASKTTSLSHVSQA--------G-GSD
SEVEPEN-------------NTQANSYEER--PDLRLTFGDWFG-LRLKQPF---KPARE
TESRT--EGSSKEQMQQKLVDNP-----LLPKITMVGISTGETG-----KVSKASLKKTM
ESLRKELEQADQGKTSSSDNGDGDFKIADR-------------DPLFVANV---------
----------------------------GDY----------SRWIRRGMS----------
----
>Mimulus_guttatus_gnl|BL_ORD_ID|16966 _mgv1a003806m|PACid:17686364
------------------------------------------------------------
--------------MA-SAA-DKSHRR---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------HHPPP--HLSRFISTASTNL-----
------------SSFL--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------TLK
----SPS-----P-----ASSS------SKIHLPLLL---------ADSDS-------FL
----SLVSRSESAQPDSTPSAPSRSPPSSSSSSSSMKST-PSSDSVSKFPPTVRI----T
TGK--G-------GGPA-------------FVGQVFSMCDLSGTGLMAVS-----THFDI
P-FLSKRTPEWLRKMYAAVTKSERNGPVFRFFMDLGDAVSYVKQLNIPSGV------VGA
CRLDIAYEHFKEKPD--------------TFQFVPNERQVKEANKLLKSFPHSDGKNKVE
GVPVFSAQNLDIAIAKKDGIKWYTPYFFDK--SMLDNILEDSVDQQF-------HSLIET
RNAHRRRDIGDDS----LPAEAIEEMGESMWDPP-----EVQEVLDEIGH-PGIPLSVIS
-KAAEIQLLYAV------------DRVILGNRWLRKAT--------GIQP----------
--------------KFPYMVDSFERKT-AASFLRAKTS-NLISNSEISEDAQLD-N-RTT
LDVEPKE-------------KTHDK-QEQKHLINSQFPFGDWLSHPWLKQPE---NQQNL
SETRH--PNSTTQNRGQVAQSSP-----FLPKITMVGVSTGEPG-----KMGKAALKKIM
DDLTKELEKVEQVNQ--ANSNSSEYMADER-------------DPLFVANV---------
----------------------------GDSYSAV-SKTGTSWRVRGGSF----------
----
>Aquilegia_coerulea_gnl|BL_ORD_ID|35613 _013_00192.1|PACid:22058731
------------------------------------------------------------
--------------MAISPSESHLNYN---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------NNNNN---FTRFIQSTSSSF-----
------------FSLF--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----NPSPL---PPL-SSSSSSFPFCSSSSICVPLLF---------SDTPPRILSLSTTL
STNSSSSSTTPSSQNDPLS----------------LNSQIKTRSPSSKFPSSIKISGLNS
NPN--G-------SGPA-------------FVGQVFSMCDVSGTGLMTVS-----THMEI
P-FISKRIPEWIKSMFSVFNKSENNGPVFRFFMDIGDAVSYVKRLNIPTGV------VGA
CRLDLAYEHFKEKPH--------------MFQFVPNEKQVKAANKILKKT-QHSEKRIVD
GVPVFTAQNLDIAIATGDGIKWYTPYFFDK--NMLDNILEESVDQHF-------HSLIQS
RHMHRRRDVIDDN----LTAEVVEDNRDNLWEPP-----EVQEVLDEMGY-PGLPMSVIS
-KAAEVQLLDAV------------DKVLLGNRWLRKAT--------GIQP----------
--------------KFPYRVDSFEKRS-AASFRKATELTSIASNRIDSCVGSKCENLKGS
EEPRLEE-------------NTQSG-QRQP--SEVRLPFGDWFSHLWSKQQH---KPDEQ
TR-----LTDSRDKYIEQLPLSP-----LLPKITMVGISTGEAG-----QTSKASLKQTM
EDLTRELEQPGQDID---DGGSNEIRHEER-------------DPLFVANV---------
----------------------------GV------------------------------
----
>Brachypodium_distachyon_gnl|BL_ORD_ID|2714 _2g07450.1|PACid:21805484
------------------------------------------------------------
--------------MP--------SSS---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------SSSNP-------FHSLTFN------
------------LPFP--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----PAPSSC-STSAS-SPPA----PAPHLAFPLLL---------------------PV
SSASTTSSYSPASHLIPQP------------QRLPGERMAGPAAASGG-------KGVSA
GKS--P-------GGPA-------------FVGQVFTMLDPSGNGLMAVT-----SRFDL
PHFIAHRTPTWFKRILSPLKKSE-SSPVFRFFMDLNDSVSYVKRLNVPSGM------VGA
CRLDVAYEHFKEKPH--------------MFQFVPNEKQVKAANKLLKSIPQKSRRKKLA
GVPVFSAQNLNIAVATDDGIRWYSPYFFDK--NLLDNILEASMDQHF-------HSIIQN
RHIRRRRDIVDDS----LTSEILEESADSLLEPP-----EVQELMNEIGP-AGIPLSVVT
-KAAEIQLLDVV------------DKLLLGNKWLRKAT--------GIQP----------
--------------RFPYVVDSFEERT-ALSVDRTATSSNSCTASKDADFFTNDQQ-SQA
LEPNVDS-------------GNHRK-HNSRDHGQSHFPFSNLLPNIWPGHDR---KFKAQ
EHDNR--FKRYGASMDNDLQANP-----LLPKITMVGISMSEGG-----QMSKANLKKTM
EELTKELEQAGEKTV----------FSDEK-------------DPLFVANV---------
----------------------------GDY-SRI-TKISST------------------
----
>Sorghum_bicolor_gnl|BL_ORD_ID|9318 _Sb03g001210.1|PACid:1960134
------------------------------------------------------------
--------------MP--------RSS---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------SSSNP-------FHSLASA------
------------FPFF--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----SSSSPSPPASASPSPSP----AAPHLAVPLLL---------------------PV
SSGSASAS----SESRRGP------------QPLPGARMAGAAAAGRG----------NK
AGG--G-------AGPA-------------FVGQVFTMLDPSGNGLMAVT-----TRFEL
PRFLTNRTPMWFKRMLSPLKKSE-SSPVFRFFMDLNDAVSYVKRLNVPSGM------VGA
CRLDVAYEHFKEKPH--------------LFQFVPNEKQVQAANKLLKSLPQRSRRKKLG
GVPVFSAQNLNIAVATNDGIRWYTPYFFDK--NLLDNILEASMDQHF-------HSIMQN
RHTQRRRDIVDDS----LTSEIIEESAESLLEPP-----EVQELMNEIGP-AGIPLNVVT
-KAAEIQFLDVV------------DKVLLGNKWLRKAS--------GIQP----------
--------------KFPYVVDSFEERT-AVSIANIATTS-SLTTSNDENCCQNNQQ-TQS
SGSSVDN-------------SSYRN-HNNEDHN--HFPFSNLLPNIWPGHDR---KFKAQ
ESDNK--FSRYDADVKSNLQSNP-----LLPKITMVGISMGDGA-----QMSKANLKKTM
EDLTKELEQTSEENM----------FSDDK-------------DPLFVANV---------
----------------------------GDY-SRI-TKISSA------------------
----
>Zea_mays_gnl|BL_ORD_ID|9045 _GRMZM2G097959_T01|PACid:20828771
------------------------------------------------------------
--------------MP--------CSS---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------SSSNP-------FHSLASA------
------------FPFL--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----SSTSP--PPSPPASPAP----AAPHLAVPLLL---------------------PV
SSAS---------ESRRGA------------QPLPGTRMVGAGATGGG----------NM
ASG--G-------GGPA-------------FVGQVFTMLDPSGNGLMAVT-----TRFEL
PRFLTNRTPMWFKRMLSPSKKTE-NSPVFRFFMDLNDAVSYVKRLNVPSGM------VGA
CRLDVAYEHFKEKPH--------------MFQFVPNEKQVQAANKLLKSLPQRGRRKKLD
GVPVFSAQNLNIAVATNDGIRWYTPYFFDK--NLLDNILEASMDQHF-------HSIMQN
RHTRRRRDIVDDS----LTSEIIEESAESLLEPP-----EVQELMNEIGP-AGIPLNVVT
-KAAEIQFLDVV------------DKVLLGNKWLRKAS--------GIQP----------
--------------KFPYVVDSFEERT-AVSIANIATTS-SLTASNDDSSCQNNQE-TQS
SEPSGDN-------------SSYRN-HNNEDHN--HFPFSNLLPNIWPGHDR---KFKSQ
ESDNK--FSRYDADVKSKLQANP-----LLPKITMVGISMGDGA-----QMSKANLKKTM
EDLTKELEQTSEENM----------FGDEK-------------DPLFVANV---------
----------------------------GDY-SRI-TKISSA------------------
----
>Setaria_italica_gnl|BL_ORD_ID|1638 _Si001606m|PACid:19674983
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------MLDPSGNGLMAVT-----TRFEL
PRFLTNRTPTWFKKILSPLKKSE-NGPVFRFFMDLNDAVSYVKRLNVPSGM------VGA
CRLDVAYEHFKEKPH--------------MFQFVPNEKQVKAANKLLKSLPQRGRRKRLG
GVPVFSAQNLNIAVATNDGIRWYTPYFFDK--NLLDNILEASMDQHF-------HSIMQN
RHKQRRRDIVDDS----LTSEIIEESADSLLEPP-----EVQELMNEIGP-AGIPLNVVT
-KAAEIQLLDVV------------DKVLLGNKWLRKAA--------GIQP----------
--------------RFPYVVDSFEERT-AVSIANIATTS-SFTASND-SCCQNDQQ-SQS
SDPSIEN--------------SYRS-HSNQDHNQFHFPFSNLLPNIWPGHDR---KFKEQ
ESDSK--FSRYDADMKTDLQSNP-----LLPKITMVGISMSEGG-----QMSKANLKKTM
EDLTKELEQTSEKNT----------FGDEK-------------DPLFVANV---------
----------------------------GDY-SRI-TKISST------------------
----
>Oryza_sativa_gnl|BL_ORD_ID|20689 _LOC_Os01g12550.1|PACid:21903161
------------------------------------------------------------
--------------MPRGRSTTTTTSS---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------SASNP-------FHAFAST------
------------LPFL--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----PSPSPS-PTSASPSPSP----PAPHLAVPLIL---------------------PI
TSSSSASAAAAS------P------------ESNRGARMA--AAASGG-----KAGGGGG
LGK--G-------GGPA-------------FVGQVFTMLDPSGNGLMAVT-----TRFEL
PQFLASRTPMWFKRILSPLKKSE-NGPVFRFFMDLNDAVSYVKRLNVPSGM------VGA
CRLDVAYEHFKEKPQ--------------MFQFVPSEKQVKAANKLLKSLPQRRRRKKLD
GVPVFSAQNLNIAVATNDGIRWYTPYFFDK--NLLDNILEASMDQHF-------HSMVQN
RHTRRRRDIVDDS----LTSEMMEESADSFLEPP-----EVQELMNEIGP-VGIPLNVVT
-KAAEIQFLDVV------------DKMLLGNKWLRKAT--------GIQP----------
--------------QFPYVVDSFEERT-AAAIDRAATASSSFTASKDADCFQISKQ-PET
LESDVDN-------------SNRGK-HENSNNGQSHFPFSNLLPNIWPGHDR---SFKAQ
GRDRA--FRRCDASINNDLQANP-----LLPKITMVGISMGEGG-----QMSKANLKKTM
EDLTKELEQAGEKTI----------FSDEK-------------DPLFVANV---------
----------------------------GDY-SRI-TKISST------------------
----
>Panucum_virgatum_gnl|BL_ORD_ID|40717 _Pavirv00055971m|PACid:23796854
------------------------------------------------------------
--------------MP--------RSS---------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------SSSNP-------FPSLASST-----
------------FPFL--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----SSSSSA-ATSSTTSPAH----PAPHLAFPLLL---------------------PV
SSASSSA------EPRRGP------------EPLPGARMAGAGAAAGGKP------GGRI
KGG--G-------GGPA-------------FVGQVFPMLDPSGNGLMAVT-----TRFEL
PRFLTNRTPAWFKKILSPLKKSE-NGPVFRFFMDLNDAVSYVKRLNVPSGM------VGA
CRLDVAYEHFKEKPH--------------MFQFVPNEKQVKAANKLLKSFPQRGRRKRLR
GVPVFSAQNLNIAVATNDGIRWYTPYFFDK--NLLDNILEASMDQHF-------HSIMQN
RHVQRRRDIVDDS----LTSEIIEESADSLLEPP-----EVQELMNEIGP-AGIPLNVVT
-KAAEIQLLDVV------------DKVLLGNKWLRKAA----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Physcomitrella_patens_gnl|BL_ORD_ID|36425 _Pp1s68_153V6.1|PACid:18072962
------------------------------------------------------------
--------------MG--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------RNRDTCNVPGCSKDEKPCLVTGPKIVSFKLPNP-ALFSSWVQTVTSNLAWTVQ
SFQTLKTDGLNCLSLL--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------VEH
----KPMVSPL-PVP---------YLALNNLIFPVP------------------------
-------------------------------SSTSSVQVCQKAVSSIPQDHFSKGNAVNE
KGEVSS-------TGPA-------------FIGQVYTMCDASRQGLIAVRPSDVLKKIKV
P-PYMKLMEKAYERAMNVLFTDDMKGPVFRFYFNKDDAAEYVRRLNITGSA------VGP
CSLDAAYKYYKSKEG--------------MFKFIADQRQVKVAKELVRRERGDKAANKLK
GVPVFTARNLTIALSTPQGVRWFRPYFFNK--KQLDSLIGHSVDHYY-------EMLISA
RRAQRYSQIAENNGDAFAGGESMDDELDGLMDPP-----EVQELMEELGQ-GGGGMEFVG
LKVLEAQFMDLA------------DRVLLGHQWSRRMI--------HLQP----------
--------------RFPVIVDSFERLISASELDHSSESEGSVTSSRNSFAKKEGTQ-EKS
QRGQGDEGMSISGRDERSASNDSSESVSKEYSQSSPNSLFNLFKKKWGANANLVFKRKDS
GNAEILEEDSDSEYLQETAQKDPPGKIPFQPKLTMMGISMNVNKVEGGLQQAMAAAAKDV
EDRLRKGEGSGPDH-----------------------------GPLFIANL---------
----------------------------GSGIPQW-GRPVSASSGVLDDDAE--------
----
>Selaginella_moellendorffii_gnl|BL_ORD_ID|1621 _424522|PACid:15402899
------------------------------------------------------------
--------------ME--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------IGS
VPLHLAYKFFKERPS--------------LFSFIPSKKQVDLAKTIIKKEQGGKAAQQFQ
GVPVFTSHCLSILVVGPSGARWFRPHFFKK--EELDGVIRSSMEHHY-------QSLIRN
RRARRHNQVSD------FPSDMAEDDLE-MLESQ-----DIQDFVEDMDEWSSVLESIMA
-KAAQMYFQDTL------------DRAIFGNKWCRMLA--------GIQP----------
--------------SFPILVDSFERRV-TSETENAVVSHH--------------------
--------------------------EQKK-------PHKDWDSTC--------------
-------------------------------------------------QLKRALIR---
------------------------------------------------------------
------------------------------------------------------------
----
>Kazachstania_africana_gi|410077799|ref|XP_003956481.1| hypothetical protein KAFR_0C03540 [Kazachstania africana CBS 2517]
MSDSDEDLGFQLKGLKISKCLEEDPQVADAMVVNIPISAMANEMSEVDRTSPDENSITGQ
ISQEAVLFEVRSSDIASRHDDMSRQENINVAGTNTQTSNNAKLSEDSSSDDDDWDTVPAI
ASYDVYNDKGELELQPYQSSDNIQRNDTTTNKQNPNITFGYTKVAGEEQAQRSYKTNKKT
AFLFEHKKVMKSLQSTDSLNETTLPTPPPEDTVDYDEFEDDVEPLDNLTPDTQLNITKLL
LNDMEKFAYLGAANVLINQMCTDLATLCLCVDITSNKKLANRLHFTQKDTANWKTIILNR
LYEHLDVTEEEINMIENLSLHKIQLNDLCKCLRVSQLMENPWEDHAGSEASKSEEQVPHN
SSVSDTSENESKSMYSDKDKKVLHPENVKDQHQLHVDVAWTIICDLFLLLLQGSSFDARS
RTLLIRFAEALNITHLEINEFEKRVTDSLDMEQSVDDQVWDEQDHMKKRRKRRKRKKMAY
VGIAMVGGSLVLGLSGGLLAPVIGAGLAAGLSTIGITGATGFLTGAGGTAIVAVSSTAIG
ANIGAKGMSRRMGSVRTFEFIPLHNNRRVNLILTISGWIIGNDDDVRLPFSTVDPVEGDL
YSLFWEPEMLKSTGQTINILASEIFTQTLQQVLGATILTALMSSIQWPMALSKLGYILDN
PWSVSLDRAWAAGLILADTLMTRNLGQRPVTLVGFSLGARVIYSCLIELCKKKALGLVEN
VFIFGTPVVRKKEELVMARSVVSGRFVNGYSDKDWVLAYLFRATSGGFSAVMGISPVDDV
EGIDNFNCTELVDGHMAYRKNMPKLLKEVNITVLAEEFAEIEETIDPEEIRKQRKLVKDL
DAAHKKLSGKKKHHGWMPQWMKPKKSKWQSMVEKTVEEKEIEEIPTEELTSSSTSKTKDN
GIFDHSALMQELANLKASLHEKENEKDDSDKGNKNGESTTTSDHDYKASPSGNNFQLLSA
GRTILPDDDEMYRKKNMEFAFPDDV
>gi|366991929|ref|XP_003675730.1| hypothetical protein NCAS_0C03750 [Naumovozyma castellii CBS 4309]
MIYECKTAFDTEDSVDDRDKTTEKEGILAFLIQILYLQIKIAKRLLLFETFLFYLCTFSK
QSNRNKVIEQIITSMSDSEDDLGIPLKGLRISKYLKEEKTKNSLPKDSLPKDDSPEDNDL
SSTPQFHSPGVSPSEPTIAPQVSSTAPESIISDSENPLT--------------------T
TNTASIDALETKDHSGVHQETD---------AIAAEQQVGIRKDEKDV------------
------LDSDSDSDSTEWQTMPTIASYNVYNQKGELELKPYS-STSLNSSQDQLTLTNS-
NIKKKKDHTFDYTKVAEETQAQRSYLSNKKTDFLFDHKKLKKL----NNSTDSHL-----
-----------SNTSSPDI---------------PDIIDEEDENYDEFEDDIEPTDDLNP
DSQLSITKNLLTDQEKFAYLGAVNVIANQMCTDLATLCLCIDIKAHKKLAHRLQFTQKDM
AAWKTVVLSRVYDHLGVSEEEIDMIERLSLHKIKVEDLCKCLKTTQNIDNPFEDTSSENK
SGVDNEKDKKEDQEPDKKLEEMEQDKTVNELESIGDSTLASTSEGVEVKDQFKEPSVNDD
DTMLAPTKIID-PNA-IKDKSKLSVDIAWTIICDLFLILLQGSNYDSRSRTLLIKFAEAL
NVTKMEICEFEKRVTDSLDMEQSTDDQVWNETDHMKARRKKKRRRKMYYVGLAMVGGSLV
LGLSGG------LLAPVIGAGIAAGLSTVGLTGATGFLTGVGGTTVVALSSTAIGANIGA
R-GMSKRMGSVRTFEFRPLHNNRR---VNLIISVSGWIIGNEDDVRLPFST------VDP
VEGDL-YSLYWE-PE--------------MLKSTGQTINIVASEVFTQTIQQ--------
---VLGA---TILTAFMSAIQW--PMALSKLGYILDNPWNVSLDRAWAAGLILADTLMTR
NLGERPVTLVGFS----LGARVIYSCLIELCKK------KALGLIENVFI-FGTPV--VR
-KKEHLVMARSVVSGRFVNGYSDKDWVL---AYLFRATAGGFSAVMGISPIEGIEGIENF
NCTELVDGHMAYRQNMPKLLKEMGIAVLGDTFVEIEELMD-------------PEE-FQR
QRKLVHD-----------VDAAQKKLSERKKHSSGWVP--KWLKPKKSKWQV---MVEEA
VEETKESDILTE-----SETPKP---------KKKDGALVDHGALMHELELLKAAMHENA
LKENTEPETAAQHDEADTHTV----KVEEEPTRQGTPSTPKPQ-----------------
----------------------------NNFQLLGAGRTILPEDDELY-SKKKKMEFAFP
DDIN
>gi|410730299|ref|XP_003671329.2| hypothetical protein NDAI_0G03090 [Naumovozyma dairenensis CBS 421]
------------------------------------------------------------
--------------MSDSEEDLGIELKGLKISKYLKKDTETNRSQQSN---EEKHNDEGL
GSTP-LQETLIEEHSDTNEAEDHSNSESSSLSDNNGNLTIDSLPMSYRNMNLEEGQKDVI
ENSSLNQSLSPSFQPIRSSETP---------SISSRNEPHQQKQEQDISPNDAIPKAKND
HEDTHSLSSDDTDDDSEWQTMPAVASYNVYNKNGELELKPYD-SNEETFDIEQIQKTGKY
NNK--NKQTFDYTKVAEETQAQRSYLSNKKTDFLFEHKKLKKA----LQSKNKST-----
---------ESQLTNYSSSNSKLNSEITLNNPEEIEEEEEEDSEFDEFEDDVEAQDDLNP
TSQLSVTKDLLSDMEKFAYLGAVNVLVNQMCTDLATVCLCVDIKSHKKLASRLHFTQKDM
AAWKTVILSRLYEHLAVSQKEIEMIEKLSLHKIQLEDLCKCLKTTQNVENPWEKDNKKKS
S-LDNSQEKGE-------KNKSSLDNSQETDANSEKMRHSNEEEGTIET-KTETKESTSM
----VPQKVIK-PEN-INDQNRLNIDIAWTIICDLFLVFLQNYTYDARSRTLLIKFAKAL
NITKLEICEFEKRITDSLDMEQSTEDQEWNETDHMKSRRKRKRRKKMAYVGLAMVGGSLV
LGLSGG------LLAPVIGAGIAAGLSTIGIGGATGFLTGVGGTTVVALSSTAIGANIGA
R-GMSKRMGSVRTFEFRPLHNNRR---VNLILSVSGWIIGNEDDVRLPFST------VDP
LEGDL-YSLYWE-PE--------------MLKSTGQTINIVASEVFTQTIQQ--------
---VLGA---TILTGLMSAIQW--PMALSKLGYILDNPWNVSLDRAWAAGLILADTLMSR
NLGERPITLVGFS----LGARVIFSCLIELSKR------KASGLVENVFI-FGTPI--VR
-KREHLVMARSIVSGRFVNGYSDKDWVL---AYLFRATGGGFKAVMGISPIEDINEIENF
NCTEFVDGHMAYRKNMPKLLREMGIAVLDDTFVEIEEIMD-------------PNE-YKR
KRKLVHD-----------VDAAQKKLSERKKH-NSWMP--KWLKPKKSKWQV---MVEEA
VEEGREGALEGEDDGSSTDEKNQNKEEG--------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>gi|367011313|ref|XP_003680157.1| hypothetical protein TDEL_0C00570 [Torulaspora delbrueckii]
------------------------------------------------------------
--------------MSDSDEDLGIALKGLKLSAKHVQNKAKDKNVNECDKVDPAP-----
-----------------------------------------------------------E
AMDGPEETKEASEGMKLPEEVV--------------------------------------
------SDVDSDSDEDSWRNMEAIASFNVYNDKGELELKTYQAQAAQTASKEALSGTAG-
SNGTARSVTFGYTKIAAEEQAQRTSRSNRKTDFLFDHKRLKR-----LNGSNSST-----
-----------TGLTEPQT---------------PSDTELHQDSYDEYEEGVEPMNDLNA
DNQLNVTKNLLDEMEKFAYVAAVNVLANQMCTELATTCLCVDIKSHKKLAQRLNFAQKDS
ANWKTHVLNSLYDHLQLSPEEVQMIEKLSMHGVHLEDLCKCLKTTQDIENPFEGVNESKQ
S-----------------LESGKEDSKDAEAESVGSHTSKDRSSIDLTT----EEEETSK
----APKQVIA-PEN-LKEQGQIKIDVAWTIICDLFLVLLHDAVYDARSRTLLMRFAKVL
NIENLEICEFERRVTDSLDMEQSTENQEWNEIDHMKSRRKKRKRKKLCYVGLAMVGGSLI
LGLSGG------LLAPVIGAGIAAGLSTIGIGGATGFLTGAGGTAVVAVASTAIGGNIGA
K-GMGRRMGSVRTFEFRPLHNNRR---VNLIISVSGWMIGNEDDVRLPYST------VDP
VEGDL-YALHWE-PE--------------MLKSIGQTIGIVANEIFTQALQQ--------
---ILGA---TILTAFISAIQW--PMGLSKLGYILDNPWSVSLDRAWAAGLILADTLMSR
NLGQRPITLMGFS----LGSRVIFSCLVELSRK------KALGLVENVYI-FGTPV--VK
-KKEHLIMARSAVSGRFVNAFSGRDWML---AYLFRAAAGGFNKVMGIAPIEGIESIENY
DCTDIVDGHLAYRKNMPKLLKRLGVEVVSEEFVEIEETVD-------------PEQ-LHR
KRQMVQD-----------VDAAQKKLQEKKHH-SGWMP--KWLKPKKSKWRT---MVEDA
VEEGTQVEVPDAPDVLHTEEVKP---------KKKDNALVDNGALMRELQKIKAAIREEQ
LQQERASAVAD-NVDAKKTTLGADTNVQKEVSPPKTP-LTTPQSP---------------
----------------------------NNFQLLSAGRPIILEDDDFG-KQKKDLTFSFS
DDF-
>gi|349577884|dbj|GAA23051.1| K7_Yfl034wp [Saccharomyces cerevisiae Kyokai no. 7]
------------------------------------------------------------
--------------MSDSEEDLGIQLKGLKIARHLKESGEHTDEESNSSPEHDCGLSNQD
DLT-----------------VMHTQAKEEVFKRREEDGT--------------------R
TEDALHEGEAGKEGTGFPSSQSVCSPNEADSGIDRADKPSLLDPFKSVHDTDPVPGTKSR
SN----SDSDSDSDDGGWQEMPAVSSFNIYNHRGELELTSKV-RNSEQASETSPTVPPGK
NCKSVNDSRFDYTKMAAEQQAQRSYRTNKKTDFLFDHKVLKKK----INSSQTSV-----
-----------NLTSSPSTTSL--------NNEKNNDDDDDDDSYDEYEDDVEPVNDLNR
DSQLNITKNLLSDMEKFAYVGAINILANQMCTNLATLCLCIDIKSHKKLAHRLQFTQKDM
AAWKTVVLSRLYDHLGISQEEIVMIEKLSLHKIQLEDLCKCLKTTQSIDNPWENDRDHEE
DDI---------------EETTERMSPNEQNGSVQASTPDPEQSATPETPKAKQSSLSSD
----VPGKVLD-PEN-VKSQDKLNIDVAWTIICDLFLICLQSSTYDSRSRTLLINFAKVL
NMTSLEICEFERRVTDSLDMEQSTEDQVWDEQDHMRNRRRSKRRKKMAYVALAMVGGSLV
LGLSGG------LLAPVIGGGIAAGLSTIGITGATSFLTGVGGTTVVAVSSTAIGANIGA
R-GMSKRMGSVRTFEFRPLHNNRR---VNLILTVSGWMVGNEDDVRLPFST------VDP
VEGDL-YSLYWE-PE--------------MLKSIGQTVSIVATEIFTTSLQQ--------
---ILGA---TVLTALISSIQW--PMALSKLGYILDNPWNVSLDRAWSAGKILADTLIAR
NLGARPITLVGFS----IGARVIFSCLIELCKK------KALGLIENVYL-FGTPA--VM
-KKEQLVMARSVVSGRFVNGYSDKDWFL---AYLFRAAAGGFSAVMGISTIENVEGIENI
NCTEFVDGHLNYRKSMPKLLKRIGIAVLSEEFVEIEEMMN-------------PEE-VKR
KRKLIND-----------VDAAQKKLSERKKH-NSWVP--KWLKPKKSKWKV---MVEEA
VEEGRDMQDLPENDVNNNENENPDEHEGVARQKRRDAALVDHGALMHELQLIKQAMHEDE
IKNKACLPGEDKEVESSNDFLG-----ESHYKPPSTPKINPPQSP---------------
----------------------------NNFQLLSAGRTILPEDDDFDPRGKKKMEFSFP
DDI-
>gi|256268897|gb|EEU04246.1| YFL034W-like protein [Saccharomyces cerevisiae JAY291]
------------------------------------------------------------
--------------MSDSEEDLGVQLKGLKIARHLKESGEHTDEESNSSPEHDCGLSNQD
DLT-----------------VMHTQAKEEVFKRREEDGT--------------------R
TEDALHEGEAGKEGTGFPSSQSVCSPNEADSGIDRADKPSLLDPFKSVHDTDPVPGTKSR
SN----SDSDSDSDDGGWQEMPAVSSFNIYNHRGELELTSKV-RNSEQASETSPTVPPGK
NCKSVNDSRFDYTKMAAEQQAQRSYRTNKKTDFLFDHKVLKKK----INSSQTSV-----
-----------NLTSSPSTTSL--------NNEKNN-DDDDDDSYDEYEDDVEPVNDLNR
DSQLNITKNLLSDMEKFAYVGAINILANQMCTNLATLCLCIDIKSHKKLAHRLQFTQKDM
AAWKTVVLSRLYDHLGISQEEIVMIEKLSLHKIQLEDLCKCLKTTQSIDNPWENDRDHEE
DGI---------------EETTERMSPNEQNGSVQASTPDPEQSATPETPKAKQSSLSSD
----VPGKVLD-PEN-VKSQDKLNIDVAWTIICDLFLICLQSSTYDSRSRTLLINFAKVL
NMTSLEICEFERRVTDSLDMEQSTEDQVWDEQDHMRNRRRSKRRKKMAYVALAMVGGSLV
LGLSGG------LLAPVIGGGIAAGLSTIGITGATSFLTGVGGTTVVAVSSTAIGANIGA
R-GMSKRMGSVRTFEFRPLHNNRR---VNLILTVSGWMVGNEDDVRLPFST------VDP
VEGDL-YSLYWE-PE--------------MLKSIGQTVSIVATEIFTTSLQQ--------
---ILGA---TVLTALISSIQW--PMALSKLGYILDNPWNVSLDRAWSAGKILADTLIAR
NLGARPITLVGFS----IGARVIFSCLIELCKK------KALGLIENVYL-FGTPA--VM
-KKEQLVMARSVVSGRFVNGYSDKDWFL---AYLFRAAAGGFSAVMGISTIENVEGIENI
NCTEFVDGHLNYRKSMPKLLKRIGIAVLSEEFVEIEEMMN-------------PEE-VKR
KRKLIND-----------VDAAQKKLSERKKH-NSWVP--KWLKPKKSKWKV---MVEEA
VEEGRDMQDLPENDVNNNENENPDEHEGIARQKRRDAALVDHGALMHELQLIKQAMHEDE
IKNKACLPGEDKEVESSNDFLG-----ESHYKPPSTPKINPPQSP---------------
----------------------------NNFQLLSAGRTILPEDDDFDPRGKKKVEFSFP
DDI-
>gi|151940730|gb|EDN59117.1| conserved protein [Saccharomyces cerevisiae YJM789]
------------------------------------------------------------
--------------MSDSEEDLGVQLKGLKIARHLKESGEHTDEESNSSPEHDCGLSNQD
DLT-----------------VMHTQAKEEVFKRREEDGT--------------------R
TEDALHEGEAGKEGTGFPSSQSVCSPNEADSGIDRADKPSLLDPFKSVHDTDPVPGTKSR
SN----SDSDSDSDDGGWQEMPAVSSFNIYNHRGELELTSKV-RNSEQASETSPTVPPGK
NCKSVNDSRFDYTKMAAEQQAQRSYRTNKKTDFLFDHKVLKKK----INSSQTSV-----
-----------NLTSSPSTTSL--------NNEKNN-DDDDDDSYDEYEDDVEPVNDLNR
DSQLNITKNLLSDMEKFAYVGAINILANQMCTNLATLCLCIDVKSHKKLAHRLQFTQKDM
AAWKTVVLSRLYDHLGISQEEIVMIEKLSLHKIQLEDLCKCLKTTQSIDNPWENDRDHEE
DGI---------------EETTERMSPNEQNGSVQASTPDPEQSATPETPKAKQSSLSSD
----VPGKVLD-PEN-VKSQDKLNIDVAWTIICDLFLICLQSSTYDSRSRTLLINFAKVL
NMTSLEICEFERRVTDSLDMEQSTEDQVWDEQDHMRNRRRSKRRKKMAYVALAMVGGSLV
LGLSGG------LLAPVIGGGIAAGLSTIGITGATSFLTGVGGTTVVAVSSTAIGANIGA
R-GMSKRMGSVRTFEFRPLHNNRR---VNLILTVSGWMVGNEDDVRLPFST------VDP
VEGDL-YSLYWE-PE--------------MLKSIGQTVSIVATEIFTTSLQQ--------
---ILGA---TVLTALISSIQW--PMALSKLGYILDNPWNVSLDRAWSAGKILADTLIAR
NLGARPITLVGFS----IGARVIFSCLIELCKK------KALGLIENVYL-FGTPA--VM
-KKEQLVMARSVVSGRFVNGYSDKDWFL---AYLFRAAAGGFSAVMGISTIENVEGIENI
NCTEFVDGHLNYRKSMPKLLKRIGIAVLSEEFVEIEEMMN-------------PEE-VKR
KRKLIND-----------VDAAQKKLSERKKH-NSWVP--KWLKPKKSKWKV---MVEEA
VEEGRDMQDLPENDVNNNENENPDEHEGIARQKRRDAALVDHGALMHELQLIKQAMHEDE
IKNKACLPGEDKEVESSNDFLG-----ESHYKPPSTPKINPPQSP---------------
----------------------------NNFQLLSAGRTILPEDDDFDPRGKKKVEFSFP
DDI-
>gi|190406542|gb|EDV09809.1| conserved hypothetical protein [Saccharomyces cerevisiae RM11-1a]
------------------------------------------------------------
--------------MSDSEEDLGIQLKGLKIARHLKESGEHTDEESNSSPEHDCGLSNQD
DLT-----------------VMHTQAKEEVFKRREEDGT--------------------R
TEDALHEGEAGKEGTGFPSSQSVCSPNEADSGIDRADKPSLLDPFKSVHDTDPVPGTKSR
SN----SDSDSDSDDGGWQEMPAVSSFNIYNHRGELELTSKV-RNSEQASETSPTVPPGK
NCKSVNDSRFDYTKMAAEQQAQRSYRTNKKTDFLFDHKVLKKK----INSSQTSV-----
-----------NLTSSPSTTSL--------NNEKNN-DDDDDDSYDEYEDDVEPVNDLNR
DSQLNITKNLLSDMEKFAYVGAINILANQMCTNLATLCLCIDIKSHKKLAHRLQFTQKDM
AAWKTVVLSRLYDHLGISQEEIVMIEKLSLHKIQLEDLCKCLKTTQSIDNPWENDRDHEE
DGI---------------EETTERMSPNEQNGSVQASTPDPEQSATPETPKAKQSSLSSD
----VPGKVLD-PEN-VKSQDKLNIDVAWTIICDLFLICLQSSTYDSRSRTLLINFAKVL
NMTSLEICEFERRVTDSLDMEQSTEDQVWDEQDHMRNRRRSKRRKKMAYVALAMVGGSLV
LGLSGG------LLAPVIGGGVAAGLSTIGITGATSFLTGVGGTTVVAVSSTAIGANIGA
R-GMSKRMGSVRTFEFRPLHNNRR---VNLILTVSGWMVGNEDDVRLPFST------VDP
VEGDL-YSLYWE-PE--------------MLKSIGQTVSIVATEIFTTSLQQ--------
---ILGA---TVLTALISSIQW--PMALSKLGYILDNPWNVSLDRAWSAGKILADTLIAR
NLGARPITLVGFS----IGARVIFSCLIELCKK------KALGLIENVYL-FGTPA--VM
-KKEQLVMARSVVSGRFVNGYSDKDWFL---AYLFRAAAGGFSAVMGISTIENVEGIENI
NCTEFVDGHLNYRKSMPKLLKRIGIAVLSEEFVEIEEMMN-------------PEE-VKR
KRKLIND-----------VDAAQKKLSERKKH-NSWVP--KWLKPKKSKWKV---MVEEA
VEEGRDMQDLPENDVNNNENENPDEHEGIARQKRRDAALVDHGALMHELQLIKQAMHEDE
IKNKACLPGEDKEVESSNDFLG-----ESHYKPPSTPKINPPQSP---------------
----------------------------NNFQLLSAGRTILPEDDDFDPRGKKKVEFSFP
DDI-
>gi|207345722|gb|EDZ72448.1| YFL034Wp-like protein [Saccharomyces cerevisiae AWRI1631]
------------------------------------------------------------
--------------MSDSEEDLGVQLKGLKIARHLKESGEHTDEESNSSPEHDCGLSNQD
DLT-----------------VMHTQAKEEVFKRREEDGT--------------------R
TEDALHEGEAGKEGTGFPSSQSVCSPNEADSGIDRADKPSLLDPFKSVHDTDPVPGTKSR
SN----SDSDSDSDDGGWQEMPAVSSFNIYNHRGELELTSKV-RNSEQASETSPTVPPGK
NCKSVNDSRFDYTKMAAEQQAQRSYRTNKKTDFLFDHKVLKKK----INSSQTSV-----
-----------NLTSSPSTTSL--------NNEKNN-DDDDDDSCDEYEDDVEPVNDLNR
DSQLNITKNLLSDMEKFAYVGAINILANQMCTNLATLCLCIDVKSHKKLAHRLQFTQKDM
AAWKTVVLSRLYDHLGISQEEIVMIEKLSLHKIQLEDLCKCLKTTQSIDNPWENDRDHEE
DGI---------------EETTERMSPNEQNGSVQASTPDPEQSATPETPKAKQSSLSSD
----VPGKVLD-PEN-VKSQDKLNIDVAWTIICDLFLICLQSSTYDSRSRTLLINFAKVL
NMTSLEICEFERRVTDSLDMEQSTEDQVWDEQDHMRNRRRSKRRKKMAYVALAMVGGSLV
LGLSGG------LLAPVIGGGIAAGLSTIGITGATSFLTGVGGTTVVAVSSTAIGANIGA
R-GMSKRMGSVRTFEFRPLHNNRR---VNLILTVSGWMVGNEDDVRLPFST------VDP
VEGDL-YSLYWE-PE--------------MLKSIGQTVSIVATEIFTTSLQQ--------
---ILGA---TVLTALISSIQW--PMALSKLGYILDNPWNVSLDRAWSAGKILADTLIAR
NLGARPITLVGFS----IGARVIFSCLIELCKK------KALGLIENVYL-FGTPA--VM
-KKEQLVMARSVVSGRFVNGYSDKDWFL---AYLFRAAAGGFSAVMGISTIENVEGIENI
NCTEFVDGHLNYRKSMPKLLKRIGIAVLSEEFVEIEEMMN-------------PEE-VKR
KRKLIND-----------VDAAQKKLSERKKH-NSWVP--KWLKPKKSKWKV---MVEEA
VEEGRDMQDLPENDVNNNENENPDEHEGIARQKRRDAALVDHGALMHELQLIKQAMHEDE
IKNKACLPGEDKEVESSNDFLG-----ESHYKPPSTPKINPPQSP---------------
----------------------------NNFQLLSAGRTILPEDDDFDPRGKKKVEFSFP
DDI-
>gi|330443533|ref|NP_116583.2| hypothetical protein YFL034W [Saccharomyces cerevisiae S288c]
------------------------------------------------------------
--------------MSDSEEDLGVQLKGLKIARHLKESGEHTDEESNSSPEHDCGLSNQD
DLT-----------------VMHTQAKEEVFKRREEDGT--------------------R
TEDALHEGEAGKEGTGFPSSQSVCSPNEADSGIDRADKPILLDPFKSVHDTDPVPGTKSR
SN----SDSDSDSDDGGWQEMPAVSSFNIYNHRGELELTSKV-RNSEQASETSPTVPPGK
NCKSVNDSRFDYTKMAAEQQAQRSYRTNKKTDFLFDHKVLKKK----INSSQTSV-----
-----------NLTSSPSTTSL--------NNEKNN-DDDDDDSYDEYEDDVEPVNDLNR
DSQLNITKNLLSDMEKFAYVGAINILANQMCTNLATLCLCIDIKSHKKLAHRLQFTQKDM
AAWKTVVLSRLYDHLGISQEEIVMIEKLSLHKIQLEDLCKCLKTTQSIDNPWENDRDHEE
DGI---------------EETTERMSPNEQNGSVQASTPDPEQSATPETPKAKQSPLSSD
----VPGKVLD-PEN-VKSQDKLNIDVAWTIICDLFLICLQSSTYDSRSRTLLINFAKVL
NMTSLEICEFERRVTDSLDMEQSTEDQVWDEQDHMRNRRRSKRRKKMAYVALAMVGGSLV
LGLSGG------LLAPVIGGGIAAGLSTIGITGATSFLTGVGGTTVVAVSSTAIGANIGA
R-GMSKRMGSVRTFEFRPLHNNRR---VNLILTVSGWMVGNEDDVRLPFST------VDP
VEGDL-YSLYWE-PE--------------MLKSIGQTVSIVATEIFTTSLQQ--------
---ILGA---TVLTALISSIQW--PMALSKLGYILDNPWNVSLDRAWSAGKILADTLIAR
NLGARPITLVGFS----IGARVIFSCLIELCKK------KALGLIENVYL-FGTPA--VM
-KKEQLVMARSVVSGRFVNGYSDKDWFL---AYLFRAAAGGFSAVMGISTIENVEGIENI
NCTEFVDGHLNYRKSMPKLLKRIGIAVLSEEFVEIEEMMN-------------PEE-VKR
KRKLIND-----------VDAAQKKLSERKKH-NSWVP--KWLKPKKSKWKV---MVEEA
VEEGRDMQDLPENDVNNNENENPDEHEGIARQKRRDAALVDHGALMHELQLIKQAMHEDE
IKNKACLPGEDKEVESSNDFLG-----ESHYKPPSTPKINPPQSP---------------
----------------------------NNFQLLSAGRTILPEDDDFDPRGKKKVEFSFP
DDI-
>gi|836720|dbj|BAA09205.1| unnamed protein product [Saccharomyces cerevisiae]
------------------------------------------------------------
--------------MSDSEEDLGVQLKGLKIARHLKESGEHTDEESNSSPEHDCGLSNQD
DLT-----------------VMHTQAKEEVFKRREEDGT--------------------R
TEDALHEGEAGKEGTGFPSSQSVCSPNEADSGIDRADKPILLDPFKSVHDTDPVPGTKSR
SN----SDSDSDSDDGGWQEMPAVSSFNIYNHRGELELTSKV-RNSEQASETSPTVPPGK
NCKSVNDSRFDYTKMAAEQQAQRSYRTNKKTDFLFDHKVLKKK----INSSQTSV-----
-----------NLTSSPSTTSL--------NNEKNN-DDDDDDSYDEYEDDVEPVNDLNR
DSQLNITKNLLSDMEKFAYVGAINILANQMCTNLATLCLCIDIKSHKNLAHRLQFTQKDM
AAWKTVVLSRLYDHLGISQEEIVMIEKLSLHKIQLEDLCKCLKTTQSIDNPWENDRDHEE
DGI---------------EETTERMSPNEQNGSVQASTPDPEQSATPETPKAKQSPLSSD
----VPGKVLD-PEN-VKSQDKLNIDVAWTIICDLFLICLQSSTYDSRSRTLLINFAKVL
NMTSLEICEFERRVTDSLDMEQSTEDQVWDEQDHMRNRRRSKRRKKMAYVALAMVGGSLV
LGLSGG------LLAPVIGGGIAAGLSTIGITGATSFLTGVGGTTVVAVSSTAIGANIGA
R-GMSKRMGSVRTFEFRPLHNNRR---VNLILTVSGWMVGNEDDVRLPFST------VDP
VEGDL-YSLYWE-PE--------------MLKSIGQTVSIVATEIFTTSLQQ--------
---ILGA---TVLTALISSIQW--PMALSKLGYILDNPWNVSLDRAWSAGKILADTLIAR
NLGARPITLVGFS----IGARVIFSCLIELCKK------KALGLIENVYL-FGTPA--VM
-KKEQLVMARSVVSGRFVNGYSDKDWFL---AYLFRAAAGGFSAVMGISTIENVEGIENI
NCTEFVDGHLNYRKSMPKLLKRIGIAVLSEEFVEIEEMMN-------------PEE-VKR
KRKLIND-----------VDAAQKKLSERKKH-NSWVP--KWLKPKKSKWKV---MVEEA
VEEGRDMQDLPENDVNNNENENPDEHEGIARQKRRDAALVDHGALMHELQLIKQAMHEDE
IKNKACLPGEDKEVESSNDFLG-----ESHYKPPSTPKINPPQSP---------------
----------------------------NNFQLLSAGRTILPEDDDFDPRGKKKVEFSFP
DDI-
>gi|259146156|emb|CAY79415.1| EC1118_1F14_0463p [Saccharomyces cerevisiae EC1118]
------------------------------------------------------------
--------------MSDSEEDLGIQLKGLTIARHLKESGEHTDEESNSSPEHDCGLSNQD
DLT-----------------VMHTQAKEEVFKRREEDGT--------------------R
TEDALHEGEAGKEGTGFPSSQSVFSPNEADSGIDRADKPSLLDPFKSVHDTDPVPGTKSR
SN----SDSDSDSDDGGWQEMPAVSSFNIYNHRGELELTSKV-RNSEQASETSPTVPPGK
NCKSVNDSRFDYTKMAAEQQAQRSYRTNKKTDFLFDHKVLKKK----INSSQTSV-----
-----------NLTSSPSTTSL--------NNEKNN-DDDDDDSYDEYEDDVEPVNDLNR
DSQLNITKNLLSDMEKFAYVGAINILANQMCTNLATLCLCIDVKSHKKLAHRLQFTQKDM
AAWKTVVLSRLYDHLGISQEEIVMIEKLSLHKIQLEDLCKCLKTTQSIDNPWENDRDHEE
DGI---------------EETTERMSPNEQNGSVQASTPDPEQSATPETPKAKQSSLSSD
----VPGKVLD-PEN-VKSQDKLNIDVAWTIICDLFLICLQSSTYDSRSRTLLINFAKVL
NMTSLEICEFERRVTDSLDMEQSTEDQVWDEQDHMRNRRRSKRRKKMAYVALAMVGGSLV
LGLSGG------LLAPVIGGGVAAGLSTIGITGATSFLTGVGGTTVVAVSSTAIGANIGA
R-GMSKRMGSVRTFEFRPLHNNRR---VNLILTVSGWMVGNEDDVRLPFST------VDP
VEGDL-YSLYWE-PE--------------MLKSIGQTVSIVATEIFTTSLQQ--------
---ILGA---TVLTALISSIQW--PMALSKLGYILDNPWNVSLDRAWSAGKILADTLIAR
NLGARPITLVGFS----IGARVIFSCLIELCKK------KALGLIENVYL-FGTPA--VM
-KKEQLVMARSVVSGRFVNGYSDKDWFL---AYLFRAAAGGFSAVMGISTIENVEGIENI
NCTEFVDGHLNYRKSMPKLLKRIGIAVLSEEFVEIEEMMN-------------PEE-VKR
KRKLIND-----------VDAAQKKLSERKKH-NSWVP--KWLKPKKSKWKV---MVEEA
VEEGRDMQDLPENDVNNNENENPDEHEGIARQKRRDAALVDHGALMHELQLIKQAMHEDE
IKNKACLPGEDKEVESSNDFLG-----ESHYKPPSTPKINPPQSP---------------
----------------------------NNFQLLSAGRTILPEDDDFDPRGKKKVEFSFP
DDI-
