>Arabidopsis_thaliana_gi|18424615|ref|NP_568958.1| Tic22-like family protein [Arabidopsis thaliana]
------------------------------------------------------------
--------------M---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------G-SPD-----KQHRRHV----------AAEFLHS--AVTSISSSIIPL
F-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------PPKTA--P------
---------SRVCLPLRF---------SVSD---------------------------DV
SS-------P----FESTVK--STSSASSSGLNSTVRISSLSSDGK--R-GGPA------
-------FVGQVFSMCDLTGTGLMAVS-----THFDIP-FISKRTPEWLKKMFSTITKSE
RNGPVFRFFMDLGDAVSYVKKLNIPSGVVGACRLDLAYEHFKEKPHLFQFVPNERQVKAA
NKLLKSMPQNGKTQKVEGVPVFGAQNLDIAVATADGIKWYTPYFFDK--AVLDNILEESV
DQHFH-------TLIQTRHVQRRRDVVDDS----LASEVMEEMGDSMLEPPEVQEAMEEI
GT-SGIPLSVVA-KAAEIQLLYAV------------DRVLLGSRWFRKAT--------GI
QPKLPYLVDSFE-----------------RR-SAFSIQRASGSATRCLGDSVEA------
D-TSASLLRVED--------------DSPSEA-EKRQ--QHLWFPFGDWISHSVSRKEH-
--THHKGSSDQR-----DMESREREMLRSP-----FLPKITMVGISTGEAA-----QMSK
ANLKKTMEDLTEDLEQSDEGND-HG-----------------------------------
-----------------SKRYDSLKIEER----------DPLFVANVGDY-YSGL-AKAG
SARLSRRGDDQ------------------
>iTic22-like_gi|18424615|ref|NP_568958.1| Tic22-like family protein [Arabidopsis thaliana]
------------------------------------------------------------
--------------M---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------G-SPD-----KQHRRHV----------AAEFLHS--AVTSISSSIIPL
F-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------PPKTA--P------
---------SRVCLPLRF---------SVSD---------------------------DV
SS-------P----FESTVK--STSSASSSGLNSTVRISSLSSDGK--R-GGPA------
-------FVGQVFSMCDLTGTGLMAVS-----THFDIP-FISKRTPEWLKKMFSTITKSE
RNGPVFRFFMDLGDAVSYVKKLNIPSGVVGACRLDLAYEHFKEKPHLFQFVPNERQVKAA
NKLLKSMPQNGKTQKVEGVPVFGAQNLDIAVATADGIKWYTPYFFDK--AVLDNILEESV
DQHFH-------TLIQTRHVQRRRDVVDDS----LASEVMEEMGDSMLEPPEVQEAMEEI
GT-SGIPLSVVA-KAAEIQLLYAV------------DRVLLGSRWFRKAT--------GI
QPKLPYLVDSFE-----------------RR-SAFSIQRASGSATRCLGDSVEA------
D-TSASLLRVED--------------DSPSEA-EKRQ--QHLWFPFGDWISHSVSRKEH-
--THHKGSSDQR-----DMESREREMLRSP-----FLPKITMVGISTGEAA-----QMSK
ANLKKTMEDLTEDLEQSDEGND-HG-----------------------------------
-----------------SKRYDSLKIEER----------DPLFVANVGDY-YSGL-AKAG
SARLSRRGDDQ------------------
>Arabidopsis_lyrata_gnl|BL_ORD_ID|26695 _496448|PACid:16060442
------------------------------------------------------------
--------------M---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------G-SPD-----KQHRRHV----------AAEFLHS--AVT----SIIPL
F-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------PPKTA--P------
---------SRVCLPLRF---------SVSD---------------------------DV
SS-------P----FESTVK--SSSSTSSSGLNSTVRISSLSSDGK--R-GGPA------
-------FVGQVFSMCDLTGTGLMAVS-----THFDIP-FISKRTPEWLKKMFSTITKSE
RNGPVFRFFMDLGDAVSYVKKLNIPSGVVGACRLDLAYEHFKEKPHLFQFVPNERQVKAA
NKLLKSMPQNGRKQKVEGVPVFGAQNLDIAVATADGIKWYTPYFFDK--AVLDNILEESV
DQHFH-------TLIQTRHVQRRRDVVDDS----LASEVMEEMGDSMLEPPEVQEAMEEI
GS-SGIPLSVVA-KAAEIQLLYAV------------DRVLLGSRWFRKAT--------GI
QPKLPYLVDSFE-----------------RR-SAFSIQRASGSATRCLGDSVEA------
D-TSASLLRVED--------------NSPSED-EKRQ--QNLWFPFGDWINHSESKKEH-
--THHKGPSDGR-----DMESREREMLRSP-----FLPKITMVGISTGEAA-----QMSK
ANLKKTMEDLTEDLEQSDEGND-HG-----------------------------------
-----------------SKRYDPRKMEER----------DPLFVANVGDY-YSGM-AKAG
SARLSRRGDDQ------------------
>Capsella_rubella_gnl|BL_ORD_ID|25653 _v10028359m|PACid:20911489
------------------------------------------------------------
--------------M---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------G-SPE-----KQHRRHI----------AAEFLHS--AVTSISSSIVPL
F-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------PPKTT--P------
---------SRVWLPLKF---------SVSD---------------------------DV
SS-------P----FESTVN--SKSSKSSSGLNSTVRISSLSSDGK--R-GGPA------
-------FVGQVFSMCDLTGTGLMAVS-----THFDIP-FISKRTPEWLKKMFSTITKSE
RNGPVFRFFMDLGDAVSYVKKLNIPSGVVGACRLDLAYEHFKEKPHLFQFVPNERQVKAA
NKLLKSMPQNGKKQKVDGVPVFGAQNLDIAVATADGIKWYTPYFFDK--AVLDNILDESV
DQHFH-------TLIQTRHVQRRRDVVDDS----LTSEVMEEMGDSMLEPPEVQEAMEEI
GS-SGIPLSVVA-KAAEIQLLYAV------------DRVLLGSRWFRKAT--------GI
QPKLPYLVDSFE-----------------RR-SALSIQRASGSAARCLSDSVET------
D-TSASLLRVEE-------------GDSPRED-EKRR--QNLWFPFGDWLKHSVSRKDQ-
--AHQKGSSGQR-----DMESRDREMLQSP-----FLPKITMVGISTGEAA-----QMSK
ANLKKTMEDLTEDLEQSDEGND-HG-----------------------------------
-----------------SKRYDPLKIEER----------DPLFVANVGDY-YSGL-AKAG
SARLSRRGDDQ------------------
>Thellungiella_halophila_gnl|BL_ORD_ID|20311 _Thhalv10003967m|PACid:20199916
------------------------------------------------------------
--------------M---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------D-LPD-----KQHRRHI----------ATEFLHS--AATSI-SSIIPL
F-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------PPKAT--P------
---------SRVCLPLRF---------SVSD---------------------------DV
-F-------P----FDSTVRNASSASTSSSSLNSTVRISSLSSDGK--R-GGPA------
-------FVGQVFSMCDLTGTGLMAVS-----THFDIP-FISKRTPEWLKKMFSSITKSE
RNGPVFRFFMDLGDAVSYVKKLNIPSGVVGACRLDLAYEHFKEKPHLFQFVPNERQVKAA
NKLLKSMPPNGKKQKVEGVPVFGAQNLDIAVATADGIKWYTPYFFDK--AVLDNILEESV
DQHFH-------TLIQTRHVQRRRDVVDDS----LTSEVMEEMGDSMLEPPEVQEAMEEI
GT-SGIPLSVVA-KAAEIQLLYAV------------DRVLLGSRWFRKAT--------GI
QPKLPYLVDSFE-----------------RR-SAFSIQRASGSTSRCIGDSAEA------
D-TSASLRRVED--------------DSPSED-EKRQ--QNLWFPFGDWLNHSGSRKEH-
--A-QKVTSDQR-----EMECREREMQQSP-----FLPKITMVGISTGEAA-----QMSK
ANLKKTMEDLTEGLEQSDEGSSEHG-----------------------------------
-----------------SKRYDPLKMEER----------DPLFVANVGDY-YSGL-AKAG
SARWSRRGGDSNETHPRS-----------
>Brassica_rapa_gnl|BL_ORD_ID|11888 _010109|PACid:22695398
------------------------------------------------------------
--------------M---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------D-SPD-----KIHRRYN----------AAEILHG--AATSI-SSIIPL
F-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------PPKTT--P------
---------SRVCLPLRF---------S------------------------------DV
-S-------P----FESTVKNASSTSTSSSGLNSTVRISSLSSDGK--R-GGPA------
-------FVGQVFSMCDLTGTGLMAVS-----THFDIP-FISKRTPEWLKKMFSTITKSE
RKGPVFRFFMDLGDAVSYVKKLNIPSGVVGACRLDLAYEHFKEKPHLFQFVPNERQVKAA
NKLLKSMPPSEKKQRVDGVPVFAAQNLDIAVATSDGIKWYTPYFFDK--AVLDNILEESV
DQHFH-------TLIQTRHVQRRRDVVDDS----LTSEIMEEMGDSMLEPPEVQEAMEEI
GT-SGIPLSVVA-KAAEIQLLYAV------------DRVLLGSRWFRKAT--------GI
QPKLPYLVDSFE-----------------RR-SALSIQRASGSTTKCLGDS---------
N-SSASLLKVED--------------GSPSEE-EKRQ--QSLWFPFGDWLK---------
---AQKDSSGQR-----EMESREREMQRSP-----FLPKITMVGISTGEAA-----HMSK
ANLKKTMEDLTQDLEQSDEGSD-HG-----------------------------------
-----------------SNRYDPLKIEER----------DPLFVANVGDY-YSGL-ARAG
SARWSRRGDDRNETPPRSS----------
>Citrus_clementina_gnl|BL_ORD_ID|24296 _0.9_006877m|PACid:19275444
------------------------------------------------------------
--------------M---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------A-SPAEP----NHLQNQ----------ISSFINA--TTSTL-FSLITP
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------TKTT--PSSQSQP
SSA----PASRLCIPLQF---------ADSSC-------PS--------SSTRSPVGSDS
IS---------------SNSGASSSESSSSGFPSTVRISAINSSGK--G-GGPA------
-------FVGQVFSMCDLSGTGLMAVS-----THFDIP-FISKRTPEWLKKLFATITKSE
RNGPVFRFFMDLGDAVTYVKQLNIPSGVVGACRLDLAYEHFKEKPHLFQFVPNEKQVKAA
NKLLRTIPDSGRKKKVDGVPVFSAQNLDIAIATADGIKWYTPYFFDK--NMLDNILEESV
DQHFH-------ALIQTRHMQRRRDVIDDN----LAAEVVEEIGDSIWEPPEVQEMMDEI
GH-PAIPLSVIS-KAAEIQLLYAV------------DRVLLGNRWLRKAT--------GI
QPKFPYMVDSFE-----------------NR-SAASFLRASESTSCLANSET--------
N-NGSSDLKLED---------------KHLDK-RDQR--PDFRFPFGDWFRHLWSKQDC-
--EAQGSSY---------IECTKRNLQLNP-----FLPKVTMVGISTGEAG-----QMTK
ANLKKTMENLTKELEQTDQENAT-------------------------------------
-----------------SSGSNEYIIEDR----------DPLFVANVGGY-YSGL-AKTG
STRWVRGRSNN------------------
>Citrus_sinensis_gnl|BL_ORD_ID|32460 _1.1g009199m|PACid:18125400
------------------------------------------------------------
--------------M---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------A-SPAEP----NHLQNQ----------ISSFINA--TTSTL-FSLITP
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------TKTT--PSSQSQP
SSA----PASRLCIPLQF---------ADSSC-------PS--------SSTRSPVGSDS
IS---------------SNSGASSSESSSSGFPSTVRISAINSSGK--G-GGPA------
-------FVGQVFSMCDLSGTGLMAVS-----THFDIP-FISKRTPEWLKKLFATITKSE
RNGPVFRFFMDLGDAVTYVKQLNIPSGVVGACRLDLAYEHFKEKPHLFQFVPNEKQVKAA
NKLLRTIPDSGRKKKVDGVPVFSAQNLDIAIATADGIKWYTPYFFDK--NMLDNILEESV
DQHFH-------ALIQTRHMQRRRDVIDDN----LAAEVVEEIGDSIWEPPEVQEMMDEI
GH-PAIPLSVIS-KAAEIQLLYAV------------DRVLLGNRWLRKAT--------GI
QPKFPYMVDSFE-----------------NR-SAASFLRASESTSCLANSET--------
N-NGSSDLKLED---------------KHLDK-RDQR--PDFRFPFGDWFRHLWSKQDC-
--EAQGSSY---------IECTKRNLQLNP-----FLPKVTMVGISTGEAG-----QMTK
ANLKKTMENLTKELEQTDQENAT-------------------------------------
-----------------SSGSNEYIIEDR----------DPLFVANVGGY-YSGL-AKTG
STRWVRGRSNN------------------
>Manihot_esculenta_gnl|BL_ORD_ID|29919 _4.1_003879m|PACid:17989925
------------------------------------------------------------
--------------M---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------A-SST-QPAPNRHH--------------SNLFHS--ATTAL-ISLVSS
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------PKAS--PLS-TIP
LCP------PKICIPFQF---------ADSSY-------PLIQ--SI--RSPFDSNQPES
VS-------P----KSAAVKGL-SSAESNSGFPSTVRIAGLKSNGK--S-GGPA------
-------FVGQVFSMCDLSGTGLMAVS-----THFDIP-FISKRTPEWLKKIFATVTKSE
RNGPVFRFFIDLGDAVAYVKRLNIPSGVVGACRLDLAYEHFKEKPHLFQFVPNEKQVKAA
NQLLKKIPQGNGRRKVDGVPVFTAQNLDIAIATADGIKWYTPYFFDK--NMLDNILEESV
DQHFH-------SLIQTRHMQRRRDVVDDN----LAAEVIEEMGDNMLEPPEVQEMLDEM
GH-PGIPLSVIS-KAAEIQLLHAV------------DRVLLGNRWLRKAT--------GI
QPKFPYMVDSFE-----------------KR-SASSFQRASESTSYLANPKT--------
--DSTSNCTFKD---------------NAQAD-HEQK--TDLRIPFGDWFRHPWLKQKW-
--KPEKLPEIRS--HESLSECTKQKLERNS-----FLPKITMVGISTGEAG-----QMSK
ASLKKTMEDLTRELEQTDRENATVGRLECNVRILILLTEAPRNIENVLMLSNILSLARYR
ENFSIVICFWECILSPYSLSSFPLSYPDRQGGTFSSLYEESGFSILTGLYGSSGIFAKET
LHSWI------------------------
>Ricinus_communis_gnl|BL_ORD_ID|23216 _30169.m006582|PACid:16821381
------------------------------------------------------------
--------------M---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------S-LSPDP---NHHHQ------------PSNFFHS--ATTAI-TSLIST
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------------NPKTS--PSS-TIP
LSP------PKICIPFQF---------ADSSYR------PLT-------RSSFESTHPDS
VS-------P----KSAAVKGL-SSAESSSGFPSTVRIAGLNSNGK--G-GGPA------
-------FVGQVFSMCDLSGTGLMAVS-----THFDIP-FISKRTPEWLKKVFTTVTKSE
RKGPVFRFFMDLGDAVTYVKRLNIPSGVVGACRLDLAYEHFKEKPHLFQFVPNEKQVKAA
NQLLKTIPQSDGRRKVDGVPVFSAQNLDIAIATTDGIKWYTPYFFDK--SMLDNILEESV
DQHFH-------ALIQTRHMQRRRDVIDDN----LAAEVIEEMGDSMLEPPEVQEMMDEI
GH-PAIPLNVIS-KAAEIQLLYAV------------DRVILGNRWLRKAT--------GI
QPKFPYMVDSFE-----------------KR-SASSFRRASEPASYLAKSKT--------
D-ADTSKLNLED---------------GAQAN-HEPI--TDLRLQFGDWFKSLGLKQQQ-
--KPEKGSEI--------SECRKQKLEMNP-----FLPKITMVGISTGEAG-----QMSK
ASLKKTMEDLTRELEHTDRENAPGS-----------------------------------
-----------------SNNGNDLEMEDR----------DPLFVANVGDY-YSGM-SKTN
SPRLVRGGSK-------------------
>Populus_trichocarpa_gnl|BL_ORD_ID|3641 _POPTR_0017s00970.1|PACid:18209660
------------------------------------------------------------
--------------M---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------P-SPPEPPQ-HRHNNHH----------LSNFLNS--TTKTL-FSLLSP
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------PNIL--------P
LAP----PQPKICISFHL---------PNAPL-------PLTQST----LSLFESTQPDS
LS--------PSKSSSASVKDI-SSAESNSGFPSAVRIGRLNPNGN--G-GGPA------
-------FVGQVFSMCDLSGTGLMAVS-----THFDVP-FISKRTPEWLKKIFATVTKSE
RNGPVFRFFMDLGDAVAYVKRLNIPSGVVGACRLDLAYEHFKEKPHLFQFVPNEKQVKAA
NQLLKSIPHGDGSRRVDGVPVFSAQNLDIAIATTDGIKWYTPYFFDK--NMLDNILEESV
DQHFH-------ALIQTRHMQRRRDVIDDN----VAAEVIEEMGDSLLEPPEVQEVLDEM
GH-PAIPLSVIS-KAAEIQLLYAV------------DKVLLGNRWLRKAT--------GI
QPKFPYLVDSFE-----------------RR-SASSLRRALESTSCLANSKI--------
D-DSTSEHKLKD---------------NVQTD-HEQR--KDLRLPFGDWFSHPWLKKHS-
--KSERESDTRK--EGLSKDCLKWKSESNP-----FLPKVTMVGVSTGDAG-----QLSK
SSLKKTMEDLTKELEQTDEANDSFI-----------------------------------
-----------------SNSSSEFKVNDR----------DPLFVANVGDY-YSGM-AKTG
ISR--------------------------
>Malus_domestica_gnl|BL_ORD_ID|44230 _0000777828|PACid:22664215
------------------------------------------------------------
--------------M---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------A-SPSEPPHTRQQLRPS----------ITHLVHS--TTSNL-LSLLAS
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------PKTT--PSP-SLS
TTP------PEIRVALFL---------PNLPK-------PL-------------AFQPDS
--------------KLSAMKGVASSPESTSGFPSTVRIAGLNSNIK--GSGGPA------
-------FVGQVFSMCDLSGTGLMAVS-----THFDIP-FISKRTPEWLKKMFKSITNSE
RNGPVFRFFMDLGDAVTYVKRLNIPSGVVGACRLDLAYEHFKEKPHLFQFVPNEKQVKAA
NKLLKTMPQSGRCKRVDGVPVFSAQNLDIAIASSDGIKWYTPYFFDK--NMLDNILEESV
DQHFH-------SLIQTRHTQRRHDVIDDN----IPAEVIEEMGDNLWEPPEVQEVMDEI
GN-SGIPLSVIS-KAAEMQLLYAV------------DKVLLGNRWLRKAT--------GI
QPKFPYMVDSFE-----------------RR-SAASFLRASQSARCLTNGEAVNDNEDSL
D-CSTSKIKSKD---------------DIHTN-KGNK--TDLRFPFSDWFSHLWSKQKD-
--QNEELS----------KERIEQSTLQNP-----NLPKITMVGISTGAAG-----PMSK
ANLKKTMEDLTKELEQTDSGNAFG------------------------------------
-----------------SDTGNELRFEDR----------DPLFVANVGDY-YSGM-AKTG
SAKWVRGGNN-------------------
>Prunus_persica_gnl|BL_ORD_ID|26753 _ppa003928m|PACid:17667413
------------------------------------------------------------
--------------M---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------A-SPTEPAH-KKQARP-----------ITHLVHS--TAANL-LSLFAS
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------PKTT--PS-----
-TP------STIRVAFLF---------PNSPK-------PL----------AFHSAQPDF
KS---------------AMKGVESSSESNSGFPSTVRIAGLNSNIK--G-GGPA------
-------FVGQVFSMCDLSGTGLMAVS-----THFDIP-FISKRTPEWLKKMFASVTNSE
RNGPVFRFFMDLGDAVTYVKRLNIPSGVVGACRLDLAYEHFKEKPHLFQFVPNEKQVKAA
NKLLKAMQQNGRCKRVDGVPVFSAQNLDIAIASSDGIKWYTPYFFDK--NMLDNILEESV
DQHFH-------SLIQTRHMQRRRDVIDDS----LPAEVIEEMGDNLWEPPEVQEVMDEM
GN-PGIPLSVIS-KAAEMQLLYAV------------DKVLLGNRWLRKAT--------GI
QPKFPYMVDSFE-----------------RR-SAASFLRASQSSNRLANREAVNDNKDSV
H-CSTSEVKLND---------------DIQTN-KGNK--LDLRFPFGDWFSHLLLKQKD-
--QTEELS----------KECVELSSQQNP-----NLPKITMVGISTGEAG-----QMSK
ATLKKTMEDLTKELEQPDAGNAGG------------------------------------
-----------------SDMSNELRFEDR----------DPLFVANVGDY-YSGM-ARTG
SARWVRGGNN-------------------
>Carica_papaya_gnl|BL_ORD_ID|1469 _evm.model.supercontig_107.127|PACid:16405310
------------------------------------------------------------
--------------M---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------A-SATDQPQHNFHHR------------IANLLHA--TSSSL-SFLLPS
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------PKTA--P----YP
PSP------PKLCVPFKF---------ADSPVL------PL--------TSVFESPQSDS
VS------------SKSTIKGV-SSAESNSGFSSAVRIGGLNSNGK--A-SGPA------
-------FVGQVFSMCDLTGTGLMAVS-----THFDIP-FISKRTPQWLKKIFATITKSE
RNGPVFRFFMDLGDAVAYVKQLNIPSGVVGACRLDLAYEHFKEKPHMFQFVPNERQIKAA
NKLLKKIPQNDGRTKVDGVPVFGAQNLDIAIATVDGIKWYTPYFFDK--NMLDNILEESV
DQHFH-------SLIQTRRIQRRRDVVDDS----FAAEVIEEMGDNSWEPPEVQEVLNEI
GH-PGIPLSVIS-KAAEIQLLYAV------------DKLLLGNRWLRKAT--------GI
QPKFPYLVDSFE-----------------RR-STASFLKASKPTNCLTDFEA--------
G-LDTSGVELDD---------------KFQGN-HRET--KDFQLPIGDWLNHSWLKQGQ-
--KHQMLADTGY------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------
>Vitis_vinifera_gnl|BL_ORD_ID|19207 _GSVIVT01028824001|PACid:17835832
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------MCDVSGNGIMAVS-----NHFDIP-FISKRMPQRIKKMFATITKSD
KNGPVFRFFMDLGDAVRYVKKLNIPSGGVGACRLDLAYGHFMEKPHLFRFVPNEKQVKAA
NKLLKKIPQNGGRKRIDGVPVFTAQNLDIAIATTDGIKWYTPYFFDK--HTLDSILEQSI
DHHFH-------HLIQSRHVQRRRDVIDDN----LAAEVLEDNAESLWEPPEVQEVLDEV
GH-PGIPLSVIS-KAAEMQLLYAV------------DRVLLGNRWLRKAT--------GI
QPKFPYMVDSFE-----------------KR-SAASFRRASPSKRFVASPEMGNDNKDTE
E-LGPSDPKLED---------------NTQRD-QGQN--SASWFPVWDLFNHPWSNKRQ-
--EPQNRSNARI--EDASREHIKQELQLAP-----FLPKITMVGISAGESG------MSK
VNLKKTMEDLTKELEQADQENAV-------------------------------------
-----------------GCINSEFEVENR----------DPLFVANVGSY-GSGL-VARS
PVPSVRGENN-------------------
>Eucalyptus_grandis_gnl|BL_ORD_ID|2953 _A02719.1|PACid:23564674
------------------------------------------------------------
--------------M---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------A-VSPEPPRKHRHHPNP----------LSHLLNS-----TL-LPLIPN
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------HKAA--PPSLVSP
PPP------PKLLLPVRL---------PP----------ALSIASPS--DSAPPPPHPTP
LK-------P----APEVKAPAEPGAAAAGAFPSTVRISAIKSNGK--G-RGPA------
-------FVGQVFSMCDLSGTGLMAVS-----THFDVP-FLSKRTPEWLKKVFASITKSE
RNGPVFRFFMDLGDAVTYVKRLNIPSGVVGACRLDLAYEHFKEKPHLFQFVPNEKQVKAA
NKLLKTISQGNGNRQIDGVPVFSAQNLDIAIATSDGIKWYTPYFFDK--NMLDNILEESV
EQHFH-------SLIQTRHMQRRRDVIDDN----L-TEVADDVGDSLWEPPEVQEVLEEM
GH-PGIPLSVIS-KAAEMQLLYAV------------DRVILGNRWLRKAT--------GI
QPKFPYIVDSFE-----------------RR-TAASLVRASDLTHYLGDRGMKT--DESS
Q-ESTDKLALEE---------------NHHVD-LGQK--ADFRFPFGDWLRHPWSKEQQ-
--KLQKEVGARHRLESLTGEPVKQKLQPNP-----FLPKITMVGISMGEAG-----QANK
ATLKKTMEDLTRELEQTDHGNAA-------------------------------------
-----------------GNIAD--VSEDR----------DPLFVANVGDY-YSGL-AKTG
SARLIRRSEAKKQQ---------------
>Glycine_max_gnl|BL_ORD_ID|45053 _16g29580.1|PACid:16303315
------------------------------------------------------------
--------------M---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------A-LPSEPHRRRRHNHNH----------ISTFLQS--TASNF-ASLFNP
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------PN----PPSLTLP
HPP------TSVSLPLFF---------AP----------PLS------------------
--------------GSSTVDSA--TSKPAHPPAKSVRIARLGANGK-GG-GGPV------
-------FLGEVFSLCDLSGTGLIAAS-----KHFGIP-FISERTPEWLKKIFAPITKSE
RNGPVFRFFIDLEDAVSYVEKLNIPSCVVGAFRLDLAYKQFKEKPHLFQFVPNEKQVKAA
NKLLKTISEHGDKKKVDGVPVFGAQNLDIAIATTDGIKWYTPYFFDK--NMLDNILEDAV
DQHFH-------NLIQTRHMQRRRDVVDDN----LAAEVIEEMSDRLGEPPEVQELLDEM
GH-PSIPLSVIS-KAAGLQFQYTV------------DKVLLGNRWLRKAT--------GI
QPKFPYMVDSFE-----------------RR-SEASLLRATESSSCLENSKVEDDRQISE
C-LDSSNCSLDG---------------NTEAI-KQPS--PSLSLPFGNWFHHLWPKQCR-
--EKASSSR---------KGVNKEEMKPRP-----ILPKVTMVGLSTEEAG-----QTSK
ANLKKTMDDLTRELEKTELDIMT-------------------------------------
-----------------DGGSKECKVEDR----------DPLFVANGGNY-YSSMRRKPG
SGR--------------------------
>Phaseolus_vulgaris_gnl|BL_ORD_ID|6869 _091010222m|PACid:23537334
------------------------------------------------------------
--------------M---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------A-LPSEPHRRRRHHNNH----------IATFLQS--TASNF-ASLFNP
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------PN----PPSLTLP
HPP------SSLSLPLFF---------AP----------PLS------------------
--------------ASNALDSAATASEPARPAAKSVRVARLGVNGKGGG-GGPA------
-------FVGQVFSMCDLSGTGLMAVS-----THFDIP-FISKRSPEWLKKIFAAITKSE
RNGPVFRFFIDLGDAVSYVKKLNIPSGVVGACRLDLAYEHFKEKPHLFQFVPNEKQVKAA
NKLLKAISQHGIRKKVDGVPVFSAENLDIAIATTDGIKWYTPYFFDK--NMLDNILEEAV
DQHFH-------TLIQTRHMQRRRDVVDDN----LAAEVIEEMGDNLGEPPEVQELLDEM
GH-PSIPLSVIS-KAAELQFHYTV------------DKVFLGNRWLRKAT--------GI
QPKFPYLVDSFE-----------------RR-SEASYLRATESRRCLENPKVEDDGKISE
C-VDSSDCGLDD---------------NTEAI-RQPS--YRLSLPFGNWFNHLWPKQCH-
--EKARSFK---------KGVNKEDMKPTP-----FLPKVTMVGLSTEEAG-----QMSK
ANLKKTMEDLTRELEKTELDNMA-------------------------------------
-----------------GGGGKECTMEDR----------DPLFVANVGDY-YSSL-GKAG
SGRWIRGGSN-------------------
>Cucumis_sativus_gnl|BL_ORD_ID|17033 _192940.1|PACid:16968025
------------------------------------------------------------
--------------M---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------A-FQIEPSS-EPHEQNPLTF-------ITHLFHS--STSNF-STLFAN
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------PQSI--PPF-PFQ
SSS------SKLCIPVAF---------PPSPK-------PPFLS-----HSGFHSIHYDL
DS-----------PKSAAVKGLSSSPNFDSGFPSTLRISGLNSDGK--T-GGPA------
-------FVGQVFSMCDLSGAGLMAVT-----SNMNIP-FVSKRTEEWLKKMFSTITKSK
RNAPIFRFFTDLGDAVTYVKRLNIPSAVVGVCRLDLAYEHFKEKPHLFQFIPNEKQVKAA
NKLLKGLPQNGGSKKIDGVPVFSAQNLDIAIATTNGIKWYTPYFFDK--NMLDNILEESV
DQHFH-------ALIQTRRLQRRREIVDDN----AAAEVLEEMGDSLLEPPEVQEVMDEM
GN-PGIPLSVIS-KVAEMQLLYTV------------DKVILGNRWLRKAV--------GI
QPKFPYMVDSFE-----------------RR-SAASLLRIQESASGLTNSESVEETKELQ
C-YSSSPLNTED---------------NREAN-QEPK--QHSFNPFRNWFGHLWSKQRQ-
--R-----------DDFSQERTKQNVQISP-----FLPKITMVGISTGDSG-----HTSK
ANLKKTMEDLTRELEHIDQGNAA-------------------------------------
-----------------SHNEYEFNNEER----------DPLFVANVSHF-SSGL-SKAG
SARWVRGND--------------------
>Linum_usitatissimum_gnl|BL_ORD_ID|5439 _10027537|PACid:23144619
------------------------------------------------------------
--------------M---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------A-TSAEPPQNHHRRHHP----------FPNFFHS--ATSAV-LSLLPN
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------PRTSSAPPI-TSP
SSS----PPPHVCIPFNF---------VDSSY-------PLNQQSVI--RSPLESGQSDS
VS-----------STSATVKGL-SSAESNSGFPSTVRISGLNSDGK--G-GGPA------
-------FVGQVFSMCDLSGTGLMAVS-----TYIELP-FINERTPEWLKKILAPVTKKD
KNGPMFRFFMDLGDAVSYVKKLNIPSGVVGACRLDLAYEHFKEKPNLFQFVPNKEQVKAA
KQLLKTMPESDGKTTVDGVPIFSAHNLDIAIATSDGIKWYTPYFFNK--SMLDGIIEDSV
DQHFH-------TLIQTRHMQRRRDVVDDN----FAADVMEEMADSLMDPPEVDEMMDEM
GN-VGIPLSVIS-KAAEMELLYAV------------DKVLLGNRWLRKAT--------GI
QPRFPYVVDSFE-----------------RR-SAYSFKKASKTTSLSHVSQA--------
G-GSDSEVEPEN---------------NTQANSYEER--PDLRLTFGDWFG-LRLKQPF-
--KPARETESRT--EGSSKEQMQQKLVDNP-----LLPKITMVGISTGETG-----KVSK
ASLKKTMESLRKELEQADQGKTSSS-----------------------------------
-----------------DNGDGDFKIADR----------DPLFVANVGDY----------
-SRWIRRGMS-------------------
>Mimulus_guttatus_gnl|BL_ORD_ID|16966 _mgv1a003806m|PACid:17686364
------------------------------------------------------------
--------------M---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------A-SAADKSHRRHHPPPH----------LSRFIST--ASTNL-SSFLTL
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------KSPS--PAS----
-------SSSKIHLPLLL---------ADSDSFLSL-------------VSRSESAQPDS
TPSAPSRSPPSSSSSSSSMKST-PSSDSVSKFPPTVRI----TTGK--G-GGPA------
-------FVGQVFSMCDLSGTGLMAVS-----THFDIP-FLSKRTPEWLRKMYAAVTKSE
RNGPVFRFFMDLGDAVSYVKQLNIPSGVVGACRLDIAYEHFKEKPDTFQFVPNERQVKEA
NKLLKSFPHSDGKNKVEGVPVFSAQNLDIAIAKKDGIKWYTPYFFDK--SMLDNILEDSV
DQQFH-------SLIETRNAHRRRDIGDDS----LPAEAIEEMGESMWDPPEVQEVLDEI
GH-PGIPLSVIS-KAAEIQLLYAV------------DRVILGNRWLRKAT--------GI
QPKFPYMVDSFE-----------------RK-TAASFLRAKTSN-LISNSEISE-DAQLD
N-RTTLDVEPKE---------------KTHDK-QEQKHLINSQFPFGDWLSHPWLKQPE-
--NQQNLSETRH--PNSTTQNRGQVAQSSP-----FLPKITMVGVSTGEPG-----KMGK
AALKKIMDDLTKELEKVEQVNQA-------------------------------------
-----------------NSNSSEYMADER----------DPLFVANVGDS-YSAV-SKTG
TSWRVRGGSF-------------------
>Aquilegia_coerulea_gnl|BL_ORD_ID|35613 _013_00192.1|PACid:22058731
------------------------------------------------------------
--------------M---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------AISPSESHLNYNNNNNN----------FTRFIQS--TSSSF-FSLFN-
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------PSPL--PPL-SSS
SSSFPFCSSSSICVPLLF---------SDTPPRILSLSTTLSTNSSS--SSTTPSSQNDP
LS----------------LNSQIKTRSPSSKFPSSIKISGLNSNPN--G-SGPA------
-------FVGQVFSMCDVSGTGLMTVS-----THMEIP-FISKRIPEWIKSMFSVFNKSE
NNGPVFRFFMDIGDAVSYVKRLNIPTGVVGACRLDLAYEHFKEKPHMFQFVPNEKQVKAA
NKILKKT-QHSEKRIVDGVPVFTAQNLDIAIATGDGIKWYTPYFFDK--NMLDNILEESV
DQHFH-------SLIQSRHMHRRRDVIDDN----LTAEVVEDNRDNLWEPPEVQEVLDEM
GY-PGLPMSVIS-KAAEVQLLDAV------------DKVLLGNRWLRKAT--------GI
QPKFPYRVDSFE-----------------KR-SAASFRKATELTSIASNRIDSCVGSKCE
NLKGSEEPRLEE---------------NTQSG-QRQP--SEVRLPFGDWFSHLWSKQQH-
--KPDEQTR-----LTDSRDKYIEQLPLSP-----LLPKITMVGISTGEAG-----QTSK
ASLKQTMEDLTRELEQPGQDID--------------------------------------
-----------------DGGSNEIRHEER----------DPLFVANVGV-----------
-----------------------------
>Brachypodium_distachyon_gnl|BL_ORD_ID|2714 _2g07450.1|PACid:21805484
------------------------------------------------------------
--------------M---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------P--------SSSSSSNP--------------FHS--LTFN--LPFPPA
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------PSSC--STSASSP
PAP-----APHLAFPLLL---------------------PVSSASTT--SSYSPASHLIP
QP------------QRLPGERMAGPAAASGGK-------GVSAGKS--P-GGPA------
-------FVGQVFTMLDPSGNGLMAVT-----SRFDLPHFIAHRTPTWFKRILSPLKKSE
-SSPVFRFFMDLNDSVSYVKRLNVPSGMVGACRLDVAYEHFKEKPHMFQFVPNEKQVKAA
NKLLKSIPQKSRRKKLAGVPVFSAQNLNIAVATDDGIRWYSPYFFDK--NLLDNILEASM
DQHFH-------SIIQNRHIRRRRDIVDDS----LTSEILEESADSLLEPPEVQELMNEI
GP-AGIPLSVVT-KAAEIQLLDVV------------DKLLLGNKWLRKAT--------GI
QPRFPYVVDSFE-----------------ER-TALSVDRTATSSNSCTASKDADFFTNDQ
Q-SQALEPNVDS---------------GNHRK-HNSRDHGQSHFPFSNLLPNIWPGHDR-
--KFKAQEHDNR--FKRYGASMDNDLQANP-----LLPKITMVGISMSEGG-----QMSK
ANLKKTMEELTKELEQAGEKTV--------------------------------------
------------------------FSDEK----------DPLFVANVGDY--SRI-TKIS
ST---------------------------
>Sorghum_bicolor_gnl|BL_ORD_ID|9318 _Sb03g001210.1|PACid:1960134
------------------------------------------------------------
--------------M---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------P--------RSSSSSNP--------------FHS--LASA--FPFFSS
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------SSPSPPASASPSP
SPA-----APHLAVPLLL---------------------PVSSGSASASSESRRGP----
--------------QPLPGARMAGAAAAGRG----------NKAGG--G-AGPA------
-------FVGQVFTMLDPSGNGLMAVT-----TRFELPRFLTNRTPMWFKRMLSPLKKSE
-SSPVFRFFMDLNDAVSYVKRLNVPSGMVGACRLDVAYEHFKEKPHLFQFVPNEKQVQAA
NKLLKSLPQRSRRKKLGGVPVFSAQNLNIAVATNDGIRWYTPYFFDK--NLLDNILEASM
DQHFH-------SIMQNRHTQRRRDIVDDS----LTSEIIEESAESLLEPPEVQELMNEI
GP-AGIPLNVVT-KAAEIQFLDVV------------DKVLLGNKWLRKAS--------GI
QPKFPYVVDSFE-----------------ER-TAVSIANIATTS-SLTTSNDENCCQNNQ
Q-TQSSGSSVDN---------------SSYRN-HNNEDHN--HFPFSNLLPNIWPGHDR-
--KFKAQESDNK--FSRYDADVKSNLQSNP-----LLPKITMVGISMGDGA-----QMSK
ANLKKTMEDLTKELEQTSEENM--------------------------------------
------------------------FSDDK----------DPLFVANVGDY--SRI-TKIS
SA---------------------------
>Zea_mays_gnl|BL_ORD_ID|9045 _GRMZM2G097959_T01|PACid:20828771
------------------------------------------------------------
--------------M---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------P--------CSSSSSNP--------------FHS--LASA--FPFLSS
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------TSPP--PSPPASP
APA-----APHLAVPLLL---------------------PVSSA-----SESRRGA----
--------------QPLPGTRMVGAGATGGG----------NMASG--G-GGPA------
-------FVGQVFTMLDPSGNGLMAVT-----TRFELPRFLTNRTPMWFKRMLSPSKKTE
-NSPVFRFFMDLNDAVSYVKRLNVPSGMVGACRLDVAYEHFKEKPHMFQFVPNEKQVQAA
NKLLKSLPQRGRRKKLDGVPVFSAQNLNIAVATNDGIRWYTPYFFDK--NLLDNILEASM
DQHFH-------SIMQNRHTRRRRDIVDDS----LTSEIIEESAESLLEPPEVQELMNEI
GP-AGIPLNVVT-KAAEIQFLDVV------------DKVLLGNKWLRKAS--------GI
QPKFPYVVDSFE-----------------ER-TAVSIANIATTS-SLTASNDDSSCQNNQ
E-TQSSEPSGDN---------------SSYRN-HNNEDHN--HFPFSNLLPNIWPGHDR-
--KFKSQESDNK--FSRYDADVKSKLQANP-----LLPKITMVGISMGDGA-----QMSK
ANLKKTMEDLTKELEQTSEENM--------------------------------------
------------------------FGDEK----------DPLFVANVGDY--SRI-TKIS
SA---------------------------
>Setaria_italica_gnl|BL_ORD_ID|1638 _Si001606m|PACid:19674983
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------MLDPSGNGLMAVT-----TRFELPRFLTNRTPTWFKKILSPLKKSE
-NGPVFRFFMDLNDAVSYVKRLNVPSGMVGACRLDVAYEHFKEKPHMFQFVPNEKQVKAA
NKLLKSLPQRGRRKRLGGVPVFSAQNLNIAVATNDGIRWYTPYFFDK--NLLDNILEASM
DQHFH-------SIMQNRHKQRRRDIVDDS----LTSEIIEESADSLLEPPEVQELMNEI
GP-AGIPLNVVT-KAAEIQLLDVV------------DKVLLGNKWLRKAA--------GI
QPRFPYVVDSFE-----------------ER-TAVSIANIATTS-SFTASND-SCCQNDQ
Q-SQSSDPSIEN----------------SYRS-HSNQDHNQFHFPFSNLLPNIWPGHDR-
--KFKEQESDSK--FSRYDADMKTDLQSNP-----LLPKITMVGISMSEGG-----QMSK
ANLKKTMEDLTKELEQTSEKNT--------------------------------------
------------------------FGDEK----------DPLFVANVGDY--SRI-TKIS
ST---------------------------
>Oryza_sativa_gnl|BL_ORD_ID|20689 _LOC_Os01g12550.1|PACid:21903161
------------------------------------------------------------
--------------M---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------PRGRSTTTTTSSSASNP--------------FHA--FAST--LPFLPS
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------PSPS-PTSASPSP
SPP-----APHLAVPLIL---------------------PITSSSSA--SAAAASP----
--------------ESNRGARMA--AAASGGKA-----GGGGGLGK--G-GGPA------
-------FVGQVFTMLDPSGNGLMAVT-----TRFELPQFLASRTPMWFKRILSPLKKSE
-NGPVFRFFMDLNDAVSYVKRLNVPSGMVGACRLDVAYEHFKEKPQMFQFVPSEKQVKAA
NKLLKSLPQRRRRKKLDGVPVFSAQNLNIAVATNDGIRWYTPYFFDK--NLLDNILEASM
DQHFH-------SMVQNRHTRRRRDIVDDS----LTSEMMEESADSFLEPPEVQELMNEI
GP-VGIPLNVVT-KAAEIQFLDVV------------DKMLLGNKWLRKAT--------GI
QPQFPYVVDSFE-----------------ER-TAAAIDRAATASSSFTASKDADCFQISK
Q-PETLESDVDN---------------SNRGK-HENSNNGQSHFPFSNLLPNIWPGHDR-
--SFKAQGRDRA--FRRCDASINNDLQANP-----LLPKITMVGISMGEGG-----QMSK
ANLKKTMEDLTKELEQAGEKTI--------------------------------------
------------------------FSDEK----------DPLFVANVGDY--SRI-TKIS
ST---------------------------
>Panucum_virgatum_gnl|BL_ORD_ID|40717 _Pavirv00055971m|PACid:23796854
------------------------------------------------------------
--------------M---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------P--------RSSSSSNP--------------FPS--LASST-FPFLSS
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------SSSA-ATSSTTSP
AHP-----APHLAFPLLL---------------------PVSSASSS--AEPRRGP----
--------------EPLPGARMAGAGAAAGGKP------GGRIKGG--G-GGPA------
-------FVGQVFPMLDPSGNGLMAVT-----TRFELPRFLTNRTPAWFKKILSPLKKSE
-NGPVFRFFMDLNDAVSYVKRLNVPSGMVGACRLDVAYEHFKEKPHMFQFVPNEKQVKAA
NKLLKSFPQRGRRKRLRGVPVFSAQNLNIAVATNDGIRWYTPYFFDK--NLLDNILEASM
DQHFH-------SIMQNRHVQRRRDIVDDS----LTSEIIEESADSLLEPPEVQELMNEI
GP-AGIPLNVVT-KAAEIQLLDVV------------DKVLLGNKWLRKAA----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------
>Physcomitrella_patens_gnl|BL_ORD_ID|36425 _Pp1s68_153V6.1|PACid:18072962
------------------------------------------------------------
--------------M---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---GRNRDTCNVPGCSKDEKPCLVTGPKIVSFKLPNPALFSSWVQT--VTSNLAWTVQSF
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------QTLKTDGLNCLSLLVEHKPMVSP------
-LPVPYLALNNLIFPVP-------------------------------------------
--------------SSTSSVQVCQKAVSSIPQDHFSKGNAVNEKGEVSS-TGPA------
-------FIGQVYTMCDASRQGLIAVRPSDVLKKIKVP-PYMKLMEKAYERAMNVLFTDD
MKGPVFRFYFNKDDAAEYVRRLNITGSAVGPCSLDAAYKYYKSKEGMFKFIADQRQVKVA
KELVRRERGDKAANKLKGVPVFTARNLTIALSTPQGVRWFRPYFFNK--KQLDSLIGHSV
DHYYE-------MLISARRAQRYSQIAENNGDAFAGGESMDDELDGLMDPPEVQELMEEL
GQ-GGGGMEFVGLKVLEAQFMDLA------------DRVLLGHQWSRRMI--------HL
QPRFPVIVDSFE-----------------RLISASELDHSSESEGSVTSSRNSFAKKEGT
Q-EKSQRGQGDEGMSISGRDERSASNDSSESVSKEYS--QSSPNSLFNLFKKKWGANANL
VFKRKDSGNAEILEEDSDSEYLQETAQKDPPGKIPFQPKLTMMGISMNVNKVEGGLQQAM
AAAAKDVEDRLRKGEGSGPDH---------------------------------------
---------------------------------------GPLFIANLGSG-IPQWGRPVS
ASSGVLDDDAE------------------
>Selaginella_moellendorffii_gnl|BL_ORD_ID|1621 _424522|PACid:15402899
------------------------------------------------------------
--------------M---------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------EIGSVPLHLAYKFFKERPSLFSFIPSKKQVDLA
KTIIKKEQGGKAAQQFQGVPVFTSHCLSILVVGPSGARWFRPHFFKK--EELDGVIRSSM
EHHYQ-------SLIRNRRARRHNQVSD------FPSDMAEDDLE-MLESQDIQDFVEDM
DEWSSVLESIMA-KAAQMYFQDTL------------DRAIFGNKWCRMLA--------GI
QPSFPILVDSFE-----------------RR-VTSETENAVVSH----------------
---------------------------------HEQK------KPHKDWDSTC-------
--------------------------------------------------------QLKR
ALIR--------------------------------------------------------
------------------------------------------------------------
-----------------------------
>Kazachstania_africana_gi|410077799|ref|XP_003956481.1| hypothetical protein KAFR_0C03540 [Kazachstania africana CBS 2517]
------------------------------------------------------------
--------------MSDSDEDLGFQLKGLKISKCLEEDPQVADAMVVNIPI--SAMANEM
SEVDRT-----------------------------------------------------S
PDENSITGQISQEAVLFEVRSSDIASRHDD---------------MSRQENINVAGTNTQ
TSNNAKLSEDSSSDDDDWDTVPAIASYDVYNDKGELELQPYQ-------SSDNIQRNDTT
TNKQNPNITFGYTKVAGEEQAQRSYKTNKKTAFLFEHKKVMKSLQS---TDSLNETTLPT
P------------------PPEDTVDYDEFEDDVEPLDNLTPDTQLNITKLLLNDMEKFA
YLGAANVLINQMCTDLATLCLCVDITSNKKLANRLHFTQKDTANWKTIILNRLYEHLDVT
EEEINMIENLSLHKIQLNDLCKCLRVSQLMENPWEDHAGSEASK----------------
-------------SEEQVPHNSSVSD----TSENESKSMYSD----KDKKVLHPEN-VKD
QHQLHVDVAWTIICDLFLLLLQGSSFDARSRTLLIRFAEALNITHLE--INEFEKRVTDS
LDMEQSVDDQVWDEQDHMKKRRKRRKRKKMAYVGIAMVGGSLVLGLSGGLLAPVIGAGLA
AGLSTIGITGATGFLTGAGGTAIVAVSSTAIGANIGAK-GMSRRMGSVRTFEFIPLHNNR
R---VNLILTISGWIIGNDDDVRLPFSTVDPVEGDL-YSLFWE-PEMLKSTGQTINILAS
EIFTQTLQQ-----------VLGA---TILTALMSSIQW--PMALSKLGYILDNPWSVSL
DRAWAAGLILADTLMTRNLGQRPVTLVGFS----LGARVIYSCLIELCK-KKALGLVENV
FI-FGTPV--VR-KKEELVMARSVVSGRFVNGYSDKDWVL---AYLFRATSGGFSAVMGI
SP-----VDDVEGIDNFNCTELVDGHMAYRK-NMPKLLKEVNITVLAEEFAEIEETIDPE
E-IRKQRKLVKD-------------LDAAHKKLSGKKKH-HGWMP--QWMKPKKSKWQS-
--MVEKTVEEKEIEEIPTEELTSSSTS------------KTKDNGIFDHSALMQELANLK
ASLHEKENEKDDSDK---------------------------------------------
---------------------GNKNGESTTTSDHDYKASP--SGNNF---------QLLS
AGRTILPDDDEMY--RKKNMEFAFPDDV-
>gi|366991929|ref|XP_003675730.1| hypothetical protein NCAS_0C03750 [Naumovozyma castellii CBS 4309]
MIYECKTAFDTEDSVDDRDKTTEKEGILAFLIQILYLQIKIAKRLLLFETFLFYLCTFSK
QSNRNKVIEQIITSMSDSEDDLGIPLKGLRISKYLKEEKTKNSLPKDSLPKDDSPEDNDL
SSTPQFHSPGVSPSEPTIAPQVSSTAPESIISDSENPLT--------------------T
TNTASIDALETKDHSGVHQETDAIAAE---------QQVGIRKDEKDV------------
------LDSDSDSDSTEWQTMPTIASYNVYNQKGELELKPYS-STSLNSSQDQLTLTNS-
NIKKKKDHTFDYTKVAEETQAQRSYLSNKKTDFLFDHKKLKKLNNS--TDSHLSNTSSPD
IPDI---------------IDEEDENYDEFEDDIEPTDDLNPDSQLSITKNLLTDQEKFA
YLGAVNVIANQMCTDLATLCLCIDIKAHKKLAHRLQFTQKDMAAWKTVVLSRVYDHLGVS
EEEIDMIERLSLHKIKVEDLCKCLKTTQNIDNPFEDTSSENKSGVDNEKDKKEDQEPDKK
LEEMEQDKTVNELESIGDSTLASTSEGVEVKDQFKEPSVNDDDTMLAPTKIIDPNA-IKD
KSKLSVDIAWTIICDLFLILLQGSNYDSRSRTLLIKFAEALNVTKME--ICEFEKRVTDS
LDMEQSTDDQVWNETDHMKARRKKKRRRKMYYVGLAMVGGSLVLGLSGGLLAPVIGAGIA
AGLSTVGLTGATGFLTGVGGTTVVALSSTAIGANIGAR-GMSKRMGSVRTFEFRPLHNNR
R---VNLIISVSGWIIGNEDDVRLPFSTVDPVEGDL-YSLYWE-PEMLKSTGQTINIVAS
EVFTQTIQQ-----------VLGA---TILTAFMSAIQW--PMALSKLGYILDNPWNVSL
DRAWAAGLILADTLMTRNLGERPVTLVGFS----LGARVIYSCLIELCK-KKALGLIENV
FI-FGTPV--VR-KKEHLVMARSVVSGRFVNGYSDKDWVL---AYLFRATAGGFSAVMGI
SP-----IEGIEGIENFNCTELVDGHMAYRQ-NMPKLLKEMGIAVLGDTFVEIEELMDPE
E-FQRQRKLVHD-------------VDAAQKKLSERKKHSSGWVP--KWLKPKKSKWQV-
--MVEEAVEETKESDILTE-----SETPKP---------KKKDGALVDHGALMHELELLK
AAMHENALKENTEPETAAQHDEADT-----------------------------------
---------------------HTVKVEEEPTRQGTP--STPKPQNNF---------QLLG
AGRTILPEDDELY-SKKKKMEFAFPDDIN
>gi|410730299|ref|XP_003671329.2| hypothetical protein NDAI_0G03090 [Naumovozyma dairenensis CBS 421]
------------------------------------------------------------
--------------MSDSEEDLGIELKGLKISKYLKKDTETNRSQQSN---EEKHNDEGL
GSTP-LQETLIEEHSDTNEAEDHSNSESSSLSDNNGNLTIDSLPMSYRNMNLEEGQKDVI
ENSSLNQSLSPSFQPIRSSETPSISSR---------NEPHQQKQEQDISPNDAIPKAKND
HEDTHSLSSDDTDDDSEWQTMPAVASYNVYNKNGELELKPYD-SNEETFDIEQIQKTGKY
N--NKNKQTFDYTKVAEETQAQRSYLSNKKTDFLFEHKKLKKALQSKNKSTESQLTNYSS
SNSKLNSEITLNNPEEIEEEEEEDSEFDEFEDDVEAQDDLNPTSQLSVTKDLLSDMEKFA
YLGAVNVLVNQMCTDLATVCLCVDIKSHKKLASRLHFTQKDMAAWKTVILSRLYEHLAVS
QKEIEMIEKLSLHKIQLEDLCKCLKTTQNVENPWEKDN-KKKSSLDNSQEKGE-KNKSSL
DNSQETDANSE--KMRHSNEEEGTIE-----TKTETKESTSM----VPQKVIKPEN-IND
QNRLNIDIAWTIICDLFLVFLQNYTYDARSRTLLIKFAKALNITKLE--ICEFEKRITDS
LDMEQSTEDQEWNETDHMKSRRKRKRRKKMAYVGLAMVGGSLVLGLSGGLLAPVIGAGIA
AGLSTIGIGGATGFLTGVGGTTVVALSSTAIGANIGAR-GMSKRMGSVRTFEFRPLHNNR
R---VNLILSVSGWIIGNEDDVRLPFSTVDPLEGDL-YSLYWE-PEMLKSTGQTINIVAS
EVFTQTIQQ-----------VLGA---TILTGLMSAIQW--PMALSKLGYILDNPWNVSL
DRAWAAGLILADTLMSRNLGERPITLVGFS----LGARVIFSCLIELSK-RKASGLVENV
FI-FGTPI--VR-KREHLVMARSIVSGRFVNGYSDKDWVL---AYLFRATGGGFKAVMGI
SP-----IEDINEIENFNCTEFVDGHMAYRK-NMPKLLREMGIAVLDDTFVEIEEIMDPN
E-YKRKRKLVHD-------------VDAAQKKLSERKKH-NSWMP--KWLKPKKSKWQV-
--MVEEAVEEGREGALEGEDDGSSTDEKNQNKEEG-------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------
>gi|367011313|ref|XP_003680157.1| hypothetical protein TDEL_0C00570 [Torulaspora delbrueckii]
------------------------------------------------------------
--------------MSDSDEDLGIALKGLKLSAKHVQNKAKDKNVNECDKVDPAP-----
-----------------------------------------------------------E
AMDGPEETKEASEGMKLPEEVV--------------------------------------
------SDVDSDSDEDSWRNMEAIASFNVYNDKGELELKTYQAQAAQTASKEALSGTAGS
N-GTARSVTFGYTKIAAEEQAQRTSRSNRKTDFLFDHKRLKRLNGSNSSTTGLTEPQTPS
D------------------TELHQDSYDEYEEGVEPMNDLNADNQLNVTKNLLDEMEKFA
YVAAVNVLANQMCTELATTCLCVDIKSHKKLAQRLNFAQKDSANWKTHVLNSLYDHLQLS
PEEVQMIEKLSMHGVHLEDLCKCLKTTQDIENPFEGVNESKQS-----------------
LESGKEDSKDAEAESVGSHTSKDRSS----IDLTTEEEETSK----APKQVIAPEN-LKE
QGQIKIDVAWTIICDLFLVLLHDAVYDARSRTLLMRFAKVLNIENLE--ICEFERRVTDS
LDMEQSTENQEWNEIDHMKSRRKKRKRKKLCYVGLAMVGGSLILGLSGGLLAPVIGAGIA
AGLSTIGIGGATGFLTGAGGTAVVAVASTAIGGNIGAK-GMGRRMGSVRTFEFRPLHNNR
R---VNLIISVSGWMIGNEDDVRLPYSTVDPVEGDL-YALHWE-PEMLKSIGQTIGIVAN
EIFTQALQQ-----------ILGA---TILTAFISAIQW--PMGLSKLGYILDNPWSVSL
DRAWAAGLILADTLMSRNLGQRPITLMGFS----LGSRVIFSCLVELSR-KKALGLVENV
YI-FGTPV--VK-KKEHLIMARSAVSGRFVNAFSGRDWML---AYLFRAAAGGFNKVMGI
AP-----IEGIESIENYDCTDIVDGHLAYRK-NMPKLLKRLGVEVVSEEFVEIEETVDPE
Q-LHRKRQMVQD-------------VDAAQKKLQEKKHH-SGWMP--KWLKPKKSKWRT-
--MVEDAVEEGTQVEVPDAPDVLHTEEVKP---------KKKDNALVDNGALMRELQKIK
AAIREEQLQQERASAVADNVDAKKTTLG--------------------------------
---------------------ADTNVQKEVSPPKTP-LTTPQSPNNF---------QLLS
AGRPIILEDDDFG-KQKKDLTFSFSDDF-
>gi|349577884|dbj|GAA23051.1| K7_Yfl034wp [Saccharomyces cerevisiae Kyokai no. 7]
------------------------------------------------------------
--------------MSDSEEDLGIQLKGLKIARHLKESGEHTDEESNSSPEHDCGLSNQD
DLT-----------------VMHTQAKEEVFKRREEDGT--------------------R
TEDALHEGEAGKEGTGFPSSQSVCSPNEADSGIDRADKPSLLDPFKSVHDTDPVPGTKSR
SN----SDSDSDSDDGGWQEMPAVSSFNIYNHRGELELTSKV-RNSEQASETSPTVPPGK
NCKSVNDSRFDYTKMAAEQQAQRSYRTNKKTDFLFDHKVLKKKINS--SQTSVNLTSSPS
TTSL--------NNEKNNDDDDDDDSYDEYEDDVEPVNDLNRDSQLNITKNLLSDMEKFA
YVGAINILANQMCTNLATLCLCIDIKSHKKLAHRLQFTQKDMAAWKTVVLSRLYDHLGIS
QEEIVMIEKLSLHKIQLEDLCKCLKTTQSIDNPWENDRDHEEDDI---------EETTER
MSPNEQNGSVQ--ASTPDPEQSATPE----TPKAKQSSLSSD----VPGKVLDPEN-VKS
QDKLNIDVAWTIICDLFLICLQSSTYDSRSRTLLINFAKVLNMTSLE--ICEFERRVTDS
LDMEQSTEDQVWDEQDHMRNRRRSKRRKKMAYVALAMVGGSLVLGLSGGLLAPVIGGGIA
AGLSTIGITGATSFLTGVGGTTVVAVSSTAIGANIGAR-GMSKRMGSVRTFEFRPLHNNR
R---VNLILTVSGWMVGNEDDVRLPFSTVDPVEGDL-YSLYWE-PEMLKSIGQTVSIVAT
EIFTTSLQQ-----------ILGA---TVLTALISSIQW--PMALSKLGYILDNPWNVSL
DRAWSAGKILADTLIARNLGARPITLVGFS----IGARVIFSCLIELCK-KKALGLIENV
YL-FGTPA--VM-KKEQLVMARSVVSGRFVNGYSDKDWFL---AYLFRAAAGGFSAVMGI
ST-----IENVEGIENINCTEFVDGHLNYRK-SMPKLLKRIGIAVLSEEFVEIEEMMNPE
E-VKRKRKLIND-------------VDAAQKKLSERKKH-NSWVP--KWLKPKKSKWKV-
--MVEEAVEEGRDMQDLPENDVNNNENENPDEHEGVARQKRRDAALVDHGALMHELQLIK
QAMHEDEIKNKACLPGEDKEVESS------------------------------------
---------------------NDFLGESHYKPPSTPKINPPQSPNNF---------QLLS
AGRTILPEDDDFDPRGKKKMEFSFPDDI-
>gi|256268897|gb|EEU04246.1| YFL034W-like protein [Saccharomyces cerevisiae JAY291]
------------------------------------------------------------
--------------MSDSEEDLGVQLKGLKIARHLKESGEHTDEESNSSPEHDCGLSNQD
DLT-----------------VMHTQAKEEVFKRREEDGT--------------------R
TEDALHEGEAGKEGTGFPSSQSVCSPNEADSGIDRADKPSLLDPFKSVHDTDPVPGTKSR
SN----SDSDSDSDDGGWQEMPAVSSFNIYNHRGELELTSKV-RNSEQASETSPTVPPGK
NCKSVNDSRFDYTKMAAEQQAQRSYRTNKKTDFLFDHKVLKKKINS--SQTSVNLTSSPS
TTSL--------NNEKNN-DDDDDDSYDEYEDDVEPVNDLNRDSQLNITKNLLSDMEKFA
YVGAINILANQMCTNLATLCLCIDIKSHKKLAHRLQFTQKDMAAWKTVVLSRLYDHLGIS
QEEIVMIEKLSLHKIQLEDLCKCLKTTQSIDNPWENDRDHEEDGI---------EETTER
MSPNEQNGSVQ--ASTPDPEQSATPE----TPKAKQSSLSSD----VPGKVLDPEN-VKS
QDKLNIDVAWTIICDLFLICLQSSTYDSRSRTLLINFAKVLNMTSLE--ICEFERRVTDS
LDMEQSTEDQVWDEQDHMRNRRRSKRRKKMAYVALAMVGGSLVLGLSGGLLAPVIGGGIA
AGLSTIGITGATSFLTGVGGTTVVAVSSTAIGANIGAR-GMSKRMGSVRTFEFRPLHNNR
R---VNLILTVSGWMVGNEDDVRLPFSTVDPVEGDL-YSLYWE-PEMLKSIGQTVSIVAT
EIFTTSLQQ-----------ILGA---TVLTALISSIQW--PMALSKLGYILDNPWNVSL
DRAWSAGKILADTLIARNLGARPITLVGFS----IGARVIFSCLIELCK-KKALGLIENV
YL-FGTPA--VM-KKEQLVMARSVVSGRFVNGYSDKDWFL---AYLFRAAAGGFSAVMGI
ST-----IENVEGIENINCTEFVDGHLNYRK-SMPKLLKRIGIAVLSEEFVEIEEMMNPE
E-VKRKRKLIND-------------VDAAQKKLSERKKH-NSWVP--KWLKPKKSKWKV-
--MVEEAVEEGRDMQDLPENDVNNNENENPDEHEGIARQKRRDAALVDHGALMHELQLIK
QAMHEDEIKNKACLPGEDKEVESS------------------------------------
---------------------NDFLGESHYKPPSTPKINPPQSPNNF---------QLLS
AGRTILPEDDDFDPRGKKKVEFSFPDDI-
>gi|151940730|gb|EDN59117.1| conserved protein [Saccharomyces cerevisiae YJM789]
------------------------------------------------------------
--------------MSDSEEDLGVQLKGLKIARHLKESGEHTDEESNSSPEHDCGLSNQD
DLT-----------------VMHTQAKEEVFKRREEDGT--------------------R
TEDALHEGEAGKEGTGFPSSQSVCSPNEADSGIDRADKPSLLDPFKSVHDTDPVPGTKSR
SN----SDSDSDSDDGGWQEMPAVSSFNIYNHRGELELTSKV-RNSEQASETSPTVPPGK
NCKSVNDSRFDYTKMAAEQQAQRSYRTNKKTDFLFDHKVLKKKINS--SQTSVNLTSSPS
TTSL--------NNEKNN-DDDDDDSYDEYEDDVEPVNDLNRDSQLNITKNLLSDMEKFA
YVGAINILANQMCTNLATLCLCIDVKSHKKLAHRLQFTQKDMAAWKTVVLSRLYDHLGIS
QEEIVMIEKLSLHKIQLEDLCKCLKTTQSIDNPWENDRDHEEDGI---------EETTER
MSPNEQNGSVQ--ASTPDPEQSATPE----TPKAKQSSLSSD----VPGKVLDPEN-VKS
QDKLNIDVAWTIICDLFLICLQSSTYDSRSRTLLINFAKVLNMTSLE--ICEFERRVTDS
LDMEQSTEDQVWDEQDHMRNRRRSKRRKKMAYVALAMVGGSLVLGLSGGLLAPVIGGGIA
AGLSTIGITGATSFLTGVGGTTVVAVSSTAIGANIGAR-GMSKRMGSVRTFEFRPLHNNR
R---VNLILTVSGWMVGNEDDVRLPFSTVDPVEGDL-YSLYWE-PEMLKSIGQTVSIVAT
EIFTTSLQQ-----------ILGA---TVLTALISSIQW--PMALSKLGYILDNPWNVSL
DRAWSAGKILADTLIARNLGARPITLVGFS----IGARVIFSCLIELCK-KKALGLIENV
YL-FGTPA--VM-KKEQLVMARSVVSGRFVNGYSDKDWFL---AYLFRAAAGGFSAVMGI
ST-----IENVEGIENINCTEFVDGHLNYRK-SMPKLLKRIGIAVLSEEFVEIEEMMNPE
E-VKRKRKLIND-------------VDAAQKKLSERKKH-NSWVP--KWLKPKKSKWKV-
--MVEEAVEEGRDMQDLPENDVNNNENENPDEHEGIARQKRRDAALVDHGALMHELQLIK
QAMHEDEIKNKACLPGEDKEVESS------------------------------------
---------------------NDFLGESHYKPPSTPKINPPQSPNNF---------QLLS
AGRTILPEDDDFDPRGKKKVEFSFPDDI-
>gi|190406542|gb|EDV09809.1| conserved hypothetical protein [Saccharomyces cerevisiae RM11-1a]
------------------------------------------------------------
--------------MSDSEEDLGIQLKGLKIARHLKESGEHTDEESNSSPEHDCGLSNQD
DLT-----------------VMHTQAKEEVFKRREEDGT--------------------R
TEDALHEGEAGKEGTGFPSSQSVCSPNEADSGIDRADKPSLLDPFKSVHDTDPVPGTKSR
SN----SDSDSDSDDGGWQEMPAVSSFNIYNHRGELELTSKV-RNSEQASETSPTVPPGK
NCKSVNDSRFDYTKMAAEQQAQRSYRTNKKTDFLFDHKVLKKKINS--SQTSVNLTSSPS
TTSL--------NNEKNN-DDDDDDSYDEYEDDVEPVNDLNRDSQLNITKNLLSDMEKFA
YVGAINILANQMCTNLATLCLCIDIKSHKKLAHRLQFTQKDMAAWKTVVLSRLYDHLGIS
QEEIVMIEKLSLHKIQLEDLCKCLKTTQSIDNPWENDRDHEEDGI---------EETTER
MSPNEQNGSVQ--ASTPDPEQSATPE----TPKAKQSSLSSD----VPGKVLDPEN-VKS
QDKLNIDVAWTIICDLFLICLQSSTYDSRSRTLLINFAKVLNMTSLE--ICEFERRVTDS
LDMEQSTEDQVWDEQDHMRNRRRSKRRKKMAYVALAMVGGSLVLGLSGGLLAPVIGGGVA
AGLSTIGITGATSFLTGVGGTTVVAVSSTAIGANIGAR-GMSKRMGSVRTFEFRPLHNNR
R---VNLILTVSGWMVGNEDDVRLPFSTVDPVEGDL-YSLYWE-PEMLKSIGQTVSIVAT
EIFTTSLQQ-----------ILGA---TVLTALISSIQW--PMALSKLGYILDNPWNVSL
DRAWSAGKILADTLIARNLGARPITLVGFS----IGARVIFSCLIELCK-KKALGLIENV
YL-FGTPA--VM-KKEQLVMARSVVSGRFVNGYSDKDWFL---AYLFRAAAGGFSAVMGI
ST-----IENVEGIENINCTEFVDGHLNYRK-SMPKLLKRIGIAVLSEEFVEIEEMMNPE
E-VKRKRKLIND-------------VDAAQKKLSERKKH-NSWVP--KWLKPKKSKWKV-
--MVEEAVEEGRDMQDLPENDVNNNENENPDEHEGIARQKRRDAALVDHGALMHELQLIK
QAMHEDEIKNKACLPGEDKEVESS------------------------------------
---------------------NDFLGESHYKPPSTPKINPPQSPNNF---------QLLS
AGRTILPEDDDFDPRGKKKVEFSFPDDI-
>gi|207345722|gb|EDZ72448.1| YFL034Wp-like protein [Saccharomyces cerevisiae AWRI1631]
------------------------------------------------------------
--------------MSDSEEDLGVQLKGLKIARHLKESGEHTDEESNSSPEHDCGLSNQD
DLT-----------------VMHTQAKEEVFKRREEDGT--------------------R
TEDALHEGEAGKEGTGFPSSQSVCSPNEADSGIDRADKPSLLDPFKSVHDTDPVPGTKSR
SN----SDSDSDSDDGGWQEMPAVSSFNIYNHRGELELTSKV-RNSEQASETSPTVPPGK
NCKSVNDSRFDYTKMAAEQQAQRSYRTNKKTDFLFDHKVLKKKINS--SQTSVNLTSSPS
TTSL--------NNEKNN-DDDDDDSCDEYEDDVEPVNDLNRDSQLNITKNLLSDMEKFA
YVGAINILANQMCTNLATLCLCIDVKSHKKLAHRLQFTQKDMAAWKTVVLSRLYDHLGIS
QEEIVMIEKLSLHKIQLEDLCKCLKTTQSIDNPWENDRDHEEDGI---------EETTER
MSPNEQNGSVQ--ASTPDPEQSATPE----TPKAKQSSLSSD----VPGKVLDPEN-VKS
QDKLNIDVAWTIICDLFLICLQSSTYDSRSRTLLINFAKVLNMTSLE--ICEFERRVTDS
LDMEQSTEDQVWDEQDHMRNRRRSKRRKKMAYVALAMVGGSLVLGLSGGLLAPVIGGGIA
AGLSTIGITGATSFLTGVGGTTVVAVSSTAIGANIGAR-GMSKRMGSVRTFEFRPLHNNR
R---VNLILTVSGWMVGNEDDVRLPFSTVDPVEGDL-YSLYWE-PEMLKSIGQTVSIVAT
EIFTTSLQQ-----------ILGA---TVLTALISSIQW--PMALSKLGYILDNPWNVSL
DRAWSAGKILADTLIARNLGARPITLVGFS----IGARVIFSCLIELCK-KKALGLIENV
YL-FGTPA--VM-KKEQLVMARSVVSGRFVNGYSDKDWFL---AYLFRAAAGGFSAVMGI
ST-----IENVEGIENINCTEFVDGHLNYRK-SMPKLLKRIGIAVLSEEFVEIEEMMNPE
E-VKRKRKLIND-------------VDAAQKKLSERKKH-NSWVP--KWLKPKKSKWKV-
--MVEEAVEEGRDMQDLPENDVNNNENENPDEHEGIARQKRRDAALVDHGALMHELQLIK
QAMHEDEIKNKACLPGEDKEVESS------------------------------------
---------------------NDFLGESHYKPPSTPKINPPQSPNNF---------QLLS
AGRTILPEDDDFDPRGKKKVEFSFPDDI-
>gi|330443533|ref|NP_116583.2| hypothetical protein YFL034W [Saccharomyces cerevisiae S288c]
------------------------------------------------------------
--------------MSDSEEDLGVQLKGLKIARHLKESGEHTDEESNSSPEHDCGLSNQD
DLT-----------------VMHTQAKEEVFKRREEDGT--------------------R
TEDALHEGEAGKEGTGFPSSQSVCSPNEADSGIDRADKPILLDPFKSVHDTDPVPGTKSR
SN----SDSDSDSDDGGWQEMPAVSSFNIYNHRGELELTSKV-RNSEQASETSPTVPPGK
NCKSVNDSRFDYTKMAAEQQAQRSYRTNKKTDFLFDHKVLKKKINS--SQTSVNLTSSPS
TTSL--------NNEKNN-DDDDDDSYDEYEDDVEPVNDLNRDSQLNITKNLLSDMEKFA
YVGAINILANQMCTNLATLCLCIDIKSHKKLAHRLQFTQKDMAAWKTVVLSRLYDHLGIS
QEEIVMIEKLSLHKIQLEDLCKCLKTTQSIDNPWENDRDHEEDGI---------EETTER
MSPNEQNGSVQ--ASTPDPEQSATPE----TPKAKQSPLSSD----VPGKVLDPEN-VKS
QDKLNIDVAWTIICDLFLICLQSSTYDSRSRTLLINFAKVLNMTSLE--ICEFERRVTDS
LDMEQSTEDQVWDEQDHMRNRRRSKRRKKMAYVALAMVGGSLVLGLSGGLLAPVIGGGIA
AGLSTIGITGATSFLTGVGGTTVVAVSSTAIGANIGAR-GMSKRMGSVRTFEFRPLHNNR
R---VNLILTVSGWMVGNEDDVRLPFSTVDPVEGDL-YSLYWE-PEMLKSIGQTVSIVAT
EIFTTSLQQ-----------ILGA---TVLTALISSIQW--PMALSKLGYILDNPWNVSL
DRAWSAGKILADTLIARNLGARPITLVGFS----IGARVIFSCLIELCK-KKALGLIENV
YL-FGTPA--VM-KKEQLVMARSVVSGRFVNGYSDKDWFL---AYLFRAAAGGFSAVMGI
ST-----IENVEGIENINCTEFVDGHLNYRK-SMPKLLKRIGIAVLSEEFVEIEEMMNPE
E-VKRKRKLIND-------------VDAAQKKLSERKKH-NSWVP--KWLKPKKSKWKV-
--MVEEAVEEGRDMQDLPENDVNNNENENPDEHEGIARQKRRDAALVDHGALMHELQLIK
QAMHEDEIKNKACLPGEDKEVESS------------------------------------
---------------------NDFLGESHYKPPSTPKINPPQSPNNF---------QLLS
AGRTILPEDDDFDPRGKKKVEFSFPDDI-
>gi|836720|dbj|BAA09205.1| unnamed protein product [Saccharomyces cerevisiae]
------------------------------------------------------------
--------------MSDSEEDLGVQLKGLKIARHLKESGEHTDEESNSSPEHDCGLSNQD
DLT-----------------VMHTQAKEEVFKRREEDGT--------------------R
TEDALHEGEAGKEGTGFPSSQSVCSPNEADSGIDRADKPILLDPFKSVHDTDPVPGTKSR
SN----SDSDSDSDDGGWQEMPAVSSFNIYNHRGELELTSKV-RNSEQASETSPTVPPGK
NCKSVNDSRFDYTKMAAEQQAQRSYRTNKKTDFLFDHKVLKKKINS--SQTSVNLTSSPS
TTSL--------NNEKNN-DDDDDDSYDEYEDDVEPVNDLNRDSQLNITKNLLSDMEKFA
YVGAINILANQMCTNLATLCLCIDIKSHKNLAHRLQFTQKDMAAWKTVVLSRLYDHLGIS
QEEIVMIEKLSLHKIQLEDLCKCLKTTQSIDNPWENDRDHEEDGI---------EETTER
MSPNEQNGSVQ--ASTPDPEQSATPE----TPKAKQSPLSSD----VPGKVLDPEN-VKS
QDKLNIDVAWTIICDLFLICLQSSTYDSRSRTLLINFAKVLNMTSLE--ICEFERRVTDS
LDMEQSTEDQVWDEQDHMRNRRRSKRRKKMAYVALAMVGGSLVLGLSGGLLAPVIGGGIA
AGLSTIGITGATSFLTGVGGTTVVAVSSTAIGANIGAR-GMSKRMGSVRTFEFRPLHNNR
R---VNLILTVSGWMVGNEDDVRLPFSTVDPVEGDL-YSLYWE-PEMLKSIGQTVSIVAT
EIFTTSLQQ-----------ILGA---TVLTALISSIQW--PMALSKLGYILDNPWNVSL
DRAWSAGKILADTLIARNLGARPITLVGFS----IGARVIFSCLIELCK-KKALGLIENV
YL-FGTPA--VM-KKEQLVMARSVVSGRFVNGYSDKDWFL---AYLFRAAAGGFSAVMGI
ST-----IENVEGIENINCTEFVDGHLNYRK-SMPKLLKRIGIAVLSEEFVEIEEMMNPE
E-VKRKRKLIND-------------VDAAQKKLSERKKH-NSWVP--KWLKPKKSKWKV-
--MVEEAVEEGRDMQDLPENDVNNNENENPDEHEGIARQKRRDAALVDHGALMHELQLIK
QAMHEDEIKNKACLPGEDKEVESS------------------------------------
---------------------NDFLGESHYKPPSTPKINPPQSPNNF---------QLLS
AGRTILPEDDDFDPRGKKKVEFSFPDDI-
>gi|259146156|emb|CAY79415.1| EC1118_1F14_0463p [Saccharomyces cerevisiae EC1118]
------------------------------------------------------------
--------------MSDSEEDLGIQLKGLTIARHLKESGEHTDEESNSSPEHDCGLSNQD
DLT-----------------VMHTQAKEEVFKRREEDGT--------------------R
TEDALHEGEAGKEGTGFPSSQSVFSPNEADSGIDRADKPSLLDPFKSVHDTDPVPGTKSR
SN----SDSDSDSDDGGWQEMPAVSSFNIYNHRGELELTSKV-RNSEQASETSPTVPPGK
NCKSVNDSRFDYTKMAAEQQAQRSYRTNKKTDFLFDHKVLKKKINS--SQTSVNLTSSPS
TTSL--------NNEKNN-DDDDDDSYDEYEDDVEPVNDLNRDSQLNITKNLLSDMEKFA
YVGAINILANQMCTNLATLCLCIDVKSHKKLAHRLQFTQKDMAAWKTVVLSRLYDHLGIS
QEEIVMIEKLSLHKIQLEDLCKCLKTTQSIDNPWENDRDHEEDGI---------EETTER
MSPNEQNGSVQ--ASTPDPEQSATPE----TPKAKQSSLSSD----VPGKVLDPEN-VKS
QDKLNIDVAWTIICDLFLICLQSSTYDSRSRTLLINFAKVLNMTSLE--ICEFERRVTDS
LDMEQSTEDQVWDEQDHMRNRRRSKRRKKMAYVALAMVGGSLVLGLSGGLLAPVIGGGVA
AGLSTIGITGATSFLTGVGGTTVVAVSSTAIGANIGAR-GMSKRMGSVRTFEFRPLHNNR
R---VNLILTVSGWMVGNEDDVRLPFSTVDPVEGDL-YSLYWE-PEMLKSIGQTVSIVAT
EIFTTSLQQ-----------ILGA---TVLTALISSIQW--PMALSKLGYILDNPWNVSL
DRAWSAGKILADTLIARNLGARPITLVGFS----IGARVIFSCLIELCK-KKALGLIENV
YL-FGTPA--VM-KKEQLVMARSVVSGRFVNGYSDKDWFL---AYLFRAAAGGFSAVMGI
ST-----IENVEGIENINCTEFVDGHLNYRK-SMPKLLKRIGIAVLSEEFVEIEEMMNPE
E-VKRKRKLIND-------------VDAAQKKLSERKKH-NSWVP--KWLKPKKSKWKV-
--MVEEAVEEGRDMQDLPENDVNNNENENPDEHEGIARQKRRDAALVDHGALMHELQLIK
QAMHEDEIKNKACLPGEDKEVESS------------------------------------
---------------------NDFLGESHYKPPSTPKINPPQSPNNF---------QLLS
AGRTILPEDDDFDPRGKKKVEFSFPDDI-
