>(0)Porphyra_purpurea_gi|11465684|ref|NP_053828.1| hypothetical protein PopuCp033 [Porphyra purpurea]
MYCSQAITQTSRLPVSNNFYCKKTFFSSVNSNYQNLSQMQSWSSLKVLAFGLPDLHSIPVNLNNSFQEAI
VISTINDNNIFADVTNSWIKMHKDKNHYSLFYKEIFKALLTKQIHVIDSPIGSKDIDNKIILIQQYIWKK
GLKSPQFNSIARLNKNVDISNISTKFIMEQLSTSPVFVVKNGLNEIILGHPLSRIRRTAFNQIASSLSNL
FHQPIATSPISNGLFFFHPDDAIEFKNFVQSKAPEACKDMDIKIQPVGLHVAYKMNRNFSSDIQFRFVPD
FKEVGDLIFRHQQAKNLHFHENQYYGKNFFQGQPIYMIQPIIIKHRNGRISIIKFTGANDDREVVFTNLE
AANKSWANFIKRTPYLKRLKKPNLLVYNLESFLKDKEVLHKADLTKFIVVTNKSAYITTKESVTLPYHNG
LSKHLELNVKPKLFFVKLWIRRLLFTLTYE

>(9)Porphyra_umbilicalis_gi|378787257|gb|AFC39888.1| hypothetical protein [Porphyra umbilicalis]
MYCSQTFXXXXXXXFSNNFYCKKKFFSSVNSXXXXXXXXXXXXXXRVLAFALPELSSIPINFRNSFQEAI
VISTIHDNNIFADVTNSWIKTHKDKNHHSLFYKEIFKALLTKQIHVTNSPIELKNIDNKIISVQKYIWSK
GFKSPQFYSSMGGDNYVNTSSISTKFIMEQLSSSPVFVVKNGFNEVILGHPLSRIKRTALKQIAFSFSNV
FHQPVATSPTSNGLFFFHPDDAIEFKNFLQSKSFEASKHMGIKIQPIGLHVAYKMNRKFAGDIQFRFIPD
FKEVGDLIFKHQKAKNLIFHENQYYGKDFFQGQPIYMIQPINIKHRNGKISTIKFTGLNDKREVVFTNLE
AANKSWTNFIKTEPYLKRIKKPTLLVYNLESFLKDKEILYRADLTKFVVVTNKSAYITTKESIAIPYSKS
LSKHLKLNIKPQLFFIKLWMRRLLSTLMCE

>(18)Gracilaria_tenuistipitata var. liui_gi|51210013|ref|YP_063677.1| conserved hypothetical plastid protein [Gracilaria tenuistipitata var. liui]
MHHINIHLCSLLSAHNIFSSRRDPHFSAINQSLVIRPFIGKLINKYWQERIFLSVPNISSEKYINQLKLE
GILIYKNEQKKFLLDFSKALLSGRIETSLNSSILESDSNSYISCIWKKGFNFSIPTQFILSFFNQNNFVL
NKQQVTFLKQLKHQPLPLFTVTNNSNQIVLADSTENIANNSNFLDKIHKWYYNKFLFNDKKQAIYYGLFF
MHPMDALEYIKHIKSHYEFSKEKHEFHLFSSYLSSYYKLTRTNLRNIQFRIIPDLQEISRLLYQYRYYPN
LRFHRNQIYSKNSFRGQPLYIIEPFLAYRKIDNQKKLLVYSYNYRSNSDHNIIQSEAVFTNYTTLIKAWH
KFKQKHTDYEISSKPKVTVYNLEDFIKDNEYKSKIEEKNILFIPSQASYQFIKNYQFVNKQNKIKQIFSN
KFLSFKILSQRIFWSLTSRQPINW

>(27)Rhodomonas_salina_gi|149072084|ref|YP_001293517.1| ORF403 [Rhodomonas salina]
MNNILEQINEILSPPSIQVQSTQVNEDPVSKLLSSLYSCRGIEVNIKSKDDVFVEDFFQGSNRNAVNVNI
DEDLKLFSKPEKIPNFFNNQRQAEFPTQQQKAIITKLKKVPIYTVVNGYNEIVVASPRSMPPKSSIEWLY
DKYYDNFLWRGDKGAVNLGLFFVNKEDAETYLQEVCKKDPKGAENIGLSVKTVGLDTFYELNRTSKPKMQ
ARLIADLEEIDLLLNEYSKSKILTFHPKQKYKKQWFQGNPIYLIKINENLNKLEKNKFTLSQYNFDESSN
NDRKIVLFRKEDAYKVWNLYKIKNKELSLPDKPSLEIYNLENYLLDLEKADVSLTEKTVFVPPYESYIHS
KRLIEESKIEKNTSIKETIDQYVTTKVKSLQRFYKGMIWLVTSDTLPSEDNSW

>(35)Guillardia_theta_gi|11467652|ref|NP_050704.1| hypothetical protein GuthCp045 [Guillardia theta]
MISNFNLSYSLKHVSSCFIFSDNNDPINKLINSLNSNLNLKVRLPSDYNLLADEFLPPNQSVLIDFKDID
DNWFSKAKHLPSLFSNRRSPYFPTLAQKHILESLKTVPVYTIVNDLNEIVIASPRDLTNFNSFNWVKRFY
NDWFIWEKDEGNVNIGLFFMNREDAELYLHQICLKDPRGVENVGVNVKTISLDTFYKLNRLSPPRLQFKL
IADLQEIKNILNVNSNSRVSFHPKQKYDKNWFKGIPIFIYSPTVTNLDWTLKSNKNMIFFQEMMHIMFQK
IY

>(42)Cryptomonas_paramecium_gi|283794866|ref|YP_003359219.1| hypothetical protein CRPAC_p002 [Cryptomonas paramecium]
MYKEYMNKINILLSMMLSNILSRNANTVLSPEYPGDHRPEVIEKLLSEDVKVKLRREFDHKKPRPKKVQQ
IKLVENTPRASLSKGKKDPFIESIQTDIGGMLRHVPTYMVTTKEGDIVVSIATVSEDILPDPRTKKPVPQ
PKKKEREPLLLFFMGKDEAKLYLNKIFNDEPEISEQLGIRITKTTLETFYRVNRDEKCKVDARLISDLEE
SHFMLSTRRKNEFYTINPKQRYKRNFFQGTPIYILKHTIGPYVNDSQYTLRGRQIYFKWSDALSSWEKSV
TSEHMKKNIKPNIEVYNLENLLQEMEEDDEEDFSAYTFMPPIIKNEVPDNPIKKK

>(49)Emiliania_huxleyi_gi|71842290|ref|YP_277378.1| hypothetical chloroplast RF80 [Emiliania huxleyi]
MENTQAPIQKSPLNVLNPPEFQEIDTISFLTDLYSYPPKFNVSVGETNVNNFNGQLKNKTRPANSLRVLE
NKLSYKITDYINGFLNKNFTSNFYKIQTKPIQKALKSVPVYIVVNGRDEIVLFHKENLNTKFSRGIWDKS
FIASPRRELAKIFYDFCGAFQDNGNTRSSDLGLVFFNYEDAEVFRDDVLKQDTRGSQTVGLTIHCVSLES
AYNLLRSPHPGFDLRFVPNLKEVSSLADQTDNARFIFEEKQEVKDAVEQSFGYTQEVVNKSTTSPTIEKT
CVQGIPIYLIQTQTTPRNFIWHNFQLAAEKIDTILNTSTFGRFSRDQGSKIKIFRAGANKLQNSDKVSNY
VFFSQQQALAFCQQNSRYLIRQNEKSWRLQFDALIRKPTIFVTSLENLLEHWENHLLLETHSQNGGEKIS
EPSQLFAAKETHFISPSSTKEYFETLNDEEIEGLSTPVTKLVRALKVRRNVFTFSLRYLFSRGGSF

>(58)uncultured_prymnesiophyte C19847_gi|299890949|gb|ADJ57448.1| hypothetical chloroplast protein RF80 [uncultured prymnesiophyte C19847]
MVLLNRSNELSFRENFFQNLPFFNKQQASLSLFKGVYSYPGKLKIKWNSLDELKNESFQTSTYDLGTDKL
PFVDLTEDYLLNSSPDEQDITQINYSRQSYKDGYKAKRNSADFYRNNTKDVQNALKGIPVYVVLNGWNQM
TLTKPTEGFSHNAPYLRELYPTPTFLKTRFKKQAYDFCGAFGSIGHENLNKGFFFLNYQDAQEYLRAIVQ
NDVDGTELVSLSVHCFGLDTAYRIMRQQQNQIDFRLVPDTKQTRKLLTRHLGTPDLIIDKTQQQIRLRRR
SVNFLPYLGGELTEKFSPFSSFLQNNEYFKGVPIYIVQIRDTPRDMLRSQYFNVVTVGDNLIGKVKQLIG
FGVGFGQNGIMQGSLMDVKSASPSDVRTNYVFFDKGQAARFQRKQGRKTVRYMGSRSLPFMRGIISKPKI
FVHNLEDFLELWEENIVNKQIDNPQNNIFQAKDTVFIPSRTAQNELKQFPRPEGMSKEQIQQKVKNNLSL
KYRTLQNFVGFFFSAM

>(68)Arabidopsis_thaliana_gi|15234162|ref|NP_195061.1| Tic22-like protein [Arabidopsis thaliana]
MESSVKPNPFLSFSSFIHHQCTRFSSDLSARIEDTKRFAETLATRRFSLPTPPPFASVSQSKSGTPTTTL
SPSLVAKALAGTSVFTVSNTNNEFVLISDPTGGKSIGLLCFRQEDAEAFLAQARLRRRELKTNAKVVPIT
LDQVYLLKVEGISFRFLPDPIQIKNALELKSSGNKNGFDGVPVFQSELLVVRKKNRRYCPVYFSKEDIER
ELSKYTRASRGDQQIMVGSLEDVLRKMEMSEKNSGWEDVIFIPPGRSYAQHMQDLIKE

>(74)Glycine_max_gi|356512421|ref|XP_003524917.1| PREDICTED: uncharacterized protein LOC100811136 [Glycine max]
MMNFDGFQKALAEFQGRCSTLLGSLTRLQPNRARPPWARIAQPWGGRPMAMTVEAIEERLEGIPVYALSN
ASEEFLLVSGSSSGKNLGLFCFNKDDAEALLNQVTLIDPHARQGSKVVPVALNKVFQLKVNGVAFRLIPE
FSQVKNALQEREKSGFASSGFSGVPVFQSRSLILKSQNKRFRPLFFRKEDLENTLKSAAREQNKLNPTMR
KGDIQVATLEDVIKEMKENSTSNWDDVIFIPPGFDVSDDSNEQ

>(80)Populus_trichocarpa_gi|224136756|ref|XP_002326937.1| predicted protein [Populus trichocarpa]
MEPSKPSNPLLSLSTVIHQHCLRLGAEFSARVSDTTRFLAGNFPPPSRLRLAPSPPFASVSQPKQTANTA
NLSSEHVAKALAGTAVYTVSNSDNEFVLISDPNGAKSIGLLCFRQEDAEAFLAQVRLRRRELRSQAKVVP
ITLDQVYMLKVEGIAFRFLPDPVQIKNALELKSADVRSGFDGVPVFQSDQLIVKKKSKRYCPVYFQKEDI
EKELSKVSRASRGPGLSQHIMVGSLEDVLKKMEISEKNSGWEDLIFIPPGKSHSQHIQEITKA

>(86)Populus_trichocarpa_gi|224067266|ref|XP_002302438.1| predicted protein [Populus trichocarpa]
MEPSGPSNPLLSLSTFIHHHCLRLGAEFSTRISDTTRFLGGNLPPPRRLCLAPSPPFASVSQPKQTATTA
NLSSDHVAKTLAGTAVYTVSNSNNEFVLISDPNGAKSIGLLCFRQEDAEAFLAQVRLRRRELRSQAKVVP
ITLDQVYMLKVEGIAFRFLPDPVQIKNALELKAVDIRSGFDGVPVFQSDLLVVKKKNKRYCPIYFQKEDI
EKELSKVSKASRGPSLSQHIMVGSLEDVLKKMEISEKKSGWEDLIFIPPGKSHSQHIHEITKV

>(92)Sorghum_bicolor_gi|242095102|ref|XP_002438041.1| hypothetical protein SORBIDRAFT_10g007160 [Sorghum bicolor]
MAPPDSISTRSSLPLAAAPMSDPTPSPYAASPPPPNPLAAAASFLQHHLSRLASHLNAPRPALAAAAAAA
RTPGPQGASLSLALAPDEVARALTGTPVFTVCNSSNEFVLVSDPATGLRSLGLLCFRSEDADALLSHVRT
RQPVLGKGAKVVPITLDQVYMLKAEGIAFRFLPDPLQIKNALEMKSGLTAFDGVPVFQSDLLVVKKQKKR
YCPIYFQKEDIERELTRASKGSRGSVLSKQIMVGSLEDVLKKMEINERNSGWDDLIFIPPGKNLNQHINE
VSA

>(99)Brachypodium_distachyon_gi|357124843|ref|XP_003564106.1| PREDICTED: uncharacterized protein LOC100825582 [Brachypodium distachyon]
MPPPNSTRSSSLPLAAAPMSNPSPSSSPPPNPLAAASSFLQHHLSNLASRFAAPRPALAAAHPPGPQGSS
LSLALAPDEVARALTGTPVFTVCNSSNEFVLVSDPATGLRSLGLLCFRSEDADALLSHVRTRQPVLGKGA
KVVPITLDQVYMLKAEGIAFRFLPDPLQIKNALELKSGLTGFDGVPVFQSDLLVVKKQKKRYCPIYFQKE
DIERELKKASKGSKGSALLKQIMVGSLEDVLKKMEINDRNSGWDDMIFIPPGKSLNQHINEVSA

>(105)Glarea_lozoyensis 74030_gi|361126402|gb|EHK98404.1| putative Calcium channel YVC1 [Glarea lozoyensis 74030]
MPSAIAPEEVTKVALRLRYLIEESVPCELEEGLITQAHSRIITHKVVQAAKEAGGDQYGACVVYCLLVNK
RWFKKQASLELWDADLHNVRAVACEVIAKQLIETEDSLDYLLQDILLKRYSIIIDNEVTHPANVIERAVD
LHALRVTGSSGYQKCVNYLWRGWLVQDDMDANRFVDYKKKDNVNYWTHVHPDRMRAPVYQNATQIVISLI
YLGLYTGAINTVNSTGDLDFVEIVLYIFTFGFLCDEFSKVWKVGRNYLGFWNVFNLMLYGMLTTSLIIRI
IALGHPIGEDKRAKFNELSYNFLDATTFILQAMANAVMGSPEFDNFDNFAPPFGIILYYIFSFLIMVILL
NVLIALYNSAYEDITSNAIDEYMALFAQKTMQFVRAPDENVFIAPFNLIEIFCLILPFEWWMSRKTYAKL
NDIVMAIVYSPLLFVAAWFEKRSAKVVRSNRKRGEEDDDTVEEWEQMAGTVDFEGEGWDKKVASAKPDVE
RDTATHEVRKLRGEVGELKELIEKLLSASGKTSA

>(115)Zea_mays_gi|194702742|gb|ACF85455.1| unknown [Zea mays]
MAPPDSISTCSSLPLAAAPMSEPTPFPFAASPLPNPLVATASFLQHHLSRLASHLNVPRPALAAAAARTP
GPQGASLSLSLAPDEVARALTGTPVFTVCNSSNEFVLVSDPATGLRSLGLLCFRSEDADALLSHVRTRQP
VLGKGAKVVPITLDQVYMLKAEGIAFRFLPDPLQIKNALEMKSGLTAFDGVPVFQSDLLVVKKQKKRYCP
VYFQKEDIERELTRASKGSRGSALSKKIMVGSLEDVLKKMEINERDSGWDDLIFIPPGKSLNQHINEVSA

>(121)Arabidopsis_thaliana_gi|334187125|ref|NP_001190901.1| Tic22-like protein [Arabidopsis thaliana]
MESSVKPNPFLSFSSFIHHQCTRFSSDLSARIEDTKRFAETLATRRFSLPTPPPFASVSQSKSGTPTTTL
SPSLVAKALAGTSVFTVSNTNNEFVLISDPTGGKSIGLLCFRQEDAEAFLAQARLRRRELKTNAKVVPIT
LDQVYLLKVEGISFRFLPDPIQIKNALELKSSGNKNGFDGVPVFQSELLVVRKKNRRYCPVGSLEDVLRK
MEMSEKNSGWEDVIFIPPGRSYAQHMQDLIKE

>(127)Physcomitrella_patens subsp. patens_gi|168027187|ref|XP_001766112.1| predicted protein [Physcomitrella patens subsp. patens]
MDVASASRVVSSAGGVADGMRGFRRCTPLGEDLVMLVRLADTRNWLRCEQLVENRKRIVAQSVGSVRRNR
RAVWNGISDCEKKLWMGSSGLGTQVETQLPRTRFERARRVRDQKPLRVPMASFSLGSPNQGDEWESKLRS
ESEEVETNLRNAMTEEQVNKCLDGVPVYTVSNSANEFVVVSEMNSPESYGIICFRETDAEAFLSQIRSRD
PSAGSDVRVTAIPLGKVLQLSSKEGETFRFVPDPNQIRNAYEVKARAGELSKAFEGVPVFQSESLTLNSI
NRRLLPIFFSKEDLETALQTAFEEQKRVDPALEFKPNIQVDSLEDILDMMEGSEEETQRAEIVFIPAGMD
VFKYLTQFEGAIAR

>(135)Zea_mays_gi|226510510|ref|NP_001151773.1| tic22 [Zea mays]
MAPPDSISTCSSLPLAAAPMSEPTPFPFAASPLPNPLVATASFLQHHLSRLASHLNVPRPALAAAAARTP
GPQGASLSLSLAPDEVARALTGTPVFTVCNSSNEFVLVSDPATGLRSLGLLCFRSEDTDALLSHVRTRQP
VLGKGAKVVPITLDQVYMLKAEGIAFRFLPDPLQIKNALEMKSGLTAFDGVPVFQSDLLVVKKQKKRYCP
VYFQKEDIERELTRASKGSRGSALSKKIMVGSLEDVLKKMEINERDSGWDDLIFIPPGKSLNQHINEVSA

>(141)Salmo_salar_gi|209733952|gb|ACI67845.1| Galectin-9 [Salmo salar]
MSFQQPFFNPRVPFTGCIQGALHEGMTITVTGRVLPGAQRFHVNLQCGSRGNPDIALHFNPRYDSFLDVV
ICNTMQHSKWGSEEREYFATMTRGANFTLMFLVNRDSYSIFVNGVLFMEYLHRLSFSRVDTISVNGGVEV
QSIAFSNPAVTSPPPQPGYPGHPHSAFSAAGFLQAPPPYTAQPPYTPKPSFVVPYKNIMAGGLYPGRNIT
IQGVVNHNADKFCINLRFNSGVAFHFNPRFNENVVVRNSLLKEQWGQEERTGGMPFYRGQPFTVIIMCDT
QCYKVMVNGALMFSYNHRHFLFQQIDILEVEGDMSLSAVLV

>(148)Ricinus_communis_gi|255538318|ref|XP_002510224.1| protein translocase, putative [Ricinus communis]
MEHSKLSNPLLSLSTFIHQHCLRLGAELSTRLGDTTWAVSNNLLPGLNNRKHRPAPLFASVSQQPKQASG
LSSEHVAKTLAGTAVYTVSNSNNEFVLVSDPDGAKSISLLCFRQEDAEAFLAQVRLRRRELRSQARIVPI
TLDQVYMLKVEGIAFRFLPDPVQIKNALELKASDTKRGFDGVPIFQSELLVVKKKNKRYCPIYFQKEDIE
KELSKVSRASRGPGLSQHIMVGSLEDVLRKMEMSEKNSGWEDLIFIPPGKSHSQHIQEVAKV

>(154)Medicago_truncatula_gi|357465499|ref|XP_003603034.1| Tic22 [Medicago truncatula]
MESQGQWNPLLSFSRFIHQNCNHLATRFEDTRKFAGTLIQSHTRTKPAFAATLTSNHVAKSLAGTSVYTV
SSSNNEFVLMSDAEGAKSIGLLCFRQEDAEAFLAQVRSRKNEFRGNAKVVPITLEQVYLLKVEGIAFRFL
PDPLQIRNALELRAANKEGFDGVPVFQSELLVVKKKNKRYCPVYFSKEDIEQELSKVSRVSKGPGVSKQI
MVGSFEDVLKKMEMSEKNSGWDDLIFIPPGKSRSQHIQEIKV

>(160)Arabidopsis_lyrata subsp. lyrata_gi|297798602|ref|XP_002867185.1| hypothetical protein ARALYDRAFT_913087 [Arabidopsis lyrata subsp. lyrata]
MESSVKPNPFLSFSSFLHHHCTRFSSDLSARIEDTKRFAETLATRRFSPFPPPPFASISQSKSGAPPTTL
NPSLVAKALAGTSVFTVSNTNNEFVLISDPTGDKSIGLLCFRQEDAEAFLAQARLRRRELKTNAKVVPIT
LDQVYLLKVEGISFRFLPDPIQIKNALELKSSGNKNGFDGVPVFQSELLVVRKKNRRYCPVYFSKEDIER
ELSKYTRASRGDQQIMVGSLEDVLRKMEMSEKNSGWEDVIFIPPGRSYAQHMQELIKE

>(166)Cyanidium_caldarium_gi|11465478|ref|NP_045131.1| hypothetical protein CycaCp114 [Cyanidium caldarium]
MFPNIVNLKIWPVELAYSSLNKDFVSLSAEKEINNKIEETIESHCLKKQGIRIRSPYGLRTLKVLQACPK
KEDLVLQRGCIKIALPFSGILSSYQSKCQYMQGLNNHLRNTLNNVVVYVVTNSSDELVSVASRSLMYRGR
GISLVDLIIDLYYRYFVLDKYNLTNVVGFVFMDYEDSNLFLRTVLQNCYDKDKKAAVQKLKLGEACKLFF
NPLNGIKVRFIPSSKELEKLFSVYQNEFDHISLHADQRFTPNSYSGVPVYLVSNKWLTNKSLVTLNPSLS
TLLSHDFVFFTYLDALKFCNIIEDLLLYGNKEVESKPSIVLFNFEEILLHLKDVASLQTKVHFLPPYSVC
DNEKLILAELKKVGSSTNPASTTWEYLSVILNSDLNNKN

>(174)Physcomitrella_patens subsp. patens_gi|168057172|ref|XP_001780590.1| predicted protein [Physcomitrella patens subsp. patens]
MTEGGSGSSAACKGEYVAGGRRMAQRRPLLDGGAVVSDVRRRLVEAQNWLGVAVAEGANRISRFGLSIED
GRGMMVQKMERIGNRRSDPRSKIRSGQLPWEKVWTAMSGFGAQFEAQLQRSKAGIPEAMLRMIWNRGAPR
PLIASLSLGLPAQGGEALEAKHVFDIAMSGEQVAKRLDGVPVYTVSNSANEFVLISDLNTSKSLGIFCFR
EADAEALLSQVRDREPSLGRGAKVVAVSLDKVYQLSTEGIAFRFLPDPRQVKNALEARSRAGEPGKAFDG
VPVFQSDNLILRSNNRRFCPIFFSKEDLETALQRAFKQQQKINPALKVSTDIQVGSFEDVLKRMEGNEED
SGWGDIVFIPPGMDAYKHLSKSQGTVVG

>(182)Cyanidium_caldarium_gi|2541891|dbj|BAA22826.1| unnamed protein product [Cyanidium caldarium]
MDDYYIFEYRLSEPQPTVWQSLWQWYVSPVQIQHLLLSRQVQSIHLPFIKSKSCGVIDYQFHYQFKSNHP
KIHDAFRQSLEACPIYYVVNPKQELILLSPRKWESEYQAPTFMNWVLDCVFRQSPTSYLLVFFHPDDAQM
YLQSVLNNPYERDKNSFVQEGDLFTFLKFNRADVKVLLVPHLKQMCQWQQFDGTPVFRVQVKDREWLFLS
KQNAQQFVKRMKKLSCKCDVVSLESILEADANRQARCVLVPLS

>(188)Coccomyxa_subellipsoidea C-169_gi|384252955|gb|EIE26430.1| hypothetical protein COCSUDRAFT_58968 [Coccomyxa subellipsoidea C-169]
MSIIIDSLSLGAATSTYRPQPICDLAYNPEEIKARLSGVPVYTVANKQNEFVLVAGESGGEVRQLGLIFF
SEADAHALVQKVMEQNPKLAKQSRVLKVSMDAIYDFAITKEKDKRAAGVTFRFMPDAKEVQSALEMYKEA
GVPSTSFTGVPVFQAQGLTVKTEKSRYTPLFLAKEDLDVAVGAAFSQRESAREAATRNKAAAAEDEVESA
RTALEAAPKGKDRKAAQAELDKAEARLSKYKGRLSAMHSSETAPKVEVGCLEEVISRMEADADGEWGSVM
FIPAGALASQQQ

>(195)Picea_sitchensis_gi|294461156|gb|ADE76142.1| unknown [Picea sitchensis]
MKSSLPSSAMDCSLESSTSRTVSSKFHPAFSLKDTLIPNIDKLLPNFHPFERSGAINRTIMPPESNNNTP
KLFPVSAVNNHTIPHLTNAVSNLFKCLTSRTNASAAKQHPWFRFGKELGQRFEDFKACLGSVISDAARPR
QRVVPCFASVSAGGQESWEPKAVFQLALSTVNVAKTLEGVPVYTVSNANNEFVLVSDPNSSRSLGLLCFR
QQDAEALLAQVQLRQPMLSRGAKVVPIPLEKVYTLKVEGIAFRFLPDPVQVKYALQMKSKDLSKAFDGVP
VFQSDRLVITKNNRRLYPLYFCKEDLERELLRNLKNQPKASRLSSDILVGSLEGILKKLEESKNRSGWDD
VVFIPPGKISTEHIQKVLV

>iTic22-like_gi|18424615|ref|NP_568958.1| Tic22-like family protein [Arabidopsis thaliana]
MGSP----------------------DKQHRRHV---AAEFLH-----------------
SAVTSIS----------------SSIIPLFPPKTA--P---------------SRVCLPL
RFSVSD-------------------------DVSSP---FESTVK--STSSASSSGLNST
VRISSLSSDGK-----R-GGPAFVGQVFSMCDLTGTGLMAVS-----THFDIP-FISKRT
PEWLKKMFSTITKSERNGPVFRFFMDLGDAVSYVKKLNI--------------PSGVVGA
CRLDLAYEHFKEKPHLFQFVPNERQVK--AANKLLKSMPQNGKTQKVEGVPVFGAQNLDI
AVATADGIKWYTPYFFDKAVLDNILEESVDQHFHTLIQTRHVQRRRDVVDDSLAS----E
VMEEMGDSMLEPPEVQEAMEEIGT-SGIP---------LSVVA-KAA-------------
----------EIQLLYAVDRVLLGSRWFRKATGIQPKLPYLVDSFERR-SAFSIQRASGS
ATRCLGD-SVEA------DTSASLLRVED-------------DSPSEAEKRQ--QHLWFP
FGDWISHSVSRKEH---THHKGSSDQR-----DMESREREMLRS-----PFLPKITMVGI
STG----EAA-QMSKANLKK---TMEDLTEDLEQSDEGND-HGSKRYDSLKIE-----ER
DPLFVANV-------------------------------------------GDYYSGL-A
KAG----SARLSRRGDDQ--------
>Arabidopsis_lyrata_gnl|BL_ORD_ID|26695 _496448|PACid:16060442
MGSP----------------------DKQHRRHV---AAEFLH-----------------
SAVT--------------------SIIPLFPPKTA--P---------------SRVCLPL
RFSVSD-------------------------DVSSP---FESTVK--SSSSTSSSGLNST
VRISSLSSDGK-----R-GGPAFVGQVFSMCDLTGTGLMAVS-----THFDIP-FISKRT
PEWLKKMFSTITKSERNGPVFRFFMDLGDAVSYVKKLNI--------------PSGVVGA
CRLDLAYEHFKEKPHLFQFVPNERQVK--AANKLLKSMPQNGRKQKVEGVPVFGAQNLDI
AVATADGIKWYTPYFFDKAVLDNILEESVDQHFHTLIQTRHVQRRRDVVDDSLAS----E
VMEEMGDSMLEPPEVQEAMEEIGS-SGIP---------LSVVA-KAA-------------
----------EIQLLYAVDRVLLGSRWFRKATGIQPKLPYLVDSFERR-SAFSIQRASGS
ATRCLGD-SVEA------DTSASLLRVED-------------NSPSEDEKRQ--QNLWFP
FGDWINHSESKKEH---THHKGPSDGR-----DMESREREMLRS-----PFLPKITMVGI
STG----EAA-QMSKANLKK---TMEDLTEDLEQSDEGND-HGSKRYDPRKME-----ER
DPLFVANV-------------------------------------------GDYYSGM-A
KAG----SARLSRRGDDQ--------
>Capsella_rubella_gnl|BL_ORD_ID|25653 _v10028359m|PACid:20911489
MGSP----------------------EKQHRRHI---AAEFLH-----------------
SAVTSIS----------------SSIVPLFPPKTT--P---------------SRVWLPL
KFSVSD-------------------------DVSSP---FESTVN--SKSSKSSSGLNST
VRISSLSSDGK-----R-GGPAFVGQVFSMCDLTGTGLMAVS-----THFDIP-FISKRT
PEWLKKMFSTITKSERNGPVFRFFMDLGDAVSYVKKLNI--------------PSGVVGA
CRLDLAYEHFKEKPHLFQFVPNERQVK--AANKLLKSMPQNGKKQKVDGVPVFGAQNLDI
AVATADGIKWYTPYFFDKAVLDNILDESVDQHFHTLIQTRHVQRRRDVVDDSLTS----E
VMEEMGDSMLEPPEVQEAMEEIGS-SGIP---------LSVVA-KAA-------------
----------EIQLLYAVDRVLLGSRWFRKATGIQPKLPYLVDSFERR-SALSIQRASGS
AARCLSD-SVET------DTSASLLRVEEG------------DSPREDEKRR--QNLWFP
FGDWLKHSVSRKDQ---AHQKGSSGQR-----DMESRDREMLQS-----PFLPKITMVGI
STG----EAA-QMSKANLKK---TMEDLTEDLEQSDEGND-HGSKRYDPLKIE-----ER
DPLFVANV-------------------------------------------GDYYSGL-A
KAG----SARLSRRGDDQ--------
>Thellungiella_halophila_gnl|BL_ORD_ID|20311 _Thhalv10003967m|PACid:20199916
MDLP----------------------DKQHRRHI---ATEFLH-----------------
SAATSI-----------------SSIIPLFPPKAT--P---------------SRVCLPL
RFSVSD-------------------------DV-FP---FDSTVRNASSASTSSSSLNST
VRISSLSSDGK-----R-GGPAFVGQVFSMCDLTGTGLMAVS-----THFDIP-FISKRT
PEWLKKMFSSITKSERNGPVFRFFMDLGDAVSYVKKLNI--------------PSGVVGA
CRLDLAYEHFKEKPHLFQFVPNERQVK--AANKLLKSMPPNGKKQKVEGVPVFGAQNLDI
AVATADGIKWYTPYFFDKAVLDNILEESVDQHFHTLIQTRHVQRRRDVVDDSLTS----E
VMEEMGDSMLEPPEVQEAMEEIGT-SGIP---------LSVVA-KAA-------------
----------EIQLLYAVDRVLLGSRWFRKATGIQPKLPYLVDSFERR-SAFSIQRASGS
TSRCIGD-SAEA------DTSASLRRVED-------------DSPSEDEKRQ--QNLWFP
FGDWLNHSGSRKEH---A-QKVTSDQR-----EMECREREMQQS-----PFLPKITMVGI
STG----EAA-QMSKANLKK---TMEDLTEGLEQSDEGSSEHGSKRYDPLKME-----ER
DPLFVANV-------------------------------------------GDYYSGL-A
KAG----SARWSRRGGDSNETHPRS-
>Brassica_rapa_gnl|BL_ORD_ID|11888 _010109|PACid:22695398
MDSP----------------------DKIHRRYN---AAEILH-----------------
GAATSI-----------------SSIIPLFPPKTT--P---------------SRVCLPL
RFS----------------------------DV-SP---FESTVKNASSTSTSSSGLNST
VRISSLSSDGK-----R-GGPAFVGQVFSMCDLTGTGLMAVS-----THFDIP-FISKRT
PEWLKKMFSTITKSERKGPVFRFFMDLGDAVSYVKKLNI--------------PSGVVGA
CRLDLAYEHFKEKPHLFQFVPNERQVK--AANKLLKSMPPSEKKQRVDGVPVFAAQNLDI
AVATSDGIKWYTPYFFDKAVLDNILEESVDQHFHTLIQTRHVQRRRDVVDDSLTS----E
IMEEMGDSMLEPPEVQEAMEEIGT-SGIP---------LSVVA-KAA-------------
----------EIQLLYAVDRVLLGSRWFRKATGIQPKLPYLVDSFERR-SALSIQRASGS
TTKCLGD-S---------NSSASLLKVED-------------GSPSEEEKRQ--QSLWFP
FGDWLK------------AQKDSSGQR-----EMESREREMQRS-----PFLPKITMVGI
STG----EAA-HMSKANLKK---TMEDLTQDLEQSDEGSD-HGSNRYDPLKIE-----ER
DPLFVANV-------------------------------------------GDYYSGL-A
RAG----SARWSRRGDDRNETPPRSS
>Citrus_clementina_gnl|BL_ORD_ID|24296 _0.9_006877m|PACid:19275444
MASP-----------------A-EP---NHLQNQ---ISSFIN-----------------
ATTSTL-----------------FSLITP--TKTT--PSSQSQPSSAPA----SRLCIPL
QFADSSC-------P------SSSTRSPVGSDSIS-------SNSGASSSESSSSGFPST
VRISAINSSGK-----G-GGPAFVGQVFSMCDLSGTGLMAVS-----THFDIP-FISKRT
PEWLKKLFATITKSERNGPVFRFFMDLGDAVTYVKQLNI--------------PSGVVGA
CRLDLAYEHFKEKPHLFQFVPNEKQVK--AANKLLRTIPDSGRKKKVDGVPVFSAQNLDI
AIATADGIKWYTPYFFDKNMLDNILEESVDQHFHALIQTRHMQRRRDVIDDNLAA----E
VVEEIGDSIWEPPEVQEMMDEIGH-PAIP---------LSVIS-KAA-------------
----------EIQLLYAVDRVLLGNRWLRKATGIQPKFPYMVDSFENR-SAASFLRASES
TSCLANS-ET--------NNGSSDLKLED-------------KHLDK-RDQR--PDFRFP
FGDWFRHLWSKQDC---EAQGSSY---------IECTKRNLQLN-----PFLPKVTMVGI
STG----EAG-QMTKANLKK---TMENLTKELEQTDQENA--TSSGSNEYIIE-----DR
DPLFVANV-------------------------------------------GGYYSGL-A
KTG----STRWVRGRSNN--------
>Citrus_sinensis_gnl|BL_ORD_ID|32460 _1.1g009199m|PACid:18125400
MASP-----------------A-EP---NHLQNQ---ISSFIN-----------------
ATTSTL-----------------FSLITP--TKTT--PSSQSQPSSAPA----SRLCIPL
QFADSSC-------P------SSSTRSPVGSDSIS-------SNSGASSSESSSSGFPST
VRISAINSSGK-----G-GGPAFVGQVFSMCDLSGTGLMAVS-----THFDIP-FISKRT
PEWLKKLFATITKSERNGPVFRFFMDLGDAVTYVKQLNI--------------PSGVVGA
CRLDLAYEHFKEKPHLFQFVPNEKQVK--AANKLLRTIPDSGRKKKVDGVPVFSAQNLDI
AIATADGIKWYTPYFFDKNMLDNILEESVDQHFHALIQTRHMQRRRDVIDDNLAA----E
VVEEIGDSIWEPPEVQEMMDEIGH-PAIP---------LSVIS-KAA-------------
----------EIQLLYAVDRVLLGNRWLRKATGIQPKFPYMVDSFENR-SAASFLRASES
TSCLANS-ET--------NNGSSDLKLED-------------KHLDK-RDQR--PDFRFP
FGDWFRHLWSKQDC---EAQGSSY---------IECTKRNLQLN-----PFLPKVTMVGI
STG----EAG-QMTKANLKK---TMENLTKELEQTDQENA--TSSGSNEYIIE-----DR
DPLFVANV-------------------------------------------GGYYSGL-A
KTG----STRWVRGRSNN--------
>Manihot_esculenta_gnl|BL_ORD_ID|29919 _4.1_003879m|PACid:17989925
MASS-----------------T-QPAPNRHH-------SNLFH-----------------
SATTAL-----------------ISLVSS--PKAS--PLS-TIPLCP------PKICIPF
QFADSSY-------PLIQ--SIRSPFDSNQPESVSP---KSAAVKGL-SSAESNSGFPST
VRIAGLKSNGK-----S-GGPAFVGQVFSMCDLSGTGLMAVS-----THFDIP-FISKRT
PEWLKKIFATVTKSERNGPVFRFFIDLGDAVAYVKRLNI--------------PSGVVGA
CRLDLAYEHFKEKPHLFQFVPNEKQVK--AANQLLKKIPQGNGRRKVDGVPVFTAQNLDI
AIATADGIKWYTPYFFDKNMLDNILEESVDQHFHSLIQTRHMQRRRDVVDDNLAA----E
VIEEMGDNMLEPPEVQEMLDEMGH-PGIP---------LSVIS-KAA-------------
----------EIQLLHAVDRVLLGNRWLRKATGIQPKFPYMVDSFEKR-SASSFQRASES
TSYLANP-KT---------DSTSNCTFKD-------------NAQAD-HEQK--TDLRIP
FGDWFRHPWLKQKW---KPEKLPEIRS--HESLSECTKQKLERN-----SFLPKITMVGI
STG----EAG-QMSKASLKK---TMEDLTRELEQTDRENA---TVGRLECNVRILILLTE
APRNIENVLMLSNILSLARYRENFSIVICFWECILSPYSLSSFPLSYPDRQGGTFSSLYE
ESGFSILTGLYGSSGIFAKETLHSWI
>Ricinus_communis_gnl|BL_ORD_ID|23216 _30169.m006582|PACid:16821381
MSLS--------------------PDPNHHHQ-----PSNFFH-----------------
SATTAI-----------------TSLISTN-PKTS--PSS-TIPLSP------PKICIPF
QFADSSYR------PL-----TRSSFESTHPDSVSP---KSAAVKGL-SSAESSSGFPST
VRIAGLNSNGK-----G-GGPAFVGQVFSMCDLSGTGLMAVS-----THFDIP-FISKRT
PEWLKKVFTTVTKSERKGPVFRFFMDLGDAVTYVKRLNI--------------PSGVVGA
CRLDLAYEHFKEKPHLFQFVPNEKQVK--AANQLLKTIPQSDGRRKVDGVPVFSAQNLDI
AIATTDGIKWYTPYFFDKSMLDNILEESVDQHFHALIQTRHMQRRRDVIDDNLAA----E
VIEEMGDSMLEPPEVQEMMDEIGH-PAIP---------LNVIS-KAA-------------
----------EIQLLYAVDRVILGNRWLRKATGIQPKFPYMVDSFEKR-SASSFRRASEP
ASYLAKS-KT--------DADTSKLNLED-------------GAQAN-HEPI--TDLRLQ
FGDWFKSLGLKQQQ---KPEKGSEI--------SECRKQKLEMN-----PFLPKITMVGI
STG----EAG-QMSKASLKK---TMEDLTRELEHTDRENAPGSSNNGNDLEME-----DR
DPLFVANV-------------------------------------------GDYYSGM-S
KTN----SPRLVRGGSK---------
>Populus_trichocarpa_gnl|BL_ORD_ID|3641 _POPTR_0017s00970.1|PACid:18209660
MPSP-----------------P-EPPQHRHNNHH---LSNFLN-----------------
STTKTL-----------------FSLLSP--PNIL--------PLAPPQ----PKICISF
HLPNAPL-------PLTQ--STLSLFESTQPDSLSPSKSSSASVKDI-SSAESNSGFPSA
VRIGRLNPNGN-----G-GGPAFVGQVFSMCDLSGTGLMAVS-----THFDVP-FISKRT
PEWLKKIFATVTKSERNGPVFRFFMDLGDAVAYVKRLNI--------------PSGVVGA
CRLDLAYEHFKEKPHLFQFVPNEKQVK--AANQLLKSIPHGDGSRRVDGVPVFSAQNLDI
AIATTDGIKWYTPYFFDKNMLDNILEESVDQHFHALIQTRHMQRRRDVIDDNVAA----E
VIEEMGDSLLEPPEVQEVLDEMGH-PAIP---------LSVIS-KAA-------------
----------EIQLLYAVDKVLLGNRWLRKATGIQPKFPYLVDSFERR-SASSLRRALES
TSCLANS-KI--------DDSTSEHKLKD-------------NVQTD-HEQR--KDLRLP
FGDWFSHPWLKKHS---KSERESDTRK--EGLSKDCLKWKSESN-----PFLPKVTMVGV
STG----DAG-QLSKSSLKK---TMEDLTKELEQTDEANDSFISNSSSEFKVN-----DR
DPLFVANV-------------------------------------------GDYYSGM-A
KTG----ISR----------------
>Malus_domestica_gnl|BL_ORD_ID|44230 _0000777828|PACid:22664215
MASP-----------------S-EPPHTRQQLRP--SITHLVH-----------------
STTSNL-----------------LSLLAS--PKTT--PSP-SLSTTP------PEIRVAL
FLPNLPK-------PL--------AF---QPDS------KLSAMKGVASSPESTSGFPST
VRIAGLNSNIK-----GSGGPAFVGQVFSMCDLSGTGLMAVS-----THFDIP-FISKRT
PEWLKKMFKSITNSERNGPVFRFFMDLGDAVTYVKRLNI--------------PSGVVGA
CRLDLAYEHFKEKPHLFQFVPNEKQVK--AANKLLKTMPQSGRCKRVDGVPVFSAQNLDI
AIASSDGIKWYTPYFFDKNMLDNILEESVDQHFHSLIQTRHTQRRHDVIDDNIPA----E
VIEEMGDNLWEPPEVQEVMDEIGN-SGIP---------LSVIS-KAA-------------
----------EMQLLYAVDKVLLGNRWLRKATGIQPKFPYMVDSFERR-SAASFLRASQS
ARCLTNG-EAVNDNEDSLDCSTSKIKSKD-------------DIHTN-KGNK--TDLRFP
FSDWFSHLWSKQKD---QNEELS----------KERIEQSTLQN-----PNLPKITMVGI
STG----AAG-PMSKANLKK---TMEDLTKELEQTDSGNA-FGSDTGNELRFE-----DR
DPLFVANV-------------------------------------------GDYYSGM-A
KTG----SAKWVRGGNN---------
>Prunus_persica_gnl|BL_ORD_ID|26753 _ppa003928m|PACid:17667413
MASP-----------------T-EPAH-KKQARP---ITHLVH-----------------
STAANL-----------------LSLFAS--PKTT--PS------TP------STIRVAF
LFPNSPK-------PL--------AFHSAQPDF-------KSAMKGVESSSESNSGFPST
VRIAGLNSNIK-----G-GGPAFVGQVFSMCDLSGTGLMAVS-----THFDIP-FISKRT
PEWLKKMFASVTNSERNGPVFRFFMDLGDAVTYVKRLNI--------------PSGVVGA
CRLDLAYEHFKEKPHLFQFVPNEKQVK--AANKLLKAMQQNGRCKRVDGVPVFSAQNLDI
AIASSDGIKWYTPYFFDKNMLDNILEESVDQHFHSLIQTRHMQRRRDVIDDSLPA----E
VIEEMGDNLWEPPEVQEVMDEMGN-PGIP---------LSVIS-KAA-------------
----------EMQLLYAVDKVLLGNRWLRKATGIQPKFPYMVDSFERR-SAASFLRASQS
SNRLANR-EAVNDNKDSVHCSTSEVKLND-------------DIQTN-KGNK--LDLRFP
FGDWFSHLLLKQKD---QTEELS----------KECVELSSQQN-----PNLPKITMVGI
STG----EAG-QMSKATLKK---TMEDLTKELEQPDAGNA-GGSDMSNELRFE-----DR
DPLFVANV-------------------------------------------GDYYSGM-A
RTG----SARWVRGGNN---------
>Carica_papaya_gnl|BL_ORD_ID|1469 _evm.model.supercontig_107.127|PACid:16405310
MASA-----------------TDQPQHNFHHR-----IANLLH-----------------
ATSSSL-----------------SFLLPS--PKTA--P----YPPSP------PKLCVPF
KFADSPVL------PL------TSVFESPQSDSVS----SKSTIKGV-SSAESNSGFSSA
VRIGGLNSNGK-----A-SGPAFVGQVFSMCDLTGTGLMAVS-----THFDIP-FISKRT
PQWLKKIFATITKSERNGPVFRFFMDLGDAVAYVKQLNI--------------PSGVVGA
CRLDLAYEHFKEKPHMFQFVPNERQIK--AANKLLKKIPQNDGRTKVDGVPVFGAQNLDI
AIATVDGIKWYTPYFFDKNMLDNILEESVDQHFHSLIQTRRIQRRRDVVDDSFAA----E
VIEEMGDNSWEPPEVQEVLNEIGH-PGIP---------LSVIS-KAA-------------
----------EIQLLYAVDKLLLGNRWLRKATGIQPKFPYLVDSFERR-STASFLKASKP
TNCLTDF-EA--------GLDTSGVELDD-------------KFQGN-HRET--KDFQLP
IGDWLNHSWLKQGQ---KHQMLADTGY---------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------
>Vitis_vinifera_gnl|BL_ORD_ID|19207 _GSVIVT01028824001|PACid:17835832
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------MCDVSGNGIMAVS-----NHFDIP-FISKRM
PQRIKKMFATITKSDKNGPVFRFFMDLGDAVRYVKKLNI--------------PSGGVGA
CRLDLAYGHFMEKPHLFRFVPNEKQVK--AANKLLKKIPQNGGRKRIDGVPVFTAQNLDI
AIATTDGIKWYTPYFFDKHTLDSILEQSIDHHFHHLIQSRHVQRRRDVIDDNLAA----E
VLEDNAESLWEPPEVQEVLDEVGH-PGIP---------LSVIS-KAA-------------
----------EMQLLYAVDRVLLGNRWLRKATGIQPKFPYMVDSFEKR-SAASFRRASPS
KRFVASP-EMGNDNKDTEELGPSDPKLED-------------NTQRD-QGQN--SASWFP
VWDLFNHPWSNKRQ---EPQNRSNARI--EDASREHIKQELQLA-----PFLPKITMVGI
SAG----ESG--MSKVNLKK---TMEDLTKELEQADQENA--VGCINSEFEVE-----NR
DPLFVANV-------------------------------------------GSYGSGL-V
ARS----PVPSVRGENN---------
>Eucalyptus_grandis_gnl|BL_ORD_ID|2953 _A02719.1|PACid:23564674
MAVS-----------------PEPPRKHRHHPNP---LSHLLN-----------------
---STL-----------------LPLIPN--HKAA--PPSLVSPPPP------PKLLLPV
RLPP----------ALSIASPSDSAPPPPHPTPLKP---APEVKAPAEPGAAAAGAFPST
VRISAIKSNGK-----G-RGPAFVGQVFSMCDLSGTGLMAVS-----THFDVP-FLSKRT
PEWLKKVFASITKSERNGPVFRFFMDLGDAVTYVKRLNI--------------PSGVVGA
CRLDLAYEHFKEKPHLFQFVPNEKQVK--AANKLLKTISQGNGNRQIDGVPVFSAQNLDI
AIATSDGIKWYTPYFFDKNMLDNILEESVEQHFHSLIQTRHMQRRRDVIDDNLT-----E
VADDVGDSLWEPPEVQEVLEEMGH-PGIP---------LSVIS-KAA-------------
----------EMQLLYAVDRVILGNRWLRKATGIQPKFPYIVDSFERR-TAASLVRASDL
THYLGDR-GMKTDESS--QESTDKLALEE-------------NHHVD-LGQK--ADFRFP
FGDWLRHPWSKEQQ---KLQKEVGARHRLESLTGEPVKQKLQPN-----PFLPKITMVGI
SMG----EAG-QANKATLKK---TMEDLTRELEQTDHGNA--AGNIAD--VSE-----DR
DPLFVANV-------------------------------------------GDYYSGL-A
KTG----SARLIRRSEAKKQQ-----
>Glycine_max_gnl|BL_ORD_ID|45053 _16g29580.1|PACid:16303315
MALP-----------------SEPHRRRRHNHNH---ISTFLQ-----------------
STASNF-----------------ASLFN---PPNP--PSL-TLPHPP------TSVSLPL
FFAP----------PLS----------------------GSSTVDSA--TSKPAHPPAKS
VRIARLGANGK----GG-GGPVFLGEVFSLCDLSGTGLIAAS-----KHFGIP-FISERT
PEWLKKIFAPITKSERNGPVFRFFIDLEDAVSYVEKLNI--------------PSCVVGA
FRLDLAYKQFKEKPHLFQFVPNEKQVK--AANKLLKTISEHGDKKKVDGVPVFGAQNLDI
AIATTDGIKWYTPYFFDKNMLDNILEDAVDQHFHNLIQTRHMQRRRDVVDDNLAA----E
VIEEMSDRLGEPPEVQELLDEMGH-PSIP---------LSVIS-KAA-------------
----------GLQFQYTVDKVLLGNRWLRKATGIQPKFPYMVDSFERR-SEASLLRATES
SSCLENS-KVEDDRQISECLDSSNCSLDG-------------NTEAI-KQPS--PSLSLP
FGNWFHHLWPKQCR---EKASSSR---------KGVNKEEMKPR-----PILPKVTMVGL
STE----EAG-QTSKANLKK---TMDDLTRELEKTELDIM--TDGGSKECKVE-----DR
DPLFVANG-------------------------------------------GNYYSSMRR
KPG----SGR----------------
>Phaseolus_vulgaris_gnl|BL_ORD_ID|6869 _091010222m|PACid:23537334
MALP-----------------SEPHRRRRHHNNH---IATFLQ-----------------
STASNF-----------------ASLFN---PPNP--PSL-TLPHPP------SSLSLPL
FFAP----------PLS----------------------ASNALDSAATASEPARPAAKS
VRVARLGVNGK---GGG-GGPAFVGQVFSMCDLSGTGLMAVS-----THFDIP-FISKRS
PEWLKKIFAAITKSERNGPVFRFFIDLGDAVSYVKKLNI--------------PSGVVGA
CRLDLAYEHFKEKPHLFQFVPNEKQVK--AANKLLKAISQHGIRKKVDGVPVFSAENLDI
AIATTDGIKWYTPYFFDKNMLDNILEEAVDQHFHTLIQTRHMQRRRDVVDDNLAA----E
VIEEMGDNLGEPPEVQELLDEMGH-PSIP---------LSVIS-KAA-------------
----------ELQFHYTVDKVFLGNRWLRKATGIQPKFPYLVDSFERR-SEASYLRATES
RRCLENP-KVEDDGKISECVDSSDCGLDD-------------NTEAI-RQPS--YRLSLP
FGNWFNHLWPKQCH---EKARSFK---------KGVNKEDMKPT-----PFLPKVTMVGL
STE----EAG-QMSKANLKK---TMEDLTRELEKTELDNM--AGGGGKECTME-----DR
DPLFVANV-------------------------------------------GDYYSSL-G
KAG----SGRWIRGGSN---------
>Cucumis_sativus_gnl|BL_ORD_ID|17033 _192940.1|PACid:16968025
MAFQ-----------------I-EPSSEPHEQNPLTFITHLFH-----------------
SSTSNF-----------------STLFAN--PQSI--PPF-PFQSSS------SKLCIPV
AFPPSPKP------PF----LSHSGFHSIHYDLDSP---KSAAVKGLSSSPNFDSGFPST
LRISGLNSDGK-----T-GGPAFVGQVFSMCDLSGAGLMAVT-----SNMNIP-FVSKRT
EEWLKKMFSTITKSKRNAPIFRFFTDLGDAVTYVKRLNI--------------PSAVVGV
CRLDLAYEHFKEKPHLFQFIPNEKQVK--AANKLLKGLPQNGGSKKIDGVPVFSAQNLDI
AIATTNGIKWYTPYFFDKNMLDNILEESVDQHFHALIQTRRLQRRREIVDDNAAA----E
VLEEMGDSLLEPPEVQEVMDEMGN-PGIP---------LSVIS-KVA-------------
----------EMQLLYTVDKVILGNRWLRKAVGIQPKFPYMVDSFERR-SAASLLRIQES
ASGLTNS-ESVEETKELQCYSSSPLNTED-------------NREAN-QEPK--QHSFNP
FRNWFGHLWSKQRQ---RDD-----------FSQERTKQNVQIS-----PFLPKITMVGI
STG----DSG-HTSKANLKK---TMEDLTRELEHIDQGNA--ASHNEYEFNNE-----ER
DPLFVANV-------------------------------------------SHFSSGL-S
KAG----SARWVRGND----------
>Linum_usitatissimum_gnl|BL_ORD_ID|5439 _10027537|PACid:23144619
MATS-----------------A-EPPQNHHRRHH--PFPNFFH-----------------
SATSAV-----------------LSLLPN--PRTSSAPPI-TSPSSSPP----PHVCIPF
NFVDSSY-------PLNQQSVIRSPLESGQSDSVSS---TSATVKGL-SSAESNSGFPST
VRISGLNSDGK-----G-GGPAFVGQVFSMCDLSGTGLMAVS-----TYIELP-FINERT
PEWLKKILAPVTKKDKNGPMFRFFMDLGDAVSYVKKLNI--------------PSGVVGA
CRLDLAYEHFKEKPNLFQFVPNKEQVK--AAKQLLKTMPESDGKTTVDGVPIFSAHNLDI
AIATSDGIKWYTPYFFNKSMLDGIIEDSVDQHFHTLIQTRHMQRRRDVVDDNFAA----D
VMEEMADSLMDPPEVDEMMDEMGN-VGIP---------LSVIS-KAA-------------
----------EMELLYAVDKVLLGNRWLRKATGIQPRFPYVVDSFERR-SAYSFKKASKT
TSLSHVS-QA--------GGSDSEVEPEN-------------NTQANSYEER--PDLRLT
FGDWFG-LRLKQPF---KPARETESRT--EGSSKEQMQQKLVDN-----PLLPKITMVGI
STG----ETG-KVSKASLKK---TMESLRKELEQADQGKTSSSDNGDGDFKIA-----DR
DPLFVANV-------------------------------------------GDY------
--------SRWIRRGMS---------
>Mimulus_guttatus_gnl|BL_ORD_ID|16966 _mgv1a003806m|PACid:17686364
MASA------------------ADKSHRRHHPPP--HLSRFIS-----------------
TASTNL-----------------SSFLTLKSPSPA---------SSS------SKIHLPL
LLADSDSFLSLVSRSESAQPDSTPSAPSRSPPSSSS---SSSSMKST-PSSDSVSKFPPT
VRI----TTGK-----G-GGPAFVGQVFSMCDLSGTGLMAVS-----THFDIP-FLSKRT
PEWLRKMYAAVTKSERNGPVFRFFMDLGDAVSYVKQLNI--------------PSGVVGA
CRLDIAYEHFKEKPDTFQFVPNERQVK--EANKLLKSFPHSDGKNKVEGVPVFSAQNLDI
AIAKKDGIKWYTPYFFDKSMLDNILEDSVDQQFHSLIETRNAHRRRDIGDDSLPA----E
AIEEMGESMWDPPEVQEVLDEIGH-PGIP---------LSVIS-KAA-------------
----------EIQLLYAVDRVILGNRWLRKATGIQPKFPYMVDSFERK-TAASFLRAKTS
N-LISNS-EISEDAQLD-NRTTLDVEPKE-------------KTHDK-QEQKHLINSQFP
FGDWLSHPWLKQPE---NQQNLSETRH--PNSTTQNRGQVAQSS-----PFLPKITMVGV
STG----EPG-KMGKAALKK---IMDDLTKELEKVEQVNQ--ANSNSSEYMAD-----ER
DPLFVANV-------------------------------------------GDSYSAV-S
KTG----TSWRVRGGSF---------
>Aquilegia_coerulea_gnl|BL_ORD_ID|35613 _013_00192.1|PACid:22058731
MAISP----------------SESHLNYNNNNNN---FTRFIQ-----------------
STSSSF-----------------FSLFN---PSPL--PPL-SSSSSSFPFCSSSSICVPL
LFSDTPPRILSLSTTLSTNSSSSSTTPSSQNDPLS----LNSQI----KTRSPSSKFPSS
IKISGLNSNPN-----G-SGPAFVGQVFSMCDVSGTGLMTVS-----THMEIP-FISKRI
PEWIKSMFSVFNKSENNGPVFRFFMDIGDAVSYVKRLNI--------------PTGVVGA
CRLDLAYEHFKEKPHMFQFVPNEKQVK--AANKILKKT-QHSEKRIVDGVPVFTAQNLDI
AIATGDGIKWYTPYFFDKNMLDNILEESVDQHFHSLIQSRHMHRRRDVIDDNLTA----E
VVEDNRDNLWEPPEVQEVLDEMGY-PGLP---------MSVIS-KAA-------------
----------EVQLLDAVDKVLLGNRWLRKATGIQPKFPYRVDSFEKR-SAASFRKATEL
TSIASNRIDSCVGSKCENLKGSEEPRLEE-------------NTQSG-QRQP--SEVRLP
FGDWFSHLWSKQQH---KPDEQTR-----LTDSRDKYIEQLPLS-----PLLPKITMVGI
STG----EAG-QTSKASLKQ---TMEDLTRELEQPGQDID---DGGSNEIRHE-----ER
DPLFVANV-------------------------------------------GV-------
--------------------------
>Brachypodium_distachyon_gnl|BL_ORD_ID|2714 _2g07450.1|PACid:21805484
MP-------------------------------SSSSSSNPFH-----------------
SLTFN------------------LPF--PPAPSSCSTSAS-SPPAPA------PHLAFPL
LL------------PVSSASTTSSYSPASHLIPQ--------------PQRLPGERMAGP
AAASGGKGVSAG--KSP-GGPAFVGQVFTMLDPSGNGLMAVT-----SRFDLPHFIAHRT
PTWFKRILSPLKKSE-SSPVFRFFMDLNDSVSYVKRLNV--------------PSGMVGA
CRLDVAYEHFKEKPHMFQFVPNEKQVK--AANKLLKSIPQKSRRKKLAGVPVFSAQNLNI
AVATDDGIRWYSPYFFDKNLLDNILEASMDQHFHSIIQNRHIRRRRDIVDDSLTS----E
ILEESADSLLEPPEVQELMNEIGP-AGIP---------LSVVT-KAA-------------
----------EIQLLDVVDKLLLGNKWLRKATGIQPRFPYVVDSFEER-TALSVDRTATS
SNSCTAS-KDADFFTNDQQSQALEPNVDS-------------GNHRK-HNSRDHGQSHFP
FSNLLPNIWPGHDR---KFKAQEHDNR--FKRYGASMDNDLQAN-----PLLPKITMVGI
SMS----EGG-QMSKANLKK---TMEELTKELEQAGEKTV----------FSD-----EK
DPLFVANV-------------------------------------------GDY-SRI-T
KIS----ST-----------------
>Sorghum_bicolor_gnl|BL_ORD_ID|9318 _Sb03g001210.1|PACid:1960134
MP-------------------------------RSSSSSNPFH-----------------
SLASA------------------FPFFSSSSPSPPA-SASPSPSPAA------PHLAVPL
LL------------PVSSGSASASS----ESRRG--------------PQPLPGARMAGA
AAAGRGNKAGG-----G-AGPAFVGQVFTMLDPSGNGLMAVT-----TRFELPRFLTNRT
PMWFKRMLSPLKKSE-SSPVFRFFMDLNDAVSYVKRLNV--------------PSGMVGA
CRLDVAYEHFKEKPHLFQFVPNEKQVQ--AANKLLKSLPQRSRRKKLGGVPVFSAQNLNI
AVATNDGIRWYTPYFFDKNLLDNILEASMDQHFHSIMQNRHTQRRRDIVDDSLTS----E
IIEESAESLLEPPEVQELMNEIGP-AGIP---------LNVVT-KAA-------------
----------EIQFLDVVDKVLLGNKWLRKASGIQPKFPYVVDSFEER-TAVSIANIATT
S-SLTTS-NDENCCQNNQQTQSSGSSVDN-------------SSYRN-HNNEDHN--HFP
FSNLLPNIWPGHDR---KFKAQESDNK--FSRYDADVKSNLQSN-----PLLPKITMVGI
SMG----DGA-QMSKANLKK---TMEDLTKELEQTSEENM----------FSD-----DK
DPLFVANV-------------------------------------------GDY-SRI-T
KIS----SA-----------------
>Zea_mays_gnl|BL_ORD_ID|9045 _GRMZM2G097959_T01|PACid:20828771
MP-------------------------------CSSSSSNPFH-----------------
SLASA------------------FPF--LSSTSPPP-SPPASPAPAA------PHLAVPL
LL------------PVSSAS---------ESRRG--------------AQPLPGTRMVGA
GATGGGNMASG-----G-GGPAFVGQVFTMLDPSGNGLMAVT-----TRFELPRFLTNRT
PMWFKRMLSPSKKTE-NSPVFRFFMDLNDAVSYVKRLNV--------------PSGMVGA
CRLDVAYEHFKEKPHMFQFVPNEKQVQ--AANKLLKSLPQRGRRKKLDGVPVFSAQNLNI
AVATNDGIRWYTPYFFDKNLLDNILEASMDQHFHSIMQNRHTRRRRDIVDDSLTS----E
IIEESAESLLEPPEVQELMNEIGP-AGIP---------LNVVT-KAA-------------
----------EIQFLDVVDKVLLGNKWLRKASGIQPKFPYVVDSFEER-TAVSIANIATT
S-SLTAS-NDDSSCQNNQETQSSEPSGDN-------------SSYRN-HNNEDHN--HFP
FSNLLPNIWPGHDR---KFKSQESDNK--FSRYDADVKSKLQAN-----PLLPKITMVGI
SMG----DGA-QMSKANLKK---TMEDLTKELEQTSEENM----------FGD-----EK
DPLFVANV-------------------------------------------GDY-SRI-T
KIS----SA-----------------
>Setaria_italica_gnl|BL_ORD_ID|1638 _Si001606m|PACid:19674983
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------MLDPSGNGLMAVT-----TRFELPRFLTNRT
PTWFKKILSPLKKSE-NGPVFRFFMDLNDAVSYVKRLNV--------------PSGMVGA
CRLDVAYEHFKEKPHMFQFVPNEKQVK--AANKLLKSLPQRGRRKRLGGVPVFSAQNLNI
AVATNDGIRWYTPYFFDKNLLDNILEASMDQHFHSIMQNRHKQRRRDIVDDSLTS----E
IIEESADSLLEPPEVQELMNEIGP-AGIP---------LNVVT-KAA-------------
----------EIQLLDVVDKVLLGNKWLRKAAGIQPRFPYVVDSFEER-TAVSIANIATT
S-SFTAS-ND-SCCQNDQQSQSSDPSIEN--------------SYRS-HSNQDHNQFHFP
FSNLLPNIWPGHDR---KFKEQESDSK--FSRYDADMKTDLQSN-----PLLPKITMVGI
SMS----EGG-QMSKANLKK---TMEDLTKELEQTSEKNT----------FGD-----EK
DPLFVANV-------------------------------------------GDY-SRI-T
KIS----ST-----------------
>Oryza_sativa_gnl|BL_ORD_ID|20689 _LOC_Os01g12550.1|PACid:21903161
MPRG-----------------------RSTTTTTSSSASNPFH-----------------
AFAST------------------LPF--LPSPSPSPTSASPSPSPPA------PHLAVPL
IL------------PITSSSSASAAAAS--------------------PESNRGARMA--
AAASGGKAGGGGGLGKG-GGPAFVGQVFTMLDPSGNGLMAVT-----TRFELPQFLASRT
PMWFKRILSPLKKSE-NGPVFRFFMDLNDAVSYVKRLNV--------------PSGMVGA
CRLDVAYEHFKEKPQMFQFVPSEKQVK--AANKLLKSLPQRRRRKKLDGVPVFSAQNLNI
AVATNDGIRWYTPYFFDKNLLDNILEASMDQHFHSMVQNRHTRRRRDIVDDSLTS----E
MMEESADSFLEPPEVQELMNEIGP-VGIP---------LNVVT-KAA-------------
----------EIQFLDVVDKMLLGNKWLRKATGIQPQFPYVVDSFEER-TAAAIDRAATA
SSSFTAS-KDADCFQISKQPETLESDVDN-------------SNRGK-HENSNNGQSHFP
FSNLLPNIWPGHDR---SFKAQGRDRA--FRRCDASINNDLQAN-----PLLPKITMVGI
SMG----EGG-QMSKANLKK---TMEDLTKELEQAGEKTI----------FSD-----EK
DPLFVANV-------------------------------------------GDY-SRI-T
KIS----ST-----------------
>Panucum_virgatum_gnl|BL_ORD_ID|40717 _Pavirv00055971m|PACid:23796854
MP-------------------------------RSSSSSNPFP-----------------
SLASST-----------------FPF--LSSSSSAATSSTTSPAHPA------PHLAFPL
LL------------PVSSASSSA------EPRRG--------------PEPLPGARMAGA
GAAAGGKPGGRI-KGGG-GGPAFVGQVFPMLDPSGNGLMAVT-----TRFELPRFLTNRT
PAWFKKILSPLKKSE-NGPVFRFFMDLNDAVSYVKRLNV--------------PSGMVGA
CRLDVAYEHFKEKPHMFQFVPNEKQVK--AANKLLKSFPQRGRRKRLRGVPVFSAQNLNI
AVATNDGIRWYTPYFFDKNLLDNILEASMDQHFHSIMQNRHVQRRRDIVDDSLTS----E
IIEESADSLLEPPEVQELMNEIGP-AGIP---------LNVVT-KAA-------------
----------EIQLLDVVDKVLLGNKWLRKAA----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------
>Physcomitrella_patens_gnl|BL_ORD_ID|36425 _Pp1s68_153V6.1|PACid:18072962
MGRNRDTCNVPGCSKDEKPCLVTGPKIVSFKLPNPALFSSWVQ-----------------
TVTSNLAWTVQSFQTLKTDGLNCLSLLVEHKPMVSPLPVPYLAL---------NNLIFPV
PSST-----------------------------------SSVQVCQKAVSSIPQDHFSKG
NAVNEKGEVSS-------TGPAFIGQVYTMCDASRQGLIAVRPSDVLKKIKVP-PYMKLM
EKAYERAMNVLFTDDMKGPVFRFYFNKDDAAEYVRRLNI--------------TGSAVGP
CSLDAAYKYYKSKEGMFKFIADQRQVK--VAKELVRRERGDKAANKLKGVPVFTARNLTI
ALSTPQGVRWFRPYFFNKKQLDSLIGHSVDHYYEMLISARRAQRYSQIAENNGDAFAGGE
SMDDELDGLMDPPEVQELMEELGQ-GGGG---------MEFVGLKVL-------------
----------EAQFMDLADRVLLGHQWSRRMIHLQPRFPVIVDSFERLISASELDHSSES
EGSVTSS-RNSFAKKEGTQEKSQRGQGDEGMSISGRDERSASNDSSESVSKEYSQSSPNS
LFNLFKKKWGANANLVFKRKDSGNAEILEEDSDSEYLQETAQKDPPGKIPFQPKLTMMGI
SMNVNKVEGGLQQAMAAAAK---DVEDRLRKGEGSGP---------------------DH
GPLFIANL-------------------------------------------G---SGI-P
QWGRPVSASSGVLDDDAE--------
>Selaginella_moellendorffii_gnl|BL_ORD_ID|1621 _424522|PACid:15402899
ME----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------IGS
VPLHLAYKFFKERPSLFSFIPSKKQVD--LAKTIIKKEQGGKAAQQFQGVPVFTSHCLSI
LVVGPSGARWFRPHFFKKEELDGVIRSSMEHHYQSLIRNRRARRHNQVSD--FPS----D
MAEDDLE-MLESQDIQDFVEDMDEWSSVL---------ESIMA-KAA-------------
----------QMYFQDTLDRAIFGNKWCRMLAGIQPSFPILVDSFERR-VTSETENAVVS
HHEQKK-----------------------------------------------------P
HKDW--------------------------------------------------------
-------DSTCQLKRALIR-----------------------------------------
------------------------------------------------------------
--------------------------
>Chlamydomonas_reinhardtii_gnl|BL_ORD_ID|12022 _13.g593950.t1.2|PACid:19870334
MA-----------------------------LQSRHGRATFLHAYWRERALRPCLRRPVL
TVSAVAASSSAAEGRGKASGLGSLTFLDFVVPFST--PLAAAIATGVYTGAVGADLAWPL
RALLVG------------------------------------------------------
------------------GGPLLVHLLFPAVDWALGPSRALA---------------ERQ
QQQAQQQALGIKAPGADHFLSRALPCLAVAVQLLVLLATYGALAAAAGAPAPPLAGAAGA
AAAGLQQQQLLLLPLLVTSLALSAGMAQAASHELLHSRH-----------PVHLAAAWLF
LTT-----HWWYPYF----------RAHHQHHLAVCTPADYASAPRGL---SLAA----Y
LPRYIGSSYTEAWQLAAA--ECRR-AGHPVFSTHNSCLVALVA-QAALTAALGLALGPAA
ALLHGAVCAVLLTYMSVLDYVL--HYGLRRP-------PLVVAAAAAA-TAGGVGGGADA
AVSTVADSREVTGVAPAAAGVAAAPAAGSG---------AVR------------YAPVTP
FNSW-SSLYPLENALFFNVLIHGDHHMTASRSYAWLVPAPSSPTFPAPINALALATFVPP
LWRAAMHERVDQANSANLRHLAATGVPVAAEQGAAEQGAA--------------------
-----------------------------------------------------------E
QVA----AEQVAAAGTA---------
