>(0)Porphyra_purpurea_gi|11465684|ref|NP_053828.1| hypothetical protein PopuCp033 [Porphyra purpurea]
M-----------------------------------------------------------
-----------------------------------------------YCSQAITQTSRLP
VSNNFYCKKTFFSSVNSNYQNLSQMQSWSSLKVLAFGLPDLHSIPVNLNNSFQEAIVIST
INDNNIFADVTNSWIKMHKDKNHYSLFYKEIFKALLTKQIHVIDSPIGSKDIDNK-----
----------------------------------------------------------II
LIQQYIWKKGLKSPQFNSIARLNK---------------------NVDISNISTKFIMEQ
------------------LST--SPVFVVK-----NGLNEIILG----------HPLSRI
RRTA------------------FNQIASSLSNLF-HQPIATSP--ISNGLFFFHPDDA--
--------IEFKNFVQSKAPEACKDMDI--------------------------------
-----KIQPVGLH-----------------------------------------------
---------------------VAYKMNR-----NFSSDIQFRFVPDFKE-VGDLIFRHQQ
A-KNLHFHENQYYGK------------------------------NFFQGQPIYMIQP--
------------------------------------------------------------
--------------------------------IIIKHRN---------------------
----------------------GRISIIKFTGANDDREVVFTNLEAANKS-WANFIKRTP
YLKRLK------------------------------------------------------
------------------------------------------KPNLLVYNLESFL-----
------------------------------------------------------------
KDKEVLHK-------------------ADLTKFIVVTNKSAYITTKESVTLPY-------
------------------HNGLSKHLELNVKPKLFFVKLWIRRLLFTLTYE---------
------------------------------------------------------------
----------------------------------
>(9)Porphyra_umbilicalis_gi|378787257|gb|AFC39888.1| hypothetical protein [Porphyra umbilicalis]
M-----------------------------------------------------------
-----------------------------------------------YCSQTFXXXXXXX
FSNNFYCKKKFFSSVNSXXXXXXXXXXXXXXRVLAFALPELSSIPINFRNSFQEAIVIST
IHDNNIFADVTNSWIKTHKDKNHHSLFYKEIFKALLTKQIHVTNSPIELKNIDNK-----
----------------------------------------------------------II
SVQKYIWSKGFKSPQFYSSMGGDN---------------------YVNTSSISTKFIMEQ
------------------LSS--SPVFVVK-----NGFNEVILG----------HPLSRI
KRTA------------------LKQIAFSFSNVF-HQPVATSP--TSNGLFFFHPDDA--
--------IEFKNFLQSKSFEASKHMGI--------------------------------
-----KIQPIGLH-----------------------------------------------
---------------------VAYKMNR-----KFAGDIQFRFIPDFKE-VGDLIFKHQK
A-KNLIFHENQYYGK------------------------------DFFQGQPIYMIQP--
------------------------------------------------------------
--------------------------------INIKHRN---------------------
----------------------GKISTIKFTGLNDKREVVFTNLEAANKS-WTNFIKTEP
YLKRIK------------------------------------------------------
------------------------------------------KPTLLVYNLESFL-----
------------------------------------------------------------
KDKEILYR-------------------ADLTKFVVVTNKSAYITTKESIAIPY-------
------------------SKSLSKHLKLNIKPQLFFIKLWMRRLLSTLMCE---------
------------------------------------------------------------
----------------------------------
>(18)Gracilaria_tenuistipitata var. liui_gi|51210013|ref|YP_063677.1| conserved hypothetical plastid protein [Gracilaria tenuistipitata var. liui]
M-----------------------------------------------------------
------------------------------------------------------------
------HHINIHLCSLLSAHNIFSSRRDPHFSAINQSLVIRPFIGKLINKYWQERIFLSV
PNISSEKYINQLKLEGILIYKNEQKKFLLDFSKALLSGRIETSLNSSILESDSNSY----
----------------------------------------------------------IS
CIWKKGFNFSIPTQFILSFFNQNN-----------------------FVLNKQQVTFLKQ
------------------LKHQPLPLFTVT-----NNSNQIVLA----------DSTENI
ANNSNF----------------LDKIHKWYYNKF-LFNDKKQA--IYYGLFFMHPMDA--
--------LEYIKHIKSHYEFSKEKHEF--------------------------------
-----HLFSSYLS-----------------------------------------------
---------------------SYYKLTR-----TNLRNIQFRIIPDLQE-ISRLLYQYRY
Y-PNLRFHRNQIYSK------------------------------NSFRGQPLYIIEP--
------------------------------------------------------------
--------------------------------FLAYRKIDNQKKLLVY------------
----------------------SYNYRSNSDHNIIQSEAVFTNYTTLIKA-WHKFKQKHT
DYEISS------------------------------------------------------
------------------------------------------KPKVTVYNLEDFI-----
------------------------------------------------------------
KDNEYKSK-------------------IEEKNILFIPSQASYQFIKNYQFVNK-------
----------------------QNKIKQIFSNKFLSFKILSQRIFWSLTSRQPINW----
------------------------------------------------------------
----------------------------------
>(27)Rhodomonas_salina_gi|149072084|ref|YP_001293517.1| ORF403 [Rhodomonas salina]
M-----------------------------------------------------------
------------------------------------------------------------
----------------------NNILEQ-INEILSPPSIQVQSTQV---NEDPVSKLLSS
LYSCRGIEVN--IKSKDDVFVEDFFQGSNRNAVNVNIDEDLK------------------
------------------------------------------------------------
-----LFSKPEKIPNFFNNQRQAE------------------------FPTQQQKAIITK
------------------LKK--VPIYTVV-----NGYNEIVVA----------SPRSMP
PKSS------------------IEWLYDKYYDNF-LWRGDKGA--VNLGLFFVNKEDA--
--------ETYLQEVCKKDPKGAENIGL--------------------------------
-----SVKTVGLD-----------------------------------------------
---------------------TFYELNR-----TSKPKMQARLIADLEE-IDLLLNEYSK
S-KILTFHPKQKYKK------------------------------QWFQGNPIYLIKI--
------------------------------------------------------------
--------------------------------NENLNKLEKNKFTLSQ------------
--------------------------YNFDESSNNDRKIVLFRKEDAYKV-WNLYKIKNK
ELSLPD------------------------------------------------------
------------------------------------------KPSLEIYNLENYL-----
------------------------------------------------------------
LDLEKADV-------------------SLTEKTVFVPPYESYIHSKRLIEESKIEK----
------------------NTSIKETIDQYVTTKVKSLQRFYKGMIWLVTSDTLPSEDNSW
------------------------------------------------------------
----------------------------------
>(35)Guillardia_theta_gi|11467652|ref|NP_050704.1| hypothetical protein GuthCp045 [Guillardia theta]
M-----------------------------------------------------------
------------------------------------------------------------
---------------------------I-SNFNLSYSLKHVSSCFIFSDNNDPINKLINS
LNSNLNLKVR--LPSDYNLLADEFLPPNQSVLIDFKDIDDN-------------------
------------------------------------------------------------
-----WFSKAKHLPSLFSNRRSPY------------------------FPTLAQKHILES
------------------LKT--VPVYTIV-----NDLNEIVIA----------SPRDLT
NFNS------------------FNWVKRFYNDWF-IWEKDEGN--VNIGLFFMNREDA--
--------ELYLHQICLKDPRGVENVGV--------------------------------
-----NVKTISLD-----------------------------------------------
---------------------TFYKLNR-----LSPPRLQFKLIADLQE-IKNILNVNSN
S--RVSFHPKQKYDK------------------------------NWFKGIPIFIYSP--
------------------------------------------------------------
--------------------------------TVT-------------------------
---------------------------NLDWTLKSNKNMIFFQEMMHIMF----------
------------------------------------------------------------
---------------------------------------------------QKIY-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------
>(42)Cryptomonas_paramecium_gi|283794866|ref|YP_003359219.1| hypothetical protein CRPAC_p002 [Cryptomonas paramecium]
M-----------------------------------------------------------
---------------------------------------------------------YKE
YMNKINILLSMMLSNILSRNANTVLSPEYPGDHRPEVIEKLLSEDVKVKLRREFDHKKPR
PKKVQQIKLV--------------------------------------------------
------------------------------------------------------------
---------ENTPRASLSKGKKDP------------------------FIESIQTDIGGM
------------------LRH--VPTYMVT-----TKEGDIVVSIATVSEDILPDPRTKK
PV---------------------------------PQPKKKER--EPLLLFFMGKDEA--
--------KLYLNKIFNDEPEISEQLGI--------------------------------
-----RITKTTLE-----------------------------------------------
---------------------TFYRVNR-----DEKCKVDARLISDLEE-SHFMLSTRRK
N-EFYTINPKQRYKR------------------------------NFFQGTPIYILKH--
------------------------------------------------------------
------------------------------------------------------------
----------------------TIGPYVNDSQYTLRGRQIYFKWSDALSSWEKSVTSEHM
KKNI--------------------------------------------------------
------------------------------------------KPNIEVYNLENLL-----
------------------------------------------------------------
QEMEEDDE-------------------EDFSAYTFMPPIIKNEVPDNPIKKK--------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------
>(49)Emiliania_huxleyi_gi|71842290|ref|YP_277378.1| hypothetical chloroplast RF80 [Emiliania huxleyi]
M-----------------------------------------------------------
------------------------------------------------------------
-----------------ENTQAPIQKSP-LNVLNPPEFQEIDTISFLTDLYSYPPKFNVS
VGETNVNNFN--GQLKNKTRPANSL-----------------------------------
----------------------------------------------------------RV
LENKLSYKITDYINGFLNKNFTSN------------------------FYKIQTKPIQKA
------------------LKS--VPVYIVV-----NGRDEIVLF-------------HKE
NLNTKFSRGIWDKSFIASPRRELAKIFYDFCGAF-QDNGNTRS--SDLGLVFFNYEDA--
--------EVFRDDVLKQDTRGSQTVGL--------------------------------
-----TIHCVSLE-----------------------------------------------
---------------------SAYNLLR-----SPHPGFDLRFVPNLKE-VSSLADQTDN
A--RFIFEEKQEVKDAVEQSFGYTQEVVNKSTTSPTIEK------TCVQGIPIYLIQT--
------------------------------------------------------------
--------------------------------QTTPRNFIWHNFQLAA---------EKI
DTILNTSTFGRFSRDQGSKIKIFRAGANKLQNSDKVSNYVFFSQQQALAF-CQQNSRYLI
RQNEKSWRLQFDALIR--------------------------------------------
------------------------------------------KPTIFVTSLENLL-----
------------------------------------------------------------
EHWENHLL-LETHSQNGGEKISEPSQLFAAKETHFISPSSTKEYFETL------------
------------------NDEEIEGLSTPVTKLVRALKVRRNVFTFSLRYLFSRGGSF--
------------------------------------------------------------
----------------------------------
>(58)uncultured_prymnesiophyte C19847_gi|299890949|gb|ADJ57448.1| hypothetical chloroplast protein RF80 [uncultured prymnesiophyte C19847]
M-----------------------------------------------------------
------------------------------------------------------------
--------------VLLNRSNELSFREN-FFQNLPFFNKQQASLSLFKGVYSYPGKLKIK
WNSLDELKNE--SFQTSTYDLGTDKLPFVDLTEDYLLNSSPDEQDITQI-----------
------------------------------------------------------------
-----NYSRQSYKDGYKAKRNSAD------------------------FYRNNTKDVQNA
------------------LKG--IPVYVVL-----NGWNQMTLT----------KPTEGF
SHNAPYLRELYPTPTFLKTR--FKKQAYDFCGAFGSIGHEN----LNKGFFFLNYQDA--
--------QEYLRAIVQNDVDGTELVSL--------------------------------
-----SVHCFGLD-----------------------------------------------
---------------------TAYRIMR-----QQQNQIDFRLVPDTKQ-TRKLLTRHLG
T-PDLIIDKTQQQIRLRRRSVNFLPYLGGELTEKFSPFSSFLQNNEYFKGVPIYIVQI--
------------------------------------------------------------
--------------------------------RDTPRDM------LRSQYFNVVTVGDNL
IGKVKQLIGFGVGFGQNGIMQGSLMDVKSASPSDVRTNYVFFDKGQAARF-QRKQGRKTV
RYMGSRSLPFMRGIIS--------------------------------------------
------------------------------------------KPKIFVHNLEDFL-----
------------------------------------------------------------
ELWEENIVNKQIDNPQNNI--------FQAKDTVFIPSRTAQNELKQFPRPEGMS-----
------------------KEQIQQKVKNNLSLKYRTLQNFVGFFFSAM------------
------------------------------------------------------------
----------------------------------
>(166)Cyanidium_caldarium_gi|11465478|ref|NP_045131.1| hypothetical protein CycaCp114 [Cyanidium caldarium]
M-----------------------------------------------------------
------------------------------------------------------------
---------------------FPNIVNL-KIWPVELAYSSLNKDFVSLSAEKEINNKIEE
------------------------------------------------------------
-------------------------TIESHCLKKQGIRIRSPYGLRTLKVLQACPKKEDL
VLQRGCIKIALPFSGILSSYQSKC--------------------QYM---QGLNNHLRNT
------------------LNN--VVVYVVT-----NSSDELVSV----------ASRSLM
YRGRGISL--------------VDLIIDLYYRYF-VLDKYNLT--NVVGFVFMDYEDS--
--------NLFLRTVLQNCYDKDK--KA--------------------------------
-----AVQKLKLG-----------------------------------------------
---------------------EACKLFF-----NPLNGIKVRFIPSSKE-LEKLFSVYQN
EFDHISLHADQRFTP------------------------------NSYSGVPVYLVSN--
------------------------------------------------------------
--------------------------------KWLTNKS---------------------
-----------------------LVTLNPSLSTLLSHDFVFFTYLDALKF-CNIIEDLL-
------------------------------------------------------------
---------------------LYGNKEVES------------KPSIVLFNFEEIL-----
------------------------------------------------------------
LHLKDVA--------------------SLQTKVHFLPPYSVCDNEKLILAELKKVGSSTN
PASTTWEYLSVILNSDLNNKN---------------------------------------
------------------------------------------------------------
----------------------------------
>(68)Arabidopsis_thaliana_gi|15234162|ref|NP_195061.1| Tic22-like protein [Arabidopsis thaliana]
ME----------------------------------------------------------
------------------------------------SSVKPNPFLS---FSSFIHHQCTR
FSSDLSARIEDT-KRFAETL---ATRRF-SLPTPPPF------ASVSQ------------
------------------------------------------------------------
------------------------------------------------------------
----------------------SK--------------------SGTPTTTLSPSLVAKA
------------------LAG--TSVFTVS-----NTNNEFVLI----------------
------------------------------------SDP-TGG--KSIGLLCFRQEDA--
--------EAFLAQARLRRRELKT--NA--------------------------------
-----KVVPITLD-----------------------------------------------
---------------------QVYLLKV--------EGISFRFLPDPIQ-IKNALELKSS
------------GNK------------------------------NGFDGVPVFQSEL--
------------------------------------------------------------
--------------------------------LVVRKKN----RRYCP------------
---------------------------------------VYFSKEDIERE-LSKYTRAS-
--------------------------R----G----------------------------
------------------------------------------DQQIMVGSLEDVL-----
------------------------------------------------------------
RKMEMS------------------EKNSGWEDVIFIPPGRSYAQHMQDLIKE--------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------
>(121)Arabidopsis_thaliana_gi|334187125|ref|NP_001190901.1| Tic22-like protein [Arabidopsis thaliana]
ME----------------------------------------------------------
------------------------------------SSVKPNPFLS---FSSFIHHQCTR
FSSDLSARIEDT-KRFAETL---ATRRF-SLPTPPPF------ASVSQ------------
------------------------------------------------------------
------------------------------------------------------------
----------------------SK--------------------SGTPTTTLSPSLVAKA
------------------LAG--TSVFTVS-----NTNNEFVLI----------------
------------------------------------SDP-TGG--KSIGLLCFRQEDA--
--------EAFLAQARLRRRELKT--NA--------------------------------
-----KVVPITLD-----------------------------------------------
---------------------QVYLLKV--------EGISFRFLPDPIQ-IKNALELKSS
------------GNK------------------------------NGFDGVPVFQSEL--
------------------------------------------------------------
--------------------------------LVVRKKN----RRYCP------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------VGSLEDVL-----
------------------------------------------------------------
RKMEMS------------------EKNSGWEDVIFIPPGRSYAQHMQDLIKE--------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------
>(160)Arabidopsis_lyrata subsp. lyrata_gi|297798602|ref|XP_002867185.1| hypothetical protein ARALYDRAFT_913087 [Arabidopsis lyrata subsp. lyrata]
ME----------------------------------------------------------
------------------------------------SSVKPNPFLS---FSSFLHHHCTR
FSSDLSARIEDT-KRFAETL---ATRRF-SPFPPPPF------ASISQ------------
------------------------------------------------------------
------------------------------------------------------------
----------------------SK--------------------SGAPPTTLNPSLVAKA
------------------LAG--TSVFTVS-----NTNNEFVLI----------------
------------------------------------SDP-TGD--KSIGLLCFRQEDA--
--------EAFLAQARLRRRELKT--NA--------------------------------
-----KVVPITLD-----------------------------------------------
---------------------QVYLLKV--------EGISFRFLPDPIQ-IKNALELKSS
------------GNK------------------------------NGFDGVPVFQSEL--
------------------------------------------------------------
--------------------------------LVVRKKN----RRYCP------------
---------------------------------------VYFSKEDIERE-LSKYTRAS-
--------------------------R----G----------------------------
------------------------------------------DQQIMVGSLEDVL-----
------------------------------------------------------------
RKMEMS------------------EKNSGWEDVIFIPPGRSYAQHMQELIKE--------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------
>(80)Populus_trichocarpa_gi|224136756|ref|XP_002326937.1| predicted protein [Populus trichocarpa]
ME----------------------------------------------------------
------------------------------------PSKPSNPLLS---LSTVIHQHCLR
LGAEFSARVSDT-TRFLAGN-FPPPSRL-RLAPSPPF------ASVSQ------------
------------------------------------------------------------
------------------------------------------------------------
----------------------PK--------------------QTANTANLSSEHVAKA
------------------LAG--TAVYTVS-----NSDNEFVLI----------------
------------------------------------SDP-NGA--KSIGLLCFRQEDA--
--------EAFLAQVRLRRRELRS--QA--------------------------------
-----KVVPITLD-----------------------------------------------
---------------------QVYMLKV--------EGIAFRFLPDPVQ-IKNALELKSA
------------DVR------------------------------SGFDGVPVFQSDQ--
------------------------------------------------------------
--------------------------------LIVKKKS----KRYCP------------
---------------------------------------VYFQKEDIEKE-LSKVSRAS-
--------------------------R----G----------------------------
---------------------------PGL------------SQHIMVGSLEDVL-----
------------------------------------------------------------
KKMEIS------------------EKNSGWEDLIFIPPGKSHSQHIQEITKA--------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------
>(86)Populus_trichocarpa_gi|224067266|ref|XP_002302438.1| predicted protein [Populus trichocarpa]
ME----------------------------------------------------------
------------------------------------PSGPSNPLLS---LSTFIHHHCLR
LGAEFSTRISDT-TRFLGGN-LPPPRRL-CLAPSPPF------ASVSQ------------
------------------------------------------------------------
------------------------------------------------------------
----------------------PK--------------------QTATTANLSSDHVAKT
------------------LAG--TAVYTVS-----NSNNEFVLI----------------
------------------------------------SDP-NGA--KSIGLLCFRQEDA--
--------EAFLAQVRLRRRELRS--QA--------------------------------
-----KVVPITLD-----------------------------------------------
---------------------QVYMLKV--------EGIAFRFLPDPVQ-IKNALELKAV
------------DIR------------------------------SGFDGVPVFQSDL--
------------------------------------------------------------
--------------------------------LVVKKKN----KRYCP------------
---------------------------------------IYFQKEDIEKE-LSKVSKAS-
--------------------------R----G----------------------------
---------------------------PSL------------SQHIMVGSLEDVL-----
------------------------------------------------------------
KKMEIS------------------EKKSGWEDLIFIPPGKSHSQHIHEITKV--------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------
>(148)Ricinus_communis_gi|255538318|ref|XP_002510224.1| protein translocase, putative [Ricinus communis]
ME----------------------------------------------------------
------------------------------------HSKLSNPLLS---LSTFIHQHCLR
LGAELSTRLGDT-TWAVSNNLLPGLNNR-KHRPAPLF------ASVSQQ-----------
------------------------------------------------------------
------------------------------------------------------------
----------------------PK--------------------Q---ASGLSSEHVAKT
------------------LAG--TAVYTVS-----NSNNEFVLV----------------
------------------------------------SDP-DGA--KSISLLCFRQEDA--
--------EAFLAQVRLRRRELRS--QA--------------------------------
-----RIVPITLD-----------------------------------------------
---------------------QVYMLKV--------EGIAFRFLPDPVQ-IKNALELKAS
------------DTK------------------------------RGFDGVPIFQSEL--
------------------------------------------------------------
--------------------------------LVVKKKN----KRYCP------------
---------------------------------------IYFQKEDIEKE-LSKVSRAS-
--------------------------R----G----------------------------
---------------------------PGL------------SQHIMVGSLEDVL-----
------------------------------------------------------------
RKMEMS------------------EKNSGWEDLIFIPPGKSHSQHIQEVAKV--------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------
>(154)Medicago_truncatula_gi|357465499|ref|XP_003603034.1| Tic22 [Medicago truncatula]
ME----------------------------------------------------------
------------------------------------SQGQWNPLLS---FSRFIHQNCNH
----LATRFEDT-RKFAGTL-IQSHTR-----TKPAF-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------AATLTSNHVAKS
------------------LAG--TSVYTVS-----SSNNEFVLM----------------
------------------------------------SDA-EGA--KSIGLLCFRQEDA--
--------EAFLAQVRSRKNEFRG--NA--------------------------------
-----KVVPITLE-----------------------------------------------
---------------------QVYLLKV--------EGIAFRFLPDPLQ-IRNALELRAA
-------------NK------------------------------EGFDGVPVFQSEL--
------------------------------------------------------------
--------------------------------LVVKKKN----KRYCP------------
---------------------------------------VYFSKEDIEQE-LSKVSRVS-
--------------------------K----G----------------------------
---------------------------PGV------------SKQIMVGSFEDVL-----
------------------------------------------------------------
KKMEMS------------------EKNSGWDDLIFIPPGKSRSQHIQEIKV---------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------
>(92)Sorghum_bicolor_gi|242095102|ref|XP_002438041.1| hypothetical protein SORBIDRAFT_10g007160 [Sorghum bicolor]
MA----------------------------------------------------------
--------PPDSISTRSSLPLAAAPMSDPTPSPYAASPPPPNPLAA---AASFLQHHLSR
LASHLNA-------------------------PRPALAAAAAAARTP-------------
------------------------------------------------------------
------------------------------------------------------------
---------------------GPQ--------------------GASLSLALAPDEVARA
------------------LTG--TPVFTVC-----NSSNEFVLV----------------
------------------------------------SDPATGL--RSLGLLCFRSEDA--
--------DALLSHVRTRQPVLGK--GA--------------------------------
-----KVVPITLD-----------------------------------------------
---------------------QVYMLKA--------EGIAFRFLPDPLQ-IKNALEMKSG
L--------------------------------------------TAFDGVPVFQSDL--
------------------------------------------------------------
--------------------------------LVVKKQK----KRYCP------------
---------------------------------------IYFQKEDIERE-LTRASKGS-
--------------------------R----G----------------------------
---------------------------SVL------------SKQIMVGSLEDVL-----
------------------------------------------------------------
KKMEIN------------------ERNSGWDDLIFIPPGKNLNQHINEVSA---------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------
>(115)Zea_mays_gi|194702742|gb|ACF85455.1| unknown [Zea mays]
MA----------------------------------------------------------
--------PPDSISTCSSLPLAAAPMSEPTPFPFA-ASPLPNPLVA---TASFLQHHLSR
LASHLNV-------------------------PRPAL--AAAAARTP-------------
------------------------------------------------------------
------------------------------------------------------------
---------------------GPQ--------------------GASLSLSLAPDEVARA
------------------LTG--TPVFTVC-----NSSNEFVLV----------------
------------------------------------SDPATGL--RSLGLLCFRSEDA--
--------DALLSHVRTRQPVLGK--GA--------------------------------
-----KVVPITLD-----------------------------------------------
---------------------QVYMLKA--------EGIAFRFLPDPLQ-IKNALEMKSG
L--------------------------------------------TAFDGVPVFQSDL--
------------------------------------------------------------
--------------------------------LVVKKQK----KRYCP------------
---------------------------------------VYFQKEDIERE-LTRASKGS-
--------------------------R----G----------------------------
---------------------------SAL------------SKKIMVGSLEDVL-----
------------------------------------------------------------
KKMEIN------------------ERDSGWDDLIFIPPGKSLNQHINEVSA---------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------
>(135)Zea_mays_gi|226510510|ref|NP_001151773.1| tic22 [Zea mays]
MA----------------------------------------------------------
--------PPDSISTCSSLPLAAAPMSEPTPFPFA-ASPLPNPLVA---TASFLQHHLSR
LASHLNV-------------------------PRPAL--AAAAARTP-------------
------------------------------------------------------------
------------------------------------------------------------
---------------------GPQ--------------------GASLSLSLAPDEVARA
------------------LTG--TPVFTVC-----NSSNEFVLV----------------
------------------------------------SDPATGL--RSLGLLCFRSEDT--
--------DALLSHVRTRQPVLGK--GA--------------------------------
-----KVVPITLD-----------------------------------------------
---------------------QVYMLKA--------EGIAFRFLPDPLQ-IKNALEMKSG
L--------------------------------------------TAFDGVPVFQSDL--
------------------------------------------------------------
--------------------------------LVVKKQK----KRYCP------------
---------------------------------------VYFQKEDIERE-LTRASKGS-
--------------------------R----G----------------------------
---------------------------SAL------------SKKIMVGSLEDVL-----
------------------------------------------------------------
KKMEIN------------------ERDSGWDDLIFIPPGKSLNQHINEVSA---------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------
>(99)Brachypodium_distachyon_gi|357124843|ref|XP_003564106.1| PREDICTED: uncharacterized protein LOC100825582 [Brachypodium distachyon]
MP----------------------------------------------------------
--------PPNSTRS-SSLPLAAAPMSNPSPS----SSPPPNPLAA---ASSFLQHHLSN
LASRFAA-------------------------PRPAL----AAAHPP-------------
------------------------------------------------------------
------------------------------------------------------------
---------------------GPQ--------------------GSSLSLALAPDEVARA
------------------LTG--TPVFTVC-----NSSNEFVLV----------------
------------------------------------SDPATGL--RSLGLLCFRSEDA--
--------DALLSHVRTRQPVLGK--GA--------------------------------
-----KVVPITLD-----------------------------------------------
---------------------QVYMLKA--------EGIAFRFLPDPLQ-IKNALELKSG
L--------------------------------------------TGFDGVPVFQSDL--
------------------------------------------------------------
--------------------------------LVVKKQK----KRYCP------------
---------------------------------------IYFQKEDIERE-LKKASKGS-
--------------------------K----G----------------------------
---------------------------SAL------------LKQIMVGSLEDVL-----
------------------------------------------------------------
KKMEIN------------------DRNSGWDDMIFIPPGKSLNQHINEVSA---------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------
>(195)Picea_sitchensis_gi|294461156|gb|ADE76142.1| unknown [Picea sitchensis]
MKSSLPSSAMDCSLESSTSRTVSSKFHPAFS----LKD---TLIPNIDKLLPNFHPFERS
GAINRTIMPPESNNNTPKLFPVSAVNNHTIPHLTNAVSNLFKCLTSRTNASAAKQHPWFR
FGKELGQRFEDF-KACLGSV-ISDAARP-RQRVVPCF------ASVSAG-----------
------------------------------------------------------------
------------------------------------------------------------
-----------------GQESWEP--------------------KAVFQLALSTVNVAKT
------------------LEG--VPVYTVS-----NANNEFVLV----------------
------------------------------------SDP-NSS--RSLGLLCFRQQDA--
--------EALLAQVQLRQPMLSR--GA--------------------------------
-----KVVPIPLE-----------------------------------------------
---------------------KVYTLKV--------EGIAFRFLPDPVQ-VKYALQMKSK
------------DLS------------------------------KAFDGVPVFQSDR--
------------------------------------------------------------
--------------------------------LVITKNN----RRLYP------------
---------------------------------------LYFCKEDLERE-LLRNLKNQ-
--------------------------PKA-------------------------------
---------------------------SRL------------SSDILVGSLEGIL-----
------------------------------------------------------------
KKLEES------------------KNRSGWDDVVFIPPGKISTEHIQKVLV---------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------
>(127)Physcomitrella_patens subsp. patens_gi|168027187|ref|XP_001766112.1| predicted protein [Physcomitrella patens subsp. patens]
MDVASASRVVSSAGGVADGMRGFRRCTPLGEDLVMLVRLADTRNWLRCEQLV--------
-----------ENRKRIVAQSVGSVRRNRRAVWNGISDCEKKLWMGSSGLGTQVETQLPR
TRFERARRVRD------------------QKPLRVPM------ASFSLGSPNQGDEWESK
L-----------------------------------------------------------
------------------------------------------------------------
-----------------RSESEEV--------------------ETNLRNAMTEEQVNKC
------------------LDG--VPVYTVS-----NSANEFVVV----------------
------------------------------------SEM-NSP--ESYGIICFRETDA--
--------EAFLSQIRSRDPSAGS--DV--------------------------------
-----RVTAIPLG-----------------------------------------------
---------------------KVLQLSS-------KEGETFRFVPDPNQ-IRNAYEVKAR
A----------GELS------------------------------KAFEGVPVFQSES--
------------------------------------------------------------
--------------------------------LTLNSIN----RRLLP------------
---------------------------------------IFFSKEDLETA-LQTAFEEQ-
--------------------------KRVDPA----------------------------
---------------------------LEF------------KPNIQVDSLEDIL-----
------------------------------------------------------------
DMMEGS------------------EEETQRAEIVFIPAGMDVFKYLTQFEGAIAR-----
------------------------------------------------------------
------------------------------------------------------------
----------------------------------
>(174)Physcomitrella_patens subsp. patens_gi|168057172|ref|XP_001780590.1| predicted protein [Physcomitrella patens subsp. patens]
MTEGGSGSSAACKGEYVAGGRRMAQRRPLLDGGAVVSDVRRRLVEAQNWLGVAVAEGANR
ISRFGLSIEDGRGMMVQKMERIGNRRSDPRSKIRSGQLPWEKVWTA-----------MSG
FGAQFEAQLQRS-KAGIPEA-MLRMIWN-RGAPRPLI------ASLSLGLPAQ-------
------------------------------------------------------------
------------------------------------------------------------
-----------------GGEALEA--------------------KHVFDIAMSGEQVAKR
------------------LDG--VPVYTVS-----NSANEFVLI----------------
------------------------------------SDL-NTS--KSLGIFCFREADA--
--------EALLSQVRDREPSLGR--GA--------------------------------
-----KVVAVSLD-----------------------------------------------
---------------------KVYQLST--------EGIAFRFLPDPRQ-VKNALEARSR
A----------GEPG------------------------------KAFDGVPVFQSDN--
------------------------------------------------------------
--------------------------------LILRSNN----RRFCP------------
---------------------------------------IFFSKEDLETA-LQRAFKQQ-
--------------------------QKINPA----------------------------
---------------------------LKV------------STDIQVGSFEDVL-----
------------------------------------------------------------
KRMEGN------------------EEDSGWGDIVFIPPGMDAYKHLSKSQGTVVG-----
------------------------------------------------------------
------------------------------------------------------------
----------------------------------
>(74)Glycine_max_gi|356512421|ref|XP_003524917.1| PREDICTED: uncharacterized protein LOC100811136 [Glycine max]
MM----------------------------------------------------------
-------------------------------------------------NFDGFQKALAE
FQGRCSTLLGSL-TRLQPNR------------ARPPW------ARIA-------------
------------------------------------------------------------
------------------------------------------------------------
----------------------QP--------------------WGGRPMAMTVEAIEER
------------------LEG--IPVYALS-----NASEEFLLV----------------
------------------------------------SGS-SSG--KNLGLFCFNKDDA--
--------EALLNQVTLIDPHARQ--GS--------------------------------
-----KVVPVALN-----------------------------------------------
---------------------KVFQLKV--------NGVAFRLIPEFSQ-VKNALQEREK
S----------GFAS------------------------------SGFSGVPVFQSRS--
------------------------------------------------------------
--------------------------------LILKSQN----KRFRP------------
---------------------------------------LFFRKEDLENT-LKSAAREQ-
--------------------------NKLNPT----------------------------
---------------------------MR-------------KGDIQVATLEDVI-----
------------------------------------------------------------
KEMKEN------------------S-TSNWDDVIFIPPGFDVSDDSNEQ-----------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------
>(188)Coccomyxa_subellipsoidea C-169_gi|384252955|gb|EIE26430.1| hypothetical protein COCSUDRAFT_58968 [Coccomyxa subellipsoidea C-169]
M-----------------------------------------------------------
------------------------------------------------------------
---------------------------------------SIIIDSLSLGA----------
------------------------------------------------------------
------------------------------------------------------------
-----------------ATSTYRP--------------------QPICDLAYNPEEIKAR
------------------LSG--VPVYTVA-----NKQNEFVLV----------------
------------------------------------AGE-SGGEVRQLGLIFFSEADA--
--------HALVQKVMEQNPKLAK--QS--------------------------------
-----RVLKVSMD-----------------------------------------------
---------------------AIYDFAITKEKDKRAAGVTFRFMPDAKE-VQSALEMYKE
A----------GVPS------------------------------TSFTGVPVFQAQG--
------------------------------------------------------------
--------------------------------LTVKTEK----SRYTP------------
---------------------------------------LFLAKEDLDVA-VGAAFSQR-
--------------------------ESAREAATRNKAAAAEDEVESARTALEAAPKGKD
RKAAQAELDKAEARLSKYKGRLSAMHSSET------------APKVEVGCLEEVI-----
------------------------------------------------------------
SRMEA-------------------DADGEWGSVMFIPAGALASQQQ--------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------
>iTic22-like_gi|18424615|ref|NP_568958.1| Tic22-like family protein [Arabidopsis thaliana]
M-----------------------------------------------------------
---------------------------------G--------SPD-----KQHRRHV---
AAEFLHSAVTSISSSIIPLFPPKTAP---------------SRVCLPLRFSVSD------
---------------------DVSS-------P---------------------------
------------------------------------------------------------
--------FESTVK--STSSASSS--------------------GLNSTVRISSLSSDGK
--R-GGPAFVGQVFSMCDLTG--TGLMAVS-----THFDIP-FI----------------
----------------------SKRTPEWLKKMFSTITKSERN--GPVFRFFMDLGDA--
--------VSYVKKLNIP--------SG--------------------------------
-----VVGACRLD-----------------------------------------------
---------------------LAYEHFK-------EKPHLFQFVPNERQ-VKAANKLLKS
M--------PQNGKT------------------------------QKVEGVPVFGAQN--
------------------------------------------------------------
--------------------------------LDIAVATADGIKWYTP------------
---------------------------------------YFFDKAVLDNI-LEESVDQHF
HTLIQTRHVQRRRDVVDDSLAS----EVMEEMGDSMLEPPEVQEAMEEIGTSGIPL-SVV
AKAAEIQLLYAVDRVLLGSRWFRKATGIQP------------KLPYLVDSFERRS-AFSI
QRASGSATRCLGDSVEA------D-TSASLLRVED-DSPSEA-E----------------
KRQ--QHLWFPFGDWISHSVSRKEHTHHKGSSDQRDM-----ESREREML-----RSPFL
PKITMVGISTGEA-----AQMSKANLKKTMEDLTEDLEQSDEGND-HGSKRYDSLKIEER
-------------DPLFVANV-------------------------------------GD
YYSGL-AKAGSARLSRRGDDQ-------------
>Arabidopsis_lyrata_gnl|BL_ORD_ID|26695 _496448|PACid:16060442
M-----------------------------------------------------------
---------------------------------G--------SPD-----KQHRRHV---
AAEFLHSAVT----SIIPLFPPKTAP---------------SRVCLPLRFSVSD------
---------------------DVSS-------P---------------------------
------------------------------------------------------------
--------FESTVK--SSSSTSSS--------------------GLNSTVRISSLSSDGK
--R-GGPAFVGQVFSMCDLTG--TGLMAVS-----THFDIP-FI----------------
----------------------SKRTPEWLKKMFSTITKSERN--GPVFRFFMDLGDA--
--------VSYVKKLNIP--------SG--------------------------------
-----VVGACRLD-----------------------------------------------
---------------------LAYEHFK-------EKPHLFQFVPNERQ-VKAANKLLKS
M--------PQNGRK------------------------------QKVEGVPVFGAQN--
------------------------------------------------------------
--------------------------------LDIAVATADGIKWYTP------------
---------------------------------------YFFDKAVLDNI-LEESVDQHF
HTLIQTRHVQRRRDVVDDSLAS----EVMEEMGDSMLEPPEVQEAMEEIGSSGIPL-SVV
AKAAEIQLLYAVDRVLLGSRWFRKATGIQP------------KLPYLVDSFERRS-AFSI
QRASGSATRCLGDSVEA------D-TSASLLRVED-NSPSED-E----------------
KRQ--QNLWFPFGDWINHSESKKEHTHHKGPSDGRDM-----ESREREML-----RSPFL
PKITMVGISTGEA-----AQMSKANLKKTMEDLTEDLEQSDEGND-HGSKRYDPRKMEER
-------------DPLFVANV-------------------------------------GD
YYSGM-AKAGSARLSRRGDDQ-------------
>Capsella_rubella_gnl|BL_ORD_ID|25653 _v10028359m|PACid:20911489
M-----------------------------------------------------------
---------------------------------G--------SPE-----KQHRRHI---
AAEFLHSAVTSISSSIVPLFPPKTTP---------------SRVWLPLKFSVSD------
---------------------DVSS-------P---------------------------
------------------------------------------------------------
--------FESTVN--SKSSKSSS--------------------GLNSTVRISSLSSDGK
--R-GGPAFVGQVFSMCDLTG--TGLMAVS-----THFDIP-FI----------------
----------------------SKRTPEWLKKMFSTITKSERN--GPVFRFFMDLGDA--
--------VSYVKKLNIP--------SG--------------------------------
-----VVGACRLD-----------------------------------------------
---------------------LAYEHFK-------EKPHLFQFVPNERQ-VKAANKLLKS
M--------PQNGKK------------------------------QKVDGVPVFGAQN--
------------------------------------------------------------
--------------------------------LDIAVATADGIKWYTP------------
---------------------------------------YFFDKAVLDNI-LDESVDQHF
HTLIQTRHVQRRRDVVDDSLTS----EVMEEMGDSMLEPPEVQEAMEEIGSSGIPL-SVV
AKAAEIQLLYAVDRVLLGSRWFRKATGIQP------------KLPYLVDSFERRS-ALSI
QRASGSAARCLSDSVET------D-TSASLLRVEEGDSPRED-E----------------
KRR--QNLWFPFGDWLKHSVSRKDQAHQKGSSGQRDM-----ESRDREML-----QSPFL
PKITMVGISTGEA-----AQMSKANLKKTMEDLTEDLEQSDEGND-HGSKRYDPLKIEER
-------------DPLFVANV-------------------------------------GD
YYSGL-AKAGSARLSRRGDDQ-------------
>Thellungiella_halophila_gnl|BL_ORD_ID|20311 _Thhalv10003967m|PACid:20199916
M-----------------------------------------------------------
---------------------------------D--------LPD-----KQHRRHI---
ATEFLHSAATSI-SSIIPLFPPKATP---------------SRVCLPLRFSVSD------
---------------------DV-F-------P---------------------------
------------------------------------------------------------
--------FDSTVRNASSASTSSS--------------------SLNSTVRISSLSSDGK
--R-GGPAFVGQVFSMCDLTG--TGLMAVS-----THFDIP-FI----------------
----------------------SKRTPEWLKKMFSSITKSERN--GPVFRFFMDLGDA--
--------VSYVKKLNIP--------SG--------------------------------
-----VVGACRLD-----------------------------------------------
---------------------LAYEHFK-------EKPHLFQFVPNERQ-VKAANKLLKS
M--------PPNGKK------------------------------QKVEGVPVFGAQN--
------------------------------------------------------------
--------------------------------LDIAVATADGIKWYTP------------
---------------------------------------YFFDKAVLDNI-LEESVDQHF
HTLIQTRHVQRRRDVVDDSLTS----EVMEEMGDSMLEPPEVQEAMEEIGTSGIPL-SVV
AKAAEIQLLYAVDRVLLGSRWFRKATGIQP------------KLPYLVDSFERRS-AFSI
QRASGSTSRCIGDSAEA------D-TSASLRRVED-DSPSED-E----------------
KRQ--QNLWFPFGDWLNHSGSRKEHA-QKVTSDQREM-----ECREREMQ-----QSPFL
PKITMVGISTGEA-----AQMSKANLKKTMEDLTEGLEQSDEGSSEHGSKRYDPLKMEER
-------------DPLFVANV-------------------------------------GD
YYSGL-AKAGSARWSRRGGDSNETHPRS------
>Brassica_rapa_gnl|BL_ORD_ID|11888 _010109|PACid:22695398
M-----------------------------------------------------------
---------------------------------D--------SPD-----KIHRRYN---
AAEILHGAATSI-SSIIPLFPPKTTP---------------SRVCLPLRFS---------
---------------------DV-S-------P---------------------------
------------------------------------------------------------
--------FESTVKNASSTSTSSS--------------------GLNSTVRISSLSSDGK
--R-GGPAFVGQVFSMCDLTG--TGLMAVS-----THFDIP-FI----------------
----------------------SKRTPEWLKKMFSTITKSERK--GPVFRFFMDLGDA--
--------VSYVKKLNIP--------SG--------------------------------
-----VVGACRLD-----------------------------------------------
---------------------LAYEHFK-------EKPHLFQFVPNERQ-VKAANKLLKS
M--------PPSEKK------------------------------QRVDGVPVFAAQN--
------------------------------------------------------------
--------------------------------LDIAVATSDGIKWYTP------------
---------------------------------------YFFDKAVLDNI-LEESVDQHF
HTLIQTRHVQRRRDVVDDSLTS----EIMEEMGDSMLEPPEVQEAMEEIGTSGIPL-SVV
AKAAEIQLLYAVDRVLLGSRWFRKATGIQP------------KLPYLVDSFERRS-ALSI
QRASGSTTKCLGDS---------N-SSASLLKVED-GSPSEE-E----------------
KRQ--QSLWFPFGDWLK---------AQKDSSGQREM-----ESREREMQ-----RSPFL
PKITMVGISTGEA-----AHMSKANLKKTMEDLTQDLEQSDEGSD-HGSNRYDPLKIEER
-------------DPLFVANV-------------------------------------GD
YYSGL-ARAGSARWSRRGDDRNETPPRSS-----
>Citrus_clementina_gnl|BL_ORD_ID|24296 _0.9_006877m|PACid:19275444
M-----------------------------------------------------------
---------------------------------A------------SPAEPNHLQNQ---
ISSFINATTSTL-FSLITP--TKTTPSSQSQPSSA----PASRLCIPLQFADSSC-----
--PS--------SSTRSPVGSDSIS-----------------------------------
------------------------------------------------------------
-----------SNSGASSSESSSS--------------------GFPSTVRISAINSSGK
--G-GGPAFVGQVFSMCDLSG--TGLMAVS-----THFDIP-FI----------------
----------------------SKRTPEWLKKLFATITKSERN--GPVFRFFMDLGDA--
--------VTYVKQLNIP--------SG--------------------------------
-----VVGACRLD-----------------------------------------------
---------------------LAYEHFK-------EKPHLFQFVPNEKQ-VKAANKLLRT
I--------PDSGRK------------------------------KKVDGVPVFSAQN--
------------------------------------------------------------
--------------------------------LDIAIATADGIKWYTP------------
---------------------------------------YFFDKNMLDNI-LEESVDQHF
HALIQTRHMQRRRDVIDDNLAA----EVVEEIGDSIWEPPEVQEMMDEIGHPAIPL-SVI
SKAAEIQLLYAVDRVLLGNRWLRKATGIQP------------KFPYMVDSFENRS-AASF
LRASESTSCLANSET--------N-NGSSDLKLED--KHLDK-R----------------
DQR--PDFRFPFGDWFRHLWSKQDCEAQGSSYI---------ECTKRNLQ-----LNPFL
PKVTMVGISTGEA-----GQMTKANLKKTMENLTKELEQTDQENA--TSSGSNEYIIEDR
-------------DPLFVANV-------------------------------------GG
YYSGL-AKTGSTRWVRGRSNN-------------
>Citrus_sinensis_gnl|BL_ORD_ID|32460 _1.1g009199m|PACid:18125400
M-----------------------------------------------------------
---------------------------------A------------SPAEPNHLQNQ---
ISSFINATTSTL-FSLITP--TKTTPSSQSQPSSA----PASRLCIPLQFADSSC-----
--PS--------SSTRSPVGSDSIS-----------------------------------
------------------------------------------------------------
-----------SNSGASSSESSSS--------------------GFPSTVRISAINSSGK
--G-GGPAFVGQVFSMCDLSG--TGLMAVS-----THFDIP-FI----------------
----------------------SKRTPEWLKKLFATITKSERN--GPVFRFFMDLGDA--
--------VTYVKQLNIP--------SG--------------------------------
-----VVGACRLD-----------------------------------------------
---------------------LAYEHFK-------EKPHLFQFVPNEKQ-VKAANKLLRT
I--------PDSGRK------------------------------KKVDGVPVFSAQN--
------------------------------------------------------------
--------------------------------LDIAIATADGIKWYTP------------
---------------------------------------YFFDKNMLDNI-LEESVDQHF
HALIQTRHMQRRRDVIDDNLAA----EVVEEIGDSIWEPPEVQEMMDEIGHPAIPL-SVI
SKAAEIQLLYAVDRVLLGNRWLRKATGIQP------------KFPYMVDSFENRS-AASF
LRASESTSCLANSET--------N-NGSSDLKLED--KHLDK-R----------------
DQR--PDFRFPFGDWFRHLWSKQDCEAQGSSYI---------ECTKRNLQ-----LNPFL
PKVTMVGISTGEA-----GQMTKANLKKTMENLTKELEQTDQENA--TSSGSNEYIIEDR
-------------DPLFVANV-------------------------------------GG
YYSGL-AKTGSTRWVRGRSNN-------------
>Manihot_esculenta_gnl|BL_ORD_ID|29919 _4.1_003879m|PACid:17989925
M-----------------------------------------------------------
---------------------------------A--------SST-QPAPNRH--H----
-SNLFHSATTAL-ISLVSS--PKASPLS-TIPLCP------PKICIPFQFADSSY-----
--PLIQ--SI--RSPFDSNQPESVS-------P---------------------------
------------------------------------------------------------
--------KSAAVKGL-SSAESNS--------------------GFPSTVRIAGLKSNGK
--S-GGPAFVGQVFSMCDLSG--TGLMAVS-----THFDIP-FI----------------
----------------------SKRTPEWLKKIFATVTKSERN--GPVFRFFIDLGDA--
--------VAYVKRLNIP--------SG--------------------------------
-----VVGACRLD-----------------------------------------------
---------------------LAYEHFK-------EKPHLFQFVPNEKQ-VKAANQLLKK
I--------PQGNGR------------------------------RKVDGVPVFTAQN--
------------------------------------------------------------
--------------------------------LDIAIATADGIKWYTP------------
---------------------------------------YFFDKNMLDNI-LEESVDQHF
HSLIQTRHMQRRRDVVDDNLAA----EVIEEMGDNMLEPPEVQEMLDEMGHPGIPL-SVI
SKAAEIQLLHAVDRVLLGNRWLRKATGIQP------------KFPYMVDSFEKRS-ASSF
QRASESTSYLANPKT--------D-S-TSNCTFKD--NAQAD-H----------------
EQK--TDLRIPFGDWFRHPWLKQKWKPEKLPEIRS--HESLSECTKQKLE-----RNSFL
PKITMVGISTGEA-----GQMSKASLKKTMEDLTRELEQTDRENA-----TVGRLECNVR
ILILLTEAPRNIENVLMLSNILSLARYRENFSIVICFWECILSPYSLSSFPLSYPDRQGG
TFSSL-YEESGFSILTGLYGSSGIFAKETLHSWI
>Ricinus_communis_gnl|BL_ORD_ID|23216 _30169.m006582|PACid:16821381
M-----------------------------------------------------------
--------------------------------------------SLSPDPNHH--HQ---
PSNFFHSATTAI-TSLIST-NPKTSPSS-TIPLSP------PKICIPFQFADSSYR----
--PL-----T--RSSFESTHPDSVS-------P---------------------------
------------------------------------------------------------
--------KSAAVKGL-SSAESSS--------------------GFPSTVRIAGLNSNGK
--G-GGPAFVGQVFSMCDLSG--TGLMAVS-----THFDIP-FI----------------
----------------------SKRTPEWLKKVFTTVTKSERK--GPVFRFFMDLGDA--
--------VTYVKRLNIP--------SG--------------------------------
-----VVGACRLD-----------------------------------------------
---------------------LAYEHFK-------EKPHLFQFVPNEKQ-VKAANQLLKT
I--------PQSDGR------------------------------RKVDGVPVFSAQN--
------------------------------------------------------------
--------------------------------LDIAIATTDGIKWYTP------------
---------------------------------------YFFDKSMLDNI-LEESVDQHF
HALIQTRHMQRRRDVIDDNLAA----EVIEEMGDSMLEPPEVQEMMDEIGHPAIPL-NVI
SKAAEIQLLYAVDRVILGNRWLRKATGIQP------------KFPYMVDSFEKRS-ASSF
RRASEPASYLAKSKT--------D-ADTSKLNLED--GAQAN-H----------------
EPI--TDLRLQFGDWFKSLGLKQQQKPEKGSEI--------SECRKQKLE-----MNPFL
PKITMVGISTGEA-----GQMSKASLKKTMEDLTRELEHTDRENAPGSSNNGNDLEMEDR
-------------DPLFVANV-------------------------------------GD
YYSGM-SKTNSPRLVRGGSK--------------
>Populus_trichocarpa_gnl|BL_ORD_ID|3641 _POPTR_0017s00970.1|PACid:18209660
M-----------------------------------------------------------
---------------------------------P--------SPP-EPPQHRHNNHH---
LSNFLNSTTKTL-FSLLS-------PPN-ILPLAP----PQPKICISFHLPNAPL-----
--PLTQ--ST--LSLFESTQPDSLS-------P---------------------------
------------------------------------------------------------
-----SKSSSASVKDI-SSAESNS--------------------GFPSAVRIGRLNPNGN
--G-GGPAFVGQVFSMCDLSG--TGLMAVS-----THFDVP-FI----------------
----------------------SKRTPEWLKKIFATVTKSERN--GPVFRFFMDLGDA--
--------VAYVKRLNIP--------SG--------------------------------
-----VVGACRLD-----------------------------------------------
---------------------LAYEHFK-------EKPHLFQFVPNEKQ-VKAANQLLKS
I--------PHGDGS------------------------------RRVDGVPVFSAQN--
------------------------------------------------------------
--------------------------------LDIAIATTDGIKWYTP------------
---------------------------------------YFFDKNMLDNI-LEESVDQHF
HALIQTRHMQRRRDVIDDNVAA----EVIEEMGDSLLEPPEVQEVLDEMGHPAIPL-SVI
SKAAEIQLLYAVDKVLLGNRWLRKATGIQP------------KFPYLVDSFERRS-ASSL
RRALESTSCLANSKI--------D-DSTSEHKLKD--NVQTD-H----------------
EQR--KDLRLPFGDWFSHPWLKKHSKSERESDTRK--EGLSKDCLKWKSE-----SNPFL
PKVTMVGVSTGDA-----GQLSKSSLKKTMEDLTKELEQTDEANDSFISNSSSEFKVNDR
-------------DPLFVANV-------------------------------------GD
YYSGM-AKTGISR---------------------
>Malus_domestica_gnl|BL_ORD_ID|44230 _0000777828|PACid:22664215
M-----------------------------------------------------------
---------------------------------A--------SPS-EPPHTRQQLRP--S
ITHLVHSTTSNL-LSLLAS--PKTTPSP-SLSTTP------PEIRVALFLPNLPK-----
--PL-------------AFQPDS-------------------------------------
------------------------------------------------------------
--------KLSAMKGVASSPESTS--------------------GFPSTVRIAGLNSNIK
--GSGGPAFVGQVFSMCDLSG--TGLMAVS-----THFDIP-FI----------------
----------------------SKRTPEWLKKMFKSITNSERN--GPVFRFFMDLGDA--
--------VTYVKRLNIP--------SG--------------------------------
-----VVGACRLD-----------------------------------------------
---------------------LAYEHFK-------EKPHLFQFVPNEKQ-VKAANKLLKT
M--------PQSGRC------------------------------KRVDGVPVFSAQN--
------------------------------------------------------------
--------------------------------LDIAIASSDGIKWYTP------------
---------------------------------------YFFDKNMLDNI-LEESVDQHF
HSLIQTRHTQRRHDVIDDNIPA----EVIEEMGDNLWEPPEVQEVMDEIGNSGIPL-SVI
SKAAEMQLLYAVDKVLLGNRWLRKATGIQP------------KFPYMVDSFERRS-AASF
LRASQSARCLTNGEAVNDNEDSLD-CSTSKIKSKD--DIHTN-K----------------
GNK--TDLRFPFSDWFSHLWSKQKDQNEELSK----------ERIEQSTL-----QNPNL
PKITMVGISTGAA-----GPMSKANLKKTMEDLTKELEQTDSGNA-FGSDTGNELRFEDR
-------------DPLFVANV-------------------------------------GD
YYSGM-AKTGSAKWVRGGNN--------------
>Prunus_persica_gnl|BL_ORD_ID|26753 _ppa003928m|PACid:17667413
M-----------------------------------------------------------
---------------------------------A--------SPT-EPAH-KKQARP---
ITHLVHSTAANL-LSLFAS--PKTTPS------TP------STIRVAFLFPNSPK-----
--PL----------AFHSAQPDF-------------------------------------
------------------------------------------------------------
--------K-SAMKGVESSSESNS--------------------GFPSTVRIAGLNSNIK
--G-GGPAFVGQVFSMCDLSG--TGLMAVS-----THFDIP-FI----------------
----------------------SKRTPEWLKKMFASVTNSERN--GPVFRFFMDLGDA--
--------VTYVKRLNIP--------SG--------------------------------
-----VVGACRLD-----------------------------------------------
---------------------LAYEHFK-------EKPHLFQFVPNEKQ-VKAANKLLKA
M--------QQNGRC------------------------------KRVDGVPVFSAQN--
------------------------------------------------------------
--------------------------------LDIAIASSDGIKWYTP------------
---------------------------------------YFFDKNMLDNI-LEESVDQHF
HSLIQTRHMQRRRDVIDDSLPA----EVIEEMGDNLWEPPEVQEVMDEMGNPGIPL-SVI
SKAAEMQLLYAVDKVLLGNRWLRKATGIQP------------KFPYMVDSFERRS-AASF
LRASQSSNRLANREAVNDNKDSVH-CSTSEVKLND--DIQTN-K----------------
GNK--LDLRFPFGDWFSHLLLKQKDQTEELSK----------ECVELSSQ-----QNPNL
PKITMVGISTGEA-----GQMSKATLKKTMEDLTKELEQPDAGNA-GGSDMSNELRFEDR
-------------DPLFVANV-------------------------------------GD
YYSGM-ARTGSARWVRGGNN--------------
>Carica_papaya_gnl|BL_ORD_ID|1469 _evm.model.supercontig_107.127|PACid:16405310
M-----------------------------------------------------------
---------------------------------A--------SATDQPQHNFH--HR---
IANLLHATSSSL-SFLLPS--PKTAP----YPPSP------PKLCVPFKFADSPVL----
--PL--------TSVFESPQSDSVS-------S---------------------------
------------------------------------------------------------
--------K-STIKGV-SSAESNS--------------------GFSSAVRIGGLNSNGK
--A-SGPAFVGQVFSMCDLTG--TGLMAVS-----THFDIP-FI----------------
----------------------SKRTPQWLKKIFATITKSERN--GPVFRFFMDLGDA--
--------VAYVKQLNIP--------SG--------------------------------
-----VVGACRLD-----------------------------------------------
---------------------LAYEHFK-------EKPHMFQFVPNERQ-IKAANKLLKK
I--------PQNDGR------------------------------TKVDGVPVFGAQN--
------------------------------------------------------------
--------------------------------LDIAIATVDGIKWYTP------------
---------------------------------------YFFDKNMLDNI-LEESVDQHF
HSLIQTRRIQRRRDVVDDSFAA----EVIEEMGDNSWEPPEVQEVLNEIGHPGIPL-SVI
SKAAEIQLLYAVDKLLLGNRWLRKATGIQP------------KFPYLVDSFERRS-TASF
LKASKPTNCLTDFEA--------G-LDTSGVELDD--KFQGN-H----------------
RET--KDFQLPIGDWLNHSWLKQGQKHQMLAD----------------------------
------------------------------------------------------------
----------------------------------------------------------TG
Y---------------------------------
>Vitis_vinifera_gnl|BL_ORD_ID|19207 _GSVIVT01028824001|PACid:17835832
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------MCDVSG--NGIMAVS-----NHFDIP-FI----------------
----------------------SKRMPQRIKKMFATITKSDKN--GPVFRFFMDLGDA--
--------VRYVKKLNIP--------SG--------------------------------
-----GVGACRLD-----------------------------------------------
---------------------LAYGHFM-------EKPHLFRFVPNEKQ-VKAANKLLKK
I--------PQNGGR------------------------------KRIDGVPVFTAQN--
------------------------------------------------------------
--------------------------------LDIAIATTDGIKWYTP------------
---------------------------------------YFFDKHTLDSI-LEQSIDHHF
HHLIQSRHVQRRRDVIDDNLAA----EVLEDNAESLWEPPEVQEVLDEVGHPGIPL-SVI
SKAAEMQLLYAVDRVLLGNRWLRKATGIQP------------KFPYMVDSFEKRS-AASF
RRASPSKRFVASPEMGNDNKDTEE-LGPSDPKLED--NTQRD-Q----------------
GQN--SASWFPVWDLFNHPWSNKRQEPQNRSNARI--EDASREHIKQELQ-----LAPFL
PKITMVGISAGES-----G-MSKVNLKKTMEDLTKELEQADQENA--VGCINSEFEVENR
-------------DPLFVANV-------------------------------------GS
YGSGL-VARSPVPSVRGENN--------------
>Eucalyptus_grandis_gnl|BL_ORD_ID|2953 _A02719.1|PACid:23564674
M-----------------------------------------------------------
---------------------------------A--------VSPEPPRKHRHHPNP---
---LSHLLNSTL-LPLIPN--HKAAPPSLVSPPPP------PKLLLPVRLPP--------
--ALSIASPS--DSAPPPPHPTPLK-------P---------------------------
------------------------------------------------------------
--------APEVKAPAEPGAAAAG--------------------AFPSTVRISAIKSNGK
--G-RGPAFVGQVFSMCDLSG--TGLMAVS-----THFDVP-FL----------------
----------------------SKRTPEWLKKVFASITKSERN--GPVFRFFMDLGDA--
--------VTYVKRLNIP--------SG--------------------------------
-----VVGACRLD-----------------------------------------------
---------------------LAYEHFK-------EKPHLFQFVPNEKQ-VKAANKLLKT
I--------SQGNGN------------------------------RQIDGVPVFSAQN--
------------------------------------------------------------
--------------------------------LDIAIATSDGIKWYTP------------
---------------------------------------YFFDKNMLDNI-LEESVEQHF
HSLIQTRHMQRRRDVIDDNLT-----EVADDVGDSLWEPPEVQEVLEEMGHPGIPL-SVI
SKAAEMQLLYAVDRVILGNRWLRKATGIQP------------KFPYIVDSFERRT-AASL
VRASDLTHYLGDRGMKTDESSQ---ESTDKLALEE--NHHVD-L----------------
GQK--ADFRFPFGDWLRHPWSKEQQKLQKEVGARHRLESLTGEPVKQKLQ-----PNPFL
PKITMVGISMGEA-----GQANKATLKKTMEDLTRELEQTDHGNA----AGNIADVSEDR
-------------DPLFVANV-------------------------------------GD
YYSGL-AKTGSARLIRRSEAKKQQ----------
>Glycine_max_gnl|BL_ORD_ID|45053 _16g29580.1|PACid:16303315
M-----------------------------------------------------------
---------------------------------A--------LPS-EPHRRRRHNHN--H
ISTFLQSTASNF-ASLFN---PPNPPSL-TLPHPP------TSVSLPLFFAP--------
--PLS-------------------------------------------------------
------------------------------------------------------------
--------GSSTVDSA--TSKPAH--------------------PPAKSVRIARLGANGK
-GG-GGPVFLGEVFSLCDLSG--TGLIAAS-----KHFGIP-FI----------------
----------------------SERTPEWLKKIFAPITKSERN--GPVFRFFIDLEDA--
--------VSYVEKLNIP--------SC--------------------------------
-----VVGAFRLD-----------------------------------------------
---------------------LAYKQFK-------EKPHLFQFVPNEKQ-VKAANKLLKT
I--------SEHGDK------------------------------KKVDGVPVFGAQN--
------------------------------------------------------------
--------------------------------LDIAIATTDGIKWYTP------------
---------------------------------------YFFDKNMLDNI-LEDAVDQHF
HNLIQTRHMQRRRDVVDDNLAA----EVIEEMSDRLGEPPEVQELLDEMGHPSIPL-SVI
SKAAGLQFQYTVDKVLLGNRWLRKATGIQP------------KFPYMVDSFERRS-EASL
LRATESSSCLENSKVEDDRQISEC-LDSSNCSLDG--NTEAI-K----------------
QPS--PSLSLPFGNWFHHLWPKQCREKASSSR---------KGVNKEEMK-----PRPIL
PKVTMVGLSTEEA-----GQTSKANLKKTMDDLTRELEKTELDIM--TDGGSKECKVEDR
-------------DPLFVANG-------------------------------------GN
YYSSMRRKPGSGR---------------------
>Phaseolus_vulgaris_gnl|BL_ORD_ID|6869 _091010222m|PACid:23537334
M-----------------------------------------------------------
---------------------------------A--------LPS-EPHRRRRHHNN--H
IATFLQSTASNF-ASLFN---PPNPPSL-TLPHPP------SSLSLPLFFAP--------
--PLS-------------------------------------------------------
------------------------------------------------------------
--------ASNALDSAATASEPAR--------------------PAAKSVRVARLGVNGK
GGG-GGPAFVGQVFSMCDLSG--TGLMAVS-----THFDIP-FI----------------
----------------------SKRSPEWLKKIFAAITKSERN--GPVFRFFIDLGDA--
--------VSYVKKLNIP--------SG--------------------------------
-----VVGACRLD-----------------------------------------------
---------------------LAYEHFK-------EKPHLFQFVPNEKQ-VKAANKLLKA
I--------SQHGIR------------------------------KKVDGVPVFSAEN--
------------------------------------------------------------
--------------------------------LDIAIATTDGIKWYTP------------
---------------------------------------YFFDKNMLDNI-LEEAVDQHF
HTLIQTRHMQRRRDVVDDNLAA----EVIEEMGDNLGEPPEVQELLDEMGHPSIPL-SVI
SKAAELQFHYTVDKVFLGNRWLRKATGIQP------------KFPYLVDSFERRS-EASY
LRATESRRCLENPKVEDDGKISEC-VDSSDCGLDD--NTEAI-R----------------
QPS--YRLSLPFGNWFNHLWPKQCHEKARSFK---------KGVNKEDMK-----PTPFL
PKVTMVGLSTEEA-----GQMSKANLKKTMEDLTRELEKTELDNM--AGGGGKECTMEDR
-------------DPLFVANV-------------------------------------GD
YYSSL-GKAGSGRWIRGGSN--------------
>Cucumis_sativus_gnl|BL_ORD_ID|17033 _192940.1|PACid:16968025
M-----------------------------------------------------------
---------------------------------A--------FQI-EPSSEPHEQNPLTF
ITHLFHSSTSNF-STLFAN--PQSIPPF-PFQSSS------SKLCIPVAFPPSPKP----
--PF----LS--HSGFHSIHYDLDS-------P---------------------------
------------------------------------------------------------
--------KSAAVKGLSSSPNFDS--------------------GFPSTLRISGLNSDGK
--T-GGPAFVGQVFSMCDLSG--AGLMAVT-----SNMNIP-FV----------------
----------------------SKRTEEWLKKMFSTITKSKRN--APIFRFFTDLGDA--
--------VTYVKRLNIP--------SA--------------------------------
-----VVGVCRLD-----------------------------------------------
---------------------LAYEHFK-------EKPHLFQFIPNEKQ-VKAANKLLKG
L--------PQNGGS------------------------------KKIDGVPVFSAQN--
------------------------------------------------------------
--------------------------------LDIAIATTNGIKWYTP------------
---------------------------------------YFFDKNMLDNI-LEESVDQHF
HALIQTRRLQRRREIVDDNAAA----EVLEEMGDSLLEPPEVQEVMDEMGNPGIPL-SVI
SKVAEMQLLYTVDKVILGNRWLRKAVGIQP------------KFPYMVDSFERRS-AASL
LRIQESASGLTNSESVEETKELQC-YSSSPLNTED--NREAN-Q----------------
EPK--QHSFNPFRNWFGHLWSKQRQRDDFSQ-----------ERTKQNVQ-----ISPFL
PKITMVGISTGDS-----GHTSKANLKKTMEDLTRELEHIDQGNA--ASHNEYEFNNEER
-------------DPLFVANV-------------------------------------SH
FSSGL-SKAGSARWVRGND---------------
>Linum_usitatissimum_gnl|BL_ORD_ID|5439 _10027537|PACid:23144619
M-----------------------------------------------------------
---------------------------------A--------TSA-EPPQNHHRRHH--P
FPNFFHSATSAV-LSLLPNPRTSSAPPI-TSPSSS----PPPHVCIPFNFVDSSY-----
--PLNQQSVI--RSPLESGQSDSVS-------S---------------------------
------------------------------------------------------------
--------TSATVKGL-SSAESNS--------------------GFPSTVRISGLNSDGK
--G-GGPAFVGQVFSMCDLSG--TGLMAVS-----TYIELP-FI----------------
----------------------NERTPEWLKKILAPVTKKDKN--GPMFRFFMDLGDA--
--------VSYVKKLNIP--------SG--------------------------------
-----VVGACRLD-----------------------------------------------
---------------------LAYEHFK-------EKPNLFQFVPNKEQ-VKAAKQLLKT
M--------PESDGK------------------------------TTVDGVPIFSAHN--
------------------------------------------------------------
--------------------------------LDIAIATSDGIKWYTP------------
---------------------------------------YFFNKSMLDGI-IEDSVDQHF
HTLIQTRHMQRRRDVVDDNFAA----DVMEEMADSLMDPPEVDEMMDEMGNVGIPL-SVI
SKAAEMELLYAVDKVLLGNRWLRKATGIQP------------RFPYVVDSFERRS-AYSF
KKASKTTSLSHVSQA--------G-GSDSEVEPEN--NTQANSY----------------
EER--PDLRLTFGDWFG-LRLKQPFKPARETESRT--EGSSKEQMQQKLV-----DNPLL
PKITMVGISTGET-----GKVSKASLKKTMESLRKELEQADQGKTSSSDNGDGDFKIADR
-------------DPLFVANV-------------------------------------GD
Y----------SRWIRRGMS--------------
>Mimulus_guttatus_gnl|BL_ORD_ID|16966 _mgv1a003806m|PACid:17686364
M-----------------------------------------------------------
---------------------------------A--------SAA-DKSHRRHHPPP--H
LSRFISTASTNL-SSFLTL--KSPSP-----ASSS------SKIHLPLLLADSDS-----
--FL----SL--VSRSESAQPDSTPSAPSRSPPS--------------------------
------------------------------------------------------------
-----SSSSSSSMKST-PSSDSVS--------------------KFPPTVRI----TTGK
--G-GGPAFVGQVFSMCDLSG--TGLMAVS-----THFDIP-FL----------------
----------------------SKRTPEWLRKMYAAVTKSERN--GPVFRFFMDLGDA--
--------VSYVKQLNIP--------SG--------------------------------
-----VVGACRLD-----------------------------------------------
---------------------IAYEHFK-------EKPDTFQFVPNERQ-VKEANKLLKS
F--------PHSDGK------------------------------NKVEGVPVFSAQN--
------------------------------------------------------------
--------------------------------LDIAIAKKDGIKWYTP------------
---------------------------------------YFFDKSMLDNI-LEDSVDQQF
HSLIETRNAHRRRDIGDDSLPA----EAIEEMGESMWDPPEVQEVLDEIGHPGIPL-SVI
SKAAEIQLLYAVDRVILGNRWLRKATGIQP------------KFPYMVDSFERKT-AASF
LRAKTS-NLISNSEISEDAQLD-N-RTTLDVEPKE--KTHDK-Q----------------
EQKHLINSQFPFGDWLSHPWLKQPENQQNLSETRH--PNSTTQNRGQVAQ-----SSPFL
PKITMVGVSTGEP-----GKMGKAALKKIMDDLTKELEKVEQVNQ--ANSNSSEYMADER
-------------DPLFVANV-------------------------------------GD
SYSAV-SKTGTSWRVRGGSF--------------
>Aquilegia_coerulea_gnl|BL_ORD_ID|35613 _013_00192.1|PACid:22058731
M-----------------------------------------------------------
---------------------------------A--------ISPSESHLNYNNNNN--N
FTRFIQSTSSSF-FSLFN---PSPLPPL-SSSSSSFPFCSSSSICVPLLFSDTPPRILSL
STTLSTNSSS--SSTTPSSQNDPLS-----------------------------------
------------------------------------------------------------
------------LNSQIKTRSPSS--------------------KFPSSIKISGLNSNPN
--G-SGPAFVGQVFSMCDVSG--TGLMTVS-----THMEIP-FI----------------
----------------------SKRIPEWIKSMFSVFNKSENN--GPVFRFFMDIGDA--
--------VSYVKRLNIP--------TG--------------------------------
-----VVGACRLD-----------------------------------------------
---------------------LAYEHFK-------EKPHMFQFVPNEKQ-VKAANKILKK
T---------QHSEK------------------------------RIVDGVPVFTAQN--
------------------------------------------------------------
--------------------------------LDIAIATGDGIKWYTP------------
---------------------------------------YFFDKNMLDNI-LEESVDQHF
HSLIQSRHMHRRRDVIDDNLTA----EVVEDNRDNLWEPPEVQEVLDEMGYPGLPM-SVI
SKAAEVQLLDAVDKVLLGNRWLRKATGIQP------------KFPYRVDSFEKRS-AASF
RKATELTSIASNRIDSCVGSKCENLKGSEEPRLEE--NTQSG-Q----------------
RQP--SEVRLPFGDWFSHLWSKQQHKPDEQTR-----LTDSRDKYIEQLP-----LSPLL
PKITMVGISTGEA-----GQTSKASLKQTMEDLTRELEQPGQDID---DGGSNEIRHEER
-------------DPLFVANV-------------------------------------GV
----------------------------------
>Brachypodium_distachyon_gnl|BL_ORD_ID|2714 _2g07450.1|PACid:21805484
M-----------------------------------------------------------
---------------------------------P--------SSS--------------S
SSNPFHSLTFN--LPFPPAPSSC-STSA-SSPPAP-----APHLAFPLLL----------
--PVSSASTT--SSYSPASHLIPQP-----------------------------------
------------------------------------------------------------
--------QRLPGERMAGPAAASG--------------------G-------KGVSAGKS
--P-GGPAFVGQVFTMLDPSG--NGLMAVT-----SRFDLPHFI----------------
----------------------AHRTPTWFKRILSPLKKSE-S--SPVFRFFMDLNDS--
--------VSYVKRLNVP--------SG--------------------------------
-----MVGACRLD-----------------------------------------------
---------------------VAYEHFK-------EKPHMFQFVPNEKQ-VKAANKLLKS
I--------PQKSRR------------------------------KKLAGVPVFSAQN--
------------------------------------------------------------
--------------------------------LNIAVATDDGIRWYSP------------
---------------------------------------YFFDKNLLDNI-LEASMDQHF
HSIIQNRHIRRRRDIVDDSLTS----EILEESADSLLEPPEVQELMNEIGPAGIPL-SVV
TKAAEIQLLDVVDKLLLGNKWLRKATGIQP------------RFPYVVDSFEERT-ALSV
DRTATSSNSCTASKDADFFTNDQQ-SQALEPNVDS--GNHRK-H----------------
NSRDHGQSHFPFSNLLPNIWPGHDRKFKAQEHDNR--FKRYGASMDNDLQ-----ANPLL
PKITMVGISMSEG-----GQMSKANLKKTMEELTKELEQAGEKTV----------FSDEK
-------------DPLFVANV-------------------------------------GD
Y-SRI-TKISST----------------------
>Sorghum_bicolor_gnl|BL_ORD_ID|9318 _Sb03g001210.1|PACid:1960134
M-----------------------------------------------------------
---------------------------------P--------RSS--------------S
SSNPFHSLASA--FPFFSSSSPSPPASA-SPSPSP----AAPHLAVPLLL----------
--PVSSGSASASSESRRGP-----------------------------------------
------------------------------------------------------------
--------QPLPGARMAGAAAAGR------------------------------GNKAGG
--G-AGPAFVGQVFTMLDPSG--NGLMAVT-----TRFELPRFL----------------
----------------------TNRTPMWFKRMLSPLKKSE-S--SPVFRFFMDLNDA--
--------VSYVKRLNVP--------SG--------------------------------
-----MVGACRLD-----------------------------------------------
---------------------VAYEHFK-------EKPHLFQFVPNEKQ-VQAANKLLKS
L--------PQRSRR------------------------------KKLGGVPVFSAQN--
------------------------------------------------------------
--------------------------------LNIAVATNDGIRWYTP------------
---------------------------------------YFFDKNLLDNI-LEASMDQHF
HSIMQNRHTQRRRDIVDDSLTS----EIIEESAESLLEPPEVQELMNEIGPAGIPL-NVV
TKAAEIQFLDVVDKVLLGNKWLRKASGIQP------------KFPYVVDSFEERT-AVSI
ANIATTSS-LTTSNDENCCQNNQQ-TQSSGSSVDN--SSYRN-H----------------
NNEDHN--HFPFSNLLPNIWPGHDRKFKAQESDNK--FSRYDADVKSNLQ-----SNPLL
PKITMVGISMGDG-----AQMSKANLKKTMEDLTKELEQTSEENM----------FSDDK
-------------DPLFVANV-------------------------------------GD
Y-SRI-TKISSA----------------------
>Zea_mays_gnl|BL_ORD_ID|9045 _GRMZM2G097959_T01|PACid:20828771
M-----------------------------------------------------------
---------------------------------P--------CSS--------------S
SSNPFHSLASA--FPFLSSTSP--PPSP-PASPAP----AAPHLAVPLLL----------
--PVSSA-----SESRRGA-----------------------------------------
------------------------------------------------------------
--------QPLPGTRMVGAGATGG------------------------------GNMASG
--G-GGPAFVGQVFTMLDPSG--NGLMAVT-----TRFELPRFL----------------
----------------------TNRTPMWFKRMLSPSKKTE-N--SPVFRFFMDLNDA--
--------VSYVKRLNVP--------SG--------------------------------
-----MVGACRLD-----------------------------------------------
---------------------VAYEHFK-------EKPHMFQFVPNEKQ-VQAANKLLKS
L--------PQRGRR------------------------------KKLDGVPVFSAQN--
------------------------------------------------------------
--------------------------------LNIAVATNDGIRWYTP------------
---------------------------------------YFFDKNLLDNI-LEASMDQHF
HSIMQNRHTRRRRDIVDDSLTS----EIIEESAESLLEPPEVQELMNEIGPAGIPL-NVV
TKAAEIQFLDVVDKVLLGNKWLRKASGIQP------------KFPYVVDSFEERT-AVSI
ANIATTSS-LTASNDDSSCQNNQE-TQSSEPSGDN--SSYRN-H----------------
NNEDHN--HFPFSNLLPNIWPGHDRKFKSQESDNK--FSRYDADVKSKLQ-----ANPLL
PKITMVGISMGDG-----AQMSKANLKKTMEDLTKELEQTSEENM----------FGDEK
-------------DPLFVANV-------------------------------------GD
Y-SRI-TKISSA----------------------
>Setaria_italica_gnl|BL_ORD_ID|1638 _Si001606m|PACid:19674983
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------MLDPSG--NGLMAVT-----TRFELPRFL----------------
----------------------TNRTPTWFKKILSPLKKSE-N--GPVFRFFMDLNDA--
--------VSYVKRLNVP--------SG--------------------------------
-----MVGACRLD-----------------------------------------------
---------------------VAYEHFK-------EKPHMFQFVPNEKQ-VKAANKLLKS
L--------PQRGRR------------------------------KRLGGVPVFSAQN--
------------------------------------------------------------
--------------------------------LNIAVATNDGIRWYTP------------
---------------------------------------YFFDKNLLDNI-LEASMDQHF
HSIMQNRHKQRRRDIVDDSLTS----EIIEESADSLLEPPEVQELMNEIGPAGIPL-NVV
TKAAEIQLLDVVDKVLLGNKWLRKAAGIQP------------RFPYVVDSFEERT-AVSI
ANIATTSS-FTASND-SCCQNDQQ-SQSSDPSIEN---SYRS-H----------------
SNQDHNQFHFPFSNLLPNIWPGHDRKFKEQESDSK--FSRYDADMKTDLQ-----SNPLL
PKITMVGISMSEG-----GQMSKANLKKTMEDLTKELEQTSEKNT----------FGDEK
-------------DPLFVANV-------------------------------------GD
Y-SRI-TKISST----------------------
>Oryza_sativa_gnl|BL_ORD_ID|20689 _LOC_Os01g12550.1|PACid:21903161
M-----------------------------------------------------------
---------------------------------PRGRSTTTTTSS--------------S
ASNPFHAFAST--LPFLPSPSPS-PTSA-SPSPSP----PAPHLAVPLIL----------
--PITSSSSA--SAAAASP-----------------------------------------
------------------------------------------------------------
--------ESNRGARMA--AAASG--------------------G-----KAGGGGGLGK
--G-GGPAFVGQVFTMLDPSG--NGLMAVT-----TRFELPQFL----------------
----------------------ASRTPMWFKRILSPLKKSE-N--GPVFRFFMDLNDA--
--------VSYVKRLNVP--------SG--------------------------------
-----MVGACRLD-----------------------------------------------
---------------------VAYEHFK-------EKPQMFQFVPSEKQ-VKAANKLLKS
L--------PQRRRR------------------------------KKLDGVPVFSAQN--
------------------------------------------------------------
--------------------------------LNIAVATNDGIRWYTP------------
---------------------------------------YFFDKNLLDNI-LEASMDQHF
HSMVQNRHTRRRRDIVDDSLTS----EMMEESADSFLEPPEVQELMNEIGPVGIPL-NVV
TKAAEIQFLDVVDKMLLGNKWLRKATGIQP------------QFPYVVDSFEERT-AAAI
DRAATASSSFTASKDADCFQISKQ-PETLESDVDN--SNRGK-H----------------
ENSNNGQSHFPFSNLLPNIWPGHDRSFKAQGRDRA--FRRCDASINNDLQ-----ANPLL
PKITMVGISMGEG-----GQMSKANLKKTMEDLTKELEQAGEKTI----------FSDEK
-------------DPLFVANV-------------------------------------GD
Y-SRI-TKISST----------------------
>Panucum_virgatum_gnl|BL_ORD_ID|40717 _Pavirv00055971m|PACid:23796854
M-----------------------------------------------------------
---------------------------------P--------RSS--------------S
SSNPFPSLASST-FPFLSSSSSA-ATSS-TTSPAH----PAPHLAFPLLL----------
--PVSSASSS--AEPRRGP-----------------------------------------
------------------------------------------------------------
--------EPLPGARMAGAGAAAG--------------------GKP------GGRIKGG
--G-GGPAFVGQVFPMLDPSG--NGLMAVT-----TRFELPRFL----------------
----------------------TNRTPAWFKKILSPLKKSE-N--GPVFRFFMDLNDA--
--------VSYVKRLNVP--------SG--------------------------------
-----MVGACRLD-----------------------------------------------
---------------------VAYEHFK-------EKPHMFQFVPNEKQ-VKAANKLLKS
F--------PQRGRR------------------------------KRLRGVPVFSAQN--
------------------------------------------------------------
--------------------------------LNIAVATNDGIRWYTP------------
---------------------------------------YFFDKNLLDNI-LEASMDQHF
HSIMQNRHVQRRRDIVDDSLTS----EIIEESADSLLEPPEVQELMNEIGPAGIPL-NVV
TKAAEIQLLDVVDKVLLGNKWLRKAA----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------
>Physcomitrella_patens_gnl|BL_ORD_ID|36425 _Pp1s68_153V6.1|PACid:18072962
M-----------------------------------------------------------
------------------------GRNRDTCNVPGCSKDEKPCLVTGPKIVSFKLPNPAL
FSSWVQTVTSNLAWTVQSFQTLKTDGLN-CLSLLVEHKPMVSPLPVPYLALNNLIFPVP-
------------------------------------------------------------
------------------------------------------------------------
--------SSTSSVQVCQKAVSSI--------------------PQDHFSKGNAVNEKGE
VSS-TGPAFIGQVYTMCDASR--QGLIAVRPSDVLKKIKVP-PY----------------
----------------------MKLMEKAYERAMNVLFTDDMK--GPVFRFYFNKDDA--
--------AEYVRRLNIT--------GS--------------------------------
-----AVGPCSLD-----------------------------------------------
---------------------AAYKYYK-------SKEGMFKFIADQRQ-VKVAKELVRR
E--------RGDKAA------------------------------NKLKGVPVFTARN--
------------------------------------------------------------
--------------------------------LTIALSTPQGVRWFRP------------
---------------------------------------YFFNKKQLDSL-IGHSVDHYY
EMLISARRAQRYSQIAENNGDAFAGGESMDDELDGLMDPPEVQELMEELGQGGGGMEFVG
LKVLEAQFMDLADRVLLGHQWSRRMIHLQP------------RFPVIVDSFERLISASEL
DHSSESEGSVTSSRNSFAKKEGTQ-EKSQRGQGDEGMSISGRDERSASNDSSESVSKEYS
QSSPNSLFNLFKKKWGANANLVFKRKDSGNAEILE--EDSDSEYLQETAQKDPPGKIPFQ
PKLTMMGISMNVNKVEGGLQQAMAAAAKDVEDRLRKGEGSGPDH----------------
-------------GPLFIANL-------------------------------------GS
GIPQWGRPVSASSGVLDDDAE-------------
>Selaginella_moellendorffii_gnl|BL_ORD_ID|1621 _424522|PACid:15402899
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----EIGSVPLH-----------------------------------------------
---------------------LAYKFFK-------ERPSLFSFIPSKKQ-VDLAKTIIKK
E--------QGGKAA------------------------------QQFQGVPVFTSHC--
------------------------------------------------------------
--------------------------------LSILVVGPSGARWFRP------------
---------------------------------------HFFKKEELDGV-IRSSMEHHY
QSLIRNRRARRHNQVSDFPS------DMAEDDLE-MLESQDIQDFVEDMDEWSSVLESIM
AKAAQMYFQDTLDRAIFGNKWCRMLAGIQP------------SFPILVDSFERRV-TSET
ENAVVSHHEQKKPHKDWDST----------------------------------------
------------------------------------------------------------
------------------CQLKRALIR---------------------------------
------------------------------------------------------------
----------------------------------
>(182)Cyanidium_caldarium_gi|2541891|dbj|BAA22826.1| unnamed protein product [Cyanidium caldarium]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------DDYYIFEYRLSEPQPTVW
QSLWQWYVSPVQIQHLLLSRQVQSIHLPFIKSKSCGVIDYQFHYQFKSNHPKIHDAFRQS
------------------LEA--CPIYYVV-----NPKQELILL----------SPRKWE
SEYQAPTF--------------MNWVLDCVFR--------QSP--TSYLLVFFHPDDA--
--------QMYLQSVLNNPYERDK--NS--------------------------------
-----FVQEGDLF-----------------------------------------------
---------------------TFLKFNR--------ADVKVLLVPHLKQ-----------
-----------MCQW------------------------------QQFDGTPVFRVQV--
------------------------------------------------------------
--------------------------------KD--------------------------
------------------------------------REWLFLSKQNAQQF-VKRMKKL--
------------------------------------------------------------
------------------------------------------SCKCDVVSLESILEADA-
------------------------------------------------------------
---------------------------NRQARCVLVPLS---------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------
>(105)Glarea_lozoyensis 74030_gi|361126402|gb|EHK98404.1| putative Calcium channel YVC1 [Glarea lozoyensis 74030]
M-----------------------------------------------------------
------------------------------------------------------------
---------------------PSAIAPE-EVTKVALRLRYLIEESVPCELEEGLITQAHS
RIITHKVVQA--AKEAGGDQYGACVVYCLLVNKRWFKKQASLELWDADLHNVRAVACEVI
AKQLIETEDSLDYLLQDILLKRYSIIIDNEVTHPANVIERAVDLHALRVTGSSGYQKCVN
YLWRGWLVQDDMDANRFVDYKKKD--------------------NVNYWTHVHPDRMRAP
-------VYQNATQIVISLIY--LGLYTGAINTV-NSTGDLDFVEIVLYIFTFGFLCDEF
SKVWKVGRNYLGFWNVFNLMLYGMLTTSLIIRIIALGHPIGEDKRAKFNELSYNFLDA--
--------TTFILQAMANAVMGSPEFDNFDNFAPPFGIILYYIFSFLIMVILLNVLIALY
NSAYEDITSNAID-----------------------------------------------
---------------------EYMALFA-------QKTMQFVRAPDENV-FIAPFNLIEI
FCLILPFEWWMSRKT---------------------------------------YAKL--
------------------------------------------------------------
--------------------------------NDIVMAI-----VYSP------------
---------------------------------------LLFVAAWFEKRSAKVVRSNR-
--------------------------KRGEEDDDTVEEWEQMAGTVD-------------
---------------FEGEGWDKKVASAKPDVERDTATHEVRKLRGEVGELKELI-----
------------------------------------------------------------
EKL---------------------LSASGKTSA---------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------
>Chlamydomonas_reinhardtii_gnl|BL_ORD_ID|12022 _13.g593950.t1.2|PACid:19870334
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------ALQSRHGRATFLHAYWRERALRPCLRRPVLTVSAVAASSSAAE
GRGKASGLGSLTFLDFVVPFSTPLAAAIATGVYTGAVGADLAWPLRALLVGGGPLLVHLL
FPAVDWALGPSRALAERQQQQAQQ--------------------QALGIKAPGADHFLSR
----ALPCLAVAVQLLVLLAT--YGALAAA-----AGAPAPPLA----------------
---------------------------------------------GAAGAAAAGLQQQ--
--------QLLLLPL---------------------------------------------
-----LVTSLALSAGMAQAASHELLHSRHPVHLAAAWLFLTTH-----------------
---------------------WWYPYFRAHHQHHLAVCTPADYASAPRG-LSLAAYLPRY
IGSSYTEAWQLAAAE------------------------------CRRAGHPVFSTHNSC
LVALVAQAALTAALGLALGPAAALLHGAVCAVLLTYMSVLDYVLHYGLRRPPLVVAAAAA
ATAGGVGGGADAAVSTVADSREVTGVAPAAAGVAAAPAAGSGAVRYAP------------
-----------------------VTPFNSWSSLYPLENALFFNVLIHGDHHMTASRSYAW
LVPAPSSP----------------------------------------------------
------------------------------------------TFPAPINALALAT-----
------------------------------------------------------------
----------------------------------FVPPLWRAAMHERVDQANSANLRHLA
ATGVPVAAEQGAAEQGAAEQVAAEQVAAAGTA----------------------------
------------------------------------------------------------
----------------------------------
>(141)Salmo_salar_gi|209733952|gb|ACI67845.1| Galectin-9 [Salmo salar]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------SFQQ--------------------PFFNPRVPFTGCIQGA
LHEGMTITVTGRV-----LPG--AQRFHVNLQCGSRGNPDIALHFNPRYDSFLDVVICNT
MQHSKWGSEEREYFATMTRG-------------------------ANFTLMFLVNRDSYS
IFVNGVLFMEYLHRLSFSRVDTISVNGGV-------------------------------
-----EVQSIAFSNPAVTSPPPQPGYPGHPHSAFSAAGFLQAPPPYTAQPPYTPKPSFVV
PYKNIMAGGLYPGRNITIQGVVNHNADKFCINLRFNSGVAFHFNPRFNENVVVRNSLLK-
---------EQWGQE------------------------------ERTGGMPFYRGQP--
------------------------------------------------------------
--------------------------------FTVIIMCDTQCYKVMV------------
-----------NGALMFSYNHRH----------------FLFQQIDI----LEVEGDMS-
------------------------------------------------------------
------------------------------------------LSAVLV------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------
