>gnl|BL_ORD_ID|1202	Escherichia_coli_UTI89 gi|91210123|ref|YP_540109.1| hypothetical protein UTI89_C1094 [Escherichia coli UTI89]	
MKREA--------------------------------------FMCLLAPENPYPIYALP
PLVR----------NAIIETQKNTQAPLAMVATSALTATSIACQNQVDVCRPGNLRGPVN
LYSLILADSGERKTTVDKVFMKAFYLRDEALAEEYAKLVENYSTEKEIWEQKQKALESKL
HKEIRAGKGCKATESELKRHLNKCPVPPQIRRTIFNETTIEGMLKYYSDSNRSFALVSSE
GGIIFDGRAMSKLGILNSLWDGGSLFIDRKSSPGIILKDPRLTVSVMIQPDVYQKGFCTR
KKELVKTSGHHARFLMCQPTSTQGTRIITGDNYSSQYQDLFEQRINELIDESLAMSGERR
CLHFSPQAARIWTDYYNDVESKLGGLGPLRHCREYAAKNAEYMARLAGLIHHSSGEEGDI
SPYTAEMARELAIWYGNEY-----VRLSNPLTFDNPALTVPV-RLIPEELELFNWI---K
SYCIEK----GIP---CMKKNDILQRGPNR------FR-------KKDKINWLLDLLYEQ
NRVVPVIEGKTLCVA---------------------------PNFDL-------------
------
>Arabidopsis_thaliana_AT3G23710.1
MNSNIFPPSKQQNELNNIQQSFSNLQSQCSNLLLNVSQTLNPLFNANTNNNKPNIFSALN
SFRDQAKQALDSRIS----------------RFNSGKAPVWARISD--------------
------DGGGARAQVTVPIRGSGKGLSADAIEERLAGV----------------------
--------------------------------PVYA----------LSNSNEEFVLVSGT
SS-------------------GKSL------------------------------GLLFC
KEE---------------------------------------------------------
-----------------DAETLLKEMKSMD------------------------------
-------PRMRK--EGSKV-----VALALSKVFQLKVNGVAF-RLIPESTQVKNALKERK
TAGIDDDDFHGVP---VFQSKSLILRSENMSYRPVFFR-------KEDLEKSLIRASSQQ
NRLNPALKPGDIQVAV--FEDIVKGMRES-TTSNWDDIVFIPPGFEVSTEQT--------
----QE
>Arabidopsis_thaliana_AT4G33350.1
MESSV----------------------------------------------KPNPFLSFS
SFIHHQCTRFSSDLSARIEDTKRFAETLATRRFSLPTPPPFASVSQ--------------
------SKSGTPTTT----------LSPSLVAKALAGT----------------------
--------------------------------SVFT----------VSNTNNEFVLISDP
TG-------------------GKSI------------------------------GLLCF
RQE---------------------------------------------------------
-----------------DAEAFLAQAR-LR------------------------------
-------RRELK--TNAKV-----VPITLDQVYLLKVEGISF-RFLPDPIQIKNAL-ELK
SSG-NKNGFDGVP---VFQSELLVVRKKNRRYCPVYFS-------KEDIERELSKYTRAS
R--------GDQQIMVGSLEDVLRKMEMSEKNSGWEDVIFIPPGRSYAQHMQDLI-----
----KE
>gnl|BL_ORD_ID|4568	@Flavobacterium_johnsoniae_UW101@ gi|146302335|ref|YP_001196926.1| unnamed protein product [Flavobacterium johnsoniae UW101]	
MKKSI----------------------------------------------TAIALFIIS
FFLHENCFSQASK-KTKFKVLVLYENGGHHLAFSKAAKP---------------------
------------------------------------------------WLNKLAAENNFT
IDYIENTKTINESLLNQYRLFIQLDYPP----YTWSEESMKAFQKYMNDGK---------
---------------------GGWI------------------------------GL---
------------------------------------------------------------
-----------------HHATLLGEFDGYP------------------------------
----------------------------IWNWFSDLMGGIRFVNYIPDFASAKVIV-EDK
VHPVMK----GVPADFLVQKEEWYTYDKSPRKIVHVLA-------SVD------ESTYQP
D---SKIKMGDHPVVWTNEHFTSRNVYIFMGHS---------PNLFDNKAYTALFKNAIL
WASNKK
>gnl|BL_ORD_ID|388	@Ehrlichia_canis_Jake@ gi|73667022|ref|YP_303038.1| dihydroneopterin aldolase [Ehrlichia canis str. Jake]	
MKIQI-----------------------------------HDL-----------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------AVYT------------------------
-----------------------CI------------------------------GL---
------------------------------------------------------------
------------------------------------------------------------
--------RRWEKVIRQKIIVDCDVTLYCYNAISDIEDTIDY-SLFTD--SLINFA----
----NSNSFELLE---IMASELLDYIMKDKRICHCYLKLYKPTAINID------------
---------GKVSVELESMQNDV-------------------------------------
----NT
