>gnl|BL_ORD_ID|1202	Escherichia_coli_UTI89 gi|91210123|ref|YP_540109.1| hypothetical protein UTI89_C1094 [Escherichia coli UTI89]	
MKREAFMCLLAPENPYPIYALPPLVRNAIIETQKNTQAPLAMVATSALTATSIACQNQVDVCRPGNLRGPVNLYSLILADSGERKTTVDKVFMKAFYLRDEALAEEYAKLVENYSTEKEIWEQKQKALESKLHKEIRAGKGCKATESELKRHLNKCPVPPQIRRTIFNETTIEGMLKYYSDSNRSFALVSSEGGIIFDGRAMSKLGILNSLWDGGSLFIDRKSSPGIILKDPRLTVSVMIQPDVYQKGFCTRKKELVKTSGHHARFLMCQPTSTQGTRIITGDNYSSQYQDLFEQRINELIDESLAMSGERRCLHFSPQAARIWTDYYNDVESKLGGLGPLRHCREYAAKNAEYMARLAGLIHHSSGEEGDISPYTAEMARELAIWYGNEYVRLSNPLTFDNPALTVPVRLIPEELELFNWIKSYCIEKGIPCMKKNDILQRGPNRFRKKDKINWLLDLLYEQNRVVPVIEGKTLCVAPNFDL
>gnl|BL_ORD_ID|4568	@Flavobacterium_johnsoniae_UW101@ gi|146302335|ref|YP_001196926.1| unnamed protein product [Flavobacterium johnsoniae UW101]	
MKKSITAIALFIISFFLHENCFSQASKKTKFKVLVLYENGGHHLAFSKAAKPWLNKLAAENNFTIDYIENTKTINESLLNQYRLFIQLDYPPYTWSEESMKAFQKYMNDGKGGWIGLHHATLLGEFDGYPIWNWFSDLMGGIRFVNYIPDFASAKVIVEDKVHPVMKGVPADFLVQKEEWYTYDKSPRKIVHVLASVDESTYQPDSKIKMGDHPVVWTNEHFTSRNVYIFMGHSPNLFDNKAYTALFKNAILWASNKK
>gnl|BL_ORD_ID|388	@Ehrlichia_canis_Jake@ gi|73667022|ref|YP_303038.1| dihydroneopterin aldolase [Ehrlichia canis str. Jake]	
MKIQIHDLAVYTCIGLRRWEKVIRQKIIVDCDVTLYCYNAISDIEDTIDYSLFTDSLINFANSNSFELLEIMASELLDYIMKDKRICHCYLKLYKPTAINIDGKVSVELESMQNDVNT
>Arabidopsis_thaliana_AT3G23710.1
MN------------------------SNIFPPSKQQNELNNIQ-----------------
--QSFSNLQS------------------------------------QCSNLLLNVSQTLN
PLFNANTNNNKPNIFSALNSFRD-QAKQALDSRISRFN-----SGKAPVWARISDD---G
GGARAQVT-VPIRGSGK-----GLSADAIEERLAGVPVYALSNSNEE----FVLVSGT-S
SG-------------KSLGLLFCKEEDAETLLKE-----MKSMDPRMRKEGSKVVALALS
KVFQL--------KV-NG-------------------------------------VAFRL
IPESTQVKNA--LKERKTAGID--DDDFHGVPVFQ-----------------------SK
SLILRSEN----MSYRPVFFRKEDLEKSLIRASSQQNRLNPAL-----------------
-------------------------------------K-PGDIQVAVFEDIVKGMRE---
------S-TT--SNWDDIV--F----------------------------IPPGFEVSTE
QTQE--------------------------------------------------------
--------------

>Arabidopsis_thaliana_AT4G33350.1
MESS------------------------------------VKP-----------------
--NPFLSFSSFIHH--------------------------------QCTRFSSDLSARI-
-----------------EDTKRFAETLATRRF----------SLPTPPPFASVS------
-----QSKSG---TPTT-----TLSPSLVAKALAGTSVFTVSNTNNE----FVLISDP-T
GG-------------KSIGLLCFRQEDAEAFLAQ-----ARLRRRELK-TNAKVVPITLD
QVYLL--------KV-EG-------------------------------------ISFRF
LPDPIQIKNA--LELKSSGN----KNGFDGVPVFQ-----------------------SE
LLVVRKKN----RRYCPVYFSKEDIERELSKYTRASRG----------------------
---------------------------------------DQQIMVGSLEDVLRKMEM---
------SEKN--SGWEDVI--F----------------------------IPPGRSYAQH
MQDLIKE-----------------------------------------------------
--------------

