>Synechocystis_sp_PCC_6803__637011978_slr0924_hypothetical_protein_[Synechocystis_sp._PCC_6803]	
M-----------------------------------------------------------
------------------------------PWLQTFSFRRSPFSLARRHLKNKIFVKIKS
IFLLSLLF--------EATATMKSLLRIGATLGLIG--------------------TTAI
GTWLG--------------------------------------T-------TLQALALPT
EEVVKILQGVPVFTIVDAQGAPL---VAVGND-----N---------EKVTGVFISQQEA
NGFLQELKKQK------------------------PDV-GSQVSVQPVSLGEVVKIAQAN
AN--QTD---------PLGFAYVPIPAQVQAAQQMPNSE------------YQGGVPLFV
AR-GGEDQGYLTIQ----QENEQ-------------------IIPFFLEASQIQQMVER-
--------------------------------------------FKQEQPAMADSIV---
-------------------------------------------------------IDVIA
MENVISTLQTS-------------------------DD--AMLKQIRIVPT---------
-----QEAIQFIRSLSAQQPK---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------
>Anabaena_sp_PCC_7120_gnl_BL_ORD_ID_113_alr0114_hypothetical_protein
M-----------------------------------------------------------
------------------------------------------------------------
----------------------KALVRWGATLGLVG--------------------STLL
GTLSL--------------------------------------G-------SLPAIALSE
QQIKEKLDSVPIYLVTNEKGLPLSRPLPNAPNGQKA-G---------GSITGAYMSRQEA
QAFINELRNAKNKDPKM------------------QEI-VKSLQVTAVPLGVIYQQLQQT
KKDPN-----------RLLFAFKPVDQEIKGAMDLLRQS-G------QQVNQFKSVPMFA
VR-FAPDQGYVPIK--VGTGNEQ-------------------VVPLFLSKQDAQGLLGQ-
--------------------------------------------VKPKHPKAD-------
-------------------------------------------------------IQVLD
IDGVLQTLQDK-------------------------ND--TWLNQVVLVPS---------
-----PESREYIRTLPKPPNTPAAPNRNNNNSRPGAK-----------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------
>Gloeobacter_violaceus_PCC_7421__637461026_glr3613_hypothetical_protein_[Gloeobacter_violaceus_PCC_7	
M-----------------------------------------------------------
------------------------------------------------------------
----------------------KRRVQGWAAAILVS--------------------SI--
-------------------------------------------------VWSGEVLALTQ
AQIIEKLKPVVLFTVATADGKPL---LSLPPDGSK--G---------PLVAGVYFSPQDA
EAFVAAFKKKD------------------------AAR-GGQLRVQPVSLGNLYRLRLES
RG--TEE---------EVTLAFFANRTEVEWALSLLQAA-G------RKPEDLQGAPLFA
ATVNAGKKQYLTLQ----QNNRT-------------------VVPVYFTKQEMTAFIDR-
--------------------------------------------YRRQQANANVPVT---
-------------------------------------------------------VEVLD
LEGILEALQEP-------------------------TD--SQTKKVMLVTP---------
-----KAALDYARTQSGSPIPTVQPPKSPPAEGLAPTPDPH-------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------
>Synechococcus_sp_PCC_7002__641611608_SYNPCC7002_A1598_hypothetical_protein_[Synechococcus_sp._PCC_7	
M-----------------------------------------------------------
------------------------------------------------------------
TAYFFRINFSNLAVILFEVLFMKSLVRLGQKALLMG--------------------TVIA
GTILG--------------------------------------V-------NGSVLALPE
AAVVEKLRPIPMYMLINDEGQPI---FATVTDQNGG-E---------SGVTGVFVSLSDA
ENLVAARQTESKRLLDAERAKPNADPQIVAELEAQAAL-WQEANVLPIGLDKIYQFAQSD
EA--E-----------DLTFKFLPTMAQLNAAAQVTQQE------------NFPGVPLFF
----------LSIQ----EKDANGQDIVSFPTLAGDDNNGNGEIPVFFEVQPILEQLDA-
--------------------------------------------FPEDEELS--------
-------------------------------------------------------INVMP
LEVFIAKLLDE----------------------DLPAEEQEFLESMTLIPS---------
-----TESAQLIQAVIEQQRQQQ-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------
>Synechococcus_sp_PCC_7335__647578192_S7335_3895_hypothetical_protein_[Synechococcus_sp._PCC_7335]	
M-----------------------------------------------------------
------------------------------------------------------------
---------------------KLSIRRIFAQVLAIG--------------------TLGL
GPMAI--------------------------------------G-----LLSAPVLALSE
EQIVQQREAVLSFILEDEEGPIA--------------G---------PDGILVFVTLQSA
SDYIAANRLED----------------------------TDTIKVIPTNLERIHQVAEEI
EGE-------------PLRITLVPEEAEVENARDIDPDYQG-------------GVPLFY
AQ-LPNGAFAPLWQ----PDGEV-------------------VFPLYFSRSDLDESLAR-
--------------------------------------------LPQEELGIE-------
-------------------------------------------------------VAVIP
LQVILQEIHTS-------------------------DN--EDLSRIRMLSP---------
------QVVDAIRAASEEAENTAPSDEPEAQ-----------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------
>Arabidopsis_thaliana_AT3G23710.1
M--------------------------------------------NSNIFPPSKQQNELN
NIQQSFSNLQSQCSNLLLNVSQTLNPLFN---ANTNNNKPNIFSALNSFRDQAKQALDS-
---------------------RISRFNSGKA-PVWA--------------------RISD
DGGGA--------------------------------------RAQVTVPIRGSGKGLSA
DAIEERLAGVPVYALSNSNEEFV---LVSGTSS----G---------KSLGLLFCKEEDA
ETLLKEMKSMD------------------------PRMRKEGSKVVALALSKVFQLKVN-
----------------GVAFRLIPESTQVKNALKERKTA-G------IDDDDFHGVPVFQ
SK-S------LILR----SENMS-------------------YRPVFFRKEDLEKSLIR-
--------------------------------------------ASSQQNRLNPALKPGD
-------------------------------------------------------IQVAV
FEDIVKGMRES-------------------------TT--SNWDDIVFIPP---------
-----GFEVSTEQTQE--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------
>Brassica_rapa_gnl_BL_ORD_ID_19281__028338_PACid_22702791
M--------------------------------------------DSNVSSSSKQQKHL-
TLQQSFSNIQTQCSDLLNNVSKTLNPLFN---PNSN----NIFSALDSFRAQAKQALDS-
---------------------GFSRFASGNTPPLWA--------------------RISD
DGG----------------------------------------KTHVAPIRRSSGPGLSA
DDMEERLAGVPVYALSNSNEEFV---LVSGTAT----G---------KSLGLLFCKAEDA
EALLNQMKAMD------------------------PRMRKEGSKVVALALSKVFQLKVN-
----------------GVAFRLIPESTQVQNALKERKTA-G------FTDDDFNGVPVFQ
SK-S------LILR----SDNKS-------------------YRPVFFRKEDLEKSLTR-
--------------------------------------------ASRQQNRLNPALKPGD
-------------------------------------------------------IQVAV
FEEIVKGMKEN-------------------------AT--SNWDDIVFIPP---------
-----GFEVSTEETKD--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------
>Brachypodium_distachyon_gnl_BL_ORD_ID_10569__4g27410.1_PACid_21813339
M-----------------------------------------------------------
---------PFDFPWL-KNPAATSTPNPN----PSKPSNPNPFLAIQAHLTSFLSSLPL-
-------------------------PRAL--PPPWA--------------------RIPS
SS--------------------------------------------------SSPVALPV
AEIEDRLSGVPVYALANSSQEFV---LVSKTHGGGAEGESS-GARPPPALGVLCFRREDA
DALLAQMD---------------------------GTM-RAGSTVVPVALNKVIQLKSD-
----------------GVAFRFLPDFTQVANAMKLMQDE-GQ-----LVNEGFLGVPVFQ
SR-S------LVLM----SDSKR-------------------CRPVFFRKEDLDNSLHR-
--------------------------------------------ASRDQQKPNP-VRIGD
-------------------------------------------------------TQVSS
LEDMITSMKDS-------------------------SS--STWDDVVFIPP---------
-----GFDLATGSK----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------
>Oryza_sativa_gnl_BL_ORD_ID_18324__LOC_Os07g19030.1_PACid_21900796
M-----------------------------------------------------------
-------PFHFQFPWLPNNPTSSSSSPTK----PPSPAIPNPFLPIQAGLASFLSSLPL-
-------------------------PRAAFPPPPWA--------------------RISS
AS-----------------------------------------------ASAASASALPV
AEIEERLAGVPVYALANSSQEFV---LVSSARGGGGGGGGARAAVPPPALGLLCFRREDA
DALLAQMD---------------------------GDM-AAGSTVVPVALNKVIQLKSD-
----------------GVAFRFVPDSSQVANAMKLMENE-GQ-----YVNDGFPGVPVFQ
SR-S------LVLM----SDNKR-------------------YRPVFFRKEDLDNSLHR-
--------------------------------------------ASRDQQKPNPAVKMGD
-------------------------------------------------------IQVSS
LENIIKSMKDS-------------------------SS--SKWDDAVFIPP---------
-----GFDLATSSKQSNHDN----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------
>Arabidopsis_thaliana_AT4G33350.1
M-----------------------------------------------------------
----------------------------------ESSVKPNPFLSFSSFIHHQCTRFSSD
LS-------ARIEDTKRFAETLATRRFSLPTPPPFA--------------------SVSQ
S------------------------------------------------KSGTPTTTLSP
SLVAKALAGTSVFTVSNTNNEFV---LISDPTG----G---------KSIGLLCFRQEDA
EAFLAQARLRR------------------------REL-KTNAKVVPITLDQVYLLKVE-
----------------GISFRFLPDPIQIKNALELKSSG---------NKNGFDGVPVFQ
SE-L------LVVR----KKNRR-------------------YCPVYFSKEDIERELSK-
--------------------------------------------YTRASRGDQQ------
-------------------------------------------------------IMVGS
LEDVLRKMEMS------------------------EKN--SGWEDVIFIPP---------
-----GRSYAQHMQDLIKE-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------
>Brassica_rapa_gnl_BL_ORD_ID_20295__011434_PACid_22703805
M-----------------------------------------------------------
--------------------------------ESSSSVKPNPFL---SFLHHHCTRFASD
LS-------SRFEDTKRLAESLTNRRFS---PSPFA--------------------SVSQ
S---------------------------------------------PKPSSGASTTTLNP
SHVAKALAGTSVFTVSNTNNEFV---LISDPTG----D---------KSIGLLCFRQEDA
EAFLAQARLRR------------------------REL-KTNAKVVPINLDQVYLLKVE-
----------------GISFRFLPDPIQIKNALELKSSS---------SKNGFDGVPVFQ
SE-L------LVVR----KKNKR-------------------YCPIYFSKEDIERELSK-
--------------------------------------------YTRA---DQQ------
-------------------------------------------------------IMVGS
LEDVLRKMERS------------------------EKN--SGWEDMIFIPP---------
-----GRSYAQHMQEVVKEIK---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------
>Brachypodium_distachyon_gnl_BL_ORD_ID_15294__1g45996.1_PACid_21818064
M----------------------------------------------------------P
PP------NSTRSSSLPLAAAPMSNP------SPSSSPPPNPLAAASSFLQHHLSNLAS-
-------------------------RFAAP-RPALA------------------------
AAHPP--------------------------------------G--PQG--SSLSLALAP
DEVARALTGTPVFTVCNSSNEFV---LVSDPATG---L---------RSLGLLCFRSEDA
DALLSHVRTRQ------------------------PVL-GKGAKVVPITLDQVYMLKAE-
----------------GIAFRFLPDPLQIKNALELKSGL-----------TGFDGVPVFQ
SD-L------LVVK----KQKKR-------------------YCPIYFQKEDIERELKK-
--------------------------------------------ASKGSKGSALLKQ---
-------------------------------------------------------IMVGS
LEDVLKKMEIN------------------------DRN--SGWDDMIFIPP---------
-----GKSLNQHINEDCYRKRE--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------
>Oryza_sativa_gnl_BL_ORD_ID_49360__LOC_Os06g11020.1_PACid_21931832
M----------------------------------------------------------P
PPPPNSSSSSSSSSSLPLAAAPMSNPSAPSSSSSSSSLPPNPLAAASSFLHHHLSRLAS-
-------------------------RFAAPPRPALA--------------------AVTA
SAAPP--------------------------------------G--PQGASASLSLALAP
DEVARALTGTPVFTVCNSSNEFV---LVSDPATG---L---------RSLGLLCFRSEDA
DALLTHVRMRQ------------------------PVV-GRGAKVVPITLDQVYMLKAE-
----------------GIAFRFLPDPLQIKNALELKSGL-----------TAFDGVPVFQ
SD-L------LVVK----KQKKR-------------------YCPIYFQK----------
------------------------------------------------------------
------------------------------------------------------------
-------LRRT-------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------
>Chlamydomonas_reinhardtii_gnl_BL_ORD_ID_2091__14.g625750.t1.1_PACid_19860381
M-----------------------------------------------------------
----------------------------------------------REGVTRWLERTPLA
---------QIIRNAQEGVATQQRQRDQGPWAPMLA--------------------SIAM
SGAGP--------------------------------------R-----PQPVMDLAMAK
DEVKARLAPVPVYTVANPKNEFV---LVAGEN-----N---------TQLGFFFFRKEDA
EALIEKIREEN------------------------PRL-ARDSKILRVPMDNVYEVFTTP
RE--QTGLQ-------GIHFRFMPDMKQVAHALQLYKDA-G------VPTRQFIGVPVFQ
AE-G------LTVT----TRDMQ-------------------YVPLFLCKEDLDIAVQS-
--------------------------------------------AYVQRNAAQIKLYKDK
ADKYQADYDQIASQLEAAANGRERGGLESRLAKARVKLEAARDKVESVERAPLPKVEVGS
FEEVVMRMTAS------------------------AGNELAAWSQVMFVAP---------
-----ELLRDSAGAGGKK------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------
>Volvox_carteri_gnl_BL_ORD_ID_8007__Vocar20001833m_PACid_23131891
M-----------------------------------------------------------
-------ERNEGPLQHLQRSLDHVGRGLASQWQQLPAQVERTFVPMRQGVSRWWEQTPIA
---------QIIRNVQEAAAAPPRVRDQGPWAPLLA--------------------SITM
GSAAH--------------------------------------R-----PQPVMDLAMAK
EEVKARLAPVPVYTVANPKNEFV---LVAGEN-----H---------TQLGFFFFRKEDA
EALIEKIREEN------------------------PRL-ARDSKILRVTMDNVYEVFTTP
RE--QTGLQ-------GIHFRFMPDMKQVAHALELYKAA-G------VPTRQFIGVPVFQ
AE-G------LTVT----TRDMQ-------------------YVPLFLCKEDLDIAIQS-
--------------------------------------------AYMQRNAAQIKLYKDK
ADKYQADYEQIASQLESAS-GRERSGLESKLAKARAKLDAAREKVESVERAPLPKVEVGS
FEEVVMRMTAS------------------------SGNELAAWSQVMFVAP---------
-----ALLQEASKGGAAAKK----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------
>Cyanophora_paradoxa_gnl_BL_ORD_ID_26154__Cyanophora_paradoxa__ConsensusfromContig52820-maker-ConsensusfromContig52820-snap-gene-0.3-mRNA-1_cds_10085/8432-8552_0_-
M----------------------------------------------------------A
SFAATLITSAVCAAPARQRSAESVPARQPASSRLFGASKRSDFFGVRAAADSRPVFRPVS
VPTISMSLKEEDVSGEETSEARSKL--AGAAIAVAG--------------------VAGI
AAFGV--------------------------------------M-----TQSESAEAIDR
ATLTKQLSEVPVFTIVDASNKPI---VASNWGEE---K---------GRFVVFYFSRKDA
MAALPKARA--------------------------GQP-GKNLKVMTVGLDKAYKLTKDA
EAAAKSGAAVDAGSDAGIQARYVPVAKQIKNAVDVLKTQ-G------RKVTHFNGTPIYQ
AE-G------LTMR--QGNDTRQ-------------------FIPLFFTKEDLEAAWAE-
--------------------------------------------MRRGNPAMSPQPRIEA
RPPPALSFL----------------------------------------------LSVGA
FEELMKRMEDT-------------------------DS--PEWQRVVFFAP---------
-----KESLDFVGQPRW-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------
>Cyanidioschyzon_merolae_gnl_BL_ORD_ID_1500__Cyanidioschyzon_merolae__gnl_CMER_CMJ105C_similar_to_chloroplast_inner_membrane_protein_Tic22
M-----------------------------------------------------------
-SAFAVPAAHPARRQRPALGLDRPLVPRWSSKRQVLFHRGRPLVTFRKHLLSATERVCLS
--------EQRTPGVVGQPAPETSWMQRAARALLLGLATVNIWTPLLRGFSLGAGLQVLL
GAPAV--------------------------------------S-----AAKTPHARYSR
KTLSEKLAQVPVFAVTNESGQPF---LAAMER-----G---------LQVGLIFFDPDDA
IKMLEDLKRSS------------------------GKE-AEDARIFIMGLDRAFEMVKSK
PQ--PSGLRGPRGDELKMVFRFYPNQQQLEYARTVAKKT---------KQPTVRGVPCFV
AK-G------LTLR----KGKEF-------------------VIPIFLDKRDLDEAWNR-
--------------------------------------------LRQELAELPKQPE---
-------------------------------------------------------IEVGD
LIEVILRLEEA-----------------AKNPKSLNETELQDLRRVAFFPS---------
-----SKSVEFMKRESAKQFKGTARMHSRP------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------
>Synechococcus_elongatus_PCC_7942__gi_81300671_ref_YP_400879.1__unnamed_protein_product_[Synechococc	
M-----------------------------------------------------------
------------------------------------------------------------
----------------------NKFLTSAAALVISL--------------------SGGV
AIPLI--------------------------------------A-------PPAAIALSD
QEVAARIGRVPVFVILTKEQQPL---LFTSRDKDGKEV---------NKTFPVFINQTQA
QAALAELQKSN------------------------QPL-GKDARIGSLLLPKALELILDF
LK--KTNDP-------KVTYEIIPDPKQRAKALELYKADKNIKPEQLKQLESEAFVPIFY
SE-S------LSIT----MTNQQGQPV------KDAKGNAIRRIPLFLEYEPLAAELEK-
--------------------------------------------LKKQDTNAKAGEYA--
-------------------------------------------------------ITVTD
LLTIINTLTAA--------------------------QPGSNESLIELLPP---------
-----VSSLPVLQELVKQLTPTNGTTPPRATTTTPPAAGTGTTPPRATNPTPTPRPAN--
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------
>at5g62650_i|18424615|ref|NP_568958.1| Tic22-like family protein [Arabidopsis thaliana]
M----------------------------------G--SPDKQHRRHVAAEFLHSAVT--
-----------SISSSIIPLFPPKTAPSRVCLPLRFSVSDDVSSPFESTVK--STSSASS
-----------------SGLNSTVRISSLSSD--GK--------------------RGGP
AFVGQ--------------------------------------VFSMCDLTGTGLMA---
--VSTHFDIP-FISKRTPEWLKKMFSTITKSER----N---------GPVFRFFMDLGDA
VSYVKKLNI-------------------------------PSGVVGACRLDLAYEHFKEK
----------------PHLFQFVPNERQVKAANKLLKSMPQN-----GKTQKVEGVPVFG
AQ-N------LDIAVATADGIKW-------------------YTPYFFDKAVLDNILEE-
--------------------------------------------SVDQHFHTLIQTRHVQ
RRRDVVDDS----LASEVM-----------------------------EEMGDSMLEPPE
VQEAMEEIGTSGIPLSVV-AKAAEIQLLYAVDRVLLGS--RWFRKATGIQPKLPYLVDSF
ERRS-AFSIQRASGSATRCLG----DSVEADTSASLLR--VEDD-------------SPS
EAEKR---QQHLWFPFG--D-----W--------ISHSVSRKEHTHHKGSSDQRDMESRE
REMLRSPFLPKITMVGISTGEAAQMSKANLKKTMEDLTEDLEQSDEGNDHGSKRYDSLKI
EERDPLFVANVGDYYSGLAKAGSARLSRRGDDQ--------
>Brassica_rapa_gnl|BL_ORD_ID|11888 _010109|PACid:22695398
M----------------------------------D--SPDKIHRRYNAAEILHGAAT--
-----------SI-SSIIPLFPPKTTPSRVCLPLRFS---DV-SPFESTVKNASSTSTSS
-----------------SGLNSTVRISSLSSD--GK--------------------RGGP
AFVGQ--------------------------------------VFSMCDLTGTGLMA---
--VSTHFDIP-FISKRTPEWLKKMFSTITKSER----K---------GPVFRFFMDLGDA
VSYVKKLNI-------------------------------PSGVVGACRLDLAYEHFKEK
----------------PHLFQFVPNERQVKAANKLLKSMPPS-----EKKQRVDGVPVFA
AQ-N------LDIAVATSDGIKW-------------------YTPYFFDKAVLDNILEE-
--------------------------------------------SVDQHFHTLIQTRHVQ
RRRDVVDDS----LTSEIM-----------------------------EEMGDSMLEPPE
VQEAMEEIGTSGIPLSVV-AKAAEIQLLYAVDRVLLGS--RWFRKATGIQPKLPYLVDSF
ERRS-ALSIQRASGSTTKCLG----DS---NSSASLLK--VEDG-------------SPS
EEEKR---QQSLWFPFG--D-----W--------LK---------AQKDSSGQREMESRE
REMQRSPFLPKITMVGISTGEAAHMSKANLKKTMEDLTQDLEQSDEGSDHGSNRYDPLKI
EERDPLFVANVGDYYSGLARAGSARWSRRGDDRNETPPRSS
>Brachypodium_distachyon_gnl|BL_ORD_ID|2714 _2g07450.1|PACid:21805484
M----------------------------------P--------SSSSSSNPFHSLTF--
-----------NL-----PFPPAPSSCSTSAS-SPPAPAPHLAFPLLLPVSSASTTSSYS
PASHLIPQPQRLPGERMAGPAAASGGKGVSAG--KS--------------------PGGP
AFVGQ--------------------------------------VFTMLDPSGNGLMA---
--VTSRFDLPHFIAHRTPTWFKRILSPLKKSE-----S---------SPVFRFFMDLNDS
VSYVKRLNV-------------------------------PSGMVGACRLDVAYEHFKEK
----------------PHMFQFVPNEKQVKAANKLLKSIPQK-----SRRKKLAGVPVFS
AQ-N------LNIAVATDDGIRW-------------------YSPYFFDKNLLDNILEA-
--------------------------------------------SMDQHFHSIIQNRHIR
RRRDIVDDS----LTSEIL-----------------------------EESADSLLEPPE
VQELMNEIGPAGIPLSVV-TKAAEIQLLDVVDKLLLGN--KWLRKATGIQPRFPYVVDSF
EERT-ALSVDRTATSSNSCTASKDADFFTNDQQSQALEPNVDSG-------------NHR
KHNSRDHGQSH--FPFS--NLLPNIW--------PGHDRKFKA--QEHDNRFKRYGASMD
NDLQANPLLPKITMVGISMSEGGQMSKANLKKTMEELTKELEQAGEKT---------VFS
DEKDPLFVANVGDY-SRITKISST-----------------
>Oryza_sativa_gnl|BL_ORD_ID|20689 _LOC_Os01g12550.1|PACid:21903161
M----------------------------------PRGRSTTTTTSSSASNPFHAFAS--
-----------TL-----PFLPSPSPSPTSASPSPSPPAPHLAVPLILPITSSSSASAAA
AS------PESNRGARMA--AAASGGKAGGGGGLGK--------------------GGGP
AFVGQ--------------------------------------VFTMLDPSGNGLMA---
--VTTRFELPQFLASRTPMWFKRILSPLKKSE-----N---------GPVFRFFMDLNDA
VSYVKRLNV-------------------------------PSGMVGACRLDVAYEHFKEK
----------------PQMFQFVPSEKQVKAANKLLKSLPQR-----RRRKKLDGVPVFS
AQ-N------LNIAVATNDGIRW-------------------YTPYFFDKNLLDNILEA-
--------------------------------------------SMDQHFHSMVQNRHTR
RRRDIVDDS----LTSEMM-----------------------------EESADSFLEPPE
VQELMNEIGPVGIPLNVV-TKAAEIQFLDVVDKMLLGN--KWLRKATGIQPQFPYVVDSF
EERT-AAAIDRAATASSSFTASKDADCFQISKQPETLESDVDNS-------------NRG
KHENSNNGQSH--FPFS--NLLPNIW--------PGHDRSFKA--QGRDRAFRRCDASIN
NDLQANPLLPKITMVGISMGEGGQMSKANLKKTMEDLTKELEQAGEKT---------IFS
DEKDPLFVANVGDY-SRITKISST-----------------
>Physcomitrella_patens_gnl|BL_ORD_ID|36425 _Pp1s68_153V6.1|PACid:18072962
MGRNRDTCNVPGCSKDEKPCLVTGPKIVSFKLPNPALFSSWVQTVTSNLAWTVQSFQTLK
TDGLNCLSLLVEHKPMVSPLPVPYLALNNLIFPVPSS---------------TSSVQVCQ
KAVSSIPQ------------DHFSKGNAVNEKGEVS--------------------STGP
AFIGQ--------------------------------------VYTMCDASRQGLIAVRP
SDVLKKIKVPPYMKLMEKAYERAMNVLFTDDM-----K---------GPVFRFYFNKDDA
AEYVRRLNI-------------------------------TGSAVGPCSLDAAYKYYKSK
----------------EGMFKFIADQRQVKVAKELVRRERGD-----KAANKLKGVPVFT
AR-N------LTIALSTPQGVRW-------------------FRPYFFNKKQLDSLIGH-
--------------------------------------------SVDHYYEMLISARRAQ
RYSQIAENNGDAFAGGESM-----------------------------DDELDGLMDPPE
VQELMEELGQGGGGMEFVGLKVLEAQFMDLADRVLLGH--QWSRRMIHLQPRFPVIVDSF
ERLISASELDHSSESEGSVTSSRNSFAKKEGTQEKSQRGQGDEGMSISGRDERSASNDSS
ESVSKEYSQSS---PNSLFNLFKKKWGANANLVFKRKDSGNAEILEEDSDSEYLQETAQK
DPPGKIPFQPKLTMMGISMN--VNKVEGGLQQAMAAAAKDVEDRLRKGE--------GSG
PDHGPLFIANLGSGIPQWGRPVSASSGVLDDDAE-------
>Selaginella_moellendorffii_gnl|BL_ORD_ID|1621 _424522|PACid:15402899
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------EIGSVPLHLAYKFFKER
----------------PSLFSFIPSKKQVDLAKTIIKKEQGG-----KAAQQFQGVPVFT
SH-C------LSILVVGPSGARW-------------------FRPHFFKKEELDGVIRS-
--------------------------------------------SMEHHYQSLIRNRRAR
RHNQVSDFP------SDMA-----------------------------EDDLE-MLESQD
IQDFVEDMDEWSSVLESIMAKAAQMYFQDTLDRAIFGN--KWCRMLAGIQPSFPILVDSF
ERRV-TSETENAVVSHHEQKKPHKDWDSTCQLKRALIR----------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------
