>Synechocystis_sp_PCC_6803__637011978_slr0924_hypothetical_protein_[Synechocystis_sp._PCC_6803]	
M----------------PWLQTFSFRRSPFSLARRHLKNKIFVKIKSIFLLSLLFEATAT
MK-SLLRIGA--------------------------------------------------
-------------------------------------TLGLIGTTAIGTWLGT-------
--------------------TLQALALPTEEVVKILQGVPVFTIV-----DAQGAP----
---------L---VAVGNDNE----------K----VTGVFISQQEANGFLQEL------
-----KKQK-------------PDVG-SQVSVQPVSLGEVVKIAQANA---N--QTD---
----PLGFAYVPIPAQVQAAQQMPNSEY------Q------GGVPLFVARG----GEDQG
YLTIQ--QEN--EQ-------------IIPFFLEASQIQQMVERFKQEQPAMADSIV---
---------IDV----------------------------------------------IA
MENVISTLQTSD-----DA----------MLKQIRI----------VPTQEAIQFIRSL-
----------------------SAQQPK--------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------
>Anabaena_sp_PCC_7120_gnl_BL_ORD_ID_113_alr0114_hypothetical_protein
M-----------------------------------------------------------
------------------------------------------------------------
-----------------------------KALVRWGATLGLVGSTLLGTLSL--------
-------------------GSLPAIALSEQQIKEKLDSVPIYLVT-----NEKGLP----
---------LSRPLPNAPNGQ----------KAGGSITGAYMSRQEAQAFINELRNAKNK
DPKMQEIV-------------------KSLQVTAVPLGVIYQQLQQTKKDPN--------
----RLLFAFKPVDQEIKGAMDLLRQSG-------QQVNQFKSVPMFAVRF----APDQG
YVPIKVGTGN--EQ-------------VVPLFLSKQDAQGLLGQVKPKHPKADIQV----
----------------------------------------------------------LD
IDGVLQTL---------------QDKNDTWLNQVVL----------VPSPESREYIRTLP
KPPNTPAAPNRNNNNSRPGAK---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------
>Gloeobacter_violaceus_PCC_7421__637461026_glr3613_hypothetical_protein_[Gloeobacter_violaceus_PCC_7	
------------------------------------------------------------
MK-RRVQGWA--------------------------------------------------
-------------------------------------AAILVSSIVW-------------
--------------------SGEVLALTQAQIIEKLKPVVLFTVA-----TADGKP----
---------L---LSLPPDGS----------K-GPLVAGVYFSPQDAEAFVAAF------
-----KKKD-------------AARG-GQLRVQPVSLGNLYRLRLESR---G--TEE---
----EVTLAFFANRTEVEWALSLLQAAG------RK-PEDLQGAPLFAATV---NAGKKQ
YLTLQ--QNN--RT-------------VVPVYFTKQEMTAFIDRYRRQQANANVPVT---
---------VEV----------------------------------------------LD
LEGILEALQEPT-----DS----------QTKKVML----------VTPKAALDYARTQS
GSPIPTVQPPKSPPAEGLA---PTPDPH--------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------
>Synechococcus_sp_PCC_7002__641611608_SYNPCC7002_A1598_hypothetical_protein_[Synechococcus_sp._PCC_7	
M-----------------------------------------------------------
------------------------------------------------------------
---TAYFFRINFSNLAVILFEVLFMKSLVRLGQKALLMGTVIAGTILG------------
-------------------VNGSVLALPEAAVVEKLRPIPMYMLI-----NDEGQP----
---------IFATVTDQNGGE-------------SGVTGVFVSLSDAENLVAARQTESKR
LLDAERAKPNADPQIVAELEAQAALW-QEANVLPIGLDKIYQFAQSD-------EAE---
----DLTFKFLPTMAQLNAAAQVTQQEN------------FPGVPLFFLSIQEKDANGQD
IVSFPTLAGD-----------DNNGNGEIPVFFEVQPILEQLDAFPEDEELS--------
---------INV----------------------------------------------MP
LEVFIAKL----------LDEDLPAEEQEFLESMTL----------IPSTESAQLIQAVI
EQQRQQQ-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------
>Synechococcus_sp_PCC_7335__647578192_S7335_3895_hypothetical_protein_[Synechococcus_sp._PCC_7335]	
M-----------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------KLSIRRI
FAQVLAIGTLGLGPMAIGLLSAPVLALSEEQIVQQREAVLSFILE-----DEEGP-----
--------------IAGPDGI-----------------LVFVTLQSASDYIAANRLEDT-
---------------------------DTIKVIPTNLERIHQVAEEI-------EGE---
----PLRITLVPEEAEVENARDIDPDY-------------QGGVPLFYAQL---------
------------PNGAFAPLWQPDGEVVFPLYFSRSDLDESLARLPQEELGIEVAV----
----------------------------------------------------------IP
LQVILQEIHTSD---------------NEDLSRIRM----------LSPQVVDAIRAASE
EAENTAPSDEPEAQ----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------
>Tic22-III_Arabidopsis_thaliana_AT3G23710.1
-----------------M----------------------NSNIFPPSKQQNELNNIQQS
FSN----LQS-------QCSNLLLNVSQTLNPLFNANT-----------N-NNKPNIFSA
LNSFRDQAKQALDSRI---SRFNS----GKAPVWARISDDGGGA---RAQVTVP------
-------------------IRGSGKGLSADAIEERLAGVPVYALS-----NSNEEF----
---------V---LVSGTSSG-------------KSLGLLFCKEEDAETLLKEM------
-----KSMD-------------PRMRKEGSKVVALALSKVFQL-----------KVN---
----GVAFRLIPESTQVKNALKERKTAG------ID-DDDFHGVPVFQSKS---------
-LILR--SEN--MS-------------YRPVFFRKEDLEKSLIRASSQQNRLNPALKPGD
---------IQV----------------------------------------------AV
FEDIVKGMRES------TT--S-------NWDDIVF----------IPPGFEVSTEQTQE
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------
>Oryza_sativa_gnl_BL_ORD_ID_18324__LOC_Os07g19030.1_PACid_21900796
M----------------PFHFQFPWLPNNPT------------SSSSSPTKPPSPAIPNP
FLP----IQA-------GLASFL-------------------------------------
-------------------SSLPLPRAAFPPPPWARISSASA------------------
-------------------SAASASALPVAEIEERLAGVPVYALA-----NSSQEF----
---------V---LVSSARGGGGGGGGARAAVPPPALGLLCFRREDADALLAQ-------
-------MD-------------GDMA-AGSTVVPVALNKVIQL-----------KSD---
----GVAFRFVPDSSQVANAMKLMENEG------QYVNDGFPGVPVFQSRS---------
-LVLM--SDN--KR-------------YRPVFFRKEDLDNSLHRASRDQQKPNPAVKMGD
---------IQV----------------------------------------------SS
LENIIKSMKDS------SS--S-------KWDDAVF----------IPPGFDLATSSKQS
---NHDN-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------
>Tic22_IV_Arabidopsis_thaliana_AT4G33350.1
----------------------------------------ME-----------SSVKPNP
FLSFSSFIHH-------QCTRFSSDLSAR-------------------------------
IEDTKRFAETLATRRF-------------SLPTPPPFASVSQS----KSG----------
---------------------TPTTTLSPSLVAKALAGTSVFTVS-----NTNNEF----
---------V---LISDP-TG------------GKSIGLLCFRQEDAEAFLAQA------
-----RLRR-------------RELK-TNAKVVPITLDQVYLL-----------KVE---
----GISFRFLPDPIQIKNALELKSSGN---------KNGFDGVPVFQSEL---------
-LVVR--KKN--RR-------------YCPVYFSKEDIERELSKYTRASRG---D---QQ
---------IMV----------------------------------------------GS
LEDVLRKMEMSE-----KN--S-------GWEDVIF----------IPPGRSYAQHMQD-
---LIKE-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------
>Oryza_sativa_gnl_BL_ORD_ID_49360__LOC_Os06g11020.1_PACid_21931832
M----------------PPPPPNSSSSSSSSSSLPLAAAPMSNPSAPSSSSSSSSLPPNP
LAAASSFLHH-------HLSRLASRFAAP-------------------------------
-----------------------------PRPALAAVTASAAPP---GPQGASA------
-------------------SLS--LALAPDEVARALTGTPVFTVC-----NSSNEF----
---------V---LVSDPATG------------LRSLGLLCFRSEDADALLTHV------
-----RMRQ-------------PVVG-RGAKVVPITLDQVYML-----------KAE---
----GIAFRFLPDPLQIKNALELKSG-----------LTAFDGVPVFQSDL---------
-LVVK--KQK--KR-------------YCPIYFQK-------------------------
------------------------------------------------------------
----LRRT----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------
>Chlamydomonas_reinhardtii_gnl_BL_ORD_ID_2091__14.g625750.t1.1_PACid_19860381
M-----------------------------------------------------------
---------------------------------------------------REGVTRWLE
RTPLAQIIRNAQEGVA---TQQRQRDQGPWAPMLASIAMSGAGPRP--------------
-------------------QPVMDLAMAKDEVKARLAPVPVYTVA-----NPKNEF----
---------V---LVAGENNT--------------QLGFFFFRKEDAEALIEKI------
-----REEN-------------PRLA-RDSKILRVPMDNVYEVFTTPR---EQTGLQ---
----GIHFRFMPDMKQVAHALQLYKDAG-------VPTRQFIGVPVFQAEG---------
-LTVT--TRD--MQ-------------YVPLFLCKEDLDIAVQSAYVQRNAAQIKLYKDK
ADKYQADYDQIASQLEAAANGRERGGLESRLAKARVKLEAARDKVESVERAPLPKVEVGS
FEEVVMRMTASA------------GNELAAWSQVMF----------VAPELLRDSAGAGG
KK----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------
>Volvox_carteri_gnl_BL_ORD_ID_8007__Vocar20001833m_PACid_23131891
M-----------------------------------------------------------
------------ERNEGPLQHLQRSLDHVGRGLASQWQQLPAQVERTFVPMRQGVSRWWE
QTPIAQIIRNVQEAAA---APPRVRDQGPWAPLLASITMGSAAHRP--------------
-------------------QPVMDLAMAKEEVKARLAPVPVYTVA-----NPKNEF----
---------V---LVAGENHT--------------QLGFFFFRKEDAEALIEKI------
-----REEN-------------PRLA-RDSKILRVTMDNVYEVFTTPR---EQTGLQ---
----GIHFRFMPDMKQVAHALELYKAAG-------VPTRQFIGVPVFQAEG---------
-LTVT--TRD--MQ-------------YVPLFLCKEDLDIAIQSAYMQRNAAQIKLYKDK
ADKYQADYEQIASQLESAS-GRERSGLESKLAKARAKLDAAREKVESVERAPLPKVEVGS
FEEVVMRMTASS------------GNELAAWSQVMF----------VAPALLQEASKGGA
AAKK--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------
>Cons_100%_Plants_green-alga
X----------------XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXX--XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXX---XXXXXXXXXXXXPXXXXXXXXXXXXXX-XXXXXXX------
-------------------XXXXXXXXXXXXXXXXLXXXXVXXXX-----NXXXEF----
---------V---LXXXXXXXXXXXXXXXXXXXXXXXGXXXXXXEDAXXXXXXX------
-----XXXX-------------XXXXXXXXXXXXXXXXXVXXXXXXXX---XXXXXX---
----GXXFRXXPXXXQXXXAXXXXXXXX------XXXXXXFXGVPVFQXXX---------
-LXXX--XXX--XX-------------YXPXXXXKXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXX-----XX--X--XXXXXXXXXXXX----------XXXXXXXXXXXXXX
XXXXXXX-----------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------
>Cyanophora_paradoxa_gnl_BL_ORD_ID_26154__Cyanophora_paradoxa__ConsensusfromContig52820-maker-ConsensusfromContig52820-snap-gene-0.3-mRNA-1_cds_10085/8432-8552_0_-
M-----------------------------------------------------------
-------------------ASFAATLITSAVCAAPARQ-----------RSAESVPARQP
ASSRLFGASKRSDFFG---VRAAADSRPVFRPVSVPTISMSLKEEDVSGEETSEARSKLA
GAAIAVAGVAGIAAFGVMTQSESAEAIDRATLTKQLSEVPVFTIV-----DASNKP----
---------I---VASNWGEE------------KGRFVVFYFSRKDAMAALPKARAGQPG
---------------------------KNLKVMTVGLDKAYKLTKDAEAAAKSGAAV-DA
GSDAGIQARYVPVAKQIKNAVDVLKTQG-------RKVTHFNGTPIYQAEG---------
-LTMR--QGNDTRQ-------------FIPLFFTKEDLEAAWAEMRRGNPAMSPQPRIEA
RPPPALSFLLSV----------------------------------------------GA
FEELMKRMEDTDSP---------------EWQRVVF----------FAPKESLDFVGQPR
W-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------
>Cyanidioschyzon_merolae_gnl_BL_ORD_ID_1500__Cyanidioschyzon_merolae__gnl_CMER_CMJ105C_similar_to_chloroplast_inner_membrane_protein_Tic22
M----------------SAF--------------------AVPAAHPARRQRPALGLDRP
LVPRWSSKRQVLFHRGRPLVTFRKHLLSATERVCLSEQ-----------RTPGVVGQPAP
ETSWMQRAARALLLGL---ATVNI-----WTPLLRGFSLGAGLQVLLGAPAVSA------
-------------------AKTPHARYSRKTLSEKLAQVPVFAVT-----NESGQP----
---------F---LAAMERGL--------------QVGLIFFDPDDAIKMLEDL------
-----KRSS-------------GKEA-EDARIFIMGLDRAFEMVKSKP---QPSGLRGPR
GDELKMVFRFYPNQQQLEYARTVAKKTK---------QPTVRGVPCFVAKG---------
-LTLR--KGK--EF-------------VIPIFLDKRDLDEAWNRLRQELAELPKQ---PE
---------IEV----------------------------------------------GD
LIEVILRLEEAA-----KNPKSLNETELQDLRRVAF----------FPSSKSVEFMKRES
AKQFKGTARMHSRP----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------
>at5g62650_i|18424615|ref|NP_568958.1| Tic22-like family protein [Arabidopsis thaliana]
M----------------G-SPD-----KQHRRHV---AAEFLHSAVTSISSSIIPLFPPK
TAP--------------SRVCLPLRFSVSD------------------------------
------DVSSP--------------FESTVK--STSSASSSGLNSTVRISSLSSDGK---
-------------------R-GGPAFVGQVFSMCDLTGTGLMAVS-----THFDIP-FIS
KRTPEWLKKMFSTITKSERNG--------------PVFRFFMDLGDAVSYVKKLNI----
---------------------------PSGVVGACRLDLAYEHF----------KEK---
----PHLFQFVPNERQVKAANKLLKSMP-----QNGKTQKVEGVPVFGAQN---------
-LDIAVATADGIKW-------------YTPYFFDKAVLDNILEESVDQHFHTLIQTRHVQ
RRRDVVDDSLAS---------------------------------EVMEEMGDSMLEPPE
VQEAMEEIGTSGIPL-SVVAKAAEIQLLYAVDRVLLGSRWFRKATGIQPKLPYLVDSFER
RS-AFSIQRASGSATRCLGD-SVEA------DTSASLLRVED-DSPSEA-E---------
-------KRQQ--HLWFPFGDWISHSVSRKEHTHHKGSSDQRDM-----ESREREML---
--RSPFLPKITMVGISTGEAAQMSKANLKKTMEDLTEDLEQSDEGND-HGSKRYDSLKIE
ERDPLFVANVGDYYSGL-AKAGSARLSRRGDDQ
>Oryza_sativa_gnl|BL_ORD_ID|20689 _LOC_Os01g12550.1|PACid:21903161
M----------------PRGRSTTTTTSSSASNP-------FHAFA-ST-LPFLPSPSPS
-PTSASPSPSP----PAPHLAVPLILPITS-----------------------------S
SSASAAAAS--------------------PESNRGARMA--AAASGGKAGGGGGLGK---
-------------------G-GGPAFVGQVFTMLDPSGNGLMAVT-----TRFELPQFLA
SRTPMWFKRILSPLKKSE-NG--------------PVFRFFMDLNDAVSYVKRLNV----
---------------------------PSGMVGACRLDVAYEHF----------KEK---
----PQMFQFVPSEKQVKAANKLLKSLP-----QRRRRKKLDGVPVFSAQN---------
-LNIAVATNDGIRW-------------YTPYFFDKNLLDNILEASMDQHFHSMVQNRHTR
RRRDIVDDSLTS---------------------------------EMMEESADSFLEPPE
VQELMNEIGPVGIPL-NVVTKAAEIQFLDVVDKMLLGNKWLRKATGIQPQFPYVVDSFEE
RT-AAAIDRAATASSSFTAS-KDADCFQISKQPETLESDVDN--SNRGK-H---------
-------ENSNNGQSHFPFSNLLPNIWPGHDRSFKAQGRDRA--FRRCDASINNDLQ---
--ANPLLPKITMVGISMGEGGQMSKANLKKTMEDLTKELEQAGEKTI----------FSD
EKDPLFVANVGDY-SRI-TKISST---------
>Oryza_sativa_gnl|BL_ORD_ID|20689 _LOC_Os01g12550.1|PACid:21903161
M----------------PRGRSTTTTTSSSASNP-------FHAFA-ST-LPFLPSPSPS
-PTSASPSPSP----PAPHLAVPLILPITS-----------------------------S
SSASAAAAS--------------------PESNRGARMA--AAASGGKAGGGGGLGK---
-------------------G-GGPAFVGQVFTMLDPSGNGLMAVT-----TRFELPQFLA
SRTPMWFKRILSPLKKSE-NG--------------PVFRFFMDLNDAVSYVKRLNV----
---------------------------PSGMVGACRLDVAYEHF----------KEK---
----PQMFQFVPSEKQVKAANKLLKSLP-----QRRRRKKLDGVPVFSAQN---------
-LNIAVATNDGIRW-------------YTPYFFDKNLLDNILEASMDQHFHSMVQNRHTR
RRRDIVDDSLTS---------------------------------EMMEESADSFLEPPE
VQELMNEIGPVGIPL-NVVTKAAEIQFLDVVDKMLLGNKWLRKATGIQPQFPYVVDSFEE
RT-AAAIDRAATASSSFTAS-KDADCFQISKQPETLESDVDN--SNRGK-H---------
-------ENSNNGQSHFPFSNLLPNIWPGHDRSFKAQGRDRA--FRRCDASINNDLQ---
--ANPLLPKITMVGISMGEGGQMSKANLKKTMEDLTKELEQAGEKTI----------FSD
EKDPLFVANVGDY-SRI-TKISST---------
>Cons.100%_Tic22-cons_and_at562650
X----------------XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXX---XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---
-------------------XXXXXXXXXXXXXXXXXXXXXXXXXX-----XXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXDAXXXXXXXXX----
-----XXXX-------------XXXXXXXXXXXXXXXXXXXXXXXXXX---XXXXXX---
----XXXFXXXPXXXQXXXAXXXXXXXX-----XXXXXXXXXGVPVFXXXX---------
-LXXXXXXXXXXXX-------------YXPXXXXKXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXX-XXXXXXXXXXXXXXXXXXXXX-XXXXXX-X---------
-------XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX---
--XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-XXXXXXXXXXXX
XXXXXXXXXXXXXXXXX-XXXXXXXXXXXXXXX
>Physcomitrella_patens_gnl|BL_ORD_ID|36425 _Pp1s68_153V6.1|PACid:18072962
MGRNRDTCNVPGCSKDEKPCLVTGPKIVSFKLPNPALFSSWVQTVTSNLAWTVQSFQTLK
TDGLNCLSLLVEHKPMVSPLPVPYLALNNL------------------------------
--------------------IFPVPSSTSSVQVCQKAVSSIPQDHFSKGNAVNEKGEV--
-------------------SSTGPAFIGQVYTMCDASRQGLIAVRPSDVLKKIKVP-PYM
KLMEKAYERAMNVLFTDDMKG--------------PVFRFYFNKDDAAEYVRRLNI----
---------------------------TGSAVGPCSLDAAYKYY----------KSK---
----EGMFKFIADQRQVKVAKELVRRER-----GDKAANKLKGVPVFTARN---------
-LTIALSTPQGVRW-------------FRPYFFNKKQLDSLIGHSVDHYYEMLISARRAQ
RYSQIAENNGDAFAG-----G------------------------ESMDDELDGLMDPPE
VQELMEELGQGGGGMEFVGLKVLEAQFMDLADRVLLGHQWSRRMIHLQPRFPVIVDSFER
LISASELDHSSESEGSVTSS-RNSFAKKEGTQEKSQRGQGDEGMSISGRDERSASNDSSE
SVSKEYSQSSPNSLFNLFKKKWGANANLVFKRKDSGNAEILE--EDSDSEYLQETAQKDP
PGKIPFQPKLTMMGISMNV--NKVEGGLQQAMAAAAKDVEDRLRKGEGSGPDH-------
--GPLFIANLGSGIPQWGRPVSASSGVLDDDAE
>Physcomitrella_patens_gnl|BL_ORD_ID|36425 _Pp1s68_153V6.1|PACid:18072962
MGRNRDTCNVPGCSKDEKPCLVTGPKIVSFKLPNPALFSSWVQTVTSNLAWTVQSFQTLK
TDGLNCLSLLVEHKPMVSPLPVPYLALNNL------------------------------
--------------------IFPVPSSTSSVQVCQKAVSSIPQDHFSKGNAVNEKGEV--
-------------------SSTGPAFIGQVYTMCDASRQGLIAVRPSDVLKKIKVP-PYM
KLMEKAYERAMNVLFTDDMKG--------------PVFRFYFNKDDAAEYVRRLNI----
---------------------------TGSAVGPCSLDAAYKYY----------KSK---
----EGMFKFIADQRQVKVAKELVRRER-----GDKAANKLKGVPVFTARN---------
-LTIALSTPQGVRW-------------FRPYFFNKKQLDSLIGHSVDHYYEMLISARRAQ
RYSQIAENNGDAFAG-----G------------------------ESMDDELDGLMDPPE
VQELMEELGQGGGGMEFVGLKVLEAQFMDLADRVLLGHQWSRRMIHLQPRFPVIVDSFER
LISASELDHSSESEGSVTSS-RNSFAKKEGTQEKSQRGQGDEGMSISGRDERSASNDSSE
SVSKEYSQSSPNSLFNLFKKKWGANANLVFKRKDSGNAEILE--EDSDSEYLQETAQKDP
PGKIPFQPKLTMMGISMNV--NKVEGGLQQAMAAAAKDVEDRLRKGEGSGPDH-------
--GPLFIANLGSGIPQWGRPVSASSGVLDDDAE
>Selaginella_moellendorffii_gnl|BL_ORD_ID|1621 _424522|PACid:15402899
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------EIGSVPLHLAYKFF----------KER---
----PSLFSFIPSKKQVDLAKTIIKKEQ-----GGKAAQQFQGVPVFTSHC---------
-LSILVVGPSGARW-------------FRPHFFKKEELDGVIRSSMEHHYQSLIRNRRAR
RHNQVSDFP------------------------------------SDMAEDDLEMLESQD
IQDFVEDMDEWSSVLESIMAKAAQMYFQDTLDRAIFGNKWCRMLAGIQPSFPILVDSFER
RV-TSETENAVVSHHEQKKPHKDWDSTCQLKRALIR------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------
>Selaginella_moellendorffii_gnl|BL_ORD_ID|1621 _424522|PACid:15402899
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------EIGSVPLHLAYKFF----------KER---
----PSLFSFIPSKKQVDLAKTIIKKEQ-----GGKAAQQFQGVPVFTSHC---------
-LSILVVGPSGARW-------------FRPHFFKKEELDGVIRSSMEHHYQSLIRNRRAR
RHNQVSDFP------------------------------------SDMAEDDLEMLESQD
IQDFVEDMDEWSSVLESIMAKAAQMYFQDTLDRAIFGNKWCRMLAGIQPSFPILVDSFER
RV-TSETENAVVSHHEQKKPHKDWDSTCQLKRALIR------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------
>Cons.100%_all_plants
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXX---XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
-----XXXX-------------XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXQXXXAXXXXXXXX-----XXXXXXXXXGXPXXXXXX---------
-LXXXXXXXXXXXX-------------XXPXXXXKXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
>Cons.100%_all_sequences
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXAXXXXXXXX-----XXXXXXXXXXXPXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXPXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
>conserved_regions
------------------------------------------------------------
------------------------------------------------------------
-------------------------------P----------------------------
-----------------------------------L----V---------N---EF----
---------V---L-----------------------G------EDA-------------
---------------------------------------V--------------------
----G--FR--P---Q---A--------------------F-GVPVFQ------------
-L-------------------------Y-P----K-------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------
