>iTic22-like_gi|18424615|ref|NP_568958.1| Tic22-like family protein [Arabidopsis thaliana]
MGSP----------------------DKQHRRHV---AAEFLH-----------------
SAVTSIS----------------SSIIPLFPPKTA--P---------------SRVCLPL
RFSVSD-------------------------DVSSP---FESTVK--STSSASSSGLNST
VRISSLSSDGK-----R-GGPAFVGQVFSMCDLTGTGLMAVS-----THFDIP-FISKRT
PEWLKKMFSTITKSERNGPVFRFFMDLGDAVSYVKKLNI--------------PSGVVGA
CRLDLAYEHFKEKPHLFQFVPNERQVK--AANKLLKSMPQNGKTQKVEGVPVFGAQNLDI
AVATADGIKWYTPYFFDKAVLDNILEESVDQHFHTLIQTRHVQRRRDVVDDSLAS----E
VMEEMGDSMLEPPEVQEAMEEIGT-SGIP---------LSVVA-KAA-------------
----------EIQLLYAVDRVLLGSRWFRKATGIQPKLPYLVDSFERR-SAFSIQRASGS
ATRCLGD-SVEA------DTSASLLRVED-------------DSPSEAEKRQ--QHLWFP
FGDWISHSVSRKEH---THHKGSSDQR-----DMESREREMLRS-----PFLPKITMVGI
STG----EAA-QMSKANLKK---TMEDLTEDLEQSDEGND-HGSKRYDSLKIE-----ER
DPLFVANV-------------------------------------------GDYYSGL-A
KAG----SARLSRRGDDQ--------
>Arabidopsis_lyrata_gnl|BL_ORD_ID|26695 _496448|PACid:16060442
MGSP----------------------DKQHRRHV---AAEFLH-----------------
SAVT--------------------SIIPLFPPKTA--P---------------SRVCLPL
RFSVSD-------------------------DVSSP---FESTVK--SSSSTSSSGLNST
VRISSLSSDGK-----R-GGPAFVGQVFSMCDLTGTGLMAVS-----THFDIP-FISKRT
PEWLKKMFSTITKSERNGPVFRFFMDLGDAVSYVKKLNI--------------PSGVVGA
CRLDLAYEHFKEKPHLFQFVPNERQVK--AANKLLKSMPQNGRKQKVEGVPVFGAQNLDI
AVATADGIKWYTPYFFDKAVLDNILEESVDQHFHTLIQTRHVQRRRDVVDDSLAS----E
VMEEMGDSMLEPPEVQEAMEEIGS-SGIP---------LSVVA-KAA-------------
----------EIQLLYAVDRVLLGSRWFRKATGIQPKLPYLVDSFERR-SAFSIQRASGS
ATRCLGD-SVEA------DTSASLLRVED-------------NSPSEDEKRQ--QNLWFP
FGDWINHSESKKEH---THHKGPSDGR-----DMESREREMLRS-----PFLPKITMVGI
STG----EAA-QMSKANLKK---TMEDLTEDLEQSDEGND-HGSKRYDPRKME-----ER
DPLFVANV-------------------------------------------GDYYSGM-A
KAG----SARLSRRGDDQ--------
>Capsella_rubella_gnl|BL_ORD_ID|25653 _v10028359m|PACid:20911489
MGSP----------------------EKQHRRHI---AAEFLH-----------------
SAVTSIS----------------SSIVPLFPPKTT--P---------------SRVWLPL
KFSVSD-------------------------DVSSP---FESTVN--SKSSKSSSGLNST
VRISSLSSDGK-----R-GGPAFVGQVFSMCDLTGTGLMAVS-----THFDIP-FISKRT
PEWLKKMFSTITKSERNGPVFRFFMDLGDAVSYVKKLNI--------------PSGVVGA
CRLDLAYEHFKEKPHLFQFVPNERQVK--AANKLLKSMPQNGKKQKVDGVPVFGAQNLDI
AVATADGIKWYTPYFFDKAVLDNILDESVDQHFHTLIQTRHVQRRRDVVDDSLTS----E
VMEEMGDSMLEPPEVQEAMEEIGS-SGIP---------LSVVA-KAA-------------
----------EIQLLYAVDRVLLGSRWFRKATGIQPKLPYLVDSFERR-SALSIQRASGS
AARCLSD-SVET------DTSASLLRVEEG------------DSPREDEKRR--QNLWFP
FGDWLKHSVSRKDQ---AHQKGSSGQR-----DMESRDREMLQS-----PFLPKITMVGI
STG----EAA-QMSKANLKK---TMEDLTEDLEQSDEGND-HGSKRYDPLKIE-----ER
DPLFVANV-------------------------------------------GDYYSGL-A
KAG----SARLSRRGDDQ--------
>Thellungiella_halophila_gnl|BL_ORD_ID|20311 _Thhalv10003967m|PACid:20199916
MDLP----------------------DKQHRRHI---ATEFLH-----------------
SAATSI-----------------SSIIPLFPPKAT--P---------------SRVCLPL
RFSVSD-------------------------DV-FP---FDSTVRNASSASTSSSSLNST
VRISSLSSDGK-----R-GGPAFVGQVFSMCDLTGTGLMAVS-----THFDIP-FISKRT
PEWLKKMFSSITKSERNGPVFRFFMDLGDAVSYVKKLNI--------------PSGVVGA
CRLDLAYEHFKEKPHLFQFVPNERQVK--AANKLLKSMPPNGKKQKVEGVPVFGAQNLDI
AVATADGIKWYTPYFFDKAVLDNILEESVDQHFHTLIQTRHVQRRRDVVDDSLTS----E
VMEEMGDSMLEPPEVQEAMEEIGT-SGIP---------LSVVA-KAA-------------
----------EIQLLYAVDRVLLGSRWFRKATGIQPKLPYLVDSFERR-SAFSIQRASGS
TSRCIGD-SAEA------DTSASLRRVED-------------DSPSEDEKRQ--QNLWFP
FGDWLNHSGSRKEH---A-QKVTSDQR-----EMECREREMQQS-----PFLPKITMVGI
STG----EAA-QMSKANLKK---TMEDLTEGLEQSDEGSSEHGSKRYDPLKME-----ER
DPLFVANV-------------------------------------------GDYYSGL-A
KAG----SARWSRRGGDSNETHPRS-
>Brassica_rapa_gnl|BL_ORD_ID|11888 _010109|PACid:22695398
MDSP----------------------DKIHRRYN---AAEILH-----------------
GAATSI-----------------SSIIPLFPPKTT--P---------------SRVCLPL
RFS----------------------------DV-SP---FESTVKNASSTSTSSSGLNST
VRISSLSSDGK-----R-GGPAFVGQVFSMCDLTGTGLMAVS-----THFDIP-FISKRT
PEWLKKMFSTITKSERKGPVFRFFMDLGDAVSYVKKLNI--------------PSGVVGA
CRLDLAYEHFKEKPHLFQFVPNERQVK--AANKLLKSMPPSEKKQRVDGVPVFAAQNLDI
AVATSDGIKWYTPYFFDKAVLDNILEESVDQHFHTLIQTRHVQRRRDVVDDSLTS----E
IMEEMGDSMLEPPEVQEAMEEIGT-SGIP---------LSVVA-KAA-------------
----------EIQLLYAVDRVLLGSRWFRKATGIQPKLPYLVDSFERR-SALSIQRASGS
TTKCLGD-S---------NSSASLLKVED-------------GSPSEEEKRQ--QSLWFP
FGDWLK------------AQKDSSGQR-----EMESREREMQRS-----PFLPKITMVGI
STG----EAA-HMSKANLKK---TMEDLTQDLEQSDEGSD-HGSNRYDPLKIE-----ER
DPLFVANV-------------------------------------------GDYYSGL-A
RAG----SARWSRRGDDRNETPPRSS
>Citrus_clementina_gnl|BL_ORD_ID|24296 _0.9_006877m|PACid:19275444
MASP-----------------A-EP---NHLQNQ---ISSFIN-----------------
ATTSTL-----------------FSLITP--TKTT--PSSQSQPSSAPA----SRLCIPL
QFADSSC-------P------SSSTRSPVGSDSIS-------SNSGASSSESSSSGFPST
VRISAINSSGK-----G-GGPAFVGQVFSMCDLSGTGLMAVS-----THFDIP-FISKRT
PEWLKKLFATITKSERNGPVFRFFMDLGDAVTYVKQLNI--------------PSGVVGA
CRLDLAYEHFKEKPHLFQFVPNEKQVK--AANKLLRTIPDSGRKKKVDGVPVFSAQNLDI
AIATADGIKWYTPYFFDKNMLDNILEESVDQHFHALIQTRHMQRRRDVIDDNLAA----E
VVEEIGDSIWEPPEVQEMMDEIGH-PAIP---------LSVIS-KAA-------------
----------EIQLLYAVDRVLLGNRWLRKATGIQPKFPYMVDSFENR-SAASFLRASES
TSCLANS-ET--------NNGSSDLKLED-------------KHLDK-RDQR--PDFRFP
FGDWFRHLWSKQDC---EAQGSSY---------IECTKRNLQLN-----PFLPKVTMVGI
STG----EAG-QMTKANLKK---TMENLTKELEQTDQENA--TSSGSNEYIIE-----DR
DPLFVANV-------------------------------------------GGYYSGL-A
KTG----STRWVRGRSNN--------
>Citrus_sinensis_gnl|BL_ORD_ID|32460 _1.1g009199m|PACid:18125400
MASP-----------------A-EP---NHLQNQ---ISSFIN-----------------
ATTSTL-----------------FSLITP--TKTT--PSSQSQPSSAPA----SRLCIPL
QFADSSC-------P------SSSTRSPVGSDSIS-------SNSGASSSESSSSGFPST
VRISAINSSGK-----G-GGPAFVGQVFSMCDLSGTGLMAVS-----THFDIP-FISKRT
PEWLKKLFATITKSERNGPVFRFFMDLGDAVTYVKQLNI--------------PSGVVGA
CRLDLAYEHFKEKPHLFQFVPNEKQVK--AANKLLRTIPDSGRKKKVDGVPVFSAQNLDI
AIATADGIKWYTPYFFDKNMLDNILEESVDQHFHALIQTRHMQRRRDVIDDNLAA----E
VVEEIGDSIWEPPEVQEMMDEIGH-PAIP---------LSVIS-KAA-------------
----------EIQLLYAVDRVLLGNRWLRKATGIQPKFPYMVDSFENR-SAASFLRASES
TSCLANS-ET--------NNGSSDLKLED-------------KHLDK-RDQR--PDFRFP
FGDWFRHLWSKQDC---EAQGSSY---------IECTKRNLQLN-----PFLPKVTMVGI
STG----EAG-QMTKANLKK---TMENLTKELEQTDQENA--TSSGSNEYIIE-----DR
DPLFVANV-------------------------------------------GGYYSGL-A
KTG----STRWVRGRSNN--------
>Manihot_esculenta_gnl|BL_ORD_ID|29919 _4.1_003879m|PACid:17989925
MASS-----------------T-QPAPNRHH-------SNLFH-----------------
SATTAL-----------------ISLVSS--PKAS--PLS-TIPLCP------PKICIPF
QFADSSY-------PLIQ--SIRSPFDSNQPESVSP---KSAAVKGL-SSAESNSGFPST
VRIAGLKSNGK-----S-GGPAFVGQVFSMCDLSGTGLMAVS-----THFDIP-FISKRT
PEWLKKIFATVTKSERNGPVFRFFIDLGDAVAYVKRLNI--------------PSGVVGA
CRLDLAYEHFKEKPHLFQFVPNEKQVK--AANQLLKKIPQGNGRRKVDGVPVFTAQNLDI
AIATADGIKWYTPYFFDKNMLDNILEESVDQHFHSLIQTRHMQRRRDVVDDNLAA----E
VIEEMGDNMLEPPEVQEMLDEMGH-PGIP---------LSVIS-KAA-------------
----------EIQLLHAVDRVLLGNRWLRKATGIQPKFPYMVDSFEKR-SASSFQRASES
TSYLANP-KT---------DSTSNCTFKD-------------NAQAD-HEQK--TDLRIP
FGDWFRHPWLKQKW---KPEKLPEIRS--HESLSECTKQKLERN-----SFLPKITMVGI
STG----EAG-QMSKASLKK---TMEDLTRELEQTDRENA---TVGRLECNVRILILLTE
APRNIENVLMLSNILSLARYRENFSIVICFWECILSPYSLSSFPLSYPDRQGGTFSSLYE
ESGFSILTGLYGSSGIFAKETLHSWI
>Ricinus_communis_gnl|BL_ORD_ID|23216 _30169.m006582|PACid:16821381
MSLS--------------------PDPNHHHQ-----PSNFFH-----------------
SATTAI-----------------TSLISTN-PKTS--PSS-TIPLSP------PKICIPF
QFADSSYR------PL-----TRSSFESTHPDSVSP---KSAAVKGL-SSAESSSGFPST
VRIAGLNSNGK-----G-GGPAFVGQVFSMCDLSGTGLMAVS-----THFDIP-FISKRT
PEWLKKVFTTVTKSERKGPVFRFFMDLGDAVTYVKRLNI--------------PSGVVGA
CRLDLAYEHFKEKPHLFQFVPNEKQVK--AANQLLKTIPQSDGRRKVDGVPVFSAQNLDI
AIATTDGIKWYTPYFFDKSMLDNILEESVDQHFHALIQTRHMQRRRDVIDDNLAA----E
VIEEMGDSMLEPPEVQEMMDEIGH-PAIP---------LNVIS-KAA-------------
----------EIQLLYAVDRVILGNRWLRKATGIQPKFPYMVDSFEKR-SASSFRRASEP
ASYLAKS-KT--------DADTSKLNLED-------------GAQAN-HEPI--TDLRLQ
FGDWFKSLGLKQQQ---KPEKGSEI--------SECRKQKLEMN-----PFLPKITMVGI
STG----EAG-QMSKASLKK---TMEDLTRELEHTDRENAPGSSNNGNDLEME-----DR
DPLFVANV-------------------------------------------GDYYSGM-S
KTN----SPRLVRGGSK---------
>Populus_trichocarpa_gnl|BL_ORD_ID|3641 _POPTR_0017s00970.1|PACid:18209660
MPSP-----------------P-EPPQHRHNNHH---LSNFLN-----------------
STTKTL-----------------FSLLSP--PNIL--------PLAPPQ----PKICISF
HLPNAPL-------PLTQ--STLSLFESTQPDSLSPSKSSSASVKDI-SSAESNSGFPSA
VRIGRLNPNGN-----G-GGPAFVGQVFSMCDLSGTGLMAVS-----THFDVP-FISKRT
PEWLKKIFATVTKSERNGPVFRFFMDLGDAVAYVKRLNI--------------PSGVVGA
CRLDLAYEHFKEKPHLFQFVPNEKQVK--AANQLLKSIPHGDGSRRVDGVPVFSAQNLDI
AIATTDGIKWYTPYFFDKNMLDNILEESVDQHFHALIQTRHMQRRRDVIDDNVAA----E
VIEEMGDSLLEPPEVQEVLDEMGH-PAIP---------LSVIS-KAA-------------
----------EIQLLYAVDKVLLGNRWLRKATGIQPKFPYLVDSFERR-SASSLRRALES
TSCLANS-KI--------DDSTSEHKLKD-------------NVQTD-HEQR--KDLRLP
FGDWFSHPWLKKHS---KSERESDTRK--EGLSKDCLKWKSESN-----PFLPKVTMVGV
STG----DAG-QLSKSSLKK---TMEDLTKELEQTDEANDSFISNSSSEFKVN-----DR
DPLFVANV-------------------------------------------GDYYSGM-A
KTG----ISR----------------
>Malus_domestica_gnl|BL_ORD_ID|44230 _0000777828|PACid:22664215
MASP-----------------S-EPPHTRQQLRP--SITHLVH-----------------
STTSNL-----------------LSLLAS--PKTT--PSP-SLSTTP------PEIRVAL
FLPNLPK-------PL--------AF---QPDS------KLSAMKGVASSPESTSGFPST
VRIAGLNSNIK-----GSGGPAFVGQVFSMCDLSGTGLMAVS-----THFDIP-FISKRT
PEWLKKMFKSITNSERNGPVFRFFMDLGDAVTYVKRLNI--------------PSGVVGA
CRLDLAYEHFKEKPHLFQFVPNEKQVK--AANKLLKTMPQSGRCKRVDGVPVFSAQNLDI
AIASSDGIKWYTPYFFDKNMLDNILEESVDQHFHSLIQTRHTQRRHDVIDDNIPA----E
VIEEMGDNLWEPPEVQEVMDEIGN-SGIP---------LSVIS-KAA-------------
----------EMQLLYAVDKVLLGNRWLRKATGIQPKFPYMVDSFERR-SAASFLRASQS
ARCLTNG-EAVNDNEDSLDCSTSKIKSKD-------------DIHTN-KGNK--TDLRFP
FSDWFSHLWSKQKD---QNEELS----------KERIEQSTLQN-----PNLPKITMVGI
STG----AAG-PMSKANLKK---TMEDLTKELEQTDSGNA-FGSDTGNELRFE-----DR
DPLFVANV-------------------------------------------GDYYSGM-A
KTG----SAKWVRGGNN---------
>Prunus_persica_gnl|BL_ORD_ID|26753 _ppa003928m|PACid:17667413
MASP-----------------T-EPAH-KKQARP---ITHLVH-----------------
STAANL-----------------LSLFAS--PKTT--PS------TP------STIRVAF
LFPNSPK-------PL--------AFHSAQPDF-------KSAMKGVESSSESNSGFPST
VRIAGLNSNIK-----G-GGPAFVGQVFSMCDLSGTGLMAVS-----THFDIP-FISKRT
PEWLKKMFASVTNSERNGPVFRFFMDLGDAVTYVKRLNI--------------PSGVVGA
CRLDLAYEHFKEKPHLFQFVPNEKQVK--AANKLLKAMQQNGRCKRVDGVPVFSAQNLDI
AIASSDGIKWYTPYFFDKNMLDNILEESVDQHFHSLIQTRHMQRRRDVIDDSLPA----E
VIEEMGDNLWEPPEVQEVMDEMGN-PGIP---------LSVIS-KAA-------------
----------EMQLLYAVDKVLLGNRWLRKATGIQPKFPYMVDSFERR-SAASFLRASQS
SNRLANR-EAVNDNKDSVHCSTSEVKLND-------------DIQTN-KGNK--LDLRFP
FGDWFSHLLLKQKD---QTEELS----------KECVELSSQQN-----PNLPKITMVGI
STG----EAG-QMSKATLKK---TMEDLTKELEQPDAGNA-GGSDMSNELRFE-----DR
DPLFVANV-------------------------------------------GDYYSGM-A
RTG----SARWVRGGNN---------
>Carica_papaya_gnl|BL_ORD_ID|1469 _evm.model.supercontig_107.127|PACid:16405310
MASA-----------------TDQPQHNFHHR-----IANLLH-----------------
ATSSSL-----------------SFLLPS--PKTA--P----YPPSP------PKLCVPF
KFADSPVL------PL------TSVFESPQSDSVS----SKSTIKGV-SSAESNSGFSSA
VRIGGLNSNGK-----A-SGPAFVGQVFSMCDLTGTGLMAVS-----THFDIP-FISKRT
PQWLKKIFATITKSERNGPVFRFFMDLGDAVAYVKQLNI--------------PSGVVGA
CRLDLAYEHFKEKPHMFQFVPNERQIK--AANKLLKKIPQNDGRTKVDGVPVFGAQNLDI
AIATVDGIKWYTPYFFDKNMLDNILEESVDQHFHSLIQTRRIQRRRDVVDDSFAA----E
VIEEMGDNSWEPPEVQEVLNEIGH-PGIP---------LSVIS-KAA-------------
----------EIQLLYAVDKLLLGNRWLRKATGIQPKFPYLVDSFERR-STASFLKASKP
TNCLTDF-EA--------GLDTSGVELDD-------------KFQGN-HRET--KDFQLP
IGDWLNHSWLKQGQ---KHQMLADTGY---------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------
>Vitis_vinifera_gnl|BL_ORD_ID|19207 _GSVIVT01028824001|PACid:17835832
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------MCDVSGNGIMAVS-----NHFDIP-FISKRM
PQRIKKMFATITKSDKNGPVFRFFMDLGDAVRYVKKLNI--------------PSGGVGA
CRLDLAYGHFMEKPHLFRFVPNEKQVK--AANKLLKKIPQNGGRKRIDGVPVFTAQNLDI
AIATTDGIKWYTPYFFDKHTLDSILEQSIDHHFHHLIQSRHVQRRRDVIDDNLAA----E
VLEDNAESLWEPPEVQEVLDEVGH-PGIP---------LSVIS-KAA-------------
----------EMQLLYAVDRVLLGNRWLRKATGIQPKFPYMVDSFEKR-SAASFRRASPS
KRFVASP-EMGNDNKDTEELGPSDPKLED-------------NTQRD-QGQN--SASWFP
VWDLFNHPWSNKRQ---EPQNRSNARI--EDASREHIKQELQLA-----PFLPKITMVGI
SAG----ESG--MSKVNLKK---TMEDLTKELEQADQENA--VGCINSEFEVE-----NR
DPLFVANV-------------------------------------------GSYGSGL-V
ARS----PVPSVRGENN---------
>Eucalyptus_grandis_gnl|BL_ORD_ID|2953 _A02719.1|PACid:23564674
MAVS-----------------PEPPRKHRHHPNP---LSHLLN-----------------
---STL-----------------LPLIPN--HKAA--PPSLVSPPPP------PKLLLPV
RLPP----------ALSIASPSDSAPPPPHPTPLKP---APEVKAPAEPGAAAAGAFPST
VRISAIKSNGK-----G-RGPAFVGQVFSMCDLSGTGLMAVS-----THFDVP-FLSKRT
PEWLKKVFASITKSERNGPVFRFFMDLGDAVTYVKRLNI--------------PSGVVGA
CRLDLAYEHFKEKPHLFQFVPNEKQVK--AANKLLKTISQGNGNRQIDGVPVFSAQNLDI
AIATSDGIKWYTPYFFDKNMLDNILEESVEQHFHSLIQTRHMQRRRDVIDDNLT-----E
VADDVGDSLWEPPEVQEVLEEMGH-PGIP---------LSVIS-KAA-------------
----------EMQLLYAVDRVILGNRWLRKATGIQPKFPYIVDSFERR-TAASLVRASDL
THYLGDR-GMKTDESS--QESTDKLALEE-------------NHHVD-LGQK--ADFRFP
FGDWLRHPWSKEQQ---KLQKEVGARHRLESLTGEPVKQKLQPN-----PFLPKITMVGI
SMG----EAG-QANKATLKK---TMEDLTRELEQTDHGNA--AGNIAD--VSE-----DR
DPLFVANV-------------------------------------------GDYYSGL-A
KTG----SARLIRRSEAKKQQ-----
>Glycine_max_gnl|BL_ORD_ID|45053 _16g29580.1|PACid:16303315
MALP-----------------SEPHRRRRHNHNH---ISTFLQ-----------------
STASNF-----------------ASLFN---PPNP--PSL-TLPHPP------TSVSLPL
FFAP----------PLS----------------------GSSTVDSA--TSKPAHPPAKS
VRIARLGANGK----GG-GGPVFLGEVFSLCDLSGTGLIAAS-----KHFGIP-FISERT
PEWLKKIFAPITKSERNGPVFRFFIDLEDAVSYVEKLNI--------------PSCVVGA
FRLDLAYKQFKEKPHLFQFVPNEKQVK--AANKLLKTISEHGDKKKVDGVPVFGAQNLDI
AIATTDGIKWYTPYFFDKNMLDNILEDAVDQHFHNLIQTRHMQRRRDVVDDNLAA----E
VIEEMSDRLGEPPEVQELLDEMGH-PSIP---------LSVIS-KAA-------------
----------GLQFQYTVDKVLLGNRWLRKATGIQPKFPYMVDSFERR-SEASLLRATES
SSCLENS-KVEDDRQISECLDSSNCSLDG-------------NTEAI-KQPS--PSLSLP
FGNWFHHLWPKQCR---EKASSSR---------KGVNKEEMKPR-----PILPKVTMVGL
STE----EAG-QTSKANLKK---TMDDLTRELEKTELDIM--TDGGSKECKVE-----DR
DPLFVANG-------------------------------------------GNYYSSMRR
KPG----SGR----------------
>Phaseolus_vulgaris_gnl|BL_ORD_ID|6869 _091010222m|PACid:23537334
MALP-----------------SEPHRRRRHHNNH---IATFLQ-----------------
STASNF-----------------ASLFN---PPNP--PSL-TLPHPP------SSLSLPL
FFAP----------PLS----------------------ASNALDSAATASEPARPAAKS
VRVARLGVNGK---GGG-GGPAFVGQVFSMCDLSGTGLMAVS-----THFDIP-FISKRS
PEWLKKIFAAITKSERNGPVFRFFIDLGDAVSYVKKLNI--------------PSGVVGA
CRLDLAYEHFKEKPHLFQFVPNEKQVK--AANKLLKAISQHGIRKKVDGVPVFSAENLDI
AIATTDGIKWYTPYFFDKNMLDNILEEAVDQHFHTLIQTRHMQRRRDVVDDNLAA----E
VIEEMGDNLGEPPEVQELLDEMGH-PSIP---------LSVIS-KAA-------------
----------ELQFHYTVDKVFLGNRWLRKATGIQPKFPYLVDSFERR-SEASYLRATES
RRCLENP-KVEDDGKISECVDSSDCGLDD-------------NTEAI-RQPS--YRLSLP
FGNWFNHLWPKQCH---EKARSFK---------KGVNKEDMKPT-----PFLPKVTMVGL
STE----EAG-QMSKANLKK---TMEDLTRELEKTELDNM--AGGGGKECTME-----DR
DPLFVANV-------------------------------------------GDYYSSL-G
KAG----SGRWIRGGSN---------
>Cucumis_sativus_gnl|BL_ORD_ID|17033 _192940.1|PACid:16968025
MAFQ-----------------I-EPSSEPHEQNPLTFITHLFH-----------------
SSTSNF-----------------STLFAN--PQSI--PPF-PFQSSS------SKLCIPV
AFPPSPKP------PF----LSHSGFHSIHYDLDSP---KSAAVKGLSSSPNFDSGFPST
LRISGLNSDGK-----T-GGPAFVGQVFSMCDLSGAGLMAVT-----SNMNIP-FVSKRT
EEWLKKMFSTITKSKRNAPIFRFFTDLGDAVTYVKRLNI--------------PSAVVGV
CRLDLAYEHFKEKPHLFQFIPNEKQVK--AANKLLKGLPQNGGSKKIDGVPVFSAQNLDI
AIATTNGIKWYTPYFFDKNMLDNILEESVDQHFHALIQTRRLQRRREIVDDNAAA----E
VLEEMGDSLLEPPEVQEVMDEMGN-PGIP---------LSVIS-KVA-------------
----------EMQLLYTVDKVILGNRWLRKAVGIQPKFPYMVDSFERR-SAASLLRIQES
ASGLTNS-ESVEETKELQCYSSSPLNTED-------------NREAN-QEPK--QHSFNP
FRNWFGHLWSKQRQ---RDD-----------FSQERTKQNVQIS-----PFLPKITMVGI
STG----DSG-HTSKANLKK---TMEDLTRELEHIDQGNA--ASHNEYEFNNE-----ER
DPLFVANV-------------------------------------------SHFSSGL-S
KAG----SARWVRGND----------
>Linum_usitatissimum_gnl|BL_ORD_ID|5439 _10027537|PACid:23144619
MATS-----------------A-EPPQNHHRRHH--PFPNFFH-----------------
SATSAV-----------------LSLLPN--PRTSSAPPI-TSPSSSPP----PHVCIPF
NFVDSSY-------PLNQQSVIRSPLESGQSDSVSS---TSATVKGL-SSAESNSGFPST
VRISGLNSDGK-----G-GGPAFVGQVFSMCDLSGTGLMAVS-----TYIELP-FINERT
PEWLKKILAPVTKKDKNGPMFRFFMDLGDAVSYVKKLNI--------------PSGVVGA
CRLDLAYEHFKEKPNLFQFVPNKEQVK--AAKQLLKTMPESDGKTTVDGVPIFSAHNLDI
AIATSDGIKWYTPYFFNKSMLDGIIEDSVDQHFHTLIQTRHMQRRRDVVDDNFAA----D
VMEEMADSLMDPPEVDEMMDEMGN-VGIP---------LSVIS-KAA-------------
----------EMELLYAVDKVLLGNRWLRKATGIQPRFPYVVDSFERR-SAYSFKKASKT
TSLSHVS-QA--------GGSDSEVEPEN-------------NTQANSYEER--PDLRLT
FGDWFG-LRLKQPF---KPARETESRT--EGSSKEQMQQKLVDN-----PLLPKITMVGI
STG----ETG-KVSKASLKK---TMESLRKELEQADQGKTSSSDNGDGDFKIA-----DR
DPLFVANV-------------------------------------------GDY------
--------SRWIRRGMS---------
>Mimulus_guttatus_gnl|BL_ORD_ID|16966 _mgv1a003806m|PACid:17686364
MASA------------------ADKSHRRHHPPP--HLSRFIS-----------------
TASTNL-----------------SSFLTLKSPSPA---------SSS------SKIHLPL
LLADSDSFLSLVSRSESAQPDSTPSAPSRSPPSSSS---SSSSMKST-PSSDSVSKFPPT
VRI----TTGK-----G-GGPAFVGQVFSMCDLSGTGLMAVS-----THFDIP-FLSKRT
PEWLRKMYAAVTKSERNGPVFRFFMDLGDAVSYVKQLNI--------------PSGVVGA
CRLDIAYEHFKEKPDTFQFVPNERQVK--EANKLLKSFPHSDGKNKVEGVPVFSAQNLDI
AIAKKDGIKWYTPYFFDKSMLDNILEDSVDQQFHSLIETRNAHRRRDIGDDSLPA----E
AIEEMGESMWDPPEVQEVLDEIGH-PGIP---------LSVIS-KAA-------------
----------EIQLLYAVDRVILGNRWLRKATGIQPKFPYMVDSFERK-TAASFLRAKTS
N-LISNS-EISEDAQLD-NRTTLDVEPKE-------------KTHDK-QEQKHLINSQFP
FGDWLSHPWLKQPE---NQQNLSETRH--PNSTTQNRGQVAQSS-----PFLPKITMVGV
STG----EPG-KMGKAALKK---IMDDLTKELEKVEQVNQ--ANSNSSEYMAD-----ER
DPLFVANV-------------------------------------------GDSYSAV-S
KTG----TSWRVRGGSF---------
>Aquilegia_coerulea_gnl|BL_ORD_ID|35613 _013_00192.1|PACid:22058731
MAISP----------------SESHLNYNNNNNN---FTRFIQ-----------------
STSSSF-----------------FSLFN---PSPL--PPL-SSSSSSFPFCSSSSICVPL
LFSDTPPRILSLSTTLSTNSSSSSTTPSSQNDPLS----LNSQI----KTRSPSSKFPSS
IKISGLNSNPN-----G-SGPAFVGQVFSMCDVSGTGLMTVS-----THMEIP-FISKRI
PEWIKSMFSVFNKSENNGPVFRFFMDIGDAVSYVKRLNI--------------PTGVVGA
CRLDLAYEHFKEKPHMFQFVPNEKQVK--AANKILKKT-QHSEKRIVDGVPVFTAQNLDI
AIATGDGIKWYTPYFFDKNMLDNILEESVDQHFHSLIQSRHMHRRRDVIDDNLTA----E
VVEDNRDNLWEPPEVQEVLDEMGY-PGLP---------MSVIS-KAA-------------
----------EVQLLDAVDKVLLGNRWLRKATGIQPKFPYRVDSFEKR-SAASFRKATEL
TSIASNRIDSCVGSKCENLKGSEEPRLEE-------------NTQSG-QRQP--SEVRLP
FGDWFSHLWSKQQH---KPDEQTR-----LTDSRDKYIEQLPLS-----PLLPKITMVGI
STG----EAG-QTSKASLKQ---TMEDLTRELEQPGQDID---DGGSNEIRHE-----ER
DPLFVANV-------------------------------------------GV-------
--------------------------
>Brachypodium_distachyon_gnl|BL_ORD_ID|2714 _2g07450.1|PACid:21805484
MP-------------------------------SSSSSSNPFH-----------------
SLTFN------------------LPF--PPAPSSCSTSAS-SPPAPA------PHLAFPL
LL------------PVSSASTTSSYSPASHLIPQ--------------PQRLPGERMAGP
AAASGGKGVSAG--KSP-GGPAFVGQVFTMLDPSGNGLMAVT-----SRFDLPHFIAHRT
PTWFKRILSPLKKSE-SSPVFRFFMDLNDSVSYVKRLNV--------------PSGMVGA
CRLDVAYEHFKEKPHMFQFVPNEKQVK--AANKLLKSIPQKSRRKKLAGVPVFSAQNLNI
AVATDDGIRWYSPYFFDKNLLDNILEASMDQHFHSIIQNRHIRRRRDIVDDSLTS----E
ILEESADSLLEPPEVQELMNEIGP-AGIP---------LSVVT-KAA-------------
----------EIQLLDVVDKLLLGNKWLRKATGIQPRFPYVVDSFEER-TALSVDRTATS
SNSCTAS-KDADFFTNDQQSQALEPNVDS-------------GNHRK-HNSRDHGQSHFP
FSNLLPNIWPGHDR---KFKAQEHDNR--FKRYGASMDNDLQAN-----PLLPKITMVGI
SMS----EGG-QMSKANLKK---TMEELTKELEQAGEKTV----------FSD-----EK
DPLFVANV-------------------------------------------GDY-SRI-T
KIS----ST-----------------
>Sorghum_bicolor_gnl|BL_ORD_ID|9318 _Sb03g001210.1|PACid:1960134
MP-------------------------------RSSSSSNPFH-----------------
SLASA------------------FPFFSSSSPSPPA-SASPSPSPAA------PHLAVPL
LL------------PVSSGSASASS----ESRRG--------------PQPLPGARMAGA
AAAGRGNKAGG-----G-AGPAFVGQVFTMLDPSGNGLMAVT-----TRFELPRFLTNRT
PMWFKRMLSPLKKSE-SSPVFRFFMDLNDAVSYVKRLNV--------------PSGMVGA
CRLDVAYEHFKEKPHLFQFVPNEKQVQ--AANKLLKSLPQRSRRKKLGGVPVFSAQNLNI
AVATNDGIRWYTPYFFDKNLLDNILEASMDQHFHSIMQNRHTQRRRDIVDDSLTS----E
IIEESAESLLEPPEVQELMNEIGP-AGIP---------LNVVT-KAA-------------
----------EIQFLDVVDKVLLGNKWLRKASGIQPKFPYVVDSFEER-TAVSIANIATT
S-SLTTS-NDENCCQNNQQTQSSGSSVDN-------------SSYRN-HNNEDHN--HFP
FSNLLPNIWPGHDR---KFKAQESDNK--FSRYDADVKSNLQSN-----PLLPKITMVGI
SMG----DGA-QMSKANLKK---TMEDLTKELEQTSEENM----------FSD-----DK
DPLFVANV-------------------------------------------GDY-SRI-T
KIS----SA-----------------
>Zea_mays_gnl|BL_ORD_ID|9045 _GRMZM2G097959_T01|PACid:20828771
MP-------------------------------CSSSSSNPFH-----------------
SLASA------------------FPF--LSSTSPPP-SPPASPAPAA------PHLAVPL
LL------------PVSSAS---------ESRRG--------------AQPLPGTRMVGA
GATGGGNMASG-----G-GGPAFVGQVFTMLDPSGNGLMAVT-----TRFELPRFLTNRT
PMWFKRMLSPSKKTE-NSPVFRFFMDLNDAVSYVKRLNV--------------PSGMVGA
CRLDVAYEHFKEKPHMFQFVPNEKQVQ--AANKLLKSLPQRGRRKKLDGVPVFSAQNLNI
AVATNDGIRWYTPYFFDKNLLDNILEASMDQHFHSIMQNRHTRRRRDIVDDSLTS----E
IIEESAESLLEPPEVQELMNEIGP-AGIP---------LNVVT-KAA-------------
----------EIQFLDVVDKVLLGNKWLRKASGIQPKFPYVVDSFEER-TAVSIANIATT
S-SLTAS-NDDSSCQNNQETQSSEPSGDN-------------SSYRN-HNNEDHN--HFP
FSNLLPNIWPGHDR---KFKSQESDNK--FSRYDADVKSKLQAN-----PLLPKITMVGI
SMG----DGA-QMSKANLKK---TMEDLTKELEQTSEENM----------FGD-----EK
DPLFVANV-------------------------------------------GDY-SRI-T
KIS----SA-----------------
>Setaria_italica_gnl|BL_ORD_ID|1638 _Si001606m|PACid:19674983
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------MLDPSGNGLMAVT-----TRFELPRFLTNRT
PTWFKKILSPLKKSE-NGPVFRFFMDLNDAVSYVKRLNV--------------PSGMVGA
CRLDVAYEHFKEKPHMFQFVPNEKQVK--AANKLLKSLPQRGRRKRLGGVPVFSAQNLNI
AVATNDGIRWYTPYFFDKNLLDNILEASMDQHFHSIMQNRHKQRRRDIVDDSLTS----E
IIEESADSLLEPPEVQELMNEIGP-AGIP---------LNVVT-KAA-------------
----------EIQLLDVVDKVLLGNKWLRKAAGIQPRFPYVVDSFEER-TAVSIANIATT
S-SFTAS-ND-SCCQNDQQSQSSDPSIEN--------------SYRS-HSNQDHNQFHFP
FSNLLPNIWPGHDR---KFKEQESDSK--FSRYDADMKTDLQSN-----PLLPKITMVGI
SMS----EGG-QMSKANLKK---TMEDLTKELEQTSEKNT----------FGD-----EK
DPLFVANV-------------------------------------------GDY-SRI-T
KIS----ST-----------------
>Oryza_sativa_gnl|BL_ORD_ID|20689 _LOC_Os01g12550.1|PACid:21903161
MPRG-----------------------RSTTTTTSSSASNPFH-----------------
AFAST------------------LPF--LPSPSPSPTSASPSPSPPA------PHLAVPL
IL------------PITSSSSASAAAAS--------------------PESNRGARMA--
AAASGGKAGGGGGLGKG-GGPAFVGQVFTMLDPSGNGLMAVT-----TRFELPQFLASRT
PMWFKRILSPLKKSE-NGPVFRFFMDLNDAVSYVKRLNV--------------PSGMVGA
CRLDVAYEHFKEKPQMFQFVPSEKQVK--AANKLLKSLPQRRRRKKLDGVPVFSAQNLNI
AVATNDGIRWYTPYFFDKNLLDNILEASMDQHFHSMVQNRHTRRRRDIVDDSLTS----E
MMEESADSFLEPPEVQELMNEIGP-VGIP---------LNVVT-KAA-------------
----------EIQFLDVVDKMLLGNKWLRKATGIQPQFPYVVDSFEER-TAAAIDRAATA
SSSFTAS-KDADCFQISKQPETLESDVDN-------------SNRGK-HENSNNGQSHFP
FSNLLPNIWPGHDR---SFKAQGRDRA--FRRCDASINNDLQAN-----PLLPKITMVGI
SMG----EGG-QMSKANLKK---TMEDLTKELEQAGEKTI----------FSD-----EK
DPLFVANV-------------------------------------------GDY-SRI-T
KIS----ST-----------------
>Panucum_virgatum_gnl|BL_ORD_ID|40717 _Pavirv00055971m|PACid:23796854
MP-------------------------------RSSSSSNPFP-----------------
SLASST-----------------FPF--LSSSSSAATSSTTSPAHPA------PHLAFPL
LL------------PVSSASSSA------EPRRG--------------PEPLPGARMAGA
GAAAGGKPGGRI-KGGG-GGPAFVGQVFPMLDPSGNGLMAVT-----TRFELPRFLTNRT
PAWFKKILSPLKKSE-NGPVFRFFMDLNDAVSYVKRLNV--------------PSGMVGA
CRLDVAYEHFKEKPHMFQFVPNEKQVK--AANKLLKSFPQRGRRKRLRGVPVFSAQNLNI
AVATNDGIRWYTPYFFDKNLLDNILEASMDQHFHSIMQNRHVQRRRDIVDDSLTS----E
IIEESADSLLEPPEVQELMNEIGP-AGIP---------LNVVT-KAA-------------
----------EIQLLDVVDKVLLGNKWLRKAA----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------
>Physcomitrella_patens_gnl|BL_ORD_ID|36425 _Pp1s68_153V6.1|PACid:18072962
MGRNRDTCNVPGCSKDEKPCLVTGPKIVSFKLPNPALFSSWVQ-----------------
TVTSNLAWTVQSFQTLKTDGLNCLSLLVEHKPMVSPLPVPYLAL---------NNLIFPV
PSST-----------------------------------SSVQVCQKAVSSIPQDHFSKG
NAVNEKGEVSS-------TGPAFIGQVYTMCDASRQGLIAVRPSDVLKKIKVP-PYMKLM
EKAYERAMNVLFTDDMKGPVFRFYFNKDDAAEYVRRLNI--------------TGSAVGP
CSLDAAYKYYKSKEGMFKFIADQRQVK--VAKELVRRERGDKAANKLKGVPVFTARNLTI
ALSTPQGVRWFRPYFFNKKQLDSLIGHSVDHYYEMLISARRAQRYSQIAENNGDAFAGGE
SMDDELDGLMDPPEVQELMEELGQ-GGGG---------MEFVGLKVL-------------
----------EAQFMDLADRVLLGHQWSRRMIHLQPRFPVIVDSFERLISASELDHSSES
EGSVTSS-RNSFAKKEGTQEKSQRGQGDEGMSISGRDERSASNDSSESVSKEYSQSSPNS
LFNLFKKKWGANANLVFKRKDSGNAEILEEDSDSEYLQETAQKDPPGKIPFQPKLTMMGI
SMNVNKVEGGLQQAMAAAAK---DVEDRLRKGEGSGP---------------------DH
GPLFIANL-------------------------------------------G---SGI-P
QWGRPVSASSGVLDDDAE--------
>Selaginella_moellendorffii_gnl|BL_ORD_ID|1621 _424522|PACid:15402899
ME----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------IGS
VPLHLAYKFFKERPSLFSFIPSKKQVD--LAKTIIKKEQGGKAAQQFQGVPVFTSHCLSI
LVVGPSGARWFRPHFFKKEELDGVIRSSMEHHYQSLIRNRRARRHNQVSD--FPS----D
MAEDDLE-MLESQDIQDFVEDMDEWSSVL---------ESIMA-KAA-------------
----------QMYFQDTLDRAIFGNKWCRMLAGIQPSFPILVDSFERR-VTSETENAVVS
HHEQKK-----------------------------------------------------P
HKDW--------------------------------------------------------
-------DSTCQLKRALIR-----------------------------------------
------------------------------------------------------------
--------------------------
>Chlamydomonas_reinhardtii_gnl|BL_ORD_ID|12022 _13.g593950.t1.2|PACid:19870334
MA-----------------------------LQSRHGRATFLHAYWRERALRPCLRRPVL
TVSAVAASSSAAEGRGKASGLGSLTFLDFVVPFST--PLAAAIATGVYTGAVGADLAWPL
RALLVG------------------------------------------------------
------------------GGPLLVHLLFPAVDWALGPSRALA---------------ERQ
QQQAQQQALGIKAPGADHFLSRALPCLAVAVQLLVLLATYGALAAAAGAPAPPLAGAAGA
AAAGLQQQQLLLLPLLVTSLALSAGMAQAASHELLHSRH-----------PVHLAAAWLF
LTT-----HWWYPYF----------RAHHQHHLAVCTPADYASAPRGL---SLAA----Y
LPRYIGSSYTEAWQLAAA--ECRR-AGHPVFSTHNSCLVALVA-QAALTAALGLALGPAA
ALLHGAVCAVLLTYMSVLDYVL--HYGLRRP-------PLVVAAAAAA-TAGGVGGGADA
AVSTVADSREVTGVAPAAAGVAAAPAAGSG---------AVR------------YAPVTP
FNSW-SSLYPLENALFFNVLIHGDHHMTASRSYAWLVPAPSSPTFPAPINALALATFVPP
LWRAAMHERVDQANSANLRHLAATGVPVAAEQGAAEQGAA--------------------
-----------------------------------------------------------E
QVA----AEQVAAAGTA---------
>Synechocystis_sp_PCC_6803__637011978_slr0924_hypothetical_protein_[Synechocystis_sp._PCC_6803]	
M-------------------------------PWLQTFSFRRSPFSLARRHLKNKIFVKI
KSIFLLSLLFEATATMK------SLLRIGATLGLIG--------------------TTAI
GTWLGTT-----------------------------------------------------
----------------------------------------------------------LQ
A--LALPTEEVVKILQGVPVFTIVDAQGAPL---VAVGN-DN--------------EKVT
GVFISQQEANGFLQEL---------------KKQK-------------PDVG-SQVSVQP
VSLGEVVKIAQANAN-----------QT-DPLGFAYVPIPAQ----VQAAQQMPN-----
-------SEYQGGVPLFVARG-GEDQGYLTI--QQENE-------------------QII
PFFLEASQIQQMVERFKQEQPAM------------ADS----------------------
------------------------IVIDVIAMENVISTLQTSDDA----------MLKQI
RIVPTQEAIQFIRSLSAQQPK---------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Anabaena_sp_PCC_7120_gnl_BL_ORD_ID_113_alr0114_hypothetical_protein
MK----------------------------------------------------------
-----------------------ALVRWGATLGLVG--------------------STLL
GTLSLGS-----------------------------------------------------
----------------------------------------------------------LP
A--IALSEQQIKEKLDSVPIYLVTNEKGLPLSRPLPNAP-NGQKA-G---------GSIT
GAYMSRQEAQAFINEL---------------RNAKNKDPKM-------QEIV-KSLQVTA
VPLGVIYQQLQQTKK-----------DP-NRLLFAFKPVDQE----IKGAMDLLRQSGQ-
-----Q-VNQFKSVPMFAVRF-APDQGYVPIKVGTGNE-------------------QVV
PLFLSKQDAQGLLGQVKPKHPKA-------------------------------------
-------------------------DIQVLDIDGVLQTLQDKNDT----------WLNQV
VLVPSPESREYIRTLPKPPNTPAAPNRNNNNSRPGAK-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Gloeobacter_violaceus_PCC_7421__637461026_glr3613_hypothetical_protein_[Gloeobacter_violaceus_PCC_7	
MK----------------------------------------------------------
-----------------------RRVQGWAAAILVS--------------------SIVW
S-----------------------------------------------------------
----------------------------------------------------------GE
V--LALTQAQIIEKLKPVVLFTVATADGKPL---LSLPP-DGSKG-----------PLVA
GVYFSPQDAEAFVAAF---------------KKKD-------------AARG-GQLRVQP
VSLGNLYRLRLESRG-----------TE-EEVTLAFFANRTE----VEWALSLLQAAGR-
-----K-PEDLQGAPLFAATVNAGKKQYLTL--QQNNR-------------------TVV
PVYFTKQEMTAFIDRYRRQQANA------------NVP----------------------
------------------------VTVEVLDLEGILEALQEPTDS----------QTKKV
MLVTPKAALDYARTQSGSPIPTVQPPKSPPAEGLAPTPDPH-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Synechococcus_sp_PCC_7002__641611608_SYNPCC7002_A1598_hypothetical_protein_[Synechococcus_sp._PCC_7	
MTAYFFRINFSNLAVILFEVLFMK------------------------------------
-----------------------SLVRLGQKALLMG--------------------TVIA
GTILGVN-----------------------------------------------------
----------------------------------------------------------GS
V--LALPEAAVVEKLRPIPMYMLINDEGQPI---FATVT-DQNGGE----------SGVT
GVFVSLSDAENLVAARQTESKRLLDAE----RAKPNADPQIVAELEAQAALW-QEANVLP
IGLDKIYQFAQSD-------------EA-EDLTFKFLPTMAQ----LNAAAQVTQ-----
-------QENFPGVPLFF----------LSI--QEKDANGQDIVSFPTLAGDDNNGNGEI
PVFFEVQPILEQLDAFPEDEEL--------------------------------------
-------------------------SINVMPLEVFIAKLLDEDLPAEE-----QEFLESM
TLIPSTESAQLIQAVIEQQRQQQ-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Synechococcus_sp_PCC_7335__647578192_S7335_3895_hypothetical_protein_[Synechococcus_sp._PCC_7335]	
MKL---------------------------------------------------------
-----------------------SIRRIFAQVLAIG--------------------TLGL
GPMAIGL-----------------------------------------------------
----------------------------------------------------------LS
APVLALSEEQIVQQREAVLSFILEDEEG------PIAGP-DG-----------------I
LVFVTLQSASDYIAAN---------------RLED----------------T-DTIKVIP
TNLERIHQVAEEIEG--------------EPLRITLVPEEAE----VENARDID------
-------PDYQGGVPLFYAQLPNGAFAPLW---QPDGE-------------------VVF
PLYFSRSDLDESLARLPQEELGI-------------------------------------
-------------------------EVAVIPLQVILQEIHTSDNE----------DLSRI
RMLSPQ-VVDAIRAASEEAENTAPSDEPEAQ-----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Aquilegia_coerulea_gnl_BL_ORD_ID_27934__058_00151.1_PACid_22051029
M--------EFPWLKKNNNQPNQLSSSSSTTTTTTEPQTQNQNIFLNIQN----------
------------------------------------------------------------
---------------------QFSSFCQH--SIQWPQPHHHHFPNFI-------------
--------------QTFQTAISTFTSTSFPKKNPPHFAHLSSAHN------KQPIH--RF
D--LAMATEDIEERLAGIPVYALSNSDEEFV---LISGV-KTG-------------KSLG
LLCFSKNDADTLLEQM---------------KSMD-------------PGMR-QSSKVVA
VALNKVFQL-----------------KL-DGVAFRFIPDSSQ----IKNAIQVNQNAGL-
-----S-DQGFSGVPVFQSQS-------LVL--KSQDK-------------------RYR
PIFFRKEDLENSLRRASIQQKQLNPAF--------R-Q----------------------
------------------------GDIQVSVLEEIIKTMKES-ST--S-------KWDDV
VFIPPGFDVSTSVPQQEKLTANG-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Vitis_vinifera_gnl_BL_ORD_ID_21103__GSVIVT01031575001_PACid_17837728
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------MR-QGSKVVA
VALNKVFQL-----------------KL-DGVAFRLMPDSTQ----VKNALRVMEKAGF-
-----S-DDGFSGVPVFQSRS-------LIL--QSQDK-------------------KYR
PVFFRKEDLENSLLSASNQQNRLNPAF--------R-Q----------------------
------------------------GDIQVAVFEEIIKGMQEN-AS--R-------QWDDV
VFIPPGFDASISSPQQQA-TANG-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Malus_domestica_gnl_BL_ORD_ID_37333__0000534726_PACid_22657315
M-----------------NLGNSNNQKTSSPPTHNPPQLSPQQAFTNLQN----------
------------------------------------------------------------
---------------------HCSGFLHH--LSHL--PLFNPNPS-SLQTHLQSTFSNLQ
NQAK----------HAFDSRFSSFNPVH-SSGKNPVWGRIAVSNK--TQVANSPGG--GS
K--AAMSTEDIEERLAGVPVYALSNASEEFV---LVSGA-STG-------------KSLG
LFCFKKEDADALLEHI---------------RIMD-------------PGMR-SGSKVVA
VALNKVFQL-----------------KV-DGVAFRLIPEYSQ----VKNALKEREKVGT-
-----SDDDGFPGVPVFQ------------------------------------------
------EDLENSLSRASRDQNQLNPAF--------R-P----------------------
------------------------GDVQ------------EG-ST--S-------TWDDV
VFIPPGFDISTDPNKQ--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Prunus_persica_gnl_BL_ORD_ID_2248__ppa023049m_PACid_17642570
L----------------------------------------QQAFTNIQN----------
------------------------------------------------------------
---------------------HCSGFLHH--LSHF--PVFNPNPS-SLKTQLESTFANLQ
NQAK----------HAFNTGLSSSVPKH-SSGKTPVWARIAVNNK--TQTTNSPGN--GS
K--AAMSTEAIEERLAGVPVYALSNAAEEFV---LVSGA-SSG-------------KSLG
LFCFKKEDAEALLEHI---------------RIMD-------------PGMR-SGSKVVA
VALNKVFQL-----------------KV-DGVAFRLIPEYSQ----VKNALKEKEKVGT-
-----SDDDGFPGVPVFQSRS-------LIL--RSQSK-------------------SYR
PVFFRKEDLESSLSRASREQNQLNPAF--------R-P----------------------
------------------------GDVQVAVLEEVIKGMKEG-ST--S-------TWDDV
VFIPPGFDISTDPTKQ--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Glycine_max_gnl_BL_ORD_ID_12487__05g28300.1_PACid_16259917
M----------------------------------MNFDGFQKALAEFQG----------
------------------------------------------------------------
---------------------RCSTLLGS--LTRLQPN----------------------
-------------------------------RARPPWARIAQPWG-------------GR
P--MAMTVEAIEERLEGIPVYALSNASEEFL---LVSGS-SSG-------------KNLG
LFCFNKDDAEALLNQV---------------TLID-------------PHAR-QGSKVVP
VALNKVFQL-----------------KV-NGVAFRLIPEFSQ----VKNALQEREKSGF-
-----A-SSGFSGVPVFQSRS-------LIL--KSQNK-------------------RFR
PLFFRKEDLENTLKSAAREQNKLNPTM--------R-K----------------------
------------------------GDIQVATLEDVIKEMKEN-ST--S-------NWDDV
IFIPPGFDVSDDSNEQ--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Phaseolus_vulgaris_gnl_BL_ORD_ID_22411__091000598m_PACid_23553221
M-----------------------------------SFDGFLKTLTDLQA----------
------------------------------------------------------------
---------------------HCSTLLAN--LTHLQPNHSFP------------------
-----------------------------APRTSPPWARIAPPAR-------------SR
P----MTVEAIEERLEGIPVYALSNASEEFL---LVSGS-SSG-------------KNLG
LFCFNKDDAEALLNQV---------------TLID-------------PHAR-PGSKVVP
VALNKVFQL-----------------KV-NGVAFRLIPEFSQ----IQNALKEREKSGS-
-----A-SSGFSGVPVFQSRS-------LIL--KNENK-------------------RYR
PLFFRKEDLENTLKSAARDQNRLNPTM--------R-R----------------------
------------------------GDIQVATLEDVIKEMREN-SA--S-------NWDDV
IFIPPGFDVSDDSNEQ--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Arabidopsis_thaliana_AT3G23710.1
M-----------------------NSNIFPPSKQQNELNNIQQSFSNLQS----------
------------------------------------------------------------
---------------------QCSNLLLN--VSQTLNPLFNANTN-NNKPNIFSALNSFR
DQAK----------QALDSRISRFN-----SGKAPVWARISDDGGGARAQVTVPIR--GS
G--KGLSADAIEERLAGVPVYALSNSNEEFV---LVSGT-SSG-------------KSLG
LLFCKEEDAETLLKEM---------------KSMD-------------PRMRKEGSKVVA
LALSKVFQL-----------------KV-NGVAFRLIPESTQ----VKNALKERKTAGI-
-----D-DDDFHGVPVFQSKS-------LIL--RSENM-------------------SYR
PVFFRKEDLEKSLIRASSQQNRLNPAL--------K-P----------------------
------------------------GDIQVAVFEDIVKGMRES-TT--S-------NWDDI
VFIPPGFEVSTEQTQE--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Brassica_rapa_gnl_BL_ORD_ID_19281__028338_PACid_22702791
M-----------------------DSNVSSSSKQQKHL-TLQQSFSNIQT----------
------------------------------------------------------------
---------------------QCSDLLNN--VSKTLNPLFNPNSN-----NIFSALDSFR
AQAK----------QALDSGFSRFA----SGNTPPLWARISDDGG--KTHVAPIRR--SS
G--PGLSADDMEERLAGVPVYALSNSNEEFV---LVSGT-ATG-------------KSLG
LLFCKAEDAEALLNQM---------------KAMD-------------PRMRKEGSKVVA
LALSKVFQL-----------------KV-NGVAFRLIPESTQ----VQNALKERKTAGF-
-----T-DDDFNGVPVFQSKS-------LIL--RSDNK-------------------SYR
PVFFRKEDLEKSLTRASRQQNRLNPAL--------K-P----------------------
------------------------GDIQVAVFEEIVKGMKEN-AT--S-------NWDDI
VFIPPGFEVSTEETKD--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Thellungiella_halophila_gnl_BL_ORD_ID_17021__Thhalv10002616m_PACid_20196604
M-----------------------NSNIF----QQKQL-NLQESFSNIHT----------
------------------------------------------------------------
---------------------QCSNLLKN--VSQTLNPLFNHKTEHEHHPNIFSALDSLR
EQAK----------QALDSGFSRFTSVS-GSKNAPVWARISDDGA--KTHVATAAP--IR
G--AGLSAEDMEERLAGVPVYALSNPNEEFV---LVSGT-STG-------------KSLG
LLFCREEDAEALLKQM---------------KMMD-------------PRMRKEGSKVVA
LALSKAFQL-----------------KV-NGVAFRLIPESTQ----VKNALKERKTAGF-
-----T-DDDFHGVPIFQSKS-------LIL--RSDNK-------------------TFR
PVFFRKEDLEKSLIRAARQQNRLNPAL--------K-P----------------------
------------------------GDIQVAVFEEIVKGMKES-A---S-------NWDDI
VFIPPGFEVSTEQTQE--------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Brachypodium_distachyon_gnl_BL_ORD_ID_10569__4g27410.1_PACid_21813339
M-----P--FDFPWLKNP-------AATSTPNPNPS-KPSNPNPFLAIQA----------
------------------------------------------------------------
---------------------HLTSFLSS--LPL--------------------------
-----------------------------PRALPPPWARIPSSS--------------SS
P--VALPVAEIEDRLSGVPVYALANSSQEFV---LVSKT-HGGGAEGESS-GARPPPALG
VLCFRREDADALLAQM------------------D-------------GTMR-AGSTVVP
VALNKVIQL-----------------KS-DGVAFRFLPDFTQ----VANAMKLMQDEGQ-
-----LVNEGFLGVPVFQSRS-------LVL--MSDSK-------------------RCR
PVFFRKEDLDNSLHRASRDQQKPNP-V--------R-I----------------------
------------------------GDTQVSSLEDMITSMKDS-SS--S-------TWDDV
VFIPPGFDLATGSK----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Oryza_sativa_gnl_BL_ORD_ID_18324__LOC_Os07g19030.1_PACid_21900796
M-----PFHFQFPWLPNNPT-------SSSSSPTKPPSPAIPNPFLPIQA----------
------------------------------------------------------------
---------------------GLASFLSSLPLPR--------------------------
-----------------------------AAFPPPPWARISSASA---------SA--AS
A--SALPVAEIEERLAGVPVYALANSSQEFV---LVSSA-RGGGGGGGGARAAVPPPALG
LLCFRREDADALLAQM------------------D-------------GDMA-AGSTVVP
VALNKVIQL-----------------KS-DGVAFRFVPDSSQ----VANAMKLMENEGQ-
-----YVNDGFPGVPVFQSRS-------LVL--MSDNK-------------------RYR
PVFFRKEDLDNSLHRASRDQQKPNPAV--------K-M----------------------
------------------------GDIQVSSLENIIKSMKDS-SS--S-------KWDDA
VFIPPGFDLATSSKQSNHDN----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Panucum_virgatum_gnl_BL_ORD_ID_5046__Pavirv00047800m_PACid_23760801
M-----PSHFQFPWLKNPTTT-TTAAGSSNPDASPSPSPSIPNPFLPIQA----------
------------------------------------------------------------
---------------------HFTSFLSS--LPR--------------------------
-----------------------------ALPPPPPWARIPSPSP-------SPSR--AS
A--TPLPSAEIEERLAGVPVYALANAAHEIV---LVSSA-RAEGQHG-GV-GARPPPALG
LLCFRKEDADALLEQM------------------E-------------GDMR-AGSSVVP
VALNKVIQL-----------------KS-DGVAFRLLPDSSQ----VANAIKLMQDEGL-
-----YAREGFPGVPVFQSRS-------LVL--MSDNK-------------------RYR
PVFFRKEDLDNSLYRTSRDQQKPNPAV--------R-L----------------------
------------------------GDTQVSSLEDIIKSMKDS-SS--S-------KWDDV
VFIPPGFDLATGSKPSHLNK----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Sorghum_bicolor_gnl_BL_ORD_ID_6203__Sb02g009350.1_PACid_1956455
M-----PFRFEFPWLKNPNTT----AGTSNRDT--NPSPRFPNPFLPIQA----------
------------------------------------------------------------
---------------------HVTSFLSS--LPQ--------------------------
-----------------------------ALPPPPPWARIPSPS----------SA--ST
S--VALPTAEIEERLAGVPVYALANAAQEFV---LVSST-RVGGQGGEGV-RVRPPPALG
LLCFRKEDADALLEQM------------------E-------------GDMR-AGSSVVP
VALNKVIQL-----------------KS-DGVAFRFLPDSSQ----VANAIKLMQDEGL-
-----YAREGFPGVPVFQSRS-------LVL--MSDNK-------------------RYR
PVFFRKEDLDNSLHRTSRDQQKPNPAV--------R-F----------------------
------------------------GDTQVSSLEDIIKSMKDS-SS--S-------KWDDV
VFIPPGFDLATGSTPSHLSK----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Zea_mays_gnl_BL_ORD_ID_14867__GRMZM2G130651_T01_PACid_20834593
M-----PFRFQFPWLKNPTTN----GGTSNIDT--NPSPRFPNPFLPIQA----------
------------------------------------------------------------
---------------------HVTSFLSS--FPR--------------------------
-----------------------------ALPPPPPWARITSPA--------------ST
S--GALPTSEIEERLAGVPVYALANAAQEFV---LVSST-RVGGQGGES---VSPTQALG
LLCFRKEDADALLEQM------------------D-------------GDMR-AGSGVVP
VALNKVIQM-----------------KS-DGVAFRFLPDSSQ----VANAIKLMQDEGL-
-----YAGEGFPGVPVFQSRS-------LVL--MSDNK-------------------RYR
PVFFRKEDLDNSLHRTSRDQQKPNPAV--------R-F----------------------
------------------------GDTQVSSLEDIIKSMKDS-SS--S-------KWDDV
VFIPPGFDLATGSTPSQLRK----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Panucum_virgatum_gnl_BL_ORD_ID_36616__Pavirv00013793m_PACid_23792711
M-----PFQFQFPWLKGPTTTAAAAAGSSNPNPSPSPGPSFPNPFLPIQA----------
------------------------------------------------------------
---------------------HVTSFLSS--LPR--------------------------
-----------------------------ALPPPPPWARIPSLSP-------SPSR--AS
A--APLPSAEIEERLAGVPVYALANAANEIV---LVSSA-RAGGQHG-GR-GARPPPALG
LLCFRKEDADALLEQM------------------E-------------GDMR-AGSCVVP
VALNKVIQL-----------------KS-DGVAFRFLPDSSQ----VANAIKV-------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------T
VFCP--------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Aquilegia_coerulea_gnl_BL_ORD_ID_19107__015_00080.1_PACid_22042170
M------------NDSSLPLSAMEF--------------PKPSPLSSITTFVHQ------
------------------------------------------------------------
---------------------QLHRFNSE--ITTR-----------------------FE
E-SK----------QFIGNAISNLPLNK-QRQQPHSHSPSSSLFASITTA--LPKH--AF
D--IALSSDYVAKTLAGTAVYTVSNSNNEFV---LISDP-NNI-------------KSLG
ILCFRQEDAETLLAQV---------------QLKQ-------------PILC-RGAKVVP
ITLDQVYML-----------------KV-EGIAFRFLPDPAQ----IRNALELKA--AD-
-----L-KNGFDGVPVFQSDL-------LVV--RKKNK-------------------RYC
PIYFQKEDLEKELMKVTRISR----GS--------GLS----------------------
------------------------QNIVVGSLEDVLKKMEMSDKN--S-------GWEDL
IFIPPGKSYSQHVQE----VAMG-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Vitis_vinifera_gnl_BL_ORD_ID_5277__GSVIVT01009503001_PACid_17821902
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------SQEARGAKR--DL
G--VALSSDHVAKSLAGTAVYTVSNSNNEFV---LISDP-NGI-------------KSIG
LLCFRQEDAEAFLAQV---------------QSRT-------------RELR-SQARVVP
ISLDQVYML-----------------KV-EGIAFRFLPDPVQ----IKNALELKA--ADI
-------KSGFDGVPVFQSDL-------LVV--KKKNR-------------------RYC
PIYFQKEDIVKELSKVSRSSR----GP--------GVT----------------------
------------------------QHIMVGSLEDVLRKMETSEKN--S-------GWEDL
IFIPPGKSHSQHIQE----VTKR-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Malus_domestica_gnl_BL_ORD_ID_47835__0000194844_PACid_22667820
M--------------------------------ESAKPYPRSNPLLSLSTFIHQ------
------------------------------------------------------------
---------------------HCLRLGAE--LSTR-----------------------FE
D-TK----------R----LXGNFAPLA---SRRMCSAPVYPPFAWLA----QSSH--AL
A--ATLSSDHVAKSLAGTAVYTVSNSNNEFV---LISDP-NEA-------------KSIG
LLCFRQEDAEAFLAQV---------------RSR--------------RELR-SAAKVVP
ITLDQVYML-----------------KV-EGIAFRFLXDPVQ----IRNALELXS--AD-
-------RSAFDGVPVFQ------------------------------------------
------------------------------------------------------------
----------------------------VG------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Prunus_persica_gnl_BL_ORD_ID_11774__ppa009744m_PACid_17652241
M--------------------------------ESPKPYGRSNPLLSLSTFIHQ------
------------------------------------------------------------
---------------------NCLQLGAE--LSSR-----------------------LE
D-TK----------RLAGTLAGNLAPSA---RRRMCSAPVAPPFAWLS----QSNH--AL
A--ATISSDHVAKSLAGTAVYTVSNSNNEFV---LISDP-NEA-------------KSIG
LLCFRHEDAEAFLAQV---------------RSR--------------RELR-SAAKVVP
ITLDQVYML-----------------KV-EGIAFRFLPDPVQ----IRNALELKS--AD-
-------RSAFDGVPVFQSDL-------LVM--KKKNK-------------------RYC
PIYFTKEDIEKELSKVSRVSR----GP--------GVS----------------------
------------------------QHIMVGSLEDVLRKMELSEKN--S-------GWEDL
IFIPPGKSYSQHIQD----VVKA-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Glycine_max_gnl_BL_ORD_ID_8827__04g04070.1_PACid_16254795
M-----------------------------------ESRGHSNPLLSFSSFIHQ------
------------------------------------------------------------
---------------------HCVRLGSD--LATR-----------------------LD
D-TK----------RALAQAHHNLL---------------------------FPKH--AL
AATSTLGSLHVAKSLVGTSVYTVSNSNNEFV---LISDA-DGA-------------KSIG
LLCFRQEDAEAFLAQV---------------RSRS-------------RELR-SKARVVP
ITLDQVYML-----------------KV-EGIAFRFLPDPVQ----IRNALELKP--AN-
-------KGGFDGVPVFQSEL-------LVV--KKKKK-------------------RYC
PVYFSKEDIEQELSKVSRASR----GP--------GVS----------------------
------------------------QHIAVGSLEDVLRKMEMSERN--S-------GWEDL
IFIPPGKSRSQHIQE----LNE--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Phaseolus_vulgaris_gnl_BL_ORD_ID_5597__091019731m_PACid_23536034
M-----------------------------------ESRGHSNPLLSFSSFIHQ------
------------------------------------------------------------
---------------------HCVRVGAD--LATR-----------------------LD
D-TR----------RALAQAHHNLL---------------------------SPKH--AL
AATATLGSHHVAKSLVGTSVYTVSNSNNEFV---LISDA-DGA-------------KSIG
LLCFRQEDAQAFLAQV---------------RSRS-------------RELR-SKARVVP
ITLDQVYML-----------------KV-EGIAFRFLPDPVQ----IKNALELKP--AN-
-------KGGFDGVPVFQSEL-------LVV--KKKNK-------------------RYC
PVYFSKEDIEQELSKVARTSR----VP--------GAS----------------------
------------------------QHIVVGSLEDVLKKMEMSERS--T-------GWEDL
IFIPPGKSHSQHIQE----ITE--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Medicago_truncatula_gnl_BL_ORD_ID_21124__Medtr3g147870.1_PACid_17452775
M-----------------------------------ESQGQWNPLLSFSRFIHQ------
------------------------------------------------------------
---------------------NC----NH--LATR-----------------------FE
D-TR----------KFAGTLIQSHT---------------------------RTKP--AF
A--ATLTSNHVAKSLAGTSVYTVSSSNNEFV---LMSDA-EGA-------------KSIG
LLCFRQEDAEAFLAQV---------------RSRK-------------NEFR-GNAKVVP
ITLEQVYLL-----------------KV-EGIAFRFLPDPLQ----IRNALELRA--AN-
-------KEGFDGVPVFQSEL-------LVV--KKKNK-------------------RYC
PVYFSKEDIEQELSKVSRVSK----GP--------GVS----------------------
------------------------KQIMVGSFEDVLKKMEMSEKN--S-------GWDDL
IFIPPGKSRSQHIQE----IKV--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Brachypodium_distachyon_gnl_BL_ORD_ID_15294__1g45996.1_PACid_21818064
MPPP------NSTRSSSLPLAAAPMSNPSP------SSSPPPNPLAAASSFLQH------
------------------------------------------------------------
---------------------HLSNLASR--FAA--------------------------
--PR----------PAL----AAAHPPG------------------------PQGS--SL
S--LALAPDEVARALTGTPVFTVCNSSNEFV---LVSDPATGL-------------RSLG
LLCFRSEDADALLSHV---------------RTRQ-------------PVLG-KGAKVVP
ITLDQVYML-----------------KA-EGIAFRFLPDPLQ----IKNALELKS--G--
-------LTGFDGVPVFQSDL-------LVV--KKQKK-------------------RYC
PIYFQKEDIERELKKASKGSK----GS--------ALL----------------------
------------------------KQIMVGSLEDVLKKMEINDRN--S-------GWDDM
IFIPPGKSLNQHINEDCYRKRE--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Panucum_virgatum_gnl_BL_ORD_ID_9252__Pavirv00015657m_PACid_23765065
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------ML-----------------KA-EGIAFRFLPDPLQ----IKNALELKS--G--
-------LTGFDGVPVFQSDL-------LVV--KKQKK-------------------RYC
PIYFQKEDIERELTKASKSSR----GS--------ALS----------------------
------------------------KQIMVGSLEDVLKKMEINERN--S-------GWDDL
IFIPPGKSLNQHINE----VSA--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Sorghum_bicolor_gnl_BL_ORD_ID_27712__Sb10g007160.1_PACid_1983025
MAPP-----DSISTRSSLPLAAAPMSDPTPSPY--AASPPPPNPLAAAASFLQH------
------------------------------------------------------------
---------------------HLSRLASH--LNA--------------------------
--PR----------PALAAAAAAARTPG------------------------PQGA--SL
S--LALAPDEVARALTGTPVFTVCNSSNEFV---LVSDPATGL-------------RSLG
LLCFRSEDADALLSHV---------------RTRQ-------------PVLG-KGAKVVP
ITLDQVYML-----------------KA-EGIAFRFLPDPLQ----IKNALEMKS--G--
-------LTAFDGVPVFQSDL-------LVV--KKQKK-------------------RYC
PIYFQKEDIERELTRASKGSR----GS--------VLS----------------------
------------------------KQIMVGSLEDVLKKMEINERN--S-------GWDDL
IFIPPGKNLNQHINE----VSA--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Zea_mays_gnl_BL_ORD_ID_17023__GRMZM5G887716_T01_PACid_20836749
MAPP-----DSISTCSSLPLAAAPMSEPTPFPF---AASPLPNPLVATASFLQH------
------------------------------------------------------------
---------------------HLSRLASH--LNV--------------------------
--PR----------PAL--AAAAARTPG------------------------PQGA--SL
S--LSLAPDEVARALTGTPVFTVCNSSNEFV---LVSDPATGL-------------RSLG
LLCFRSEDADALLSHV---------------RTRQ-------------PVLG-KGAKVVP
ITLDQVYML-----------------KA-EGIAFRFLPDPLQ----IKNALEMKS--G--
-------LTAFDGVPVFQSDL-------LVV--KKQKK-------------------RYC
PVYFQKEDIERELTRASKGSR----GS--------ALS----------------------
------------------------KKIMVGSLEDVLKKMEINERD--S-------GWDDL
IFIPPGKSLNQHINE----VSA--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Oryza_sativa_gnl_BL_ORD_ID_49360__LOC_Os06g11020.1_PACid_21931832
MPPPPPNSSSSSSSSSSLPLAAAPMSNPSAPSSSSSSSSLPPNPLAAASSFLHH------
------------------------------------------------------------
---------------------HLSRLASR--FAAP-------------------------
--PR----------PALAAVTASAAPPG------------------------PQGASASL
S--LALAPDEVARALTGTPVFTVCNSSNEFV---LVSDPATGL-------------RSLG
LLCFRSEDADALLTHV---------------RMRQ-------------PVVG-RGAKVVP
ITLDQVYML-----------------KA-EGIAFRFLPDPLQ----IKNALELKS--G--
-------LTAFDGVPVFQSDL-------LVV--KKQKK-------------------RYC
PIYFQK------------------------------------------------------
-----------------------------------LRRT---------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Arabidopsis_thaliana_AT4G33350.1
M-----------------------------------ESSVKPNPFLSFSSFIHH------
------------------------------------------------------------
---------------------QCTRFSSD--LSAR-----------------------IE
D-TK----------RFAETLATRRF-----------SLPTPPPFASVSQS---KSG--TP
T--TTLSPSLVAKALAGTSVFTVSNTNNEFV---LISDP-TGG-------------KSIG
LLCFRQEDAEAFLAQA---------------RLRR-------------RELK-TNAKVVP
ITLDQVYLL-----------------KV-EGISFRFLPDPIQ----IKNALELKS--SG-
-----N-KNGFDGVPVFQSEL-------LVV--RKKNR-------------------RYC
PVYFSKEDIERELSKYTRASR----G-----------D----------------------
------------------------QQIMVGSLEDVLRKMEMSEKN--S-------GWEDV
IFIPPGRSYAQHMQD----LIKE-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Thellungiella_halophila_gnl_BL_ORD_ID_14624__Thhalv10025972m_PACid_20194177
M-----------------------------------ESSVKPNPLLSFSSFLHH------
------------------------------------------------------------
---------------------HCNRFASD--LSAR-----------------------IE
D-TK----------RFAETLTTRRF-------------SPPSPFASVSQS-KPSSTAVTS
S--TTLNPSHVAKALAGTSVFTVSNTNNEFV---LISDP-TGD-------------KSIG
LLCFRQEDAEAFLAQA---------------RLRR-------------RELK-TNAKVVP
INLDQVYLL-----------------KV-EGISFRFLPDPIQ----IKNALELKS--SG-
-----S-KNGFDGVPVFQSEL-------LVV--RKRNK-------------------RYC
PVYFSKEDIERELSKYTRASR----G-----------D----------------------
------------------------QQIMVGSLEDVLRKMERSEKN--S-------GWEDV
IFIPPGRSYAQHMQE----VIQE-------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Brassica_rapa_gnl_BL_ORD_ID_20295__011434_PACid_22703805
M---------------------------------ESSSSVKPNPFL---SFLHH------
------------------------------------------------------------
---------------------HCTRFASD--LSSR-----------------------FE
D-TK----------RLAESLTNRRF--------------SPSPFASVSQSPKPSSG--AS
T--TTLNPSHVAKALAGTSVFTVSNTNNEFV---LISDP-TGD-------------KSIG
LLCFRQEDAEAFLAQA---------------RLRR-------------RELK-TNAKVVP
INLDQVYLL-----------------KV-EGISFRFLPDPIQ----IKNALELKS--SS-
-----S-KNGFDGVPVFQSEL-------LVV--RKKNK-------------------RYC
PIYFSKEDIERELSKYTRA------------------D----------------------
------------------------QQIMVGSLEDVLRKMERSEKN--S-------GWEDM
IFIPPGRSYAQHMQE----VVKEIK-----------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Glycine_max_gnl_BL_ORD_ID_8828__04g04070.2_PACid_16254796
M-----------------------------------ESRGHSNPLLSFSSFIHQ------
------------------------------------------------------------
---------------------HCVRLGSD--LATR-----------------------LD
D-TK----------RALAQAHHNLL---------------------------FPKH--AL
AATSTLGSLHVAKSLVGTSVYTVSNSNNEFV---LISDA-DGA-------------KSIG
LLCFRQEDAEAFLAQV---------------RSRS-------------RELR-SKARVVP
ITLDQVYML-----------------KV-EGIAFRFLPDPVQ----IRNALEVSIL----
-------LYSSRIQHITLSHT-------IIV--HHFSP-------------------VAM
TVYMVAA-----------------------------------------------------
-------------------------------------------------------MWELV
LWHQFKLNYT--------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Panucum_virgatum_gnl_BL_ORD_ID_51866__Pavirv00010181m_PACid_23808112
M---------------------------TGPTPSPTSAAPPPNPLAAASSFLHH------
------------------------------------------------------------
---------------------HLSRLASH--LTA--------------------------
--PR----------PAL-AAAATRAPG-------------------------PQGA--SL
S--LALAPDEVARALTGTPVFTVCNSNNEFV---LVSDPGTGL-------------RSLG
LLCFRSEDADALLTHV---------------RTRQ-------------PVLG-RGAKVVP
ITLDQVYML-----------------KA-EGIAFRFLPDPLQ----IKNALELKS--G--
-------LTGFDGVPVFQSDL-------LVV--KKQKK-------------------RYC
PIYFQKEDIERELTKASKSSR----GS--------ALS----------------------
------------------------KKIMVGSLEDVLKKMEISERN--S-------GWDDL
IFIPPGKSLNQHINE----ISTNAWRRRAMGSVGAIQGERHLPPVAEKRRPSGLGAVTAV
LFLASPLLLLFFLFGDRAAASIAADYPAWQRFKVQSTCSAPSSFAQHRFHGSGNAPSSRR
AERGAHDRLLSGLLSPDFDGATCLSRYEASKRWKPSPFPVSPYLIQKLRRYEANHRRCGP
GTANYRAAMAQLMSGRNADGAECKYVVWLPLQGLGNRMLSVVSTFLYALLAGRVLLVHEP
PEMEGLFCEPFPGTSWVLPPGFPYTDGFSASTKESYANMLENNIVRSDGGGDASALPAYV
YFHLEQIGLRLQNHTFCEEDHRVLSRFNWMVLRSDSYFAVALFLMPVYRGELDRMFPAKA
SVFHHLGRYLLHPGNRAWGIVERFYDGYLAGADERLGIQVRPAPFLPITSEDMYEQIARC
AREHDLLPRVTGTSGDNPGARLPASGVAKVKAVLVVSLKPEYYDKLHSVYYTNATATGEV
VTVFQPSHDQDQHTEALAHNERALAEIFLLSYSDRLVTTGFSTFGYTAHSLAGLRPWLLL
LPDRNTMTAEVACVRSASVEPCLHSPPSLVCRAEQDLDPVAHVPFLRHCEDVDFGLKLI-
>Setaria_italica_gnl_BL_ORD_ID_30215__Si007932m_PACid_19703754
M---------------------------TDPTPSPTSAAPPPNPLAAASSFFHH------
------------------------------------------------------------
---------------------HLSRLASH--LTA--------------------------
--PR----------PALAAAAATRAPG-------------------------PQGA--SL
S--LALAPDEVARALTGTPVFTVCNSNNEFV---LVSDPATGL-------------RSLG
LLCFRSEDANALLSHV---------------RTRQ-------------PVLG-RGAKVVP
ITLDQVYML-----------------KA-EGIAFRFLPDPLQ----IKNALELKS--G--
-------LTAFDGVPVFQSDL-------LVV--KKQKK-------------------RYC
PIYFQKEDIERELTKASKSSR----GS--------ALS----------------------
------------------------KQIMVGSLEDVLRKMEINDRN--S-------GWDDL
IFIPPGKSLNQHINE----VRAS-------------------------------------
--VSSPFV--------------------------------------SRIAGSGNASSSRN
AGGSAHDRLLGGLLSPDFDAATCLSRYEASKRWKPSPFPVSPYLVQKLRQYEANHRRCGP
GTANYREAMAQLMSGRNADSAECKYVVWLPVQGLGNRMLSVVSAFLYALLSGRVLLVHEP
PEMQGLFCEPFPGTSWVLPPDFPYTDSFSADTKESYVNMLENNIVRYNGGGDARALPPYV
YFHLEQISLRLQNHTFCEEDHRVLDRFHWMVLRSDSYFAVALFLMPMYRGELDRMFPAKE
SVFHHLGRYLLHPGNRAWGIVERFYDGYLIGADERLGIQVRLQPFLPMTFEIMYEQITRC
AREHELLPQVTDTS--EPGSR-PSNGAAKVKAVLVVSLKPEYYDKLHNVYYTNATATGEV
VTVFQPSHDQDQHTEALAHNERALAEIFLLSYSDRLVTTGFSTFGYAAHSLAGLRPWLLM
LPDQTTMRAKVACVRSASVEPCLHSPPSLVCRAEQDLDPVAHVPFLRHCEDVYFGLKLVD
>Physcomitrella_patens_gnl_BL_ORD_ID_25445__Physcomitrella_patens__Pp1s282_30V6.3_PACid_18061981
M----------------TEGGSGSSAACKGEYVAGGRRMAQRRPLLDGGAVVSDVRRRLV
EAQNWLGVAVAEGANRISRFGLSIEDGRGMMVQKME--------------------RIGN
RRSDPRSKIRSGQLPWEKVWTAMSGFGAQ--FEAQ-----------------------LQ
R-SK----------AGIPEAMLRMIWNR-GAPRPLIASLSLGLPAQGGEAL-EAKH--VF
D--IAMSGEQVAKRLDGVPVYTVSNSANEFV---LISDL-NTS-------------KSLG
IFCFREADAEALLSQV---------------RDRE-------------PSLG-RGAKVVA
VSLDKVYQL-----------------ST-EGIAFRFLPDPRQ----VKNALEARSRAGE-
-----P-GKAFDGVPVFQSDN-------LIL--RSNNR-------------------RFC
PIFFSKEDLETALQRAFKQQQKINPAL--------K------------------------
----------------------------VGSFEDVLKRMEGNEED--S-------GWGDI
VFIPPGMDAYKHLSKSQGTVVG--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Selaginella_moellendorffii_gnl_BL_ORD_ID_20616__Selaginella_moellendorffii__26102_PACid_15421894
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------------------F
D--LAMAPDQVSKRLDGVPVYTVSNHDNEFV---LISDS-NGH-------------KSLG
LFCFRHEDAEALLAQI---------------RDRE-------------PGLG-RGAKIVA
VSLDKVYQL-----------------KT-EGIAFRFLPDPLQ----VKHALESRAKAGD-
-----P-GKAFDGVPVFQSDN-------LVL--RSKNR-------------------RFC
PIFFSKEDLERALLGAFKQQQKINPAL--------KVN----------------------
------------------------TDIQVGSFEDVLQRLESSDDG--S-------GWGDV
VFIPPGMDALSHFSEKVS------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Physcomitrella_patens_gnl_BL_ORD_ID_32296__Pp1s81_171V6.1_PACid_18068833
MDVASASRVVSSAGGVADGMRGFRRCTPLGEDLVMLVRLADTRNWLRCEQLVEN------
-----------------------------RKRIVAQ--------------------SVGS
VRRNRRAVWNGISDCEKKLWMGSSGLGTQ--VETQ-----------------------LP
R-TRFERARRVRDQKPLRVPMASFSLGS-PNQGDEWESKLRSESE-------EVET--NL
R--NAMTEEQVNKCLDGVPVYTVSNSANEFV---VVSEM-NSP-------------ESYG
IICFRETDAEAFLSQI---------------RSRD-------------PSAG-SDVRVTA
IPLGKVLQL-----------------SSKEGETFRFVPDPNQ----IRNAYEVKARAGE-
-----L-SKAFEGVPVFQSES-------LTL--NSINR-------------------RLL
PIFFSKEDLETALQTAFEEQKRVDPAL--------EFK----------------------
------------------------PNIQVDSLEDILDMMEGSEEE--T-------QRAEI
VFIPAGMDVFKYLTQFEGAIAR--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Chlamydomonas_reinhardtii_gnl_BL_ORD_ID_2091__14.g625750.t1.1_PACid_19860381
M-----------------------------------------------REGVTRWLERTP
LAQIIRNAQEGVATQQ-------RQRDQGPWAPMLA--------------------SIAM
SGAGPRPQP---------------------------------------------------
----------------------------------------------------------VM
D--LAMAKDEVKARLAPVPVYTVANPKNEFV---LVAGE-NN--------------TQLG
FFFFRKEDAEALIEKI---------------REEN-------------PRLA-RDSKILR
VPMDNVYEVFTTPREQT---------GL-QGIHFRFMPDMKQ----VAHALQLYKDAGV-
-----P-TRQFIGVPVFQAEG-------LTV--TTRDM-------------------QYV
PLFLCKEDLDIAVQSAYVQRNAAQIKLYKDKADKYQADYDQIASQLEAAANGRERGGLES
RLAKARVKLEAARDKVESVERAPLPKVEVGSFEEVVMRMTASAGNELA-------AWSQV
MFVAPELLRDSAGAGGKK------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Volvox_carteri_gnl_BL_ORD_ID_8007__Vocar20001833m_PACid_23131891
M--------ERNEGPLQHLQRSLDHVGRGLASQWQQLPAQVERTFVPMRQGVSRWWEQTP
IAQIIRNVQEAAAAPP-------RVRDQGPWAPLLA--------------------SITM
GSAAHRPQP---------------------------------------------------
----------------------------------------------------------VM
D--LAMAKEEVKARLAPVPVYTVANPKNEFV---LVAGE-NH--------------TQLG
FFFFRKEDAEALIEKI---------------REEN-------------PRLA-RDSKILR
VTMDNVYEVFTTPREQT---------GL-QGIHFRFMPDMKQ----VAHALELYKAAGV-
-----P-TRQFIGVPVFQAEG-------LTV--TTRDM-------------------QYV
PLFLCKEDLDIAIQSAYMQRNAAQIKLYKDKADKYQADYEQIASQLESAS-GRERSGLES
KLAKARAKLDAAREKVESVERAPLPKVEVGSFEEVVMRMTASSGNELA-------AWSQV
MFVAPALLQEASKGGAAAKK----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Cyanophora_paradoxa_gnl_BL_ORD_ID_26154__Cyanophora_paradoxa__ConsensusfromContig52820-maker-ConsensusfromContig52820-snap-gene-0.3-mRNA-1_cds_10085/8432-8552_0_-
MASFAATLITSAVCAAPARQRSAESVPARQPASSRLFGASKRSDFFGVRAAADSRPVFRP
VSVPTISMSLKEEDVSGEETSEARSKLAGAAIAVAG--------------------VAGI
AAFGVMTQS---------------------------------------------------
----------------------------------------------------------ES
A--EAIDRATLTKQLSEVPVFTIVDASNKPI---VASNW-GEEK------------GRFV
VFYFSRKDAMAALPKA---------------RAGQ-------------P--G-KNLKVMT
VGLDKAYKLTKDAEAAAKSGAAVDAGSD-AGIQARYVPVAKQ----IKNAVDVLKTQGR-
-----K-VTHFNGTPIYQAEG-------LTM--RQGNDTR-----------------QFI
PLFFTKEDLEAAWAEMRRGNPAMSPQPRIEARPPPALS----------------------
------------------------FLLSVGAFEELMKRMEDTDSP----------EWQRV
VFFAPKESLDFVGQPRW-------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Cyanophora_paradoxa_gnl_BL_ORD_ID_31422__Cyanophora_paradoxa__ConsensusfromContig9031-snap_masked-ConsensusfromContig9031-abinit-gene-0.4-mRNA-1_cds_2409/422-473_0_-
MAKN--------------------------------------------------------
-----------------------RARAVGALATLLA------------------------
------------------------------------------------------------
----------------------------------------------------------KE
A--EAIPLSNVLKALENVPVFTITNAQGTPL---TASSI-SGNK------------GRVG
VFFINRLDAEQMLNKARPPSQRRSPLSLRLVRADN-------------PSVG-RTAKVTA
VGLDKAYEIQRKFAK--DGD------KG-EEVIFRFYPNLEQASRLVKHAQNILKGQGK-
-----K-WEPLHG--------------------DGDNN-------------------MYI
PLFFTKEDMESAWREMRKSNPQM------------KAT----------------------
------------------------PDV---------EEMESDNAP----------HWHQV
VFFAPVDSLNYIKASRGKGLKI--------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Cyanidioschyzon_merolae_gnl_BL_ORD_ID_1500__Cyanidioschyzon_merolae__gnl_CMER_CMJ105C_similar_to_chloroplast_inner_membrane_protein_Tic22
MSAFAVP--AAHPARRQRPALGLDRPLVPRWSSKRQVLFHRGRPLVTFRKHLLSATERVC
LSEQRTPGVVGQPAPET------SWMQRAARALLLGLATVNIWTPLLRGFSLGAGLQVLL
GAPAVSA-----------------------------------------------------
----------------------------------------------------------AK
TPHARYSRKTLSEKLAQVPVFAVTNESGQPF---LAAME-RG--------------LQVG
LIFFDPDDAIKMLEDL---------------KRSS-------------GKEA-EDARIFI
MGLDRAFEMVKSKPQ--PSGLRGPRGDE-LKMVFRFYPNQQQ----LEYARTVAKKTK--
-------QPTVRGVPCFVAKG-------LTL--RKGKE-------------------FVI
PIFLDKRDLDEAWNRLRQELAEL------------PKQ----------------------
------------------------PEIEVGDLIEVILRLEEAAKNPKSLNETELQDLRRV
AFFPSSKSVEFMKRESAKQFKGTARMHSRP------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
>Synechococcus_elongatus_PCC_7942__gi_81300671_ref_YP_400879.1__unnamed_protein_product_[Synechococc	
MN----------------------------------------------------------
-----------------------KFLTSAAALVISL--------------------SGGV
AIPLIAP-----------------------------------------------------
----------------------------------------------------------PA
A--IALSDQEVAARIGRVPVFVILTKEQQPL---LFTSR-DKDGKEV---------NKTF
PVFINQTQAQAALAEL---------------QKSN-------------QPLG-KDARIGS
LLLPKALELILDFLK---------KTND-PKVTYEIIPDPKQ----RAKALELYKADKNI
KPEQLKQLESEAFVPIFYSES-------LSI--TMTNQQGQPVKDAKGNAI------RRI
PLFLEYEPLAAELEKLKKQDTNAK-----------AGE----------------------
------------------------YAITVTDLLTIINTLTAAQPG--S-------NESLI
ELLPPVSSLPVLQELVKQLTPTNGTTPPRATTTTPPAAGTGTTPPRATNPTPTPRPAN--
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
