>iTic22-like_gi|18424615|ref|NP_568958.1| Tic22-like family protein [Arabidopsis thaliana]
MGSPDKQHRRHVAAEFLHSAVTSISSSIIPLFPPKTAPSRVCLPLRFSVSDDVSSPFESTVKSTSSASSS
GLNSTVRISSLSSDGKRGGPAFVGQVFSMCDLTGTGLMAVSTHFDIPFISKRTPEWLKKMFSTITKSERN
GPVFRFFMDLGDAVSYVKKLNIPSGVVGACRLDLAYEHFKEKPHLFQFVPNERQVKAANKLLKSMPQNGK
TQKVEGVPVFGAQNLDIAVATADGIKWYTPYFFDKAVLDNILEESVDQHFHTLIQTRHVQRRRDVVDDSL
ASEVMEEMGDSMLEPPEVQEAMEEIGTSGIPLSVVAKAAEIQLLYAVDRVLLGSRWFRKATGIQPKLPYL
VDSFERRSAFSIQRASGSATRCLGDSVEADTSASLLRVEDDSPSEAEKRQQHLWFPFGDWISHSVSRKEH
THHKGSSDQRDMESREREMLRSPFLPKITMVGISTGEAAQMSKANLKKTMEDLTEDLEQSDEGNDHGSKR
YDSLKIEERDPLFVANVGDYYSGLAKAGSARLSRRGDDQ



>Aquilegia_coerulea_gnl|BL_ORD_ID|35613 _013_00192.1|PACid:22058731

MA----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------ISPSESHLNYNNNNNNFTRFIQSTSSSFFSLF
NPSPLPPLSSSSSSFPFCSSSSICVPLLFSDTPPRILSLSTTLSTNSSSSSTTPSSQNDP
LSLNSQIKTRSPSSKFPSSIKISGLNSNPNGSGPAFVGQVFSMCDVSGTG----LMTVST
HMEIPFISKRIPE-----WIKSMFSVFNKSENNGPVFRFFMDIGDAVSYVKRLNIPTGVV
GACRLDLAYEHFKEKPHMFQFVPNEK-----------------------QVKAANKILKK
T-QHSEKRIVDGVPVFTAQNLDIAIATGDGIKWYTPYFFDKNMLDNI--LEESVDQHFHS
LIQSRHMHRRRDVIDDNLTAEVVEDNRDNLWEPPEVQEVLDEMGYPGLPMSVISKAAEVQ
LLDAVDKVLLGNRWLRKATGIQPKFPYRVD---------------SFEKRSAASFRKATE
LTSIASNRID--------------------------------------------SCVGSK
CENLKGSEEPRLEEN--TQS-GQRQ---------PSEVRLPFGDWFSHLWSKQQ---HKP
DE-QTRLT--------DSRDKYIEQLPLSPL----------LPKIT-MVGISTGEAG---
QTSKASLKQTMEDLTRELEQPGQDIDDGGS--NEIRHEERDPLFVANV------------
G--------------------V
>Arabidopsis_lyrata_gnl|BL_ORD_ID|26695 _496448|PACid:16060442

MGSPDKQHRRHVAAEFLHSAVT----SIIPLFPPKTAPSRVCLPLRFSVSDDVSSPFEST
VKSSSSTSSSGLNSTVRISSLSSDGKRGGPAFVGQVFSMCDLTGTGLMAVS-THFDIPFI
SKRTPEWLKKMFSTITKSERNGPVFRFFMDLGDAVSYVKKLNIPSGVVGACRLDLAYEHF
KEKPHLFQFVPNERQVKAANKLLKSMPQNGRKQKVEGVPVFGAQNLDIAVATADGIKWYT
PYFFDKAVLDNILEESVDQHFHTLIQTRHVQRRRDVVDDSLASEVMEEMGDSMLEPPEVQ
EAMEEIGSSGIPLSVVAKAA-EIQLLYAVDRVLLGSRWFRKATGIQPKLPYLVDSFER--
----RSAFSIQRASGSATRCLGDSVEADTSASLLRVEDNSPSEDEKRQQNLWFPFG----
-------DWINHSESKKEHTHHKGPSD---GRDMESRER-EMLRSPFLPKITMVGISTGE
AAQMSKANLK-KTMEDLTEDLEQSDEGNDHGSKRYDPRKMEERDPLFVANVGDY------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------YSG---------MAKAG-----------------------------
---------------------------------------SARLSRR--------------
------------------------------------------------------------
-------------------------------------------GDDQ----------
>gnl|BL_ORD_ID|31448 Arabidopsis_thaliana AT5G62650.1|PACid:19669395
MGSPDKQHRRHVAAE---------FLHSAVTSISSSIIPLFPPKTAPSRVCLPLRFSVSD
DVSSPFESTVKSTSSASSSGLNSTVRISSLSSDGKRGGPAFVGQVFSMCDLTGTGLMAVS
-THFDIPFISKRTPEWLKKMFSTITKSERNGPVFRFFMDLGDAVSYVKKLNIPSGVVGAC
RLDLAYEHFKEKPHLFQFVPNERQVKAAN---------------------KLLKSMPQNG
KTQKVEGVPVFGAQNLDIAVATADGIKWYTPYFFDKAVLDNILEESVDQHFHTLIQTRHV
QRRRDVVDDSLASEVMEEMGD-----------SMLEPPEVQEAMEEIGTSGIPLSVVAKA
AEIQL--------------LYAVDRVLLGS--------RWFRKATGIQ-----PKLPYLV
DSFE-----RRSAFSIQRAS--GSATRCLGDSVEADTSASLLRVEDDSPSEAEKRQQHLW
FPFGDWISHSVSRKEHTHHKGSSDQRDMESREREMLRSPFLPKITMVGISTGEAAQMSKA
NLKKTMEDLTEDLEQSDEGNDHGSKRYDSLKIEERDPLFVANVGDYYSGLAKAGSARLSR
RG-----DDQ
>Brachypodium_distachyon_gnl|BL_ORD_ID|2714 _2g07450.1|PACid:21805484

MPSSSSS------------------------------SNPFHSLTFNLPFPPAPSSCSTS
---ASS------PPAPAP-HLAFPLLLPVSS------ASTTS-----------------S
YSPASHLIPQPQRLPGERMAGPAAASGGKGVSAGKSPGGPAF---------------VGQ
VFTMLDPSGNG---------LMAVTSRFDLPHFIAH----------------------RT
----------------------------PTWFKRILS--------------PLKKSE-SS
PVFRFFMDLNDSV--SYVKRLNVPSGMVGACRLDVAYEHFKEKPHMFQFV----------
-----PNEKQVKAA--NKLLKSIPQKSRRKKLAGVPVFSAQNLNIAVATDDGIRWYSPYF
FDKNLLDNILE--ASMDQHFHSIIQNRHIRRRRDIVDDSLT-----SEILEESADSLLEP
PEVQELMNEIGPAGI--PLSVVT-------------------------------------
--------------------KAAEI-------------QLLDV----------------V
DKLLL-------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------GNKWLRK-------ATGIQPR-F
PY----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------VVD---------SFEERTALS---------------------------------
-------VDRTATSSN------------SC------------------------------
--------------------------------TASKDADFFTNDQQSQAL----------
------------------------------------------------------------
------------------------------------------------------------
-----------------------EPNVDSGNHRKHNSRDHGQSH--FPFSNLLPNI----
----------WPGH--DRKFKAQEHDNRFKRYGASMDNDLQANPLLPK------------
---------------------------------------ITMVGISMSE--GGQMSKA--
-------------------------------NLKKTM-----------------------
----------EELTKELEQAGE--------------------------------------
---KTVFS-DEK------------------------------------------------
----------------DPLFVANVGD--YSRITKISST----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------
>Brassica_rapa_gnl|BL_ORD_ID|11888 _010109|PACid:22695398

MD----------------------------------------------------------
--------SPDKIHRRYNAAEILHGAATSI--------------------------SSII
PLFPPKTTPSRVCLPLRFS---DV-S-----------------PFESTVKN---------
-----------------------------------ASSTSTSSSGLN-------------
------------------------------------------------------------
------------------------------------------------------------
---STVRISSLSSDGKRGGPAFVGQVFSMCDLTGTGLMAVS-THFDIPFISKRTPEWLKK
MFSTITKSERKGPVFRFFMDLGD---AVSYVKKLNI----------PSGVVGACRLDLAY
EHFKEKPHLFQFVPN---ERQVKAANKLLKSMPPS-----------------EKKQRVDG
VPVFAAQNLDIAVATSDGIKWYTPYFFDKAVLDNILEESVDQHFHTLIQ-TRHVQRRRDV
VDD---SLTSEIMEEMGDSMLEP---------PE--------VQEAMEEIG---TSGIPL
SVVAKAAEIQLLYAVDRVLLGSRWFRKATGIQPKLPYLVDSFERRSALSIQRASGSTTKC
------------------------------------------------------------
-LGDS---NSSASLLK----VEDGSPSEEEKRQQSLWF-----PFGDWLK---------A
QKDSSGQREMESREREMQRSPFLPKITMVG-ISTGEAAHMSKANLKKTMEDLTQDLEQSD
EGSDHGSNRYDPLKIEERDPLFVANVGDYYSGL------------------ARAGSARWS
RRGDDRNETPPRSS----------------------------------------------
-------------------
>Citrus_clementina_gnl|BL_ORD_ID|24296 _0.9_006877m|PACid:19275444

MASPAEPNHLQNQISSFINATTSTLFSLITPTKTTPSSQSQPSSAPASRLCIPLQFADSS
CPSSSTRSPVGSDSISSNSGASSSESSSSGFPSTVRISAINSSGKGGGPAFVGQVFSMCD
LSGTGLMAVSTHFDIPFISKRTPEWLKKLFATITKSERNGPVFRFFMDLGDAVTYVKQLN
IPSGVVGACRLDLAYEHFKEKPHLFQFVPNEKQVKAANKLLRTIPDSGRKKKVDGVPVFS
AQNLDIAIATADGIKWYTPYFFDKNMLDNILEESVDQHFHALIQTRHMQRRRDVIDDNLA
AEVVEEIGDSIWEPPEVQEMMDEIGHPAIPLSVISKAAEIQLLYAVDRVLLGNRWLRKAT
GIQPKFPYMVDSFENRSAASFLRASES-TSCLANS-ETNNGSSDLKLEDKHLDKRDQRPD
-FRFPFGDWFRHLWS-KQDCEAQGSS---YIECTKRNLQLNPFLPKVTMVGISTGEAGQM
TKANLKKTMENLTKELEQTDQENATSSGSNEY---IIEDRDPLFVANVGGYYSGLAKTGS
TRWVRGRSNN
>Carica_papaya_gnl|BL_ORD_ID|1469 _evm.model.supercontig_107.127|PACid:16405310

MASAT---DQPQ------HNFHHRIANLLHATSSSLS---FLLPSPKTAPYPPSPPKLCV
PFKFADSPVLPLT------------------SVFESPQSDSVSS--KSTIKGVSSAESNS
GFSSAVRIGGLNSNGKASGPAFVGQVFSMCDLTGTGLMAVSTHFDIPFISKRTPQWLKKI
FATITKSERNGPVFRFFMDLGDAVAYVKQLNIPSG---VVGACRLDLAYEHFKEKPHMFQ
FVPNERQIKAANK------------LLKKIPQNDGRTKVDGVPVFGAQNLDIAIATVDGI
KWYTPYFFDKNMLDNILE-------ESVDQHFHSL-IQTRRIQRRRDVVDDSFAAEVIE-
-----EMGDNSWEPPEVQEVLNEIGHPGIPLSVIS-------KAAEIQLLYAVDKLLLGN
RWLRKATGI-QPKFPYLV-DSFERRSTASFLKAS-KPTNCLTDFEAGLDTSGVEL---DD
KFQGNHRETKDFQLPIGDWLNHSWLKQGQKHQM---------------------------
---------------------------LADTGY---------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------
>Chlamydomonas_reinhardtii_gnl|BL_ORD_ID|12022 _13.g593950.t1.2|PACid:19870334

MA----LQSRHGRATFLH------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------AY--
-------------------------------WRERAL-----------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------------------RPCLRRPV-----
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------LTVSAVAASSSAAEGR---------------
------------------------------------------------------------
------------------------------------------------------------
----------------GKASGLGSLT--------FLDFVVPFSTPLAAAIATGVYTGAVG
ADLAWPLRALLVGGGPLLVHLLFPAVDWALGP----------------------SRALAE
RQQQQAQQQALGIKAPGADHFL-----SRALPCLAVAVQLLVLLATYGALAAA-------
------------AGAPAPPLAGAAGAAAAGLQQQQLLLLPLLVTSLALSAGMAQAASHEL
LHSRHPVHLAAAWLFL-----------TTHWWYPY--------FRAHHQHHLAVCTPADY
ASAPRGLSLAAYLPR--YIGSSYTEAWQLAAAECRRAGHPVFSTHNSCLVALVAQAALTA
ALGLALGPAAALLHGAVCAVLLTYMSVLDYVLHYGLRRPPLVVAAAAAATAGGVGGGADA
AVSTVADSREVTGVAPAAAGVAAAPAAGSGAVRYAPVTPFNSWSSLYPLENALFFNVLIH
GDHHMTASRSYAWLVPAPSSPTFPAPINALALATFVPPLWRAAMHERVDQANSANLRHLA
ATGVPVAA----EQGAAEQGAAEQVAA--------EQVAAAGTA----------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------
>Chlamydomonas_reinhardtii_gnl|BL_ORD_ID|5295 _06.g304000.t1.1|PACid:19863592

M------DLTCGEVCFLARSASGQSLALPGVFSLSFALKGQGKRAALQLVFKTKDETADG
QTPGPSAAPTVRSPHRRAHANGAAAVADDVFALVDRTATNRVEWLPQNQRGVADPVGQLQ
AALGAGLIRLTPMALAPHTYAGSGAAGGHAGSGGATGSNRITSRTGTNADGVLVPASGYL
EVHAAVVLLPAAFELVVPEPVPRAAAALGGLGDVLARSAAAAALVAVVEMLEEGPAAEEE
AEQGGEEGAEGGAAAGGAAGGSAAAASGPVDQQQQGSQWEGSQQHPEQEPEQEPPHAYAD
VRDEVFDIVAPRDWAV-THPDPPGLKCRLFRYQQRCLSWMVWRETQPELGAQAAHPHEPG
QQGQQGGGAGADTAGGALATGGDAASISAVPPEAAAAAAAAAAHLGDYATQDLFWRRVRL
RYGGGLSAAAAAAAGGGAAVAAGLGEGELWLNTYPGGGLRATPPPPPPRQKVGILADEMG
LGKTVEVIALMLARPAPPPEARAQAAAAAAAAAAAAAAAAEQQEEAAAADTGGAGVKEQG
DGEEDADVDGRRRSGRQRRAVRFTDNYYDCVDDDDDEDYKPGGGSSRHGGGRGGTRRGSA
PGMEAVGSGSGAAGGGGGAAGGVVRPLGPSLIVVPATLLQQWSNELEDHSSLKVHVYDGL
KWHRVQAQEREKQAIKEAKRKAREDKAAEQQAKRQERARLAAARIMAKRAARRNARSTDG
GSTKRRRGGAAPADADAAGAGPSLNGGAAAGGAPRAKRRRTARRDPGYEGMDLDSEEEEE
EEVELTETDAEELDPDAVEGGSGAGPSQSTAQRQRSQRQAARREMQEELERHGEDLRKAL
EASRREGAGGAGGSAAAPAAAAAAGGPAGAQTPGAAAAAAPATGGAYGDAGGAAAAPPAN
GTSHATANGAGPTAAAAAVHVPSRYEVLAREMTMALYAGTARCPASCDPAAEAEAAVAEL
LQADVVLTTYQVLKEEVHYSPSNRALQGLRHGKKYSVPESPLLQVHWYRLVLDEAQQVGG
SLSHVAVMAGRIQAEHRWCVTGTPIGRGGLEDVFGLVKVLGYKPYDDHPVFRRLVSDPYR
TGSAEGRSRLAALLKPIMWRNSKAVAAADHPLPRRVLQEARLCFSAAEASFYEVVLGKTR
KAVTAMDSHTAEQQQQQGQLGQQQQQQLGQQQAATGVEVVDLTQDHTAHVANGHGHGHGG
HKRKTKDKGAELQAEAGAELHQLRRACVHVKLTRHWRQLSTELGFGGGAGEALPTADVVM
VRLRDQAQLELQNAERDLCMTLNALAWRLEATHRRVAALAAKKRAAEAAAGGGGGGGGAA
GATPKKGAKKGGPGALVPAAAAPAGDVMVVEGEEEADVGALGSPGGATGGAGAGGEVVVS
AFRYNHSGKSAADLAADARHLLADAYRTLDTSWQVGENGIEAAAAAEAEAGEGGDDGGGY
EADIKAAGASIRAWRFVQAHTSQLLVDLLTRHPHVLAHTNAAAFATGTAAGGNAAANGGA
AAAADGAGPSTAGAAATSATVTAAAAPSEPDAAALAAAAAAAASRAADLRQYVSSRAADI
RSGADRELGKARERRDKVMTAIQRLEKQVVEEHETAVGRGLPPQLVSEPRAWLAELGQRL
EAARQAEAARRAEEQAAAGANATLSLMGKEVPALLAAEEAAVNKQRVGLDAVAGQHLVAA
ALARLRAAERGLRQRYGGGGGASSITPDPALWTPVLVGGITLMVPPEGYVDTGSSGGE--
ADPARAARAGWAASYPPALGLLRRAVAGCCEPEPVEGAAVGIAHACDTMTVMLVERHLRH
PHRMLDSRLAE--QRRTADSHG-----TSSLHGLGLGVLLPALEAVRGRIELLRQWREHN
VAELQVELAEHHVEVVSEEVAAAAGGRVAGMAP----LLRAGEEELRAKAAELKARCEEL
RRNRTFFN-------------------NKYLEATS--------LRRHHTHHQTHHQQASQ
QAQPAQQGPAAQQPQ--GLGANAPAAGPSSDAAAAKAA-------AAAVAAGPSGSAAGA
AAPVAGSPPPAQPQAAPVSVDVE-------------------VVEAAAARPHEEGDGMEV
EVEVVGGS--AVGKRMAAATAAAHVGVACRTGIFACLHPWLEWAPGYDPR-------VWN
RQRQQQQQQQQQQHSPAAAGGGGPATAGS------------AGADRRGGGAGGADADMVD
LTGADVEAIVVEEDAGEEQGGGEAAAARREQEQERRRTAAAAAAAAAAIARAEVAARGSG
PDTSAGAAGGADAMNGVAVAASTVAAAAGVGADAGGAAGSGSLSQAAAQPGQYPEGQQRQ
GQPQQGQQQQAAEADDSNMCILCCDQFGHDVRIFPCGHWFCGNCTDQLMSAPPDKRRCPT
CRCEVRDKTSILQASGVGGAARQRRAAAGGEVDPPEGPHILNVKVEAADELMTKIGALLR
RLVWLRNHRPAEKSLVFSQWADALQIVERGLRANDIGCVTLESGRRMRPAMNAFLHDPAC
RVFLLSLRQGAAGLTLVRANHVFLLEPALDPAIEQQAVARVHRIGQTRDVSVTRLLVDDS
VERHVMAMLKAKQQLFMEAAGSASTSTSGGAAAAGAGAARGALVAPTAVPLLEGGEGEEA
SLQAPAPAKEVAAGADLRYLFSAVLK
>Capsella_rubella_gnl|BL_ORD_ID|25653 _v10028359m|PACid:20911489

-------------MGSPEKQHRRHIAAEFL------------------------------
-------------------------------------------------------HSAV-
--------TSISSSIVP-------------------------------------------
--------------------------------------------------------LFPP
KTTPSRVWLP--------------------LKFSVSDDV---------------------
------------------------------------------------------------
---------------SSPFE----------------------------------------
-------------------------------------------------------STVNS
KSSKSSSGLNSTVRISSLSSDGKR------------------------------------
-------GGPAFVG----------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------QVFSM
CDLTGTGLMAVS-THFDIPFISKRTPEWLKKMFSTITKSERNGPVFRFFMDLGDAVSYVK
KLNIPSGVVGACRLDLAYEHF-----KEKPHLFQFVPNERQVKAANKLLKSMPQNGKKQK
VDGVPVFGAQNL-DIAVATADGI---KWYTPYFFDKAVLDNILDESVDQHFHTLIQT---
--------------------------RHVQRRRDVVDDSLTSEVMEEMGDSMLEPPEVQE
AMEEIGSSGIPLSVVAKAAEIQLLYAVD-RVLLGSRWFRKATGIQPKLPYLVDSFERRSA
LSIQRASGSAARCLSDSVETDT-------SASLLRVEEGDSPREDEKRRQNLWFPFGDWL
KHSVSRKDQAHQKGSSGQRDMESRDREMLQSPFLPKITMVGISTGEAAQM------SKAN
LKKTMEDLTEDLE-QSD-EGNDHGSKRYDPLKIEERDPLFVANVGD--------------
--------------------------------------------------------YYSG
LAKAGSARLSRRGDDQ
>Cucumis_sativus_gnl|BL_ORD_ID|17033 _192940.1|PACid:16968025

MA----------------------------------------------------------
------------------------------------------------------------
--------------------------------------------------FQIEPSSEPH
E-----------------QNPLTFITHLFHS--STSNFSTLFANPQSIPPFPFQSSSSKL
CIPVAFPPSPKPPFLSHSGFHSIHYDLDSPKSAAVK-----GLSSSPNFD---SGFPSTL
RIS----------GLNSDGKTGGPAFVGQVFSMCDLSGAGLMAVTSNMNIPFVSKRTEEW
LKKMFSTITKSKRNAPIFRFFTDLGDAVTYVKRLNIPSAVVGVCRLDLAYEHFKEKPHLF
Q-FIPNEKQVKAANKLLKGLPQNGGSKKIDGVPVFSAQNLDIAIATTNGIKWYTPYFFDK
NMLDNILEESVDQHFHALIQTRRLQRRREIVDDNAAAEVLEEMGDSLLEPPEVQEVMDEM
GNPGIPLSVISKVAEMQLLYTVDKVILGNRWLRKAVGIQPKFPYMVDSFERRSAASLLRI
QESASGLTNSESVEETKELQCYSSSPLNTEDNREANQEPK-QHSFNPFRNWFGHLWSKQR
---------QRDDFSQERTKQNVQISPFLPKITMVGISTGDSGHTSKANLKKTMEDLTRE
LEHIDQGNAASHNEYE-FNNEERDPLFVANVSHFSSGLSKAGSARWVRGND--
>Citrus_sinensis_gnl|BL_ORD_ID|32460 _1.1g009199m|PACid:18125400

MASPAEPNHLQNQI---SSFINATTSTLFSLITPTKTTPSSQSQPSSAPASRLC------
----IPLQ---FADSSCPSSSTRSPVGSDSISSNSGASSSESSSSGFPSTVRISAINSSG
KGGGPAFVGQVFSMCDLSGTGLMAVSTHFDI-PFISKRTPEWLKKLFATITKSERNGPVF
RFFMDLGDAVTYVKQLNIPSGVVGACRLDLAYEHFKEKPHLFQFVPNEKQVKAANKLLRT
IPD-SGRKKKVDGVPVFS-AQNLDIAIATADGIKWYTPYFFDKNMLDNILEES--VDQHF
HALIQTRHMQRRRDVIDDNLAAEVVEEIGDSIWEPPEVQ-----EMMDEIGHPA------
--------IPLSVISKAAEIQLL----YAVDRVLLGNRWLRK-----------------A
TGIQPKFPYMVDSFENRSAASFLRASES-TSCLANS-ETNNGSSDLKLEDKHLDKRDQRP
D-FRFPFGDWFRHLWS-KQDCEAQGSS---YIECTKRNLQLNPFLPKVTMVGI-------
-----STGEAGQMTKANLKKTMENLTKELEQTDQENATSSGSNEY---IIEDRDPLFVAN
VGGYYSGLAKTGSTRWVRGRSNN
>Eucalyptus_grandis_gnl|BL_ORD_ID|2953 _A02719.1|PACid:23564674

MAVSPEP-----------------------------------------------------
------------------------------------------------------------
--------------------------------------------------------PRKH
RHH-----PNPLSHLLNSTLLPLIPNHKAAPPSLVSPPPPPKLLLPVRLPPALSIASPSD
SAPPPPHPTPLKPAPEVKAPAEPGAAAAGAFPSTVRISAIKSNGKGRGPAF-----VGQV
FSMCDLSGTGLMAVSTHFDVPFLSK--RTPEWLKKVFASITKSERNGPVFRFFMDLGDAV
TYVKRLNIPSGVVGACRLDLAYEHFKEKPHLFQFVPNEKQVKAANKLLKTISQGNGNRQI
DGVPV-FSAQNLDIAIATSDGIKWYTPYFFDKNMLDNILEESVEQHFHSLIQTRHMQRRR
DVIDDNL-TEVADDVGDSLWEPPEVQEVLEEMGHPGIPLSVISKAAEMQLLYAVDRVILG
NRWLRKATGIQPKFPYIVDSFERRTAASLVRAS-DLTHYLGDRGMKTDESSQESTDKLAL
EENHHVDLGQ-------KAD-FRFPFGDWLRHPWSKEQQK-LQKEVGARHRLESLTGEPV
KQKLQPNPFLPKITMVGISMGEAGQANKATLKKTMEDLTRELEQTDHGNAAGNIADVS--
-EDRDPLFVANVGDYYSGLAKTGSARLIRRSEAKKQQ
>Glycine_max_gnl|BL_ORD_ID|45053 _16g29580.1|PACid:16303315

M-ALPSEPHRRRRHNHNHIST-FLQSTASNFASLFNPPNPPSLTLPHPPTSVSLPLFFAP
PLSGS----STVDSATSK------PAHPPAKSV--------RIARLGANGKGGGGPVFLG
EVFSLCDLSGTGLIAASKHFGIPFISERTPEWLKKIFAPITKSERNGPVFRFFIDLEDAV
SYVEKLN-IPS--------CVVGAFRLDL-AYKQFKEKPHLFQFVPNEKQVKAANKLLKT
ISEHGDK------------KKVDGVPVFGAQNLDIAIATTDGIKWYTPYFFDKNMLDNIL
EDAVDQHFHNLIQTRHMQRRRDVVDDNLAAEVIEEMSDRLGEPPEVQELLDEMGHPSIPL
SVISKAAGLQFQYTVDKVLLGNRWLRKATG------------IQPKFPYMVDSFERR---
------------------------------SEASLLRATESSSCLENSKVEDDRQISECL
DSSNCSLDGNTEAIKQPSPSLSLPFGNWFHHLWPKQCREKASSSRKGVNKE--------E
MKPRPILPKVTMVGLSTEEAGQTSKANLKKTMDDLTRELEKTELDIMTDGGSK---ECKV
EDRDPLFVANGGNYYSSMRRKPGSGR--------
>Linum_usitatissimum_gnl|BL_ORD_ID|5439 _10027537|PACid:23144619

MATSAEPPQNHHRRHHPFPNFFHSATSAVLSLLPNPRTSSAPPITSPSSSPPPHVCIPFN
FVDSSYPLNQQSVIRSPLESGQSDSVSSTSATVKGLSSAESNSGFPSTVRISGL---NSD
GKGG-GPAFVGQVFSMCDLSGTGL-MAVSTYIELPFI--------------NERTPEWLK
K-ILAPVTKKDKNGPMFRFFMDLGDAVS------------------YVKKLNIPSGVVGA
CRLDLAYEH--------------FKEKPNLFQFVPNKEQVKAAKQLLKT--MPESDGKTT
VDGVPIFSAHNL---DIAIATSDGIKWYTPYFFNKSML----DGIIEDSVDQH---FHTL
IQTRHMQRRRDVVDDNFAADVMEEMADSLMDPPEVDEMMDEMGNVGIPLSVISKAAEMEL
LYAVDKVLLGNRWLRKATGIQPRFPYVVDSFERRSAYSFKKA--SKTTSLSH-----VSQ
AGGSDSEVEPENNTQANSYEERPDLRLTFGDWFGLRLKQPFKPARETESRTEGSSK----
EQMQQKLVDNPLLPKITM--VGISTGETGKVSKA-SLKKTMESLRKELEQADQGKTSSSD
NGDGDFKIADRDPLFVANVGDYS---------RWIRRGMS-
>Malus_domestica_gnl|BL_ORD_ID|44230 _0000777828|PACid:22664215

M-----------------------------------------------------------
--------------ASPSEPPHTRQQLRPSITHLVHSTTSNLLSLLASPKTTPSPSLSTT
---PPEI------------RVALFLPNLPKPLAFQPDS------KLSA---MKGVASSPE
STS-GFPSTVRIAGLNSNIKGSGGPA-----FVGQVFSMCDLSGTGLMAVSTHFDIPFIS
KRTPEWLKKMFKSITNSERNGPVFRFFMDLGDAVTYVKRLNIPSGVVGAC----------
--RLDLAYEHFKEKPHLFQFVPNEKQVK-AANKLLKTMPQSGRCKRV-------DGVPVF
SAQNLDIAIASSDGIKWYTPYFFDKNMLD--NILEE--------------SVDQHFHSLI
QTRHTQRRHDVID--DNIPAEVIEEMGDNLWEPPEVQEVMDEI---------GNSGIPLS
VISKAAEMQLLYAVDKVLLGNRWLRKATGIQPKFPYMVDSFERRSAASF---------LR
ASQSA-RCLTNGEAVNDNEDSLDCSTSK----------IKSKDDIHT-------------
---NKGNKTD-LRFPFSDWF---SHLWSKQ-----KDQNEELS-----------KERIEQ
STLQNPNLPKITMVGISTGAAGPMSKANLKKTMEDL------------------------
------------------------------------------------------------
------------------------------------------------------------
---------TKEL--EQTDSGNAFGSDTGNELRFE-------------------------
------------------------------------------------------------
----------------------------DRDPLFVAN-----VGDYYS------------
-----------------------------GMAKTGSAKWVR-------------------
------GGN-----------------N---------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------
>Manihot_esculenta_gnl|BL_ORD_ID|29919 _4.1_003879m|PACid:17989925

MASSTQPAPNRHH-----SNLFHSA-------------------TTALISLVSSPKASPL
STIPLCPPK-----ICIPF-------QFADSSYPLIQSIRSPFDSNQPESVSPKSAAVKG
LSSAESN---SGFPSTVRIAGLKSNGKSGGPAFVGQVFSMCDLSGTGLMAVSTHFDIPFI
SKRTPEWLKKIFATVTKSE-RNGPVFRFFIDLGDAVAYVKRLNIPSGVVGACRLDLAYEH
FKEKPHLFQFVPNEKQVKAANQLLKKIPQGNGRRKVDGVPVFTAQNLDIAIATADGIKWY
TPYFFDKNMLDNILEESVDQHFHSLIQTRHMQRRRDVVDDNLAAEVI--EEMGDNMLEPP
EVQEMLDE--------MGHPGIPLSVISKAAEIQLLHAVDRVLLGN-RWLRKATGIQPKF
PYMVDSFEKRSASSFQRASESTSYLANPKTDSTSNCTF---KDNAQADHEQKTD-LRIPF
GDWFRHPWLKQKWKPEKLPEIRSHESLSECTKQKLERNSFLPKITMVGISTGEAGQMSKA
SLKKTMEDLTRELEQTDRENATVGRLECNVRILILLTEAPRNIENVLMLSNILSLARYRE
NFSIVICFWECILSPYSLSSFPLSYPDRQGGTFSSLYEESGFSILTGLYGSSGIFAKETL
HSWI
>Mimulus_guttatus_gnl|BL_ORD_ID|16966 _mgv1a003806m|PACid:17686364

MAS------------------AADKSHRRHHPPPHLSRFISTASTNLSSFLTLKSPSPAS
SSSKIHLPLLLADSDSFLSLVSRSESAQPDSTPSAPSRSPPSSSSSSSSMKSTPSSDSVS
KFPPTVRIT----------TGKGGGPAFVGQVFSMCDLSGTGLMAVSTHFDIPFLSKRTP
EWLRKMYAAVTKSERNGPVFRFFMDLGDAVSYVKQLNIPSGVVGACRLDIAYEHFKEKPD
TF-QFVPN---ERQVKEANKLLKSFPHSDGKNKVEGVPVFSAQNLDIAIAKKDGIKWYTP
YFFDKSMLDNILEDSVDQQFHSLIETRNAHRRRDIGDDSLPAEAIEEMGESMWDPPEVQE
VLDEIGHPGIPLSVISK-AAEIQLLYAVDRVILGNRWLRKATGIQPKFPYMVDSFERKTA
ASFLRAKTSNLISNSEISEDAQLDNRTT-LDVEPKEKTHDKQEQKHLINSQFPFGDWLSH
PWLKQPENQQNLSETRHPNSTTQ----NRGQVAQSSPFLPKITMVGVSTGEPGKMGKAAL
KKIMDDLTKELEKVEQVNQANSNSSEYMA-DERDPLFVANVGDSYSAVSKTGTSWRVRGG
SF-
>gi|18424615|ref|NP_568958.1| Tic22-like family protein [Arabidopsis thaliana]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------GSPDKQHRRHV-AAEFLHSAVTSIS----SSIIPLFPPKTAPSR--
--------------VCLPLRFSVSDDVSSPFESTVKSTSSAS----SSGLNST------V
RISSLSSDGKRGGPAFVGQVFSMCDLTGTGLMAVSTHFDIPFISKRTPEWLKKMFSTITK
SERNGPVFRFFMDLGDAVSYVKKLNIPSGVVGACRLDLAYEHFKEKPHLFQFVPNERQVK
AANKLLKSMPQNGKTQKVEGVPVFGAQNLDIAVATADGIKWYTPYFFDKAVLDNILEESV
DQHFHTLIQTRHVQRRRDVVDDSLASEVMEEMGDSMLEPPEVQEAMEEIGTSGIPLSVVA
KAAEIQLLYAVDRVLLGSRWF-RKATGIQPK--LPYLVDSFERRSAFSIQRASGSATRCL
GDSVE--------ADTSASLLRVEDDSPSEA------EKRQQHLWFPFG-----------
-------------DWISHSVSRKEHTHHK-------------GSSDQRDMESREREMLRS
PFLPKITMVGISTGEAAQM------------SKANLKKTMEDLT----------------
---EDLEQSD------EGN----------DHG-------SKRYDSLKIEE----------
------------------------------------------------------------
-----RDPLFVANVG---------------------------------------------
------------------------------------------------DYYSGLAKAGSA
RLSRRGDDQ
>Oryza_sativa_gnl|BL_ORD_ID|20689 _LOC_Os01g12550.1|PACid:21903161

M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------PRG-------------R------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------------------------------------------STT
TTTSSSASNPFHAFASTL------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------------PF-------LPSPSPS----PTSASPSPSPPA-------
-------PHLAVPLILP-------------------------------------------
--------------------------------------ITSSSSASAAAA----------
--------------------------SPESNRGARMA-----------------AAA---
------------------------------------------------------------
--------------------SGGKAGGGGGLGK---------------------------
------------------------------------------------------------
---------------------------------------------GGG------------
------------------------------------------------------------
----------------------------PAFVGQVFTMLDP---------SGNGLMAVTT
RFELPQFLAS--RTPMW-------------------------------------FKRILS
---------------PLKKSE-NGPVFRFFMDLNDAVSYVKRLNVPS-------------
-----------GMVGACRLDVAYEHFKEKPQMFQF---VPS------------EKQVKAA
NKL--------------LK--SLPQRRRRKKLDGVPVFSAQNLNIAVATNDGI-RWYTPY
-----------------------FFDKN--------------------------------
----------------------------------LLDNIL-EASMDQHFHSMVQNRHTRR
RRDIVDDSLTS--EMMEESA-----DSFLEPPEVQELMNEIGPVGIPLNVVTKAAEIQFL
DVVDKML-------------LGNKWLRKATGIQPQFPYVVDSFEERTAAAIDRAATASSS
FTASKDADCFQISKQPETLESDVDNSNRGKHENSNNGQSH--FPFSNLLPNIWPGHDRSF
KAQGRDR--AFRRCDASINNDLQANPLLPKITMVGISMGEGGQMSKANLKKTME------
------------------------DLTKELEQAGE---------KTIF------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------SDEKDP
LFVANVGD-YSRITKISST-----------------------------------------
-----------------------
>Physcomitrella_patens_gnl|BL_ORD_ID|36425 _Pp1s68_153V6.1|PACid:18072962

MGRNRDTCNVP--------GCSKDEKPCLVTGPKIVSFKLPNPALFSSWVQTVTSNLAWT
VQSFQTLKTDGLNCLSLLVEHKPMVSPLPVPYLALNNLIF-PVPSSTSSVQV-----CQK
AVSSIPQDHFSK-GNAVNEKGEVSST-------GPAFIGQVYTMCDASRQGLIAVRPSDV
LKKIKVPPYMKLMEKAYERAMNVLFTDDMKGPVFRFYFNKDDAAEYVRRLNITGSAVG--
----PCSLDAAYKYYKSKEGMFKFIADQRQVKVAKELVRRERGDKAANKLKGVPVFTARN
LTIALSTPQGVRWFRPYFFNKKQL--DSLIGHSVDHYYEMLISAR-----RAQRYSQIAE
NNGDAFAGGESMDDELDGLMDPP--EVQELMEELGQGGGGMEFVGLKVLEAQFMDLADRV
LLGHQWSRRMIHLQPRFPVIVDSFERLISASELDHSSESEGSVTSSRNSFAKKEGTQEKS
QRGQGDEGMSISGRDERSASNDSSESVSKEYSQSSPNSLFNLFKKKWGANANLVFKRKDS
GNA--EILEEDSDSEYLQETAQKDPPGKIPFQPKLTMMGISMNVNKVEGGLQQAMAAAAK
DVEDRLRKGEGS--GPDHG-------------PLFIANLGSGIPQWGRPVSASSGVLDDD
AE
>Prunus_persica_gnl|BL_ORD_ID|26753 _ppa003928m|PACid:17667413

MA-SPTEPAHKKQARPITH-LVHSTAANLLSLFASPKTTPSTPSTIRVAFLFPNSPK---
----------------------PLAFHSAQPDFKSAMKGV--ESS--SESNSGFPSTVRI
AGLNSNIKGGGPAFVGQVFSMCDLSG-----TGLMAVSTHFD---IPFISKRTPEWLKKM
FASVTNSERNGPVFRFFMDLGDAVTYVKRLNIPSGVVGACRLDLAYEHFKEKPHLFQFVP
NEKQV-----------KAANKLLKA-MQQNGRC---KRVDGVPVFSAQNLDIAIASSDGI
KWYTPYFFDKNM---LDNILEESV----------------------DQHFHSLIQTRHMQ
RRRDVIDDSLPAEVIEEMGDNLWEPPEV--QEVMDEMGNPGIPLSVISKAAEMQLLYAV-
DKVLLGNRWLRKATGIQPKFPYMVDSFERRSAAS------FLRASQ-SSNRLANREAVND
NKDSVHCSTSEVKL----NDDIQTNKGNKLDLRFPF------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------GDWFSH---------LLLKQ----------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------KDQTEELSKECVEL-SSQQNPNLPKITMVGISTGEAGQMSKAT--LKKT
MEDLTK-ELEQPDAGNAGGSDMSNEL----------------------------------
--------RFED------------------------------------------------
-------------------------RDP--------------------------------
--------------------------------LFV-------------------------
----------------------------ANVGD---------------------------
-------YYSG------------MARTGSARWVRGG------------------------
------------------------------------------------------------
------------------------------------------------------------
---------------NN-
>Populus_trichocarpa_gnl|BL_ORD_ID|3641 _POPTR_0017s00970.1|PACid:18209660

MPSPPEPP-QHRHNNHHLSNFLNSTTKTLFSLLSPPNILPLAPPQ-P--KICISFHLPNA
PLPLTQSTLSLFESTQPDSLSPSKSSSASVKDISSAESNSGFPSAVRIGRLNPNGNGGGP
AFVGQVFSMCDLSGTGLMAVSTHFDVPFISKRTPEWLKKIFATVTKSERNGPVFRFFMDL
GDAVAYVKRLNIPSGVVGACRLDLAYEHFKEKPHLFQFVPNEKQVKAANQLLKSIPHGDG
SRRVDGVPVFSAQNLDIAIATTDGIKWYTPYFFDKNMLDNILEESVDQHFHALIQTRHMQ
RRRDVIDDNVAAEVIEEMGDSLLEPPEVQEVLDEMGHPAIPLSVISKAAEIQLLYAVDKV
LLGNRWLRKATGIQPKFPYLVDSFERRSASSLRRALES-TSCLANS-KIDDSTSEHKLKD
NVQTDHEQRKD-LRLPFGDWFSHPWLKKHSKSERESDTRKEGLSKDCLKWKSESNPFLPK
VTMVGVSTGDAGQLSKSSLKKTMEDLTKELEQTDEANDSFISNSSSEFKVNDRDPLFVAN
VGDYYSGMAKTGISR--------
>Panucum_virgatum_gnl|BL_ORD_ID|40717 _Pavirv00055971m|PACid:23796854

MPRS--SSSSNPFPSLASSTFPFLSSSSSAATSSTTS--PAHPAP-HLAFPLLLPVSSAS
SS---AEPRRGPEPLPGARM-----AGAGAAAGG-KPGGRIKGG---G--GGPAFVGQVF
PMLDPSGNGLMAVTTRFELPRFLTNRTPAWFKKILSPLKKSE-NGPVFRFFMDLNDAVSY
VK----------------------------RLNVPSGMVGACRLDVAYEHFKEKPHMFQF
VPNEKQVKAANKLLKSFPQRGRRKRLRGVPVFSAQNLNIAVATNDGIRWYTPYFFDKNLL
DNIL-EASMDQHFHS---IMQNRHVQRRRDIVDDSLTSEIIEESADSLLEPPEVQELMNE
IGPAGIPLNVVTKAAEIQLLDVVDKVLLGNKWLRKAA-----------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------------------------------------
>Phaseolus_vulgaris_gnl|BL_ORD_ID|6869 _091010222m|PACid:23537334

MALPSEPHRRRRHHNNHIAT-FLQSTASNFASLFNPPNPPSLTLPHPPSSLSLPLFFAPP
LSASNALDSA--ATASEPARPAAKSVRVARLGVNGKGGGGGPAFVGQVFSMCDLSGTGLM
AVSTHFDIPFISKRSPEWLKK--IFAAITKSERNGPVFRFFIDLG----DAVSYVKKL--
------NIP-SGVVGACRLDLAYEHFKEKPHLFQFVPNEKQVKAANKLLKAISQ------
------------------HGIRKKVDGVP--------------VFSAENLDIAIAT----
-TDGIKWYTPYFFDKNML--DNILEEAVDQHFHTLIQTRHMQRRRDVVDDNLAAEVIEEM
GDNLGEPPEVQELLDEMGHPSIPLSVISKAAELQFHYT-----VDKVFLGNRWLRKATGI
QPKFPYLVDSFERRSEASYLRATES-RRCLENPKVEDDGKISECVDSSDCGLDDNTEAIR
QPSYRLSLPFGNWFNHLW----------------PKQ--CHEKARSFKK---GVN-----
------------------------------------------------------------
-----KEDMKPTPFLPKVTMV---------------------GL-----STEEAGQMSKA
NLKKTMEDLTRELE-----KTELDNMAG---------------GGGKEC-TMEDRDPLFV
ANV--GDYYSSLGKAGSGRWIRGGSN----------------------------
>Ricinus_communis_gnl|BL_ORD_ID|23216 _30169.m006582|PACid:16821381

MS----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------LSPDPNH-HHQP------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------------------------SNFFHSATTAITSLIS
TNPKTSPSSTIPLSPPK-----ICIPFQFADSSYRPLTRSSFESTHPDSVSPKSAAVKGL
SSAESSSGFPSTVRIAGLNSNGKGGGPAFVGQVFSMCDLSGTGLM---------------
--------------AVSTHFDIPFISK-------------------------------RT
PEWLKKVFTTVTKSERKGPVFRFFMDLGDAVTYVKRLNIPSGVVG---------------
------------------------------------------------------------
-----------------------------ACRLDLAYEHFKEKP-----------HLFQF
VPNEKQVKAANQ------------------------------------------------
---------------------LLKTIPQSDGRRKVDGVPVFSAQNLDIAIATTDGIKWYT
PYFFDKSMLDNI----------------------------------------LEE-----
------------------------------------------------------------
------------------------------------------SVDQHFHALIQTRHMQRR
RDVIDDNLAAEVIEEM----GDSM-LEPPEVQEMMDEIGHPAIPL---------------
-----NVISKAAEIQLLYAVDRVILGNRWLRKATGIQPKFPYMVDSFEKRSASSF-----
----RRASEPASYLAKSKTDADTSK--LNLEDG-AQANHEPITD-LRLQFGDWFKSLGLK
QQQKPEKGSEIS---ECRKQKLEMNPFLPKITMVGISTGEA-------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------GQMSKASLKKTMED----------------------------------LTRE
------------LEHTDRENAPGSSNNGN---------------------------DLEM
E-------------------------------------------DRDPLFVANVGDYYSG
MSK---------TNSPR-----------------LVRGG---------------------
-------SK
>Sorghum_bicolor_gnl|BL_ORD_ID|9318 _Sb03g001210.1|PACid:1960134

MP----------------RSSSSSNPFHSLASAFPFFSSSSPSPPASASP--S-------
-----PSPAAPHLAVPLLLPVSSGSASASSESRRGPQPLPGARMAGAAAAGRG-NKAGGG
AGPAFVGQVFTMLDPSGNGLMAVTTRFELPRFLTNRTPMWFKRMLSPLKKSE-SSPVFRF
FMDLNDAVSYVKRLNVPSGMVGACRLDVAYEHFKEKPHLFQFVPNEKQVQA--ANKLLKS
LPQRSRRKKL--GGVPVFSAQNLNIAVATNDGIRWYTPYFFDKNLLDNIL-EAS-MDQHF
HSIMQNRHTQR-----RRDIVDDSL---TSEIIEESAESLLEPPEVQELMNEIGPAGIPL
NVVTKAAEIQFLDVVDKVLLGNKWLRKASGI-----------------------------
----QPKFPYVVDSFEERTAVSIANIATTSSLTTSNDENCCQNNQQTQSSGSSV---DNS
S------------YRNHNNEDHNHFPFSNLLPNIWPGHDRKFKAQESDNKFSRYDADVKS
---NLQSNPLLPKITMVGISMGDGAQMSKANLKKTMEDLTKELEQTSEEN---------M
FSDDKDPLFVANVGD-YSRI-----------------------TKISSA---------
>Setaria_italica_gnl|BL_ORD_ID|1638 _Si001606m|PACid:19674983

M-----------------------------------------------------------
---------------------------------------LDPSG--------NGLMAVTT
RFELPRFLTNRTPTWFKKILSPLKKSE-------NGPVFRFFMDLNDAVSYVKRLNVPSG
MVGACRLDVAYEHFKEKPHMFQFVPNEKQVKAANKLLKSLPQRGRRKRLGGVP-------
----------VFSAQNLNIA--VATNDGIRWYTPYFFDKNLLDNILEASMDQHF------
---------HSIMQNRHKQRRRDIVDDSLTSEIIEESA---------DSLLEPP------
---------EVQELMNEIGPAGIPLNVVTKAAEIQLLDVVDK----VLL--------GNK
WLRKAAGIQPRFPY-----VVDSFEERTAVSIAN--------IATTSSFTAS--------
----------------NDSCCQNDQQSQSSDPSIENSYRSHSNQDHNQFHFPFSNLLPNI
WPGHDRKFKEQESDSKFSRYDADMKT---DLQSNPLLPKITMVGISMSEGGQMSKANLKK
TMEDLTKELEQTSEK--NTFG---------DEKDPLFVANVGDY-SRITKISST------
---
>Selaginella_moellendorffii_gnl|BL_ORD_ID|1621 _424522|PACid:15402899

ME----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------IGSVP-------------------
-------LHLAYKFFKERPSLFSFIPSKKQVDLA-----------KTIIKKEQGGK---A
AQQFQGVPVFTSHCLSILVVGPS---GARWFRPHFFKKEELDG----VIRSSM-------
-EHHYQSLIRNRR------------------------ARRHNQVSD--------------
---------FPSDMAEDDLEMLESQDIQDFV-----EDMDEWSSVLESIMAKAAQMYFQD
TLDRAIFGNKWCRMLAG----IQPSF---PILVDSF------------ERRVTSETENAV
VS---------------------------HHEQKKPHKDWDSTCQLKRALIR--------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----
>Thellungiella_halophila_gnl|BL_ORD_ID|20311 _Thhalv10003967m|PACid:20199916

MDLPDK----QHRRHIATEFLHSAATSI-SSIIPLFPPKATPSRVCLPLRFSVSDDV-FP
FDSTVRNASSASTSSSSLNSTVRISSLSSDGKRGGPAFV-----GQVFSMCDLTGTGLMA
VS-THFDIPFISKRTPE-----WLKKMFSSITKSE-------RNGPVFRFFMDLGDAVSY
VKKLNIPSGVVGACRLDLAYEHFKEKPHLFQFVPNERQVKAANKLLKSMPPNGKKQKVEG
VPVFGAQNLDIAVATADGIKWYTPYFFDKAVLDNILEESVDQHFHTLIQTRHVQR-----
------------------RRDVVDDSLTSEVMEEM------GDSMLEPPEVQEAM-----
-EEIGTSGIPLSVVAKAAEIQLLYAVDRVLLGSRWFRKATGI--QPKLPYLVDSF-----
-ERRSAFSIQRASGSTSRCIGDSAEADTSASLRRVEDDSPSEDEKRQQNLWFPFGDWLNH
SGSRKEHA-QKVTSDQREMECREREMQQSPFLPKITMVGISTGEA-----AQMSKANLKK
TMEDLTEGLEQSDEGS--------SEHGSKRYDPLKMEERDPLFVANVGDYYSGLAKAGS
ARWSRRGGDSNETHPRS-------------------------------------------
-----------
>gi|18424615|ref|NP_568958.1| Tic22-like family protein [Arabidopsis thaliana]
M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------GSPDKQHRRHVAAEFLHSAVTSISSSIIPLFPPK-
-----TAPSRVCLPLRFSVSDDVSS--PFESTVKSTSSASS-------------------
------------------------------------------------------------
--------------------------------------------------------SGLN
STVRISSLSSDGKRGGPA------------------------------------------
------------------------------------------FVGQVFSMCDLTGTGLMA
VSTHFDIPFISKRTPEWLKKMFSTITK--------SERNGPVFRFFM---------DLGD
A-VSYVKKLNIPSGVVGACRLDL----------------AYEHFKEKPHLFQFVPNERQV
KAANK-----------------LLKSMPQNGKTQKVEGVPVFGAQNLDIAVATADGIKWY
TPYFFDKAVLDNILEESVDQHFHTLIQTRHVQRRRDVVDDSLA--SEVMEEMGDSMLEPP
EVQEAMEEI---------------GTSGIPLSVVAKAAEI---------------QLL--
------------YAVDRVLLGSRWFRKATGIQPKLPYLVDSFER---------------R
SAFSIQRASGSATRCLGDSVEADTS---ASLLRV------EDDSPSEAEKR---------
--QQHLWFPFGDWISHSVSRKEH--------------------THHKGSSDQRDMESRER
EMLRS-PFLPKITMVGISTG--------------EAAQMSKANLKKTMEDLTEDLEQS--
------------------------------------------------------------
----------------------------------DEGN-------------------DHG
SKRYDSLKIEERDPLFVANVGDYYSGLAKAGSARLSRRGDDQ------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
--------------------------
>Vitis_vinifera_gnl|BL_ORD_ID|19207 _GSVIVT01028824001|PACid:17835832

M-----------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
----------------------------------------CDVSGNG----------IMA
VSNHFDIPFI---------------SKRMPQRIKKMF--------ATITKS-DKNGPVFR
FFMD-----LGDAVRYVKKLNIPSGGVGACRLDLAYGHFMEK------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-------------------------PHLFRFVPNEKQVKAANKLLKKIPQNGGRKRIDGV
PVFTAQNLDIAIATTDGIKWY----TPYFFDKHTLDSILE---------QSIDHHFHHLI
QSRHVQRRRDVIDDNLAAEVLEDNA--------------ESLWEPP----EVQ-------
-----------------------EVLDEVGHPGIPLSVISKAAEMQLLYAVDRVLLGNRW
LRKATGIQPKFPYMV---------------------------------------------
-----DSFEKRS-----------------------AASFRRASPSKRFV-----------
------------------------------------------------------------
------------------------------------------------------------
------------------------------ASPEMGNDNKDTEELGPSDPKLEDNTQRD-
QGQNSASW-------------------------------------------------FPV
WDLFNHPWSNKRQEPQNRSNARIEDASREHIKQELQLAPFLPKITMVG------------
------------------------------------------------------------
--ISAGESG-MSKVNLKKTMEDLTKELEQADQENAVGCIN-SEFEVENRDPLFVANVGSY
GSGLV-ARSPVPSVRGENN-----------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
------------------------------------------------------------
-----------------------------------
>Zea_mays_gnl|BL_ORD_ID|9045 _GRMZM2G097959_T01|PACid:20828771

MPCSSSSSNPFHS---LASAFPFL---SSTSPPPSPPASPAPAAPHLAVPLLLPVSS--A
SESRRGAQPLPGTRMVGAGATGGG--------NMASGG--GGPAFVGQVFTMLDPSGNGL
MAVTTRFELPRFLTNRTPMWFKRMLSPSKKTE-NSPVFRFFMDLNDAVSYVKRLNVPSGM
VGACRLDVAYEHFKEKPHMFQFVPNEKQVQAANKLLKSLPQRGRRKKLDGVPVFSAQNLN
IAVATNDGIRWYTPYFFDKNLLDNILEASMDQHFHSIMQNR----HTRRRRDIVDDSLTS
EIIEESAESLLEPPEVQELMNEIGPAGIPLNVVTKAAEIQFLDVVDKVLLGNKWLRKASG
IQPKFPYVVDSFEERTAVSIANIATTSSLTASNDDSSCQNNQETQSSEPSGDNSSYRNHN
NEDHNHFPFSNLLPNIWPGHDRKFKSQESDNKFSRYDADVKSK---LQANPLLPKITMVG
ISMGDGAQMSKANLKKTMEDLTKELEQTSEENMFG---------DEKDPLFVANVGD-YS
RITKISSA---------
